/* DNA Imersivo v2.1 (Portal 360º) — controlador único das atividades, interface e WebXR.
   Mantém o catálogo externo intacto. Não altera os marcadores da abertura do Portal. */
(function(){'use strict';
const D=DNA_DATA,M=window.DNA_MODELS,T=window.THREE,$=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const freshPair=(n=10,sequence=null)=>({sequence:sequence||Array.from({length:n},()=>Object.keys(D.bases)[Math.floor(Math.random()*4)]).join(''),answers:Array(n).fill(null),target:0,selected:null,errors:Array(n).fill(0),hints:Array(n).fill(0),skipped:Array(n).fill(false),done:false});
const freshRep=()=>({sequence:'ATGCCG',phase:0,open:0,answers:[Array(6).fill(null),Array(6).fill(null)],selected:null,target:{branch:0,index:5},identified:[],prediction:null});
const initial=()=>({version:D.version,view:'estrutura',level:'intro',guided:false,gstep:0,context:0,visited:[],completed:[],assembly:{base:'A',done:[],selected:null},pair:freshPair(),rep:freshRep(),quiz:{phase:0,index:0,answers:[],transfer:freshPair(6,'GTCAGT'),done:false},events:[],started:Date.now(),autoRotate:false,reducedMotion:window.matchMedia('(prefers-reduced-motion: reduce)').matches,quality:'balanced',captions:true,autoVoice:true});
let S=initial(),view=null,actions=[],feedbackText='',instruction='',instructionKey=null,inspectKey=null,atoms=null,atomPromise=null,molecularStatus='idle',spacefill=false,overlayFeedbackTimer=null;
try{const saved=JSON.parse(sessionStorage.getItem('pde_dna_lab_v2')||'null');if(saved&&saved.version===D.version&&D.activities.some(a=>a.id===saved.view)){S=Object.assign(initial(),saved);}}catch(_){}
function save(){try{sessionStorage.setItem('pde_dna_lab_v2',JSON.stringify(S));}catch(_){} }
function log(event,skill,value={}){S.events.push({event,skill,...value,at:new Date().toISOString()});if(S.events.length>600)S.events.shift();save();updateStatus();}
function mark(key){if(!S.completed.includes(key))S.completed.push(key);save();}
function fb(text,type='ok'){feedbackText=text;const e=$('feedback');e.hidden=!text;e.className='feedback'+(type==='ok'?'':' '+type);e.textContent=text;if(view&&view.xr)view.buildXRUI();}
function setInstruction(text,key,play=false){instruction=text;instructionKey=key;const c=$('captionText');c.textContent=text;c.hidden=!S.captions;if(play&&S.autoVoice)narrator.say(text,key);}
const narrator=new DNANarrator(({state,text,key})=>{const labels={loading:'CARREGANDO NARRAÇÃO',playing:'ÁUDIO GRAVADO',speech:'VOZ DO NAVEGADOR',text:'ORIENTAÇÃO EM TEXTO',ended:'NARRAÇÃO CONCLUÍDA',stopped:'ORIENTAÇÃO DA ATIVIDADE'};$('voiceStatus').textContent=labels[state]||'ORIENTAÇÃO';$('stopVoice').hidden=!['loading','playing','speech'].includes(state);if(text){$('captionText').textContent=text;$('captionText').hidden=!S.captions;}});
function btn(label,cmd,style='',disabled=false){actions.push({label,cmd,disabled});return '<button data-act="'+esc(cmd)+'" class="'+esc(style)+'" '+(disabled?'disabled':'')+'>'+esc(label)+'</button>';}
function pill(s){return '<span class="status-pill">'+esc(s)+'</span>';}
function activePair(){return S.view==='desafio'?S.quiz.transfer:S.pair;}
function isGuideDone(){const key=D.guide[S.gstep].check;if(key==='estrutura')return S.visited.length>=3;return S.completed.includes(key);}
function updateStatus(){$('sessionStatus').textContent=S.visited.length+' componentes investigados · '+S.completed.length+' atividades concluídas';}
function renderGuide(){const p=$('guidePanel');p.hidden=!S.guided;if(!S.guided)return;const g=D.guide[S.gstep],done=isGuideDone();p.innerHTML='<span class="eyebrow">AULA GUIADA · '+(S.gstep+1)+' / '+D.guide.length+'</span><h3>'+esc(g.title)+'</h3><p>'+esc(g.goal)+'</p><progress value="'+(S.gstep+(done?1:0))+'" max="6"></progress><div class="button-row">'+btn('Ouvir','guide:listen')+btn(S.gstep===5?'Concluir aula':'Continuar','guide:next','primary',!done)+'</div>'+btn('Sair da aula guiada','guide:exit','wide')+(done?'<p>✓ Objetivo desta etapa realizado.</p>':'<p>Complete a ação indicada para liberar a próxima etapa.</p>');}
function metrics(pair){const done=pair.answers.filter(Boolean).length,first=pair.answers.filter((a,i)=>a&&!pair.errors[i]&&!pair.hints[i]&&!pair.skipped[i]).length;return '<div class="metric-row"><span>Posições completadas</span><b>'+done+' / '+pair.sequence.length+'</b></div><div class="metric-row"><span>Sem erro nem pista</span><b>'+first+'</b></div>';}
function pairUI(pair,isChallenge=false){let h='<p>'+ (isChallenge?'A sequência é diferente da atividade anterior. Complete os espaços sem pular.':'Use as peças coloridas abaixo da molécula ou os botões. Escolha uma letra e clique no espaço de destino.')+'</p>';
 h+='<div class="pair-choices">'+Object.entries(D.bases).map(([l,b])=>{actions.push({label:l+' · '+b.name,cmd:'base:'+l});return '<button data-act="base:'+l+'" class="'+(pair.selected===l?'selected':'')+'" style="--base:'+b.hex+'" title="'+b.name+'">'+l+'</button>';}).join('')+'</div>';
 h+='<p class="fine">'+(pair.done?'Trecho concluído.':'Destino atual: posição '+(pair.target+1)+', molde '+pair.sequence[pair.target]+'.')+'</p><div class="slot-choices">';for(let i=0;i<pair.sequence.length;i++)h+='<button class="'+(pair.answers[i]?'filled':'')+(pair.target===i?' current':'')+'" data-act="pair:target:'+i+'" title="Selecionar posição '+(i+1)+'">'+(pair.answers[i]||String(i+1).padStart(2,'0'))+'</button>';h+='</div>';
 h+=metrics(pair);h+='<div class="button-row">'+btn('Encaixar','pair:place','primary',!pair.selected||pair.done);if(!isChallenge)h+=btn('Pista','pair:hint','',pair.done);h+='</div>';if(!isChallenge)h+='<div class="button-row">'+btn('Pular posição','pair:skip','',pair.done)+btn('Nova sequência','pair:reset')+'</div>';return h;}
function renderSidebar(){actions=[];renderGuide();let h='',a=D.activities.find(x=>x.id===S.view);h+='<span class="eyebrow">'+esc(a.kicker)+' · '+(S.level==='medio'?'APROFUNDAMENTO':'INTRODUÇÃO')+'</span>';
 if(inspectKey&&['estrutura','molecular'].includes(S.view)){const i=D.info[inspectKey]||D.info.dna;h+='<h2>'+esc(i.name)+'</h2>'+pill(i.kind)+'<p>'+esc(i.text)+'</p><details><summary>Mais detalhes</summary><p>'+esc(i.detail)+'</p></details><div class="button-row">'+btn('Ouvir novamente','inspect:listen','primary')+btn('Fechar inspeção','inspect:close')+'</div>';setInstruction(i.text,inspectKey);}
 else if(S.view==='contexto'){const c=D.context[S.context];h+='<h2>'+c.name+'</h2><div class="step-list">'+D.context.map((x,i)=>'<span class="'+(i<=S.context?'done':'')+'"></span>').join('')+'</div><p>'+c.text+'</p><div class="button-row">'+btn('Etapa anterior','context:back','',S.context===0)+btn(c.target?'Investigar '+(c.target==='nucleo'?'núcleo':c.target==='cromatina'?'cromatina':'DNA'):'Explorar a estrutura',c.target?'context:next':'view:estrutura','primary')+'</div><div class="info-card"><p>Representação celular esquemática. O tamanho relativo muda entre etapas, e o DNA nuclear não é o único DNA possível em uma célula eucariótica.</p></div>';setInstruction(c.text,'contexto-'+S.context);}
 else if(S.view==='estrutura'){h+='<h2>Explore a dupla hélice</h2><p>Selecione uma parte para vê-la ampliada. O modelo permanece ao fundo, e as informações ficam nesta lateral.</p><div class="button-row">'+btn('Ver o DNA','inspect:dna')+btn('Fita','inspect:esqueleto')+'</div><div class="pair-choices">'+Object.entries(D.bases).map(([l,b])=>{actions.push({label:b.name,cmd:'inspect:'+b.key});return '<button data-act="inspect:'+b.key+'" style="--base:'+b.hex+'">'+l+'</button>';}).join('')+'</div>'+btn('Ligações de hidrogênio','inspect:ligacoes','wide')+'<div class="info-card"><p>Fita 1: 5′ → 3′, de baixo para cima.<br>Fita 2: 3′ → 5′ no mesmo sentido visual.<br>A sequência tem 24 pares ilustrativos.</p></div><details><summary>Orientação e escala</summary><p>'+esc(D.info.dna.detail)+'</p></details>';setInstruction('Selecione uma base, uma fita ou uma ligação. Observe as orientações opostas das duas fitas.','aula-estrutura');}
 else if(S.view==='montagem'){const s=S.assembly;h+='<h2>Monte um nucleotídeo</h2><p>Selecione uma peça. Depois clique no encaixe correspondente, ou arraste a peça até ele. O encaixe é uma analogia didática.</p><div class="assembly-choices">';for(const [part,name,k] of [['fosfato','Grupo fosfato','P'],['acucar','Desoxirribose','D'],['base','Base: '+D.bases[s.base].name,s.base]])h+=btn((s.done.includes(part)?'✓ ':'')+name,'part:select:'+part,s.selected===part?'selected':s.done.includes(part)?'done':'',s.done.includes(part));h+='</div><div class="info-card"><p>'+s.done.length+' de 3 componentes encaixados.<br>'+(s.selected?'Peça selecionada: '+(s.selected==='base'?D.bases[s.base].name:s.selected==='acucar'?'desoxirribose':'fosfato')+'.':'Escolha uma peça disponível.')+'</p></div><div class="button-row">'+btn('Encaixar peça','part:place','primary',!s.selected||s.done.length===3)+btn('Pista','part:hint')+'</div>'+btn('Desmontar e tentar de novo','part:reset','wide');h+='<details><summary>Escolher outra base</summary><div class="button-row">'+Object.keys(D.bases).map(l=>btn(l,'part:base:'+l)).join('')+'</div></details>';if(s.done.length===3)h+='<p>✓ Fosfato + desoxirribose + base formam uma unidade. Uma fita reúne muitas dessas unidades.</p>';setInstruction(s.done.length===3?'Você montou um nucleotídeo. Várias dessas unidades formam uma fita.':'Monte um nucleotídeo usando fosfato, desoxirribose e uma base nitrogenada.',s.done.length===3?'montagem-concluida':'aula-montagem');}
 else if(S.view==='pareamento'){h+='<h2>Complete a fita</h2>';h+=pairUI(S.pair);setInstruction(S.pair.done?'O trecho foi completado. Compare as letras das fitas e observe suas orientações opostas.':'A fita de molde permite encontrar a sequência complementar. Selecione um nucleotídeo e encaixe no espaço escolhido.',S.pair.done?'pareamento-concluido':'aula-pareamento');}
 else if(S.view==='replicacao'){const r=S.rep;h+='<h2>'+['Antes de copiar','Separe as fitas','Construa as novas fitas','Acompanhe as originais','Replicação concluída'][r.phase]+'</h2>';h+=pill('ORIGINAL · DOURADO')+pill('NOVA · CIANO');
 if(r.phase===0){h+='<p>Faça uma previsão: como estarão as duas moléculas ao final da replicação semiconservativa?</p><div class="answer-list">'+btn('Cada uma terá uma fita original e uma nova','rep:predict:0')+btn('Uma será antiga e a outra inteiramente nova','rep:predict:1')+btn('As duas terão apenas fitas novas','rep:predict:2')+'</div>';setInstruction('Antes de copiar o DNA, faça uma previsão sobre a origem das fitas em cada molécula formada.','replicacao-previsao');}
 if(r.phase===1){h+='<p>Abra a dupla hélice sem romper os esqueletos das fitas. O movimento é ilustrativo, não uma simulação de velocidade molecular.</p><div class="metric-row"><span>Separação das fitas</span><b>'+Math.round(r.open*100)+'%</b></div><div class="button-row">'+btn('Abrir mais','rep:open','primary',r.open>=1)+btn('Fechar','rep:close','',r.open<=0)+'</div>'+btn('Usar as fitas como molde','rep:build','wide primary',r.open<1);setInstruction('As fitas originais se separam. Seus esqueletos permanecem. Cada uma será usada como molde.','replicacao-abertura');}
 if(r.phase===2){const t=r.target,old=t?(t.branch?D.bases[r.sequence[t.index]].pair:r.sequence[t.index]):null;h+='<p>Complete a nova fita, seguindo a seta 5′ → 3′. Trabalhamos uma fita por vez para dar clareza ao processo.</p><div class="info-card"><p>'+(t?'Molécula '+(t.branch+1)+' · posição '+(t.index+1)+'<br>Base do molde: <b>'+old+'</b>. Selecione o complemento.':'Todas as posições completadas.')+'</p></div><div class="pair-choices">'+Object.entries(D.bases).map(([l,b])=>{actions.push({label:l+' · '+b.name,cmd:'base:'+l});return '<button data-act="base:'+l+'" class="'+(r.selected===l?'selected':'')+'" style="--base:'+b.hex+'">'+l+'</button>';}).join('')+'</div><div class="button-row">'+btn('Adicionar à fita','rep:place','primary',!r.selected)+btn('Pista','rep:hint')+'</div><p class="fine">'+r.answers.flat().filter(Boolean).length+' de '+r.sequence.length*2+' nucleotídeos adicionados.</p>';setInstruction('Cada fita original serve como molde. Escolha o nucleotídeo complementar e adicione na extremidade em crescimento da nova fita.','replicacao-construcao');}
 if(r.phase>=3){h+='<p>Selecione a fita original em cada molécula. A cor do esqueleto indica sua origem; as cores das bases continuam A, T, C e G.</p><div class="button-row">'+btn('Original da molécula 1','rep:identify:0:0','',r.identified.includes(0))+btn('Original da molécula 2','rep:identify:1:1','',r.identified.includes(1))+'</div><p>'+r.identified.length+' de 2 fitas originais identificadas.</p>';if(r.phase===4)h+='<div class="info-card"><p>✓ Cada molécula tem uma fita original e uma nova: replicação semiconservativa.</p></div>';h+=btn('Recomeçar experimento','rep:reset','wide');setInstruction('Em cada molécula, identifique a fita que já existia. Cada uma conserva uma fita original e possui uma fita nova.','replicacao-resultado');}
 h+='<details><summary>'+ (S.level==='medio'?'Aprofundar: enzimas e direção':'Limites desta representação')+'</summary><p>O laboratório ilustra um trecho isolado e o princípio semiconservativo. Não reproduz uma forquilha completa, iniciadores ou fragmentos de Okazaki.</p>'+(S.level==='medio'?'<p>Na célula, a helicase promove a separação. A DNA polimerase estende uma extremidade 3′ a partir de um iniciador. Na forquilha, uma fita é sintetizada de forma contínua e a outra em fragmentos, unidos pela ligase.</p>':'')+'</details>';}
 else if(S.view==='molecular'){h+='<h2>Modelo experimental 1BNA</h2><p>Um trecho real de DNA estudado por difração de raios X. Possui uma sequência diferente da maquete didática: CGCGAATTCGCG.</p>'+pill('12 pares')+pill('Resolução: 1,90 Å')+'<p class="fine">'+(molecularStatus==='ready'?atoms.length+' átomos de DNA carregados; moléculas de água omitidas.':molecularStatus==='loading'?'Carregando coordenadas estruturais…':molecularStatus==='error'?'Não foi possível obter as coordenadas. As outras atividades continuam funcionando.':'As coordenadas do 1BNA acompanham a aplicação e não dependem de internet.')+'</p><div class="button-row">'+btn(molecularStatus==='loading'?'Carregando…':molecularStatus==='ready'?'✓ Estrutura carregada':'Carregar estrutura','molecular:load','primary',molecularStatus==='loading'||molecularStatus==='ready')+btn(spacefill?'Bolas e varetas':'Esferas maiores','molecular:style','',!atoms)+'</div><details><summary>Como interpretar</summary><p>Cinza: carbono; azul: nitrogênio; vermelho: oxigênio; dourado: fósforo. As cores são convencionais. Varetas inferidas por proximidade não representam ordem de ligação. Hidrogênios ausentes no arquivo não são inventados.</p></details>';setInstruction('Este modelo usa coordenadas experimentais da estrutura 1BNA. As cores dos átomos são convenções e a sequência não é a mesma da maquete.','modelo-molecular');}
 else if(S.view==='desafio'){const q=S.quiz;h+='<h2>'+ (q.phase===0?'Uma sequência diferente':q.done?'Desafio concluído':'Explique a estrutura')+'</h2>';if(q.phase===0){h+=pairUI(q.transfer,true);setInstruction('Complete esta sequência diferente, aplicando a complementaridade. Use a regra que investigou nas atividades anteriores.','desafio-sequencia');}else if(!q.done){const item=D.questions[q.index],answer=q.answers[q.index];h+='<span class="status-pill">Situação '+(q.index+1)+' / '+D.questions.length+'</span><p>'+esc(item.q)+'</p><div class="answer-list">';item.options.forEach((o,i)=>{h+=btn(o,'quiz:answer:'+i,answer!==undefined?(i===item.correct?'correct':i===answer?'incorrect':''):'',answer!==undefined);});h+='</div>';if(answer!==undefined)h+='<div class="info-card"><p>'+item.why+'</p></div>'+btn(q.index===D.questions.length-1?'Concluir desafio':'Próxima situação','quiz:next','wide primary');setInstruction(item.q,'desafio-'+item.id);}else{const correct=q.answers.filter((a,i)=>a===D.questions[i].correct).length;h+='<div class="big-stat">'+correct+' / '+D.questions.length+'</div><p>Situações respondidas corretamente na primeira tentativa. Consulte também o resumo da construção da sequência e das demais atividades.</p><div class="button-row">'+btn('Ver resumo','summary','primary')+btn('Novo desafio','quiz:reset')+'</div>';setInstruction('Desafio concluído. Compare suas respostas com as explicações e retome as atividades que geraram dúvidas.','desafio-fim');}}
 $('lessonPanel').innerHTML=h;$('modelNote').textContent=S.view==='molecular'?'Exemplo experimental RCSB PDB 1BNA. Escala ampliada; água omitida e ligações inferidas.':'Modelo didático: cores e escalas convencionais. A montagem ilustra relações, não reações químicas em tempo real.';
 if(view&&view.xr)view.buildXRUI();updateStatus();}
function rebuild(){if(view)view.show();}
function render(){renderSidebar();rebuild();save();}
function switchView(id,announce=true){if(!D.activities.some(a=>a.id===id))return;narrator.stop(false);inspectKey=null;S.view=id;fb('');log('atividade','navegacao',{value:id});const a=D.activities.find(x=>x.id===id);$('sceneTitle').textContent=a.title;$('sceneSub').textContent=a.subtitle;$('sceneKicker').textContent=a.kicker;document.querySelectorAll('#activityNav button').forEach(b=>{const on=b.dataset.view===id;b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false');});render();if(announce&&S.autoVoice)narrator.say(instruction,instructionKey);if(id==='molecular'&&atoms){molecularStatus='ready';render();}else if(id==='molecular'&&!atoms&&molecularStatus!=='loading')loadMolecular();}
function inspect(key,announce=true){if(!D.info[key])return;inspectKey=key;if(!S.visited.includes(key))S.visited.push(key);if(S.visited.length>=3)mark('estrutura');log('inspecao','estrutura',{component:key});render();if(announce&&S.autoVoice)narrator.say(D.info[key].text,key);}
function selectBase(l){if(!D.bases[l])return;if(S.view==='replicacao')S.rep.selected=l;else activePair().selected=l;render();fb('Selecionado: '+D.bases[l].name+'. Clique no destino ou use Encaixar.');}
function pairTarget(i){const p=activePair();if(i<0||i>=p.sequence.length||p.answers[i])return;p.target=i;render();}
function pairPlace(i=activePair().target){const p=activePair();if(p.done||p.answers[i])return;if(!p.selected){pairTarget(i);fb('Escolha primeiro uma letra.','warning');return;}const good=D.bases[p.sequence[i]].pair,ok=good===p.selected;log('tentativa',S.view==='desafio'?'transferencia':'pareamento',{position:i,choice:p.selected,correct:ok});if(!ok){p.errors[i]++;render();fb('Ainda não. Compare o nucleotídeo escolhido com a base do molde e tente outro.','warning');return;}
 p.answers[i]=good;p.selected=null;p.target=p.answers.findIndex(x=>!x);p.done=p.target<0;if(p.done){mark(S.view==='desafio'?'transferencia':'pareamento');if(S.view==='desafio'){S.quiz.phase=1;render();fb('Sequência nova completada. Agora explique o que observou.');return;}}render();fb(p.done?'Trecho concluído. Observe a complementaridade e as extremidades 5′ e 3′.':'Encaixe correto. Complete a próxima posição.');}
function repNext(){const r=S.rep;for(let i=r.sequence.length-1;i>=0;i--)if(!r.answers[0][i])return r.target={branch:0,index:i};for(let i=0;i<r.sequence.length;i++)if(!r.answers[1][i])return r.target={branch:1,index:i};r.target=null;r.phase=3;}
function repPlace(branch,index){const r=S.rep,t=r.target;if(r.phase!==2||!t)return;if(branch!==undefined&&(t.branch!==branch||t.index!==index)){fb('Siga a extremidade indicada pela seta. A nova fita cresce de 5′ para 3′.','warning');return;}if(!r.selected){fb('Escolha um nucleotídeo para adicionar.','warning');return;}const old=t.branch?D.bases[r.sequence[t.index]].pair:r.sequence[t.index],correct=D.bases[old].pair,ok=r.selected===correct;log('tentativa','replicacao',{branch:t.branch,position:t.index,choice:r.selected,correct:ok});if(!ok){render();fb('Esse nucleotídeo não é o complemento. Observe a base do molde.','warning');return;}r.answers[t.branch][t.index]=r.selected;r.selected=null;repNext();render();fb(r.phase===3?'As novas fitas estão completas. Identifique as originais.':'Adicionado à nova fita. O molde foi preservado.');}
async function loadMolecular(){if(atomPromise)return atomPromise;molecularStatus='loading';renderSidebar();atomPromise=(async()=>{try{let text;try{text=sessionStorage.getItem('pde_dna_1bna_raw');}catch(_){}if(!text&&window.DNA_1BNA_PDB)text=window.DNA_1BNA_PDB;if(!text){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),15000);try{let r=await fetch('https://files.rcsb.org/view/1BNA.pdb',{signal:ctrl.signal});if(!r.ok)throw new Error('Resposta '+r.status);text=await r.text();}finally{clearTimeout(timer);}try{sessionStorage.setItem('pde_dna_1bna_raw',text);}catch(_){}}atoms=M.parsePDB(text);molecularStatus='ready';if(S.view==='molecular')render();}catch(e){molecularStatus='error';if(S.view==='molecular'){render();fb('Não foi possível montar o modelo 1BNA neste navegador. A maquete e as atividades continuam funcionando.','warning');}}finally{atomPromise=null;}})();return atomPromise;}
function returnCatalog(){const url=new URL('../../?catalog=1',location.href).href;try{if(window.top!==window){window.top.location.href=url;return;}}catch(_){}location.href=url;}
function handle(cmd){const [kind,op,a,b]=cmd.split(':');
 if(kind==='view'){switchView(op);return;}
 if(kind==='context'){if(op==='next'&&S.context<3){S.context++;log('contexto','localizacao',{level:S.context});if(S.context===3)mark('contexto');}if(op==='back')S.context=Math.max(0,S.context-1);render();if(S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='inspect'){if(op==='close'){inspectKey=null;render();narrator.stop();}else if(op==='listen'){const i=D.info[inspectKey]||D.info.dna;narrator.say(i.text,inspectKey||'dna');}else inspect(op);return;}
 if(kind==='part'){const p=S.assembly;if(op==='select'&&!p.done.includes(a)){p.selected=a;render();}if(op==='place'){const part=a||p.selected;if(!p.selected){fb('Selecione uma peça primeiro.','warning');return;}const ok=part===p.selected;log('tentativa','componentes',{piece:p.selected,slot:part,correct:ok});if(!ok){fb('Esse encaixe corresponde a outro componente. Tente novamente.','warning');return;}if(!p.done.includes(part))p.done.push(part);p.selected=null;if(p.done.length===3)mark('montagem');render();fb(p.done.length===3?'Nucleotídeo montado: fosfato, desoxirribose e base.':'Peça encaixada. Escolha o próximo componente.');}if(op==='hint'){log('pista','componentes');fb('Observe os nomes sob os encaixes: fosfato à esquerda, açúcar no meio e base à direita.','warning');}if(op==='reset'){S.assembly={base:p.base,done:[],selected:null};render();fb('Montagem reiniciada.');}if(op==='base'){S.assembly={base:a,done:[],selected:null};render();}return;}
 if(kind==='base'){selectBase(op);return;}
 if(kind==='pair'){const p=activePair();if(op==='target'){pairTarget(Number(a));return;}if(op==='place'){pairPlace();return;}if(op==='at'){pairPlace(Number(a));return;}if(op==='hint'&&!p.done){p.hints[p.target]++;log('pista','pareamento',{position:p.target});fb(p.hints[p.target]>1?'Neste espaço, '+p.sequence[p.target]+' combina com '+D.bases[p.sequence[p.target]].pair+'.':'Use a regra: A com T e C com G. Observe a letra da fita molde.','warning');return;}if(op==='skip'&&!p.done){const i=p.target;p.answers[i]=D.bases[p.sequence[i]].pair;p.skipped[i]=true;log('pulo','pareamento',{position:i});p.target=p.answers.findIndex(x=>!x);p.done=p.target<0;if(p.done)mark('pareamento');render();fb('Posição revelada e registrada como pulada, não como acerto independente.','warning');return;}if(op==='reset'){S.pair=freshPair(S.guided?6:10);render();fb('Nova sequência preparada.');return;}}
 if(kind==='rep'){const r=S.rep;if(op==='predict'){const ok=a==='0';r.prediction=Number(a);log('previsao','replicacao',{choice:Number(a),correct:ok});r.phase=1;render();fb(ok?'Boa previsão. Investigue agora como isso acontece.':'Vamos testar a previsão e acompanhar a origem de cada fita.','ok');return;}if(op==='open'||op==='close'){r.open=Math.max(0,Math.min(1,r.open+(op==='open'?.25:-.25)));render();return;}if(op==='build'){if(r.open<1)return;r.phase=2;repNext();render();return;}if(op==='place'){repPlace();return;}if(op==='at'){repPlace(Number(a),Number(b));return;}if(op==='hint'&&r.target){log('pista','replicacao');fb('Use a complementaridade e siga a seta 5′ → 3′ da nova fita. Não mova a fita original.','warning');return;}if(op==='identify'){const branch=Number(a),strand=Number(b),correct=strand===(branch?1:0);log('identificacao','replicacao',{branch,strand,correct});if(!correct){fb('Essa fita é nova. Procure o esqueleto dourado.','warning');return;}if(!r.identified.includes(branch))r.identified.push(branch);if(r.identified.length===2){r.phase=4;mark('replicacao');}render();fb(r.phase===4?'Cada molécula preservou uma fita original. Experimento concluído.':'Original identificada. Encontre a original na outra molécula.');return;}if(op==='reset'){S.rep=freshRep();render();return;}}
 if(kind==='molecular'){if(op==='load')loadMolecular();else if(op==='style'){spacefill=!spacefill;render();}return;}
 if(kind==='quiz'){const q=S.quiz;if(op==='answer'&&!q.done&&q.answers[q.index]===undefined){const i=Number(a),item=D.questions[q.index];q.answers[q.index]=i;log('avaliacao',item.skill,{question:item.id,choice:i,correct:i===item.correct});render();fb(item.why,i===item.correct?'ok':'warning');}if(op==='next'&&q.answers[q.index]!==undefined){q.index++;if(q.index>=D.questions.length){q.done=true;mark('desafio');}render();if(S.autoVoice)narrator.say(instruction,instructionKey);}if(op==='reset'){let seq=freshPair(6).sequence;if(seq===S.pair.sequence)seq=D.complement(seq);S.quiz={phase:0,index:0,answers:[],transfer:freshPair(6,seq),done:false};render();}return;}
 if(kind==='guide'){if(op==='start'){S.guided=true;S.gstep=0;S.context=0;switchView('contexto');return;}if(op==='listen'){const g=D.guide[S.gstep];narrator.say(g.goal,g.audio);return;}if(op==='next'&&isGuideDone()){if(S.gstep===D.guide.length-1){S.guided=false;mark('aula');renderSidebar();showSummary();return;}S.gstep++;if(D.guide[S.gstep].view==='pareamento'&&!S.completed.includes('pareamento'))S.pair=freshPair(6);switchView(D.guide[S.gstep].view);return;}if(op==='exit'){S.guided=false;renderSidebar();save();return;}}
 if(kind==='summary'){showSummary();return;}if(kind==='center'){if(view)view.center();return;}if(kind==='rotate'){S.autoRotate=!S.autoRotate;$('rotateBtn').textContent=S.autoRotate?'Ⅱ Pausar':'▷ Girar';$('rotateBtn').setAttribute('aria-pressed',String(S.autoRotate));save();return;}if(kind==='voice'){if(op==='stop')narrator.stop();else narrator.say(instruction,instructionKey);return;}
 if(kind==='vr'){if(view)view.toggleVR();return;}if(kind==='catalog'){narrator.dispose();if(view&&view.xrSession)view.xrSession.end().finally(returnCatalog);else returnCatalog();return;}
}
class LabView {
 constructor(){this.stage=$('stage');this.canvas=$('scene');this.xr=false;this.xrSession=null;this.drag=null;this.controllers=[];this.held=new Map();this.uiPage=0;this.xrReport=false;this.anchor=null;this.width=0;this.height=0;this.pixel=0;this.az=.25;this.elev=.12;this.dist=12;this.target=new T.Vector3(0,.2,0);this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.last=performance.now();this.rotation=0;
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(44,1,.025,200);this.scene.add(this.camera);this.root=new T.Group();this.scene.add(this.root);this.ui=new T.Group();this.scene.add(this.ui);this.uiHits=[];
  this.scene.add(new T.HemisphereLight(0xceeaff,0x263542,.86));const key=new T.DirectionalLight(0xffeddb,1.2);key.position.set(5,7,8);this.scene.add(key);const fill=new T.DirectionalLight(0x77d2ec,.72);fill.position.set(-6,2,-4);this.scene.add(fill);
  try{this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true});this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.setClearColor(0x081929,0);this.renderer.xr.enabled=true;this.renderer.setAnimationLoop((time,frame)=>this.frame(time,frame));this.bind();this.ok=true;}catch(e){console.error(e);$('webglError').hidden=false;this.stage.classList.add('error');this.ok=false;}
 }
 clear(){if(this.model)M.dispose(this.model);this.model=null;this.drag=null;for(const [c,o] of this.held){M.dispose(o);this.held.delete(c);}this.animatedInspect=null;}
 show(){if(!this.ok)return;this.clear();const g=new T.Group();this.model=g;this.root.add(g);this.root.position.set(0,0,0);this.root.rotation.set(0,0,0);this.root.scale.setScalar(1);let obj;
  if(S.view==='contexto')obj=M.context(S.context);
  else if(S.view==='montagem')obj=M.assembly(S.assembly);
  else if(S.view==='pareamento')obj=M.pair(S.pair);
  else if(S.view==='replicacao')obj=M.replication(S.rep);
  else if(S.view==='desafio')obj=S.quiz.phase===0?M.pair(S.quiz.transfer):M.helix(D.sequence.slice(0,12),{colors:[M.C.old,M.C.new],rise:.44});
  else if(S.view==='molecular'){obj=atoms?M.atomic(atoms,spacefill):new T.Group();if(!atoms){M.textAt(obj,'MODELO EXPERIMENTAL 1BNA',0,.5,0,5,'#9dccdc');M.textAt(obj,'Carregue as coordenadas usando a lateral.',0,-.1,0,5,'#6e9fb8');}}
  else obj=M.helix();
  g.add(obj);if(inspectKey&&['estrutura','molecular'].includes(S.view)){obj.position.set(-2.4,-.1,-2.5);obj.scale.setScalar(.65);const copy=M.inspection(inspectKey);copy.traverse(o=>{if(o.isMesh&&!o.userData.hit)o.userData.hit={type:'inspect',key:inspectKey};});const box=new T.Box3().setFromObject(copy),size=box.getSize(new T.Vector3()),factor=2.5/Math.max(size.x,size.y,size.z,.1);copy.scale.setScalar(factor);copy.position.set(.95,.05,1.1);copy.userData.rotateCopy=true;g.add(copy);this.animatedInspect={object:copy,target:factor,start:performance.now()};if(!S.reducedMotion)copy.scale.setScalar(factor*.82);this.copy=copy;}else this.copy=null;
  this.modelHitTargets=[];g.traverseVisible(o=>{if(o.isMesh&&o.userData.hit)this.modelHitTargets.push(o);});
  if(this.lastView!==S.view){this.uiPage=0;this.xrReport=false;}this.lastView=S.view;this.az=['montagem','pareamento','replicacao','desafio'].includes(S.view)?0:.25;this.elev=['montagem','pareamento','replicacao','desafio'].includes(S.view)?0:.12;this.rotation=0;
  $('closeInspect').hidden=!inspectKey;$('stageHint').textContent=inspectKey?'Arraste o objeto ampliado para girar · Voltar ao modelo encerra a inspeção':S.view==='montagem'?'Arraste uma peça até o encaixe, ou selecione e clique no destino':['pareamento','replicacao','desafio'].includes(S.view)?'Selecione um nucleotídeo e clique no espaço · Controles equivalentes na lateral':'Arraste o fundo para girar · use a roda do mouse para aproximar';
  this.legend();this.fit();if(this.xr){this.placeXR();this.buildXRUI();}
 }
 legend(){let pairs=Object.entries(D.bases).map(([l,b])=>[b.hex,l+' · '+b.name]);if(S.view==='replicacao'||S.view==='pareamento')pairs=[['#edbf7c','Fita original'],['#63d4d1','Fita nova'],...pairs.slice(0,4).map(x=>[x[0],x[1].slice(0,1)])];if(S.view==='molecular')pairs=[['#8399a8','Carbono'],['#5789ed','Nitrogênio'],['#f07772','Oxigênio'],['#f5bf69','Fósforo']];$('sceneLegend').innerHTML=pairs.map(([c,n])=>'<span><i style="background:'+c+'"></i>'+n+'</span>').join('');}
 fit(){if(!this.model)return;const box=new T.Box3().setFromObject(this.model),size=box.getSize(new T.Vector3()),aspect=this.stage.clientWidth/Math.max(this.stage.clientHeight,1),height=Math.max(size.y,3.5),width=Math.max(size.x,3);const vf=Math.tan(44*Math.PI/360);this.dist=Math.max(6.8,Math.max(height,width/aspect)/(2*vf)*1.32+size.z*.6);this.target.set(0,.35,0);this.cameraPosition();}
 cameraPosition(){if(this.xr)return;const d=this.dist;this.camera.position.set(this.target.x+d*Math.cos(this.elev)*Math.sin(this.az),this.target.y+d*Math.sin(this.elev),this.target.z+d*Math.cos(this.elev)*Math.cos(this.az));this.camera.lookAt(this.target);this.camera.updateMatrixWorld(true);}
 resize(){if(this.xr)return;const w=Math.max(1,this.stage.clientWidth),h=Math.max(1,this.stage.clientHeight),p=Math.min(devicePixelRatio||1,S.quality==='low'?1:S.quality==='high'?2:1.5);if(w!==this.width||h!==this.height||p!==this.pixel){this.renderer.setPixelRatio(p);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.width=w;this.height=h;this.pixel=p;}}
 center(){this.rotation=0;if(this.model)this.model.rotation.y=0;if(this.xr){this.anchor=null;this.placeXR();this.buildXRUI();}else{this.az=['montagem','pareamento','replicacao','desafio'].includes(S.view)?0:.25;this.elev=.08;this.fit();}}
 zoom(delta){if(this.xr){this.xrZoom=Math.max(.65,Math.min(1.5,(this.xrZoom||1)+delta*.1));this.placeXR();}else{this.dist=Math.max(3.5,Math.min(40,this.dist*(delta>0?.86:1.16)));this.cameraPosition();}}
 pointerRay(e){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.camera.updateMatrixWorld();this.scene.updateMatrixWorld(true);this.ray.setFromCamera(this.pointer,this.camera);return this.ray;}
 hits(ray=this.ray,exclude=null){return ray.intersectObjects(this.modelHitTargets||[],false).filter(h=>{let o=h.object;while(o){if(o===exclude)return false;o=o.parent;}return true;});}
 hitData(hit){if(!hit)return null;const d=hit.object.userData.hit;if(d&&d.type==='atomInstances')return {type:'atom',atom:d.atoms[hit.instanceId]};return d;}
 activate(data){if(!data)return;switch(data.type){case'inspect':inspect(data.key);break;case'context':handle('context:next');break;case'assemblyPiece':handle('part:select:'+data.part);break;case'assemblySlot':handle('part:place:'+data.slot);break;case'basePiece':handle('base:'+data.letter);break;case'pairSlot':if(activePair().selected)pairPlace(data.index);else pairTarget(data.index);break;case'repSlot':repPlace(data.branch,data.index);break;case'template':fb('A base do molde é '+data.letter+'. Escolha o seu complemento.');break;case'strand':handle('rep:identify:'+data.branch+':'+data.strand);break;case'atom':{const a=data.atom,key=D.bases[a.res.slice(-1)]?.key||'dna';inspect(key);fb('Selecionado no 1BNA: átomo '+a.name+' · resíduo '+a.res+' '+a.num+' · cadeia '+a.chain+'. A inspeção ampliada usa uma representação didática da base.');break;}}}
 closestDrop(world,data){let targets=[];if(S.view==='montagem'){for(const [slot,p] of Object.entries(M.assemblyPos))if(!S.assembly.done.includes(slot))targets.push({p:this.model.localToWorld(p.clone()),data:{type:'assemblySlot',slot}});}else if(S.view==='pareamento'||S.view==='desafio'){const p=activePair(),n=p.sequence.length,dy=Math.min(.41,3.4/Math.max(1,n-1)),min=-(n-1)*dy/2+.2;for(let i=0;i<n;i++)if(!p.answers[i])targets.push({p:this.model.localToWorld(new T.Vector3(.86,min+i*dy,0)),data:{type:'pairSlot',index:i}});}else if(S.view==='replicacao'&&S.rep.phase===2){const r=S.rep,t=r.target;if(t){const center=t.branch?2.4:-2.4,x=center+(t.branch?-.68:.68)+(t.branch?.42:-.42);targets.push({p:this.model.localToWorld(new T.Vector3(x,-(r.sequence.length-1)*.43/2+.25+t.index*.43,0)),data:{type:'repSlot',branch:t.branch,index:t.index}});}}
  targets.sort((a,b)=>world.distanceTo(a.p)-world.distanceTo(b.p));const threshold=this.xr?.23:.82;if(targets[0]&&world.distanceTo(targets[0].p)<threshold)return targets[0].data;return null;
 }
 bind(){const canvas=this.canvas;canvas.addEventListener('pointerdown',e=>{if(this.xr)return;this.pointerRay(e);const hit=this.hits()[0];let group=hit?.object;while(group&&group!==this.model&&!group.userData.draggable&&!group.userData.rotateCopy)group=group.parent;const type=group?.userData.draggable?'piece':group?.userData.rotateCopy?'copy':'orbit';let plane=null,start=null;if(type==='piece'){const pos=group.getWorldPosition(new T.Vector3()),dir=this.camera.getWorldDirection(new T.Vector3());plane=new T.Plane().setFromNormalAndCoplanarPoint(dir,pos);start=this.ray.ray.intersectPlane(plane,new T.Vector3());}
   this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false,hit:this.hitData(hit),group,type,plane,start};canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(this.xr)return;if(!this.drag){this.pointerRay(e);canvas.style.cursor=this.hits().length?'pointer':'grab';return;}const d=this.drag,dx=e.clientX-d.x,dy=e.clientY-d.y;d.x=e.clientX;d.y=e.clientY;if(Math.hypot(e.clientX-d.sx,e.clientY-d.sy)>5)d.moved=true;if(!d.moved)return;S.autoRotate=false;$('rotateBtn').textContent='▷ Girar';if(d.type==='piece'){this.pointerRay(e);const p=this.ray.ray.intersectPlane(d.plane,new T.Vector3());if(p){d.group.position.copy(d.group.parent.worldToLocal(p));}}
   else if(d.type==='copy'){d.group.rotation.y+=dx*.008;d.group.rotation.x+=dy*.008;}else{this.az-=dx*.005;this.elev=Math.max(-1.1,Math.min(1.1,this.elev+dy*.005));this.cameraPosition();}});
  canvas.addEventListener('pointerup',e=>{const d=this.drag;this.drag=null;try{canvas.releasePointerCapture(e.pointerId);}catch(_){}if(!d||this.xr)return;if(d.moved&&d.type==='piece'){const world=d.group.getWorldPosition(new T.Vector3()),target=this.closestDrop(world,d.hit);if(d.hit?.type==='assemblyPiece')S.assembly.selected=d.hit.part;else if(d.hit?.type==='basePiece'){if(S.view==='replicacao')S.rep.selected=d.hit.letter;else activePair().selected=d.hit.letter;}if(target)this.activate(target);else{render();fb('Aproxime a peça de um encaixe. Também é possível selecionar e usar o botão Encaixar.','warning');}}
   else if(!d.moved)this.activate(d.hit);});canvas.addEventListener('pointercancel',()=>{this.drag=null;rebuild();});
  canvas.addEventListener('wheel',e=>{e.preventDefault();this.dist=Math.max(3.5,Math.min(40,this.dist+e.deltaY*.012));this.cameraPosition();},{passive:false});
  canvas.addEventListener('keydown',e=>{if(e.key==='Escape'&&inspectKey){handle('inspect:close');return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home',' '].includes(e.key)){e.preventDefault();if(e.key==='Home')this.center();else if(e.key==='+')this.zoom(1);else if(e.key==='-')this.zoom(-1);else if(e.key===' ')handle('rotate');else{this.az+=(e.key==='ArrowLeft'?.08:e.key==='ArrowRight'?-.08:0);this.elev=Math.max(-1.1,Math.min(1.1,this.elev+(e.key==='ArrowUp'?.08:e.key==='ArrowDown'?-.08:0)));this.cameraPosition();}}});
 }
 frame(time,frame){if(!this.renderer)return;const now=performance.now(),dt=Math.min(.05,Math.max(0,(now-this.last)/1000));this.last=now;this.resize();if(S.autoRotate&&this.model){if(this.copy)this.copy.rotation.y+=dt*.3;else this.model.rotation.y+=dt*.2;}if(this.animatedInspect){const i=this.animatedInspect,t=Math.min(1,(now-i.start)/300),s=S.reducedMotion?1:.82+.18*(1-(1-t)**3);i.object.scale.setScalar(i.target*s);if(t>=1)this.animatedInspect=null;}
  if(this.xr){if(this.waitFrames){this.waitFrames--;if(!this.waitFrames){this.anchor=null;this.placeXR();this.buildXRUI();}}this.updateXR(dt);}
  this.renderer.render(this.scene,this.camera);
 }
 head(){const c=this.renderer.xr.getCamera(this.camera),p=c.getWorldPosition(new T.Vector3()),f=c.getWorldDirection(new T.Vector3());f.y=0;if(f.lengthSq()<.001)f.set(0,0,-1);f.normalize();return{p,f,yaw:Math.atan2(-f.x,-f.z)};}
 placeXR(){if(!this.xr||!this.model)return;if(!this.anchor)this.anchor=this.head();const a=this.anchor;this.root.position.set(0,0,0);this.root.scale.setScalar(1);this.root.rotation.set(0,0,0);this.root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(this.model),size=box.getSize(new T.Vector3()),scale=(this.xrZoom||1)*1.28/Math.max(size.x,size.y,5);this.root.scale.setScalar(scale);this.root.rotation.y=a.yaw;this.root.position.copy(a.p).addScaledVector(a.f,1.95);this.root.position.y-=.25;
  this.ui.position.copy(a.p);this.ui.rotation.set(0,a.yaw,0);this.root.updateMatrixWorld(true);this.ui.updateMatrixWorld(true);
 }
 clearXRUI(){for(const c of [...this.ui.children])M.dispose(c);this.uiHits=[];}
 textPlane(title,body,w=.82,h=.66){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=820;const c=canvas.getContext('2d');c.fillStyle='rgba(10,31,46,.97)';c.fillRect(0,0,1024,820);c.strokeStyle='#4c8294';c.lineWidth=3;c.strokeRect(2,2,1020,816);let y=76;const write=(text,size,color)=>{c.font=(size>40?'600 ':'400 ')+size+'px Segoe UI,Arial';c.fillStyle=color;let line='';for(const word of String(text).split(/\s+/)){const next=(line?line+' ':'')+word;if(c.measureText(next).width>910&&line){if(y<788)c.fillText(line,56,y);y+=size*1.5;line=word;}else line=next;}if(line&&y<788){c.fillText(line,56,y);y+=size*1.55;}};write(title,50,'#a4e6d1');y+=24;write(body,37,'#d3eaf6');const texture=new T.CanvasTexture(canvas);texture.encoding=T.sRGBEncoding;texture.minFilter=T.LinearFilter;texture.generateMipmaps=false;return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:texture,transparent:true,side:T.DoubleSide,depthWrite:false}));}
 xrButton(label,cmd,x,y,w=.4,disabled=false){const c=document.createElement('canvas');c.width=768;c.height=192;const g=c.getContext('2d');g.fillStyle=disabled?'#172c3b':'#144957';g.fillRect(0,0,768,192);g.strokeStyle=disabled?'#314756':'#6098a7';g.lineWidth=6;g.strokeRect(3,3,762,186);let size=53;g.font='600 '+size+'px Segoe UI,Arial';while(g.measureText(label).width>710&&size>21){size-=2;g.font='600 '+size+'px Segoe UI,Arial';}g.textAlign='center';g.textBaseline='middle';g.fillStyle=disabled?'#6b8190':'#ebfbff';g.fillText(label,384,96);const tex=new T.CanvasTexture(c);tex.encoding=T.sRGBEncoding;tex.minFilter=T.LinearFilter;tex.generateMipmaps=false;const m=new T.Mesh(new T.PlaneGeometry(w,.10),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));m.position.set(x,y,-1.62);m.rotation.y=-Math.atan2(x,1.62);m.userData.command=cmd;this.ui.add(m);if(!disabled)this.uiHits.push(m);return m;}
 buildXRUI(){if(!this.xr)return;this.clearXRUI();if(this.anchor){this.ui.position.copy(this.anchor.p);this.ui.rotation.y=this.anchor.yaw;}let title=$('lessonPanel').querySelector('h2')?.textContent||'DNA Imersivo',body=instruction+(feedbackText?' '+feedbackText:'');
  if(this.xrReport){const r=report();title='Resumo da experiência';body=S.completed.length+' atividades concluídas. '+r.independent+' respostas independentes. '+r.errors+' tentativas incorretas. '+r.hints+' pistas consultadas. '+r.skips+' posições puladas. Consulte e exporte os registros no modo 3D.';}
  const panel=this.textPlane(title,body);panel.position.set(1.13,.17,-1.65);panel.rotation.y=-.58;this.ui.add(panel);
  let list=this.xrReport?[{label:'Voltar à atividade',cmd:'xr:reportclose'}]:actions;const max=8,pages=Math.max(1,Math.ceil(list.length/max));this.uiPage=Math.min(this.uiPage,pages-1);list.slice(this.uiPage*max,(this.uiPage+1)*max).forEach((a,i)=>this.xrButton(a.label,a.cmd,1.13+(i%2? .22:-.22),-.25-Math.floor(i/2)*.13,.4,a.disabled));if(pages>1){this.xrButton('◀ Opções','xr:prev',.91,-.81,.4,this.uiPage===0);this.xrButton('Mais opções ▶','xr:next',1.35,-.81,.4,this.uiPage===pages-1);}
  D.activities.forEach((a,i)=>this.xrButton(a.label,'view:'+a.id,-1.12,.45-i*.13,.45));this.xrButton('Centralizar','center',-.50,-.79,.4);this.xrButton(S.autoRotate?'Pausar':'Girar','rotate',-.05,-.79,.4);this.xrButton('Ouvir','voice:repeat',-.50,-.93,.4);this.xrButton('Parar voz','voice:stop',-.05,-.93,.4);this.xrButton('Sair do VR','vr',-1.12,-.56,.45);this.xrButton('Catálogo','catalog',-1.12,-.70,.45);
 }
 controllerRay(ctrl){ctrl.updateMatrixWorld(true);const ray=new T.Raycaster();ray.camera=this.renderer.xr.getCamera(this.camera);ray.ray.origin.setFromMatrixPosition(ctrl.matrixWorld);ray.ray.direction.set(0,0,-1).transformDirection(ctrl.matrixWorld);return ray;}
 xrSelect(ctrl){if(this.held.has(ctrl))return;const ray=this.controllerRay(ctrl),ui=ray.intersectObjects(this.uiHits,false)[0];if(ui){const cmd=ui.object.userData.command;if(cmd==='xr:prev'){this.uiPage--;this.buildXRUI();return;}if(cmd==='xr:next'){this.uiPage++;this.buildXRUI();return;}if(cmd==='xr:reportclose'){this.xrReport=false;this.buildXRUI();return;}this.xrReport=false;handle(cmd);return;}this.root.updateMatrixWorld(true);const hit=this.hits(ray)[0];if(hit)this.activate(this.hitData(hit));}
 gripStart(ctrl){const ray=this.controllerRay(ctrl),hit=this.hits(ray)[0];if(!hit)return;const data=this.hitData(hit);if(!['assemblyPiece','basePiece'].includes(data.type)){if(data.type==='inspect'){this.activate(data);}return;}const copy=M.component(data.type==='assemblyPiece'?data.part:'base',data.letter||S.assembly.base);copy.scale.setScalar(.15);copy.position.set(0,-.02,-.32);ctrl.add(copy);copy.userData.heldData=data;this.held.set(ctrl,copy);if(data.type==='assemblyPiece')S.assembly.selected=data.part;else if(S.view==='replicacao')S.rep.selected=data.letter;else activePair().selected=data.letter;}
 gripEnd(ctrl){const copy=this.held.get(ctrl);if(!copy)return;const data=copy.userData.heldData,pos=copy.getWorldPosition(new T.Vector3()),target=this.closestDrop(pos,data);M.dispose(copy);this.held.delete(ctrl);if(target)this.activate(target);else{renderSidebar();fb('Peça selecionada. Aponte para o encaixe e pressione o gatilho.');}}
 controllersInit(){if(this.controllers.length)return;for(let i=0;i<2;i++){const ctrl=this.renderer.xr.getController(i);this.scene.add(ctrl);const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-1)]),line=new T.Line(geo,new T.LineBasicMaterial({color:0x73d8e5}));line.scale.z=3;line.name='ray';ctrl.add(line);ctrl.addEventListener('selectstart',()=>this.xrSelect(ctrl));ctrl.addEventListener('squeezestart',()=>this.gripStart(ctrl));ctrl.addEventListener('squeezeend',()=>this.gripEnd(ctrl));ctrl.addEventListener('disconnected',()=>this.gripEnd(ctrl));this.controllers.push(ctrl);}}
 updateXR(dt){if(!this.anchor)return;this.scene.updateMatrixWorld(true);for(const ctrl of this.controllers){const ray=this.controllerRay(ctrl),hit=ray.intersectObjects(this.uiHits,false)[0]||this.hits(ray)[0];const line=ctrl.getObjectByName('ray');line.material.color.setHex(hit?0xb8f6d7:0x66b7cb);line.scale.z=hit?Math.min(4,hit.distance):3;}
  if(this.xrSession)for(const src of this.xrSession.inputSources){const gp=src.gamepad;if(!gp)continue;const x=gp.axes[2]||0,y=gp.axes[3]||0;if(Math.abs(x)>.23&&this.model){if(this.copy)this.copy.rotation.y-=x*dt;else this.model.rotation.y-=x*dt*.55;}if(Math.abs(y)>.23){this.root.position.y=Math.max(.25,Math.min(2.4,this.root.position.y-y*dt*.25));}}
 }
 async toggleVR(){if(this.xrSession){await this.xrSession.end();return;}if(!window.isSecureContext||!navigator.xr){fb('O modo VR precisa de HTTPS e de um navegador compatível no óculos. Aqui você pode usar o modo 3D.','warning');return;}
  narrator.stop();try{const supported=await navigator.xr.isSessionSupported('immersive-vr');if(!supported){fb('Este dispositivo não informou suporte a VR imersivo.','warning');return;}const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});let reference='local-floor';try{await session.requestReferenceSpace('local-floor');}catch(_){reference='local';}this.renderer.xr.setReferenceSpaceType(reference);try{await this.renderer.xr.setSession(session);}catch(e){await session.end();throw e;}this.xrSession=session;this.xr=true;this.waitFrames=3;this.anchor=null;this.xrZoom=1;this.camera.position.set(0,0,0);this.camera.rotation.set(0,0,0);this.controllersInit();document.body.classList.add('xr');this.ui.visible=true;session.addEventListener('end',()=>this.exitXR());session.addEventListener('visibilitychange',()=>{if(session.visibilityState!=='visible'){narrator.stop();S.autoRotate=false;}});this.placeXR();this.buildXRUI();}catch(e){fb('Não foi possível iniciar VR: '+e.message,'warning');}
 }
 exitXR(){for(const [ctrl,copy] of this.held)M.dispose(copy);this.held.clear();this.xr=false;this.xrSession=null;this.anchor=null;this.clearXRUI();document.body.classList.remove('xr');narrator.stop();this.root.position.set(0,0,0);this.root.rotation.set(0,0,0);this.root.scale.setScalar(1);this.width=0;this.cameraPosition();this.show();}
}
function report(){const list=S.events;return{version:D.version,started:new Date(S.started).toISOString(),exported:new Date().toISOString(),completed:[...S.completed],components:[...S.visited],errors:list.filter(e=>e.correct===false).length,hints:list.filter(e=>e.event==='pista').length,skips:list.filter(e=>e.event==='pulo').length,independent:S.pair.answers.filter((a,i)=>a&&!S.pair.errors[i]&&!S.pair.hints[i]&&!S.pair.skipped[i]).length+S.quiz.transfer.answers.filter((a,i)=>a&&!S.quiz.transfer.errors[i]).length,transfer:{sequence:S.quiz.transfer.sequence,answers:S.quiz.transfer.answers,errors:S.quiz.transfer.errors},pairing:{sequence:S.pair.sequence,answers:S.pair.answers,errors:S.pair.errors,hints:S.pair.hints,skipped:S.pair.skipped},quiz:S.quiz.answers.map((a,i)=>({question:D.questions[i].q,answer:D.questions[i].options[a],correct:a===D.questions[i].correct})),events:[...list]};}
function showSummary(){narrator.stop();if(view&&view.xr){view.xrReport=true;view.buildXRUI();return;}const r=report();const rows=[['Contexto celular',S.completed.includes('contexto')?'Percurso realizado':'Não concluído'],['Exploração da estrutura',S.visited.length+' componentes diferentes'],['Montagem do nucleotídeo',S.completed.includes('montagem')?'Concluída':'Não concluída'],['Pareamento',S.pair.answers.filter(Boolean).length+' / '+S.pair.sequence.length],['Replicação',S.completed.includes('replicacao')?'Originais identificadas':'Em andamento ou não iniciada'],['Desafio',S.quiz.done?'Concluído':'Não concluído']];$('summaryContent').innerHTML='<p class="fine">Um retrato das ações realizadas nesta sessão.</p><table><thead><tr><th>Atividade</th><th>Registro</th></tr></thead><tbody>'+rows.map(([a,b])=>'<tr><td>'+a+'</td><td>'+b+'</td></tr>').join('')+'</tbody></table><div class="metric-row"><span>Tentativas incorretas / previsões revistas</span><b>'+r.errors+'</b></div><div class="metric-row"><span>Pistas consultadas</span><b>'+r.hints+'</b></div><div class="metric-row"><span>Posições puladas</span><b>'+r.skips+'</b></div><p class="fine">Erros e pistas não diminuem um placar global. Use os registros para conversar com o aluno e escolher uma retomada.</p>';$('summaryDialog').showModal();}
function download(name,text,mime){const blob=new Blob([text],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setup(){
 $('activityNav').innerHTML=D.activities.map((a,i)=>'<button data-view="'+a.id+'" aria-label="'+a.label+'"><span class="nav-num">'+String(i+1).padStart(2,'0')+'</span><span>'+a.label+'</span></button>').join('');
 $('activityNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view);});$('sidebar').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b&&!b.disabled)handle(b.dataset.act);});
 $('guideStart').onclick=()=>handle('guide:start');$('summaryBtn').onclick=showSummary;$('settingsBtn').onclick=()=>{$('level').value=S.level;$('settingsDialog').showModal();};$('closeSummary').onclick=()=>$('summaryDialog').close();$('sourcesBtn').onclick=()=>$('sourcesDialog').showModal();
 $('sourcesContent').innerHTML='<p class="fine">A aplicação foi ampliada a partir do DNA Imersivo enviado. Preserva as bases e o pareamento, com atividades adicionais e revisões científicas documentadas em FONTES.md.</p><ul class="resource-list">'+D.sources.map(([t,u])=>'<li><a href="'+u+'" target="_blank" rel="noopener noreferrer">'+esc(t)+'</a></li>').join('')+'</ul><p class="fine">Modelo didático: cores e encaixes convencionais, escalas alteradas entre níveis e replicação conceitual de um trecho. Não simula cinética molecular, uma forquilha completa ou expressão gênica. A estrutura 1BNA é um exemplo separado. Revisão docente recomendada.</p><p class="fine">As conexões curriculares devem ser definidas pelo professor. Completar o pareamento não comprova, isoladamente, domínio de hereditariedade ou das leis de Mendel.</p>';
 $('level').onchange=e=>{S.level=e.target.value;renderSidebar();save();};$('voiceVolume').oninput=e=>{const n=Number(e.target.value);$('voiceValue').textContent=n+'%';narrator.setVoice(n/100);};$('musicVolume').oninput=e=>{const n=Number(e.target.value);$('musicValue').textContent=n+'%';narrator.setMusic($('musicEnabled').checked,n/100);};$('musicEnabled').onchange=e=>narrator.setMusic(e.target.checked);$('autoVoice').checked=S.autoVoice;$('autoVoice').onchange=e=>{S.autoVoice=e.target.checked;if(!S.autoVoice)narrator.stop();save();};$('syntheticVoice').onchange=e=>{narrator.synthetic=e.target.checked;narrator.stop();};$('captionsEnabled').checked=S.captions;$('captionsEnabled').onchange=e=>{S.captions=e.target.checked;$('captionText').hidden=!S.captions;save();};$('reducedMotion').checked=S.reducedMotion;$('reducedMotion').onchange=e=>{S.reducedMotion=e.target.checked;save();};$('quality').value=S.quality;$('quality').onchange=e=>{S.quality=e.target.value;if(view)view.pixel=0;save();};
 $('newStudent').onclick=()=>{if(!confirm('Iniciar um novo aluno? Exporte o resumo antes de limpar esta sessão.'))return;narrator.stop();S=initial();inspectKey=null;feedbackText='';$('settingsDialog').close();save();switchView('estrutura',false);};$('repeatVoice').onclick=()=>narrator.say(instruction,instructionKey);$('stopVoice').onclick=()=>narrator.stop();$('closeInspect').onclick=()=>handle('inspect:close');$('centerBtn').onclick=()=>handle('center');$('rotateBtn').onclick=()=>{handle('rotate');if(view&&view.xr)view.buildXRUI();};$('zoomIn').onclick=()=>view&&view.zoom(1);$('zoomOut').onclick=()=>view&&view.zoom(-1);$('vrBtn').onclick=()=>handle('vr');
 $('fullscreenBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen({navigationUI:'hide'}).catch(()=>fb('O navegador não autorizou tela cheia.','warning'));};
 $('downloadJSON').onclick=()=>download('DNA-resumo.json',JSON.stringify(report(),null,2),'application/json');$('downloadCSV').onclick=()=>{const r=report(),rows=[['evento','habilidade','correto','posicao','escolha','data'],...r.events.map(e=>[e.event,e.skill,e.correct??'',e.position??'',e.choice??'',e.at])];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');download('DNA-atividades.csv',csv,'text/csv;charset=utf-8');};
 $('backPortal').onclick=e=>{e.preventDefault();handle('catalog');};window.addEventListener('pagehide',()=>{save();narrator.dispose();});document.addEventListener('visibilitychange',()=>{if(document.hidden){narrator.stop();narrator.music.pause();}});
 if(T&&M)view=new LabView();else{$('webglError').hidden=false;$('stage').classList.add('error');}
 switchView(S.view,false);$('rotateBtn').textContent=S.autoRotate?'Ⅱ Pausar':'▷ Girar';
 window.DNALab={version:D.version,get state(){return S;},command:handle,report,view,narrator,loadMolecular};
}
setup();
})();
