/* Modelos 3D: maquetes didáticas independentes da avaliação. Three.js r128. */
(function(){'use strict';
const T=THREE,D=DNA_DATA,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),C={old:0xedbf7c,new:0x63d4d1,sugar:0xd7a95b,phosphate:0xeac988};
const material=(color,extra={})=>new T.MeshStandardMaterial(Object.assign({color,roughness:.38,metalness:.1},extra));
function tag(o,data){o.traverse(x=>{if(x.isMesh)x.userData.hit=data;});return o;}
function ball(r,color,pos,extra){const m=new T.Mesh(new T.SphereGeometry(r,20,14),material(color,extra));if(pos)m.position.copy(pos);return m;}
function rod(a,b,r,color,extra){const dir=b.clone().sub(a),m=new T.Mesh(new T.CylinderGeometry(r,r,dir.length(),10),material(color,extra));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(V(0,1,0),dir.normalize());return m;}
function label(text,color='#e7f6ff',width=1.5,size=56){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.clearRect(0,0,512,128);ctx.font='600 '+size+'px Segoe UI,Arial';while(ctx.measureText(text).width>490&&size>17){size-=2;ctx.font='600 '+size+'px Segoe UI,Arial';}ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#031220';ctx.shadowBlur=7;ctx.fillStyle=color;ctx.fillText(text,256,64);const tx=new T.CanvasTexture(c);tx.encoding=T.sRGBEncoding;tx.minFilter=T.LinearMipmapLinearFilter;tx.generateMipmaps=true;tx.anisotropy=8;const sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthWrite:false,depthTest:true}));sp.scale.set(width,width/4,1);return sp;}
function textAt(g,text,x,y,z=0,width=1.5,color){const sp=label(text,color,width);sp.position.set(x,y,z);g.add(sp);return sp;}
function polygon(n,r,depth,color){const s=new T.Shape();for(let i=0;i<n;i++){const a=(i/n)*Math.PI*2+Math.PI/2,x=Math.cos(a)*r,y=Math.sin(a)*r;i?s.lineTo(x,y):s.moveTo(x,y);}s.closePath();const g=new T.ExtrudeGeometry(s,{depth,bevelEnabled:true,bevelThickness:.025,bevelSize:.025,bevelSegments:2,steps:1});g.translate(0,0,-depth/2);return new T.Mesh(g,material(color));}
function component(type,letter='A',ghost=false){const group=new T.Group();const b=D.bases[letter]||D.bases.A;
 if(type==='fosfato'){group.add(ball(.27,C.phosphate));for(let i=0;i<4;i++){const a=i*Math.PI/2,pt=V(Math.cos(a)*.42,Math.sin(a)*.42,i%2?.16:-.16);group.add(rod(V(),pt,.04,C.phosphate),ball(.09,0xf3ded1,pt));}}
 else if(type==='acucar'){group.add(polygon(5,.42,.20,C.sugar));const ld=label('D','#162638',.8,122);ld.position.set(0,0,.15);group.add(ld);}
 else{group.add(polygon(6,.4,.14,b.color));if(b.rings===2){const p=polygon(5,.33,.14,b.color);p.position.x=.48;group.add(p);}const lb=label(letter,'#0b1f2c',1.0,122);lb.position.set(b.rings===2?.18:0,0,.14);group.add(lb);}
 if(ghost)group.traverse(o=>{if(o.material){o.material.transparent=true;o.material.opacity=.16;o.material.depthWrite=false;}});
 return group;
}
function nucleotide(letter='A',color=C.old){const g=new T.Group(),p=component('fosfato'),s=component('acucar'),b=component('base',letter);p.position.set(-.88,.12,0);s.position.set(0,0,0);b.position.set(.9,0,0);g.add(p,s,b,rod(V(-.65,.1),V(-.3,0),.06,color),rod(V(.28,0),V(.6,0),.06,color));tag(p,{type:'inspect',key:'fosfato'});tag(s,{type:'inspect',key:'acucar'});tag(b,{type:'inspect',key:D.bases[letter].key});return g;}
function helix(sequence=D.sequence,opt={}){const group=new T.Group(),n=sequence.length,r=opt.radius||.98,rise=opt.rise||.29,parts=[],oldColors=opt.colors||[C.old,C.old];const point=(i,f)=>{const a=i*(Math.PI*2/10.5)+(f?Math.PI*.84:0);return V(Math.cos(a)*r,(i-(n-1)/2)*rise,-Math.sin(a)*r);};
 for(let f=0;f<2;f++){const pts=[];for(let i=0;i<=(n-1)*5;i++)pts.push(point(i/5,f));const curve=new T.CatmullRomCurve3(pts);const tube=new T.Mesh(new T.TubeGeometry(curve,n*5,.055,8,false),material(oldColors[f]));tag(tube,{type:opt.strandPick?'strand':'inspect',key:'esqueleto',strand:f,branch:opt.branch});group.add(tube);
  for(let i=0;i<n;i++){const p=point(i,f),bead=ball(.09,oldColors[f],p);tag(bead,{type:opt.strandPick?'strand':'inspect',key:'esqueleto',strand:f,branch:opt.branch});group.add(bead);}
  textAt(group,f?'3′':'5′',point(0,f).x,-n*rise/2-.22,point(0,f).z, .48);textAt(group,f?'5′':'3′',point(n-1,f).x,n*rise/2+.22,point(n-1,f).z,.48);
 }
 for(let i=0;i<n;i++){const seq=[sequence[i],D.bases[sequence[i]].pair],p=[point(i,0),point(i,1)],mid=p[0].clone().add(p[1]).multiplyScalar(.5);for(let f=0;f<2;f++){const near=p[f].clone().lerp(mid,.93),part=rod(p[f],near,.073,D.bases[seq[f]].color);tag(part,{type:'inspect',key:D.bases[seq[f]].key,letter:seq[f],index:i});group.add(part);parts.push(part);if(opt.letters!==false){const pos=p[f].clone().lerp(mid,.48);const sp=label(seq[f], '#f4fcff',.26,86);sp.position.copy(pos).add(V(0,.02,.035));group.add(sp);}}
  for(let j=0;j<D.bases[sequence[i]].bonds;j++){const dot=ball(.025,0xb8e1ef,mid.clone().add(V(0,(j-1)*.045,0)));tag(dot,{type:'inspect',key:'ligacoes'});group.add(dot);}
 }
 group.userData.parts=parts;group.userData.point=point;return group;
}
function stageBase(g,width=5,z=0){const m=new T.Mesh(new T.CircleGeometry(width,72),material(0x0b2637,{roughness:.7,metalness:.12}));m.rotation.x=-Math.PI/2;m.position.set(0,-3.15,z);g.add(m);const rim=new T.Mesh(new T.RingGeometry(width-.016,width+.016,72),new T.MeshBasicMaterial({color:0x305d72,side:T.DoubleSide}));rim.rotation.x=-Math.PI/2;rim.position.set(0,-3.14,z);g.add(rim);}
const assemblyPos={fosfato:V(-1.9,.45,0),acucar:V(-.45,.45,0),base:V(1.05,.45,0)};
function assembly(state){const g=new T.Group();stageBase(g,4.9);textAt(g,'MONTE A UNIDADE DO DNA',0,2.2,0,4.5,'#87b9cb');
 for(const [i,type] of ['fosfato','acucar','base'].entries()){const complete=state.done.includes(type),pos=assemblyPos[type];const slot=component(type,state.base,!complete);slot.position.copy(pos);tag(slot,{type:'assemblySlot',slot:type});g.add(slot);textAt(g, type==='base'?'Base nitrogenada':type==='acucar'?'Desoxirribose':'Fosfato',pos.x,-.3,0,1.42,'#9cbed0');if(!complete){const piece=component(type,state.base);piece.position.set(-1.9+i*1.65,-1.85,.35);piece.userData.draggable=true;piece.userData.piece=type;tag(piece,{type:'assemblyPiece',part:type});g.add(piece);if(state.selected===type){const ring=new T.Mesh(new T.TorusGeometry(.59,.018,6,36),new T.MeshBasicMaterial({color:0x93e9ce}));ring.position.copy(piece.position);g.add(ring);}}}
 if(state.done.includes('fosfato')&&state.done.includes('acucar'))g.add(rod(V(-1.52,.45),V(-.8,.45),.055,C.old));if(state.done.includes('acucar')&&state.done.includes('base'))g.add(rod(V(-.1,.45),V(.7,.45),.055,C.old));textAt(g,state.done.length===3?'NUCLEOTÍDEO CONCLUÍDO':'ESCOLHA ABAIXO · ENCAIXE ACIMA',0,-2.75,.2,4.3,state.done.length===3?'#99e5c7':'#7297ac');return g;}
function plateBase(letter,x,y,color,hit,ghost=false,dir=1){const g=new T.Group();g.position.set(x,y,0);const bar=new T.Mesh(new T.BoxGeometry(.74,.22,.18),material(ghost?0x29495e:D.bases[letter].color,{transparent:ghost,opacity:ghost?.55:1}));bar.position.x=dir*.42;g.add(bar,ball(.09,color,V()));if(hit)tag(g,hit);const lt=label(ghost?'?':letter,ghost?'#ffe3a8':'#06202e',.78,118);lt.position.set(dir*.44,0,.17);g.add(lt);return g;}
function tray(g,selected,mode='pair'){for(const [i,l] of ['A','T','C','G'].entries()){const piece=component('base',l);piece.scale.setScalar(.95);piece.position.set((i-1.5)*1.5,-2.45,.3);tag(piece,{type:'basePiece',letter:l,mode});piece.userData.draggable=true;piece.userData.letter=l;g.add(piece);if(l===selected){const ring=new T.Mesh(new T.TorusGeometry(.6,.022,6,40),new T.MeshBasicMaterial({color:0xffffff}));ring.position.copy(piece.position);g.add(ring);}}}
function pair(state){const g=new T.Group(),n=state.sequence.length,dy=Math.min(.41,3.4/Math.max(1,n-1)),minY=-(n-1)*dy/2+.2,maxY=(n-1)*dy/2+.2;
 g.add(rod(V(-1.3,minY),V(-1.3,maxY),.048,C.old),rod(V(1.3,minY),V(1.3,maxY),.048,C.new));
 for(let i=0;i<n;i++){const y=minY+i*dy,l=state.sequence[i],answer=D.bases[l].pair,filled=!!state.answers[i];g.add(plateBase(l,-1.3,y,C.old,{type:'template',letter:l},false,1));g.add(plateBase(answer,1.3,y,C.new,{type:'pairSlot',index:i},!filled,-1));textAt(g,String(i+1),1.95,y,.1,.5,i===state.target?'#ffdb9f':'#8fb0c2');if(i===state.target&&!filled){const marker=new T.Mesh(new T.BoxGeometry(1.05,.31,.07),new T.MeshBasicMaterial({color:0xefd094,wireframe:true}));marker.position.set(.84,y,.02);g.add(marker);}if(filled){g.add(rod(V(-.32,y),V(.32,y),.02,0xb3dbe4));}}
 textAt(g,'5′',-1.3,minY-.28,0,.55);textAt(g,'3′',-1.3,maxY+.3,0,.55);textAt(g,'3′',1.3,minY-.28,0,.55);textAt(g,'5′',1.3,maxY+.3,0,.55);textAt(g,'FITA MOLDE',-1.3,2.55,0,2.2,'#edc17e');textAt(g,'FITA COMPLEMENTAR',1.3,2.55,0,2.7,'#81d8d2');tray(g,state.selected);return g;
}
function replication(state){const g=new T.Group(),n=state.sequence.length,dy=.43,minY=-(n-1)*dy/2+.25,maxY=(n-1)*dy/2+.25;
 if(state.phase===0){const h=helix(state.sequence,{rise:.45});g.add(h);textAt(g,'MOLÉCULA ORIGINAL',0,2.3,0,3.6,'#edc17e');return g;}
 if(state.phase===1){const sep=.95+state.open*2.2;for(let f=0;f<2;f++){const x=f?sep:-sep;g.add(rod(V(x,minY),V(x,maxY),.055,C.old));for(let i=0;i<n;i++){const l=f?D.bases[state.sequence[i]].pair:state.sequence[i];g.add(plateBase(l,x,minY+i*dy,C.old,null,false,f?-1:1));}textAt(g,f?'FITA ORIGINAL 2':'FITA ORIGINAL 1',x,2.3,0,2.35,'#edc17e');textAt(g,f?'3′':'5′',x,minY-.3,0,.4);textAt(g,f?'5′':'3′',x,maxY+.3,0,.4);}textAt(g,'As fitas se separam; o esqueleto de cada uma permanece.',0,-2.4,0,6.4,'#a8cedb');return g;}
 if(state.phase===2){for(let branch=0;branch<2;branch++){const center=branch?2.4:-2.4,oldX=center+(branch?.68:-.68),newX=center+(branch?-.68:.68);g.add(rod(V(oldX,minY),V(oldX,maxY),.05,C.old),rod(V(newX,minY),V(newX,maxY),.05,C.new));textAt(g,'MOLÉCULA '+(branch+1),center,2.3,0,2.7,'#bad9e6');for(let i=0;i<n;i++){const old=branch?D.bases[state.sequence[i]].pair:state.sequence[i],l=D.bases[old].pair;g.add(plateBase(old,oldX,minY+i*dy,C.old,{type:'template',letter:old},false,branch?-1:1));const filled=state.answers[branch][i];g.add(plateBase(l,newX,minY+i*dy,C.new,{type:'repSlot',branch,index:i},!filled,branch?1:-1));if(!filled&&state.target&&state.target.branch===branch&&state.target.index===i){const ring=new T.Mesh(new T.BoxGeometry(.89,.32,.06),new T.MeshBasicMaterial({color:0xf0d39e,wireframe:true}));ring.position.set(newX+(branch?.42:-.42),minY+i*dy,.06);g.add(ring);}}textAt(g,branch?'3′':'5′',oldX,minY-.3,0,.35);textAt(g,branch?'5′':'3′',oldX,maxY+.3,0,.35);textAt(g,branch?'5′':'3′',newX,minY-.3,0,.35);textAt(g,branch?'3′':'5′',newX,maxY+.3,0,.35);
 // Arrows show the pedagogical addition order on the NEW strand, 5′ to 3′.
 const tip=branch?V(newX+.4,maxY+.18,.2):V(newX-.4,minY-.18,.2),tail=branch?V(newX+.4,minY-.1,.2):V(newX-.4,maxY+.1,.2);const arrow=new T.ArrowHelper(tip.clone().sub(tail).normalize(),tail,tip.distanceTo(tail),C.new,.19,.1);g.add(arrow);
 }tray(g,state.selected,'rep');return g;}
 for(let b=0;b<2;b++){const colors=b?[C.new,C.old]:[C.old,C.new];const h=helix(state.sequence,{rise:.44,colors,branch:b,strandPick:true});h.position.set(b?2.15:-2.15,.2,0);h.rotation.y=b?-.25:.3;g.add(h);textAt(g,'MOLÉCULA '+(b+1),b?2.15:-2.15,2.3,0,2.7,'#bddde9');textAt(g,state.identified.includes(b)?'ORIGINAL IDENTIFICADA':'SELECIONE A FITA ORIGINAL',b?2.15:-2.15,-2,0,3.1,state.identified.includes(b)?'#91e0bf':'#edc17e');}
 return g;}
function context(level){const g=new T.Group();if(level===3){g.add(helix());return g;}
 if(level===0){const cell=ball(2.75,0x4eabc0,null,{transparent:true,opacity:.1,side:T.DoubleSide,depthWrite:false,roughness:.15});cell.scale.set(1.4,.85,.8);g.add(cell);const nucleus=ball(1.22,0x6478ac,V(.1,.18,0),{transparent:true,opacity:.56,roughness:.2});tag(nucleus,{type:'context',target:'nucleo'});g.add(nucleus);const center=ball(.38,0xd2a5d2,V(.3,.35,.7));tag(center,{type:'context',target:'nucleo'});g.add(center);for(let i=0;i<7;i++){const a=i*6.283/7,m=ball(.24,0xc5a36b,V(Math.cos(a)*2.5,Math.sin(a)*1.45,.2));m.scale.set(1.75,.8,.8);g.add(m);const ridge=new T.Mesh(new T.TorusGeometry(.19,.034,5,16),material(0x9d7656));ridge.position.copy(m.position);ridge.scale.x=1.5;g.add(ridge);}textAt(g,'NÚCLEO',.1,.18,1.45,1.6,'#f0e1ff');textAt(g,'CÉLULA EUCARIÓTICA · ESQUEMA',0,-2.8,0,4.6,'#89acbd');}
 if(level===1){g.add(ball(2.5,0x6f76ad,null,{transparent:true,opacity:.13,depthWrite:false,side:T.DoubleSide}));const pts=[];for(let i=0;i<120;i++){const t=i/119*Math.PI*9;pts.push(V(Math.sin(t)*1.5, (i/119-.5)*3.4,Math.cos(t*1.31)*1.2));}const fiber=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),240,.075,8,false),material(C.old));tag(fiber,{type:'context',target:'cromatina'});g.add(fiber);textAt(g,'CROMATINA',0,-2.8,0,2.8,'#edc17e');}
 if(level===2){const pts=[];for(let i=0;i<5;i++){const x=(i-2)*1.18;const bead=ball(.42,0x6592aa,V(x,Math.sin(i)*.18,0));tag(bead,{type:'context',target:'dna'});g.add(bead);for(let j=0;j<34;j++){const a=j/33*Math.PI*3.3;pts.push(V(x+Math.cos(a)*.51,Math.sin(a)*.51+Math.sin(i)*.18,(j/33-.5)*.5));}}const coil=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),400,.05,8,false),material(C.old));tag(coil,{type:'context',target:'dna'});g.add(coil);textAt(g,'DNA ASSOCIADO A HISTONAS',0,-1.3,0,4.5,'#edc17e');textAt(g,'Organização esquemática da cromatina',0,-1.75,0,5,'#8dabbd');}
 return g;}
function inspection(key){const data=D.info[key]||D.info.dna;let g;if(key==='dna'){g=helix(D.sequence.slice(0,12));}else if(key==='esqueleto'){g=nucleotide('A');const other=nucleotide('T');other.position.set(0,1.35,0);g.add(other);}else if(key==='ligacoes'){g=new T.Group();g.add(plateBase('A',-1.3,0,C.old,null,false,1),plateBase('T',1.3,0,C.old,null,false,-1));for(let i=0;i<2;i++)g.add(rod(V(-.34,(i-.5)*.14),V(.34,(i-.5)*.14),.025,0xa4cfe1));}else{g=component(key==='fosfato'||key==='acucar'?key:'base',data.letter||'A');}return g;}
function parsePDB(text){const atoms=[];for(const l of text.split(/\r?\n/)){if(!l.startsWith('ATOM  '))continue;const name=l.slice(12,16).trim(),res=l.slice(17,20).trim(),chain=l[21],num=parseInt(l.slice(22,26)),x=parseFloat(l.slice(30,38)),y=parseFloat(l.slice(38,46)),z=parseFloat(l.slice(46,54)),element=l.slice(76,78).trim()||name[0];if([x,y,z].every(Number.isFinite))atoms.push({name,res,chain,num,x,y,z,element});}if(atoms.length<50)throw new Error('Coordenadas do DNA não disponíveis.');return atoms;}
function atomic(atoms,spacefill=false){
 const g=new T.Group(),colors={C:0x8399a8,N:0x5789ed,O:0xf07772,P:0xf5bf69,H:0xecf8ff},radii={C:.35,N:.34,O:.33,P:.46,H:.23};
 let mean=V();atoms.forEach(a=>mean.add(V(a.x,a.y,a.z)));mean.multiplyScalar(1/atoms.length);
 const coords=atoms.map(a=>V(a.x,a.z,-a.y).sub(V(mean.x,mean.z,-mean.y)).multiplyScalar(.14));
 const groups={};atoms.forEach((a,i)=>{(groups[a.element]||(groups[a.element]=[])).push(i);});
 for(const [element,ids] of Object.entries(groups)){
  const geo=new T.SphereGeometry((radii[element]||.34)*.14*(spacefill?3:1),16,12),mesh=new T.InstancedMesh(geo,material(colors[element]||0xcccccc),ids.length),dummy=new T.Object3D();
  ids.forEach((i,n)=>{dummy.position.copy(coords[i]);dummy.updateMatrix();mesh.setMatrixAt(n,dummy.matrix);});
  mesh.instanceMatrix.needsUpdate=true;mesh.userData.hit={type:'atomInstances',atoms:ids.map(i=>atoms[i])};g.add(mesh);
 }
 if(!spacefill){const positions=[];for(let i=0;i<atoms.length;i++)for(let j=i+1;j<atoms.length;j++){
  const a=atoms[i],b=atoms[j];if(a.chain!==b.chain||Math.abs(a.num-b.num)>1)continue;
  const dist=coords[i].distanceTo(coords[j])/.14,threshold=(a.element==='P'||b.element==='P')?1.95:1.75;
  if(dist>.55&&dist<threshold)positions.push(...coords[i].toArray(),...coords[j].toArray());
 }
 const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.add(new T.LineSegments(geom,new T.LineBasicMaterial({color:0xaac6d8})));
 }
 return g;
}
function dispose(g){if(!g)return;const geos=new Set(),mats=new Set(),tex=new Set();g.traverse(o=>{if(o.geometry&&!o.isSprite)geos.add(o.geometry);for(const m of [].concat(o.material||[])){if(!m)continue;mats.add(m);if(m.map)tex.add(m.map);}});geos.forEach(x=>x.dispose());mats.forEach(x=>x.dispose());tex.forEach(x=>x.dispose());if(g.parent)g.parent.remove(g);}
window.DNA_MODELS={V,C,material,ball,rod,label,textAt,component,nucleotide,helix,assembly,pair,replication,context,inspection,parsePDB,atomic,dispose,assemblyPos,tag};
})();
