/* Esqueleto e Movimento · conteúdo (fichas, atividades, roteiro, desafio)
   Pergunta central: como o corpo se sustenta e se move? Nível Introdutório (Fundamental II) e aprofundamento (medio). */
window.ESQ_DATA={
 version:'1.0.0',
 info:{
  corpo:{name:'Corpo inteiro',kind:'Visão geral',color:'#8fc3dd',text:'O corpo se sustenta sobre o esqueleto: 206 ossos que dão forma, protegem órgãos e servem de apoio para os músculos. São os músculos, puxando os ossos, que produzem cada movimento.',detail:'Ossos não se movem sozinhos. Cada movimento é uma parceria entre osso (alavanca), articulação (dobradiça) e músculo (motor).'},
  esqueleto:{name:'Esqueleto',kind:'Visão geral',color:'#e9e4d6',text:'O esqueleto tem duas partes: o eixo (crânio, coluna, costelas e esterno) e os membros (braços e pernas, presos ao eixo pelos ombros e pela pelve).',detail:'Esqueleto axial: 80 ossos. Esqueleto apendicular: 126 ossos. O maior é o fêmur; os menores ficam dentro do ouvido.'},
  cranio:{name:'Crânio',kind:'Esqueleto axial',color:'#e9e4d6',text:'O crânio é um capacete de ossos encaixados que protege o cérebro. Os ossos da face sustentam os olhos, o nariz e os dentes de cima.',detail:'Os ossos do crânio se unem por suturas, linhas fixas que parecem costuras. No bebê elas ainda estão abertas: são as moleiras.',medio:'Aprofundando: a calota craniana é formada pelos ossos frontal, parietais, temporais e occipital; o esfenoide e o etmoide formam a base. As suturas são articulações fibrosas, imóveis.'},
  mandibula:{name:'Mandíbula',kind:'Esqueleto axial',color:'#e9e4d6',text:'A mandíbula é o único osso do crânio que se move. Ela sustenta os dentes de baixo e se articula com o osso temporal, perto da orelha, para abrir e fechar a boca.',detail:'Coloque os dedos na frente da orelha e abra a boca: você sente a articulação da mandíbula trabalhando.'},
  cervical:{name:'Coluna cervical',kind:'Coluna vertebral',color:'#e9e4d6',text:'As sete vértebras cervicais formam o pescoço. A primeira, o atlas, sustenta a cabeça; a segunda, o áxis, tem um pino que deixa a cabeça girar para os lados.',detail:'Dizer "sim" usa a articulação entre o crânio e o atlas. Dizer "não" usa a articulação entre o atlas e o áxis, um pivô.',medio:'Aprofundando: a articulação atlantoaxial é do tipo pivô (trocoide): o dente do áxis gira dentro do anel do atlas, preso pelo ligamento transverso.'},
  toracica:{name:'Coluna torácica',kind:'Coluna vertebral',color:'#e9e4d6',text:'As doze vértebras torácicas ficam nas costas, na altura do peito. Cada uma delas segura um par de costelas, formando a caixa torácica.',detail:'Essa parte da coluna se move pouco, justamente porque está presa às costelas, protegendo o coração e os pulmões.'},
  lombar:{name:'Coluna lombar',kind:'Coluna vertebral',color:'#e9e4d6',text:'As cinco vértebras lombares são as maiores da coluna: elas carregam o peso do tronco. É aqui que aparecem as dores nas costas de quem senta torto ou carrega peso errado.',detail:'Entre uma vértebra e outra há um disco de cartilagem que amortece impactos, como uma almofada.',medio:'Aprofundando: os discos intervertebrais têm um anel fibroso em volta de um núcleo gelatinoso; a hérnia de disco é o deslocamento desse núcleo, que pode comprimir nervos.'},
  sacro:{name:'Sacro',kind:'Coluna vertebral',color:'#e9e4d6',text:'O sacro é um osso triangular formado por cinco vértebras que se fundiram. Ele se encaixa entre os dois ossos do quadril e transmite o peso do tronco para as pernas.',detail:'No bebê as vértebras do sacro ainda são separadas; elas se unem até a vida adulta.'},
  coccix:{name:'Cóccix',kind:'Coluna vertebral',color:'#e9e4d6',text:'O cóccix é a pontinha final da coluna, com três a cinco vértebras minúsculas fundidas. É o que sobrou da cauda dos nossos ancestrais.',detail:'Cair sentado machuca o cóccix, e por isso dói tanto.'},
  costelas:{name:'Costelas',kind:'Esqueleto axial',color:'#e9e4d6',text:'São doze pares de costelas, curvas, presas atrás nas vértebras e na frente no esterno por cartilagens. Elas formam uma gaiola flexível que protege coração e pulmões e se abre quando respiramos.',detail:'Os dois últimos pares são "flutuantes": não chegam ao esterno.'},
  esterno:{name:'Esterno',kind:'Esqueleto axial',color:'#e9e4d6',text:'O esterno é o osso chato no meio do peito, onde as costelas se prendem pela frente. Nele também se apoiam as clavículas.',detail:'Na massagem cardíaca, as mãos pressionam o esterno para comprimir o coração que fica logo atrás.'},
  clavicula:{name:'Clavícula',kind:'Membro superior',color:'#e9e4d6',text:'A clavícula é o osso fino em forma de S que liga o esterno ao ombro. É a única ligação óssea entre o braço e o eixo do corpo.',detail:'É um dos ossos que mais quebram em quedas, porque recebe o impacto do ombro.'},
  escapula:{name:'Escápula',kind:'Membro superior',color:'#e9e4d6',text:'A escápula é a "pá" chata nas costas, atrás do ombro. Ela tem a cavidade onde o úmero se encaixa e serve de ancoragem para vários músculos.',detail:'A escápula desliza sobre as costelas: levante os ombros e sinta como ela se mexe.'},
  umero:{name:'Úmero',kind:'Membro superior',color:'#e9e4d6',text:'O úmero é o osso do braço, entre o ombro e o cotovelo. Sua cabeça redonda se encaixa na escápula, formando a articulação mais móvel do corpo.',detail:'Bater o cotovelo e sentir choque é apertar o nervo ulnar, que passa por um sulco na ponta do úmero.'},
  radio:{name:'Rádio',kind:'Membro superior',color:'#e9e4d6',text:'O rádio é o osso do antebraço do lado do polegar. Ele gira em volta da ulna quando viramos a palma da mão para cima e para baixo.',detail:'Vire a palma da mão para cima e para baixo: é o rádio cruzando por cima da ulna.'},
  ulna:{name:'Ulna',kind:'Membro superior',color:'#e9e4d6',text:'A ulna é o osso do antebraço do lado do dedo mínimo. A ponta dela forma o cotovelo e se encaixa no úmero como uma dobradiça.',detail:'A "pontinha" do cotovelo que você sente é o olécrano, a extremidade da ulna.'},
  mao:{name:'Mão',kind:'Membro superior',color:'#e9e4d6',text:'Cada mão tem 27 ossos: oito no punho (carpo), cinco na palma (metacarpos) e catorze nos dedos (falanges). Tantos ossos pequenos dão à mão sua precisão.',detail:'O polegar tem só duas falanges; os outros dedos têm três. Por isso o polegar é mais curto e consegue se opor aos outros.'},
  pelve:{name:'Pelve (quadril)',kind:'Membro inferior',color:'#e9e4d6',text:'A pelve é a bacia de ossos que liga o tronco às pernas. Cada lado é um osso do quadril, e no meio, atrás, encaixa-se o sacro. Ela sustenta os órgãos do abdome e recebe a cabeça do fêmur.',detail:'A pelve da mulher é mais larga e aberta que a do homem, para a passagem do bebê no parto.'},
  femur:{name:'Fêmur',kind:'Membro inferior',color:'#e9e4d6',text:'O fêmur é o osso da coxa, o maior e mais forte do corpo. Sua cabeça redonda se encaixa no quadril, e a outra ponta forma o joelho com a tíbia.',detail:'O fêmur aguenta várias vezes o peso do corpo ao correr e saltar.',medio:'Aprofundando: o osso compacto da diáfise do fêmur resiste à compressão como o concreto, enquanto o osso esponjoso das extremidades distribui as cargas.'},
  patela:{name:'Patela',kind:'Membro inferior',color:'#e9e4d6',text:'A patela é o osso redondo da frente do joelho. Ela fica dentro do tendão do quadríceps e funciona como uma polia, aumentando a força do músculo para esticar a perna.',detail:'É o maior osso sesamoide do corpo: um osso que nasce dentro de um tendão.'},
  tibia:{name:'Tíbia',kind:'Membro inferior',color:'#e9e4d6',text:'A tíbia é a canela: o osso grosso da frente da perna, que carrega o peso do corpo do joelho até o tornozelo.',detail:'Dá para sentir a tíbia logo abaixo da pele, na frente da perna. Por isso bater a canela dói tanto.'},
  fibula:{name:'Fíbula',kind:'Membro inferior',color:'#e9e4d6',text:'A fíbula é o osso fino ao lado da tíbia. Ela quase não carrega peso: serve de apoio para músculos e forma a saliência externa do tornozelo.',detail:'O "ossinho" de fora do tornozelo é a ponta da fíbula.'},
  pe:{name:'Pé',kind:'Membro inferior',color:'#e9e4d6',text:'Cada pé tem 26 ossos: sete no tornozelo e calcanhar (tarso), cinco no meio (metatarsos) e catorze nos dedos. Eles formam um arco que amortece cada passo.',detail:'O calcâneo, osso do calcanhar, é o maior do pé e recebe o tendão de Aquiles.'},
  biceps:{name:'Bíceps braquial',kind:'Músculo',color:'#d9666c',text:'O bíceps fica na frente do braço. Quando se contrai, ele encurta e puxa o antebraço para cima: é a flexão do cotovelo. Para esticar o braço, ele relaxa e o tríceps trabalha.',detail:'Músculos só puxam, nunca empurram. Por isso trabalham em pares: um dobra, o outro estica.',medio:'Aprofundando: bíceps e tríceps são um par antagonista. Quando o agonista se contrai, o sistema nervoso inibe o antagonista (inervação recíproca).'},
  triceps:{name:'Tríceps braquial',kind:'Músculo',color:'#d9666c',text:'O tríceps fica atrás do braço. Ele é o par do bíceps: quando se contrai, estende o cotovelo e estica o braço, como ao empurrar algo.',detail:'Tem três "cabeças", daí o nome: tri-ceps.'},
  deltoide:{name:'Deltoide',kind:'Músculo',color:'#d9666c',text:'O deltoide é o músculo que arredonda o ombro. Ele levanta o braço para os lados, para a frente e para trás.',detail:'Tem forma de triângulo, como a letra grega delta.'},
  peitoral:{name:'Peitoral maior',kind:'Músculo',color:'#d9666c',text:'O peitoral maior é o grande músculo do peito. Ele traz o braço para a frente e para o meio do corpo, como ao abraçar ou empurrar.',detail:'É o músculo trabalhado na flexão de braço.'},
  reto_abdominal:{name:'Reto abdominal',kind:'Músculo',color:'#d9666c',text:'O reto abdominal vai do esterno até a pelve, na frente da barriga. Ele dobra o tronco para a frente e protege os órgãos do abdome.',detail:'Os "gominhos" do abdome são as faixas desse músculo separadas por tendões.'},
  obliquo:{name:'Oblíquo externo',kind:'Músculo',color:'#d9666c',text:'Os oblíquos ficam nas laterais do abdome. Eles giram e inclinam o tronco para os lados.',detail:'Trabalham junto com o reto abdominal para manter a postura.'},
  trapezio:{name:'Trapézio',kind:'Músculo',color:'#d9666c',text:'O trapézio é o grande músculo entre o pescoço, os ombros e o meio das costas. Ele levanta os ombros e move a escápula.',detail:'A tensão no "pescoço" depois de horas no celular é o trapézio cansado.'},
  latissimo:{name:'Latíssimo do dorso',kind:'Músculo',color:'#d9666c',text:'O latíssimo é o músculo largo das costas. Ele puxa o braço para baixo e para trás, como ao subir numa barra ou nadar.',detail:'É o músculo que dá o formato de V nas costas dos nadadores.'},
  gluteo:{name:'Glúteo máximo',kind:'Músculo',color:'#d9666c',text:'O glúteo máximo é o maior músculo do corpo. Ele estende o quadril: levanta o tronco ao ficar de pé, sobe escadas e impulsiona a corrida.',detail:'É tão grande porque andar sobre duas pernas exige muito dele.'},
  quadriceps:{name:'Quadríceps',kind:'Músculo',color:'#d9666c',text:'O quadríceps é o grupo de quatro músculos da frente da coxa. Ele estica o joelho: chutar uma bola ou levantar da cadeira depende dele.',detail:'Seu tendão passa pela patela e se prende na tíbia.'},
  isquiotibiais:{name:'Isquiotibiais',kind:'Músculo',color:'#d9666c',text:'Os isquiotibiais ficam atrás da coxa. São o par do quadríceps: dobram o joelho e ajudam a estender o quadril.',detail:'Costumam ficar "encurtados" em quem passa o dia sentado; alongar ajuda.'},
  gastrocnemio:{name:'Gastrocnêmio (panturrilha)',kind:'Músculo',color:'#d9666c',text:'O gastrocnêmio é a "batata da perna". Ele se prende ao calcanhar pelo tendão de Aquiles e empurra o pé para baixo: é o impulso de cada passo e de cada salto.',detail:'O tendão de Aquiles é o mais forte do corpo.'},
  tibial_anterior:{name:'Tibial anterior',kind:'Músculo',color:'#d9666c',text:'O tibial anterior fica na frente da canela. Ele levanta a ponta do pé, para o pé não arrastar no chão quando andamos.',detail:'É o par da panturrilha: um levanta a ponta do pé, o outro abaixa.'},
  esternocleidomastoideo:{name:'Esternocleidomastóideo',kind:'Músculo',color:'#d9666c',text:'É o músculo que aparece na lateral do pescoço quando viramos a cabeça. Ele gira e inclina a cabeça.',detail:'O nome longo diz onde ele se prende: esterno, clavícula e osso mastoide (atrás da orelha).'},
  joelho:{name:'Joelho (dobradiça)',kind:'Articulação',color:'#f1e9c4',text:'O joelho é uma dobradiça: dobra e estica num só plano. Entre o fêmur e a tíbia ficam os meniscos, almofadas de cartilagem, e os ligamentos cruzados, que seguram a articulação no lugar.',detail:'Lesão de ligamento cruzado é comum no futebol, quando o joelho gira com o pé preso no chão.',medio:'Aprofundando: o LCA impede que a tíbia deslize para a frente; o LCP, para trás. Os colaterais limitam o movimento lateral; os meniscos distribuem a carga.'},
  cotovelo:{name:'Cotovelo (dobradiça)',kind:'Articulação',color:'#f1e9c4',text:'O cotovelo também é uma dobradiça: a ulna se encaixa no úmero e só permite dobrar e esticar.',detail:'Girar a palma da mão não é o cotovelo: é o rádio girando sobre a ulna.'},
  ombro:{name:'Ombro (bola e soquete)',kind:'Articulação',color:'#f1e9c4',text:'O ombro é uma articulação de bola e soquete: a cabeça redonda do úmero gira numa cavidade rasa da escápula. É a articulação mais móvel do corpo, e por isso também a que mais se desloca.',detail:'Um anel de cartilagem, o labrum, aprofunda a cavidade e ajuda a segurar a cabeça do úmero.'},
  quadril:{name:'Quadril (bola e soquete)',kind:'Articulação',color:'#f1e9c4',text:'O quadril também é bola e soquete, mas com uma cavidade funda e ligamentos fortes: menos mobilidade que o ombro, muito mais estabilidade para carregar o corpo.',detail:'É a articulação mais substituída por prótese em idosos.'},
  pivo:{name:'Atlas e áxis (pivô)',kind:'Articulação',color:'#f1e9c4',text:'Entre a primeira e a segunda vértebra do pescoço há um pivô: o dente do áxis gira dentro do anel do atlas. É o movimento de dizer "não".',detail:'Um ligamento forte segura o dente no lugar; é ele que protege a medula nesse ponto.'}
 },
 activities:[
  {id:'contexto',label:'Contexto',title:'Como o corpo se sustenta e se move?',subtitle:'Da pele ao esqueleto, do esqueleto aos músculos.',kicker:'LOCALIZE'},
  {id:'explorar',label:'Ossos',title:'Duzentos e seis ossos. Vamos aos principais.',subtitle:'Aponte em um osso para ver a ficha e ouvir a explicação.',kicker:'EXPLORE'},
  {id:'movimento',label:'Movimento',title:'O que dobra o braço?',subtitle:'Contraia o bíceps e veja o par de músculos trabalhando.',kicker:'EXPERIMENTE'},
  {id:'coluna',label:'Coluna',title:'Monte a coluna vertebral',subtitle:'Coloque as regiões na ordem, do pescoço ao cóccix.',kicker:'ORGANIZE'},
  {id:'articulacoes',label:'Articulações',title:'Onde o esqueleto dobra?',subtitle:'Encontre os três tipos de articulação no esqueleto.',kicker:'INVESTIGUE'},
  {id:'braco',label:'Monte o braço',title:'Do ombro à mão',subtitle:'Coloque os ossos do braço na ordem, do ombro aos dedos.',kicker:'ORGANIZE'},
  {id:'musculos',label:'Músculos',title:'Os motores do corpo',subtitle:'Aponte em um músculo para ver o que ele move.',kicker:'EXPLORE'},
  {id:'desafio',label:'Desafio',title:'Agora, explique o que descobriu.',subtitle:'Situações para aplicar o que você viu.',kicker:'APLIQUE'}
 ],
 guide:[
  {view:'contexto',title:'Localize',goal:'Veja o corpo inteiro, depois só o esqueleto e, por fim, os músculos por cima dos ossos.',check:'contexto',audio:'aula-contexto'},
  {view:'explorar',title:'Explore os ossos',goal:'Aponte em pelo menos três ossos e ouça a ficha de cada um.',check:'explorar',audio:'aula-explorar'},
  {view:'movimento',title:'Mova o braço',goal:'Dobre e estique o cotovelo três vezes observando o bíceps e o tríceps.',check:'movimento',audio:'aula-movimento'},
  {view:'coluna',title:'Monte a coluna',goal:'Ordene as cinco regiões da coluna, do pescoço ao cóccix.',check:'coluna',audio:'aula-coluna'},
  {view:'articulacoes',title:'Encontre as articulações',goal:'Localize no esqueleto uma dobradiça, uma bola-e-soquete e um pivô.',check:'articulacoes',audio:'aula-articulacoes'},
  {view:'braco',title:'Monte o braço',goal:'Ordene os ossos do braço, do ombro até a mão.',check:'braco',audio:'aula-braco'},
  {view:'musculos',title:'Explore os músculos',goal:'Aponte em pelo menos três músculos e descubra o que cada um move.',check:'musculos',audio:'aula-musculos'},
  {view:'desafio',title:'Desafio',goal:'Responda às oito situações explicando o que acontece no corpo.',check:'desafio',audio:'aula-desafio'}
 ],
 context:[
  {name:'Corpo inteiro',text:'Por fora vemos a pele. Por dentro, tudo se apoia no esqueleto. Selecione o esqueleto para tirar a pele.',target:'esqueleto'},
  {name:'Esqueleto',text:'Este é o esqueleto: 206 ossos. No meio, o eixo: crânio, coluna, costelas. Nas laterais, os membros. Selecione um osso para vestir os músculos.',target:'musculos'},
  {name:'Músculos sobre os ossos',text:'Os músculos se prendem aos ossos e, ao se contrair, puxam. É assim que o esqueleto se move. Agora explore cada parte.'}
 ],
 sequencias:{
  coluna:{titulo:'COLUNA VERTEBRAL',ordem:['cervical','toracica','lombar','sacro','coccix'],rotulos:{cervical:'Cervical (7)',toracica:'Torácica (12)',lombar:'Lombar (5)',sacro:'Sacro',coccix:'Cóccix'},cor:'#d7e3ea',
   pistas:['A primeira região sustenta a cabeça: é o pescoço.','Depois vêm as vértebras que seguram as costelas.','As maiores vértebras ficam na parte baixa das costas.','O osso triangular que encaixa na pelve vem antes da pontinha final.']},
  braco:{titulo:'DO OMBRO À MÃO',ordem:['clavicula','escapula','umero','antebraco','mao'],rotulos:{clavicula:'Clavícula',escapula:'Escápula',umero:'Úmero',antebraco:'Rádio e ulna',mao:'Mão'},cor:'#d7e3ea',
   pistas:['Comece pelo osso fino que liga o esterno ao ombro.','A "pá" das costas recebe a cabeça do osso do braço.','Entre o cotovelo e o punho há dois ossos lado a lado.','Os 27 ossos pequenos ficam por último.']}
 },
 questions:[
  {id:'par',skill:'movimento',q:'Para dobrar o cotovelo, o que acontece com o bíceps e o tríceps?',options:['Os dois se contraem ao mesmo tempo','O bíceps se contrai e o tríceps relaxa','O tríceps se contrai e o bíceps relaxa'],correct:1,why:'Músculos só puxam. Para dobrar o cotovelo, o bíceps encurta e puxa o antebraço, enquanto o tríceps relaxa. Para esticar, é o contrário.'},
  {id:'dobradica',skill:'articulacoes',q:'Qual articulação funciona como uma dobradiça, movendo-se num só plano?',options:['Ombro','Joelho','Quadril'],correct:1,why:'O joelho dobra e estica num só plano, como uma dobradiça. Ombro e quadril são bola-e-soquete, que giram em várias direções.'},
  {id:'ombro',skill:'articulacoes',q:'Por que o ombro é a articulação que mais se desloca?',options:['Porque é a mais móvel, com cavidade rasa','Porque não tem ligamentos','Porque o úmero é oco'],correct:0,why:'A cabeça do úmero gira numa cavidade rasa da escápula. Muita mobilidade cobra o preço de menos estabilidade.'},
  {id:'coluna',skill:'coluna',q:'Em que ordem vêm as regiões da coluna, de cima para baixo?',options:['Cervical, lombar, torácica, sacro','Cervical, torácica, lombar, sacro','Torácica, cervical, lombar, sacro'],correct:1,why:'Cervical (pescoço), torácica (costelas), lombar (parte baixa das costas), sacro e cóccix.'},
  {id:'pivo',skill:'articulacoes',q:'Quando você vira a cabeça para dizer "não", qual articulação está trabalhando?',options:['Entre o crânio e o atlas','Entre o atlas e o áxis (pivô)','Entre a mandíbula e o temporal'],correct:1,why:'O dente do áxis gira dentro do anel do atlas: um pivô. Dizer "sim" usa a articulação entre o crânio e o atlas.'},
  {id:'protecao',skill:'explorar',q:'Qual conjunto de ossos protege o coração e os pulmões?',options:['Pelve e sacro','Costelas, esterno e vértebras torácicas','Escápula e clavícula'],correct:1,why:'As costelas, presas atrás nas vértebras torácicas e na frente no esterno, formam a caixa torácica que protege coração e pulmões.'},
  {id:'patela',skill:'explorar',q:'Para que serve a patela?',options:['Para proteger o joelho e dar vantagem ao quadríceps, como uma polia','Para ligar a tíbia à fíbula','Para produzir sangue'],correct:0,why:'A patela fica dentro do tendão do quadríceps e desvia a força do músculo, facilitando esticar a perna.'},
  {id:'salto',skill:'musculos',q:'Ao saltar, qual músculo empurra o pé contra o chão pelo tendão de Aquiles?',options:['Tibial anterior','Gastrocnêmio (panturrilha)','Reto abdominal'],correct:1,why:'O gastrocnêmio se prende ao calcanhar pelo tendão de Aquiles e empurra o pé para baixo: é o impulso do salto e da corrida.'}
 ],
 sources:[
  ['Z-Anatomy (atlas 3D, CC BY-SA 4.0)','https://github.com/LluisV/Z-Anatomy'],
  ['BNCC · Ciências · EF06CI07, EF06CI08 e EF06CI09','http://basenacionalcomum.mec.gov.br/'],
  ['Khan Academy · Sistema musculoesquelético','https://pt.khanacademy.org/science/biology'],
  ['Anatomia humana · Sobotta (referência docente)','https://www.elsevier.com/']
 ]
};
