/* Corpo Humano Imersivo v3.0 · controlador das atividades, interface e WebXR (dois módulos: respiração/circulação/digestão e esqueleto/movimento)
   Base: arquitetura do DNA Imersivo v2.1 (Portal 360º VR). Regra 9: data-act + delegação. */
(function(){'use strict';
const D=CORPO_DATA,M=window.CORPO_MODELS,ME=window.ESQ_MODELS,T=window.THREE,$=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const embaralhar=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const freshSeq=(id)=>{const ordem=D.sequencias[id].ordem;return {colocados:Array(ordem.length).fill(null),target:0,selected:null,erros:0,pistas:0,done:false,bandeja:embaralhar(ordem)};};
const initial=()=>({version:D.version,view:'contexto',modulo:'resp',level:'intro',guided:false,gstep:0,context:0,esqContext:0,visited:[],completed:[],
  movimento:{fase:'repouso',abertura:0,ciclos:0,flexionou:false},coluna:freshSeq('coluna'),braco:freshSeq('braco'),artic:{dobradica:false,esferoide:false,pivo:false},esqQuiz:{phase:1,index:0,answers:[],done:false},
  respire:{fase:'repouso',abertura:0,ciclos:0,inspirou:false},caminhoAr:freshSeq('caminhoAr'),caminhoSangue:freshSeq('caminhoSangue'),alimento:freshSeq('alimento'),troca:{o2:false,co2:false},
  quiz:{phase:1,index:0,answers:[],done:false},events:[],started:Date.now(),autoRotate:false,reducedMotion:window.matchMedia('(prefers-reduced-motion: reduce)').matches,quality:'balanced',captions:true,autoVoice:true});
const INSPECT_VIEWS=['explorar','troca','respire','alimento','ossos','musculos','articulacoes','coluna','braco','esqContexto','esqDesafio','movimento'],SEQ_VIEWS=['caminhoAr','caminhoSangue','alimento','coluna','braco'],ESQ_VIEWS=['esqContexto','ossos','movimento','coluna','articulacoes','braco','musculos','esqDesafio'];
const moduloDe=v=>(D.activities.find(a=>a.id===v)||{}).modulo||'resp';const ehOsso=k=>!!(ME&&ME.APOIO)&&!ME.APOIO[k]&&!!window.ESQ_GLTF&&(!!window.ESQ_GLTF.C.esqueleto[k]||!!window.ESQ_GLTF.C.esqueleto[k+'_d']);const ehMusculo=k=>!!(ME&&ME.APOIO&&ME.APOIO[k]);
const guideAtual=()=>S.modulo==='esq'?D.esqGuide:D.guide;const quizState=()=>S.modulo==='esq'?S.esqQuiz:S.quiz;const questoes=()=>S.modulo==='esq'?D.esqQuestions:D.questions;
let S=initial(),view=null,feedbackText='',instruction='',instructionKey=null,inspectKey=null;
try{const saved=JSON.parse(sessionStorage.getItem('pde_corpo_v3')||'null');if(saved&&saved.version===D.version&&D.activities.some(a=>a.id===saved.view)){S=Object.assign(initial(),saved);}}catch(_){}
function save(){try{sessionStorage.setItem('pde_corpo_v3',JSON.stringify(S));}catch(_){}}
function log(event,skill,value={}){S.events.push({event,skill,...value,at:new Date().toISOString()});if(S.events.length>600)S.events.shift();save();updateStatus();}
function mark(key){if(!S.completed.includes(key))S.completed.push(key);save();}
function fb(text,type='ok'){feedbackText=text;const e=$('feedback');e.hidden=!text;e.className='feedback'+(type==='ok'?'':' '+type);e.textContent=text;if(view&&view.xr)view.buildXRUI();}
function setInstruction(text,key){instruction=text;instructionKey=key;const c=$('captionText');c.textContent=text;c.hidden=!S.captions;}
const narrator=new CorpoNarrator(({state,text})=>{const labels={loading:'CARREGANDO NARRAÇÃO',playing:'ÁUDIO GRAVADO',speech:'VOZ DO NAVEGADOR',text:'ORIENTAÇÃO EM TEXTO',ended:'NARRAÇÃO CONCLUÍDA',stopped:'ORIENTAÇÃO DA ATIVIDADE'};$('voiceStatus').textContent=labels[state]||'ORIENTAÇÃO';$('stopVoice').hidden=!['loading','playing','speech'].includes(state);if(text){$('captionText').textContent=text;$('captionText').hidden=!S.captions;}});
function btn(label,cmd,style='',disabled=false){return '<button data-act="'+esc(cmd)+'" class="'+esc(style)+'" '+(disabled?'disabled':'')+'>'+esc(label)+'</button>';}
function pill(s){return '<span class="status-pill">'+esc(s)+'</span>';}
function isGuideDone(){const key=guideAtual()[S.gstep].check;if(key==='explorar')return S.visited.filter(k=>!ehOsso(k)&&!ehMusculo(k)).length>=3;if(key==='ossos')return S.visited.filter(ehOsso).length>=3;if(key==='musculos')return S.visited.filter(ehMusculo).length>=3;return S.completed.includes(key);}
function updateStatus(){$('sessionStatus').textContent=S.visited.length+' estruturas investigadas · '+S.completed.length+' atividades concluídas';}
function renderGuide(){const p=$('guidePanel');p.hidden=!S.guided;if(!S.guided)return;const G=guideAtual(),g=G[S.gstep],done=isGuideDone();p.innerHTML='<span class="eyebrow">AULA GUIADA · '+(S.gstep+1)+' / '+G.length+'</span><h3>'+esc(g.title)+'</h3><p>'+esc(g.goal)+'</p><progress value="'+(S.gstep+(done?1:0))+'" max="'+D.guide.length+'"></progress><div class="button-row">'+btn('Ouvir','guide:listen')+btn(S.gstep===guideAtual().length-1?'Concluir aula':'Continuar','guide:next','primary',!done)+'</div>'+btn('Sair da aula guiada','guide:exit','wide')+(done?'<p>✓ Objetivo desta etapa realizado.</p>':'<p>Complete a ação indicada para liberar a próxima etapa.</p>');}
function seqUI(id){const st=S[id],cfg=D.sequencias[id];let h='<p>Escolha uma peça e clique na posição de destino, ou arraste a peça até ela. A ordem segue o percurso real.</p><div class="pair-choices seq">';
 cfg.ordem.forEach(k=>{const usado=st.colocados.includes(k);h+='<button data-act="seq:pick:'+k+'" class="'+(st.selected===k?'selected':'')+'" '+(usado?'disabled':'')+' style="--base:'+cfg.cor+'">'+esc(cfg.rotulos[k])+'</button>';});h+='</div>';
 h+='<p class="fine">'+(st.done?'Percurso completo.':'Destino atual: posição '+(st.target+1)+' de '+cfg.ordem.length+'.')+'</p><div class="slot-choices">';st.colocados.forEach((k,i)=>{h+='<button class="'+(k?'filled':'')+(st.target===i?' current':'')+'" data-act="seq:target:'+i+'">'+(k?esc(cfg.rotulos[k]):String(i+1).padStart(2,'0'))+'</button>';});h+='</div>';
 h+='<div class="metric-row"><span>Posições completadas</span><b>'+st.colocados.filter(Boolean).length+' / '+cfg.ordem.length+'</b></div><div class="metric-row"><span>Tentativas incorretas</span><b>'+st.erros+'</b></div>';
 h+='<div class="button-row">'+btn('Encaixar','seq:place','primary',!st.selected||st.done)+btn('Pista','seq:hint','',st.done)+'</div>'+btn('Recomeçar','seq:reset','wide');return h;}
function renderSidebar(){renderGuide();let h='',a=D.activities.find(x=>x.id===S.view);h+='<span class="eyebrow">'+esc(a.kicker)+' · '+(S.level==='medio'?'APROFUNDAMENTO':'INTRODUÇÃO')+'</span>';
 if(inspectKey&&INSPECT_VIEWS.includes(S.view)){const i=D.info[inspectKey]||D.info.corpo;h+='<h2>'+esc(i.name)+'</h2>'+pill(i.kind)+'<p>'+esc(i.text)+'</p><details'+(S.level==='medio'?' open':'')+'><summary>Mais detalhes</summary><p>'+esc(i.detail)+'</p>'+(S.level==='medio'&&i.medio?'<p class="medio">'+esc(i.medio)+'</p>':'')+'</details>'+(S.level!=='medio'&&i.medio?'<p class="fine">Ajustes → Ensino Médio libera o aprofundamento desta ficha.</p>':'')+'<div class="button-row">'+btn('Ouvir novamente','inspect:listen','primary')+btn('Fechar ficha','inspect:close')+'</div>';setInstruction(i.text,inspectKey);}
 else if(S.view==='contexto'){const c=D.context[S.context];h+='<h2>'+esc(c.name)+'</h2><div class="step-list">'+D.context.map((x,i)=>'<span class="'+(i<=S.context?'done':'')+'"></span>').join('')+'</div><p>'+esc(c.text)+'</p><div class="button-row">'+btn('Etapa anterior','context:back','',S.context===0)+btn(c.target?(c.target==='torax'?'Olhar o tórax':'Ver os órgãos'):'Explorar os órgãos',c.target?'context:next':'view:explorar','primary')+'</div><div class="info-card"><p>Representação esquemática. Os órgãos foram ampliados e as proporções simplificadas para facilitar a observação.</p></div>';setInstruction(c.text,'contexto-'+S.context);}
 else if(S.view==='explorar'){h+='<h2>Explore o tórax</h2><p>Aponte em um órgão na cena ou escolha abaixo. A ficha aparece aqui, com explicação em áudio.</p><div class="pair-choices seq">'+['coracao','pulmoes','traqueia','bronquios','diafragma','alveolos','laringe','nariz'].map(k=>'<button data-act="inspect:'+k+'" style="--base:'+D.info[k].color+'">'+esc(D.info[k].name)+'</button>').join('')+'</div><div class="info-card"><p>Pergunta central: <b>como o oxigênio que respiramos chega às células?</b><br>Investigados: '+S.visited.length+'.</p></div>';setInstruction('Aponte em um órgão para ver a ficha e ouvir a explicação. Investigue pelo menos três.','aula-explorar');}
 else if(S.view==='respire'){const r=S.respire;h+='<h2>Controle a respiração</h2><p>Aperte <b>Inspirar</b> para o diafragma descer e os pulmões encherem. Depois <b>Expirar</b>. No óculos, aponte no diafragma e aperte o gatilho.</p><div class="metric-row"><span>Fase</span><b>'+({repouso:'Em repouso',inspirando:'Inspirando',expirando:'Expirando'})[r.fase]+'</b></div><div class="metric-row"><span>Ciclos completos</span><b>'+r.ciclos+' / 3</b></div><div class="button-row">'+btn('⬇ Inspirar','resp:in','primary',r.fase==='inspirando')+btn('⬆ Expirar','resp:out','',r.fase!=='inspirando')+'</div><div class="info-card"><p>Inspirar: o diafragma se contrai e desce, o tórax aumenta, o ar entra.<br>Expirar: o diafragma relaxa e sobe, o tórax diminui, o ar sai.</p></div>'+(r.ciclos>=3?'<p>✓ Três ciclos completos. Você viu o motor da respiração.</p>':'');setInstruction(r.ciclos>=3?'Três ciclos completos. O diafragma é o músculo que faz o ar entrar e sair.':'Faça o pulmão respirar: inspire e expire três vezes controlando o diafragma.',r.ciclos>=3?'respire-concluido':'aula-respire');}
 else if(S.view==='caminhoAr'){h+='<h2>Caminho do ar</h2>'+seqUI('caminhoAr');setInstruction(S.caminhoAr.done?'Percurso completo: nariz, faringe, laringe, traqueia, brônquios e alvéolos.':'Coloque as etapas na ordem em que o ar passa, do nariz até os alvéolos.',S.caminhoAr.done?'ar-concluido':'aula-ar');}
 else if(S.view==='caminhoSangue'){h+='<h2>Caminho do sangue</h2>'+pill('POBRE EM O₂ · AZUL')+pill('RICO EM O₂ · VERMELHO')+seqUI('caminhoSangue');setInstruction(S.caminhoSangue.done?'Percurso completo: o sangue passa pelo lado direito, vai aos pulmões, volta pelo lado esquerdo e segue para o corpo.':'Siga a gota de sangue que chega do corpo: por onde ela passa até voltar oxigenada para as células?',S.caminhoSangue.done?'sangue-concluido':'aula-sangue');}
 else if(S.view==='alimento'){h+='<h2>Caminho do alimento</h2>'+pill('TUBO DIGESTÓRIO')+pill('GLÂNDULAS ANEXAS')+seqUI('alimento')+'<p class="fine">Aponte em um órgão da cena para ver a ficha (estômago, fígado, intestinos).</p>';setInstruction(S.alimento.done?'Percurso completo: boca, faringe, esôfago, estômago, intestino delgado e intestino grosso. Os nutrientes entram no sangue no intestino delgado.':'Siga o alimento desde a boca. Em que ordem ele passa pelos órgãos do tubo digestório?',S.alimento.done?'alimento-concluido':'aula-alimento');}
 else if(S.view==='troca'){const t=S.troca;h+='<h2>Troca gasosa</h2><p>No alvéolo, o ar e o sangue ficam separados por uma parede finíssima. Selecione cada molécula para ver o caminho que ela faz.</p><div class="button-row">'+btn((t.o2?'✓ ':'')+'O₂ → sangue','gas:o2','',t.o2)+btn((t.co2?'✓ ':'')+'CO₂ → ar','gas:co2','',t.co2)+'</div><div class="info-card"><p>'+(t.o2&&t.co2?'✓ Troca completa: o sangue sai rico em oxigênio e o gás carbônico é eliminado na expiração.':'O oxigênio atravessa a parede do alvéolo para o capilar; o gás carbônico faz o caminho contrário.')+'</p></div>'+btn('Recomeçar','gas:reset','wide');setInstruction(t.o2&&t.co2?'Troca completa. O sangue segue rico em oxigênio para o coração.':'Selecione a molécula de oxigênio e depois a de gás carbônico para ver a troca gasosa.',t.o2&&t.co2?'troca-concluida':'aula-troca');}
 else if(S.view==='esqContexto'){const c=D.esqContext[S.esqContext];h+='<h2>'+esc(c.name)+'</h2><div class="step-list">'+D.esqContext.map((x,i)=>'<span class="'+(i<=S.esqContext?'done':'')+'"></span>').join('')+'</div><p>'+esc(c.text)+'</p><div class="button-row">'+btn('Etapa anterior','ectx:back','',S.esqContext===0)+btn(c.target?(c.target==='esqueleto'?'Tirar a pele':'Vestir os músculos'):'Explorar os ossos',c.target?'ectx:next':'view:ossos','primary')+'</div><div class="info-card"><p>Modelo anatômico real (Z-Anatomy): proporções de um adulto. Alguns detalhes foram simplificados para a leitura em sala.</p></div>';setInstruction(c.text,'esq-contexto-'+S.esqContext);}
 else if(S.view==='ossos'){h+='<h2>Explore os ossos</h2><p>Aponte em um osso na cena ou escolha abaixo. A ficha aparece aqui, com explicação em áudio.</p><div class="pair-choices seq">'+['cranio','cervical','costelas','umero','mao','pelve','femur','pe'].map(k=>'<button data-act="inspect:'+k+'" style="--base:'+D.info[k].color+'">'+esc(D.info[k].name)+'</button>').join('')+'</div><div class="info-card"><p>Pergunta central: <b>como o corpo se sustenta e se move?</b><br>Ossos investigados: '+S.visited.filter(ehOsso).length+'.</p></div>';setInstruction('Aponte em um osso para ver a ficha e ouvir a explicação. Investigue pelo menos três.','esq-aula-explorar');}
 else if(S.view==='musculos'){h+='<h2>Explore os músculos</h2><p>Aponte em um músculo na cena ou escolha abaixo. A ficha mostra o que ele move e em que ossos se prende.</p><div class="pair-choices seq">'+['biceps','triceps','deltoide','peitoral','reto_abdominal','gluteo','quadriceps','gastrocnemio'].map(k=>'<button data-act="inspect:'+k+'" style="--base:'+D.info[k].color+'">'+esc(D.info[k].name)+'</button>').join('')+'</div><div class="info-card"><p>Músculos só puxam. Cada movimento tem um músculo que faz e outro que desfaz.<br>Músculos investigados: '+S.visited.filter(ehMusculo).length+'.</p></div>';setInstruction('Aponte em um músculo para ver o que ele move. Investigue pelo menos três.','esq-aula-musculos');}
 else if(S.view==='movimento'){const r=S.movimento;h+='<h2>Dobre e estique o braço</h2><p>Aperte <b>Flexionar</b> para o bíceps contrair e o antebraço subir. Depois <b>Estender</b>: o tríceps assume. No óculos, aponte no braço e aperte o gatilho.</p><div class="metric-row"><span>Fase</span><b>'+({repouso:'Braço estendido',flexionando:'Flexionando (bíceps)',estendendo:'Estendendo (tríceps)'})[r.fase]+'</b></div><div class="metric-row"><span>Ciclos completos</span><b>'+r.ciclos+' / 3</b></div><div class="button-row">'+btn('⤴ Flexionar','mov:in','primary',r.fase==='flexionando')+btn('⤵ Estender','mov:out','',r.fase!=='flexionando')+'</div><div class="info-card"><p>Flexionar: o bíceps encurta e engrossa; puxa o rádio; o cotovelo dobra.<br>Estender: o tríceps encurta; puxa a ulna; o cotovelo abre.</p></div>'+(r.ciclos>=3?'<p>✓ Três ciclos completos. Você viu um par de músculos antagonistas.</p>':'');setInstruction(r.ciclos>=3?'Três ciclos completos. Bíceps e tríceps são um par: um dobra, o outro estica.':'Dobre e estique o cotovelo três vezes, observando qual músculo engrossa em cada fase.',r.ciclos>=3?'esq-movimento-concluido':'esq-aula-movimento');}
 else if(S.view==='coluna'){h+='<h2>Monte a coluna</h2>'+pill('33 VÉRTEBRAS')+pill('5 REGIÕES')+seqUI('coluna')+'<p class="fine">Aponte numa região do recorte ao lado para ver a ficha.</p>';setInstruction(S.coluna.done?'Coluna completa: cervical, torácica, lombar, sacro e cóccix. As curvas da coluna amortecem o peso da cabeça e do tronco.':'Coloque as regiões da coluna na ordem, do pescoço até o cóccix.',S.coluna.done?'esq-coluna-concluido':'esq-aula-coluna');}
 else if(S.view==='braco'){h+='<h2>Monte o braço</h2>'+pill('MEMBRO SUPERIOR')+seqUI('braco')+'<p class="fine">Aponte num osso do recorte ao lado para ver a ficha.</p>';setInstruction(S.braco.done?'Braço completo: clavícula, escápula, úmero, rádio e ulna, e a mão com seus 27 ossos.':'Coloque os ossos do braço na ordem, do ombro até a mão.',S.braco.done?'esq-braco-concluido':'esq-aula-braco');}
 else if(S.view==='articulacoes'){const t=S.artic;const n=['dobradica','esferoide','pivo'].filter(k=>t[k]).length;h+='<h2>Três tipos de articulação</h2><p>Aponte nos marcadores do esqueleto para descobrir o tipo de cada articulação. Encontre as três.</p><div class="button-row">'+btn((t.dobradica?'✓ ':'')+'Dobradiça','artic:dobradica','',t.dobradica)+btn((t.esferoide?'✓ ':'')+'Bola e soquete','artic:esferoide','',t.esferoide)+btn((t.pivo?'✓ ':'')+'Pivô','artic:pivo','',t.pivo)+'</div><div class="info-card"><p>'+(n===3?'✓ Três tipos encontrados. Dobradiça: um plano. Bola e soquete: todas as direções. Pivô: rotação.':'Dobradiça (joelho, cotovelo): dobra num só plano. Bola e soquete (ombro, quadril): gira em todas as direções. Pivô (atlas e áxis): roda em torno de um eixo.')+'</p></div>'+btn('Recomeçar','artic:reset','wide');setInstruction(n===3?'Três tipos encontrados. O formato dos ossos decide como a articulação se move.':'Encontre no esqueleto uma dobradiça, uma articulação de bola e soquete e um pivô.',n===3?'esq-artic-concluida':'esq-aula-articulacoes');}
 else if(S.view==='desafio'||S.view==='esqDesafio'){const q=quizState(),Q=questoes(),pref=S.modulo==='esq'?'esq-':'';h+='<h2>'+(q.done?'Desafio concluído':'Explique o que descobriu')+'</h2>';if(!q.done){const item=Q[q.index],answer=q.answers[q.index];h+=pill('Situação '+(q.index+1)+' / '+Q.length)+'<p>'+esc(item.q)+'</p><div class="answer-list">';item.options.forEach((o,i)=>{h+=btn(o,'quiz:answer:'+i,answer!==undefined?(i===item.correct?'correct':i===answer?'incorrect':''):'',answer!==undefined);});h+='</div>';if(answer!==undefined)h+='<div class="info-card"><p>'+esc(item.why)+'</p></div>'+btn(q.index===Q.length-1?'Concluir desafio':'Próxima situação','quiz:next','wide primary');setInstruction(item.q,pref+'desafio-'+item.id);}else{const correct=q.answers.filter((a,i)=>a===Q[i].correct).length;h+='<div class="big-stat">'+correct+' / '+Q.length+'</div><p>Situações respondidas corretamente na primeira tentativa.</p><div class="button-row">'+btn('Ver resumo','summary','primary')+btn('Novo desafio','quiz:reset')+'</div>';setInstruction('Desafio concluído. Compare suas respostas com as explicações e retome as atividades que geraram dúvidas.',pref+'desafio-fim');}}
 $('lessonPanel').innerHTML=h;$('modelNote').textContent='Modelos anatômicos reais (Z-Anatomy, CC BY-SA 4.0), simplificados para a leitura em sala e no óculos. Alvéolo, capilar e volume dos músculos em movimento são representações.';
 if(view&&view.xr)view.buildXRUI();updateStatus();}
function rebuild(){if(view)view.show();}
function render(){renderSidebar();rebuild();save();}
function switchView(id,announce=true){if(!D.activities.some(a=>a.id===id))return;narrator.stop(false);inspectKey=null;const mudouModulo=moduloDe(id)!==S.modulo;S.view=id;S.modulo=moduloDe(id);if(mudouModulo&&S.guided){S.guided=false;}$('activityNav').querySelectorAll('[data-modulo]').forEach(b=>b.classList.toggle('active',b.dataset.modulo===S.modulo));fb('');log('atividade','navegacao',{value:id});const a=D.activities.find(x=>x.id===id);$('sceneTitle').textContent=a.title;$('sceneSub').textContent=a.subtitle;$('sceneKicker').textContent=a.kicker;document.querySelectorAll('#activityNav button[data-mod]').forEach(b=>{const on=b.dataset.view===id;b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false');b.hidden=b.dataset.mod!==S.modulo;});render();if(announce&&S.autoVoice){const intro=!S.guided&&((id==='desafio'&&S.quiz.index===0&&!S.quiz.done&&S.quiz.answers[0]===undefined)?'aula-desafio':(id==='contexto'&&S.context===0)?'aula-contexto':(id==='esqDesafio'&&S.esqQuiz.index===0&&!S.esqQuiz.done&&S.esqQuiz.answers[0]===undefined)?'esq-aula-desafio':(id==='esqContexto'&&S.esqContext===0)?'esq-aula-contexto':null);const g=intro&&D.guide.concat(D.esqGuide).find(x=>x.audio===intro);if(g)narrator.say(g.goal,intro,{text:instruction,key:instructionKey});else narrator.say(instruction,instructionKey);}}
function inspect(key,announce=true){if(!D.info[key])return;inspectKey=key;if(!S.visited.includes(key))S.visited.push(key);if(S.visited.filter(k=>!ehOsso(k)&&!ehMusculo(k)).length>=3)mark('explorar');if(S.visited.filter(ehOsso).length>=3)mark('ossos');if(S.visited.filter(ehMusculo).length>=3)mark('musculos');log('inspecao','explorar',{component:key});render();if(announce&&S.autoVoice)narrator.say(D.info[key].text,key);}
function seqState(){return SEQ_VIEWS.includes(S.view)?S[S.view]:null;}
function seqPlace(index){const st=seqState();if(!st||st.done)return;const cfg=D.sequencias[S.view];if(index===undefined)index=st.target;if(st.colocados[index])return;if(!st.selected){st.target=index;render();fb('Escolha primeiro uma peça.','warning');return;}
 const ok=cfg.ordem[index]===st.selected;log('tentativa',S.view,{position:index,choice:st.selected,correct:ok});if(!ok){st.erros++;render();fb('Ainda não. Pense em que ponto do percurso essa etapa acontece.','warning');return;}
 st.colocados[index]=st.selected;st.selected=null;st.target=st.colocados.findIndex(x=>!x);st.done=st.target<0;if(st.done)mark(S.view);render();fb(st.done?'Percurso completo!':'Encaixe correto. Próxima posição.');if(st.done&&S.autoVoice)narrator.say(instruction,instructionKey);}
function handle(cmd){const [kind,op,a]=cmd.split(':');
 if(kind==='view'){switchView(op);return;}
 if(kind==='context'){if(op==='next'&&S.context<2){S.context++;log('contexto','localizacao',{level:S.context});if(S.context===2)mark('contexto');}if(op==='back')S.context=Math.max(0,S.context-1);render();if(S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='ectx'){if(op==='next'&&S.esqContext<2){S.esqContext++;log('contexto','esqueleto',{level:S.esqContext});if(S.esqContext===2)mark('esqContexto');}if(op==='back')S.esqContext=Math.max(0,S.esqContext-1);render();if(S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='modulo'){const a=D.activities.find(x=>x.modulo===op);if(a)switchView(a.id);return;}
 if(kind==='inspect'){if(op==='close'){inspectKey=null;render();narrator.stop();}else if(op==='listen'){const i=D.info[inspectKey]||D.info.corpo;narrator.say(i.text,inspectKey||'corpo');}else inspect(op);return;}
 if(kind==='resp'){const r=S.respire;if(op==='in'&&r.fase!=='inspirando'){r.fase='inspirando';r.inspirou=true;log('respirar','respiracao',{fase:'in'});}if(op==='out'&&r.fase==='inspirando'){r.fase='expirando';if(r.inspirou){r.ciclos++;r.inspirou=false;log('respirar','respiracao',{fase:'out',ciclos:r.ciclos});if(r.ciclos>=3)mark('respire');}}if(op==='toggle'){handle(r.fase==='inspirando'?'resp:out':'resp:in');return;}renderSidebar();save();if(r.ciclos===3&&op==='out'&&S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='seq'){const st=seqState();if(!st)return;if(op==='pick'){if(!st.colocados.includes(a)){st.selected=a;render();fb('Selecionado: '+D.sequencias[S.view].rotulos[a]+'. Clique na posição de destino.');}return;}if(op==='target'){if(!st.colocados[Number(a)]){st.target=Number(a);render();}return;}if(op==='place'){seqPlace();return;}if(op==='at'){seqPlace(Number(a));return;}
  if(op==='hint'&&!st.done){st.pistas++;log('pista',S.view,{position:st.target});const cfg=D.sequencias[S.view];fb(st.pistas>cfg.pistas.length?'Posição '+(st.target+1)+': '+cfg.rotulos[cfg.ordem[st.target]]+'.':cfg.pistas[(st.pistas-1)%cfg.pistas.length],'warning');return;}
  if(op==='reset'){S[S.view]=freshSeq(S.view);render();fb('Peças embaralhadas de novo.');return;}}
 if(kind==='gas'){const t=S.troca;if(op==='o2'&&!t.o2){t.o2=true;log('troca','troca-gasosa',{gas:'o2'});renderSidebar();save();fb('O oxigênio atravessou a parede do alvéolo e entrou no sangue.');if(S.autoVoice)narrator.say('O oxigênio atravessa a parede fina do alvéolo e se liga à hemoglobina das hemácias. O sangue fica vermelho-vivo.','troca-o2',t.co2?{text:instruction,key:'troca-concluida'}:null);}
  if(op==='co2'&&!t.co2){t.co2=true;log('troca','troca-gasosa',{gas:'co2'});renderSidebar();save();fb('O gás carbônico saiu do sangue para o ar do alvéolo. Ele será eliminado na expiração.');if(S.autoVoice)narrator.say('O gás carbônico sai do sangue para o ar do alvéolo e será eliminado quando você expirar.','troca-co2',t.o2?{text:instruction,key:'troca-concluida'}:null);}
  if(t.o2&&t.co2&&!S.completed.includes('troca')){mark('troca');renderSidebar();}
  if(op==='reset'){S.troca={o2:false,co2:false};render();}return;}
 if(kind==='mov'){const r=S.movimento;if(op==='in'&&r.fase!=='flexionando'){r.fase='flexionando';r.flexionou=true;log('mover','movimento',{fase:'in'});}if(op==='out'&&r.fase==='flexionando'){r.fase='estendendo';if(r.flexionou){r.ciclos++;r.flexionou=false;log('mover','movimento',{fase:'out',ciclos:r.ciclos});if(r.ciclos>=3)mark('movimento');}}if(op==='toggle'){handle(r.fase==='flexionando'?'mov:out':'mov:in');return;}renderSidebar();save();if(r.ciclos===3&&op==='out'&&S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='artic'){const t=S.artic;const TXT={dobradica:['Dobradiça: o joelho dobra e estica num só plano, como a dobradiça de uma porta.','esq-artic-dobradica','joelho'],esferoide:['Bola e soquete: a cabeça redonda do úmero gira na cavidade da escápula, em todas as direções.','esq-artic-esferoide','ombro'],pivo:['Pivô: o dente do áxis gira dentro do anel do atlas. É o movimento de dizer não.','esq-artic-pivo','pivo']};
  if(TXT[op]){const novo=!t[op];t[op]=true;log('articulacao','articulacoes',{tipo:op});if(novo){const n=['dobradica','esferoide','pivo'].filter(k=>t[k]).length;if(n===3)mark('articulacoes');inspectKey=TXT[op][2];if(!S.visited.includes(inspectKey))S.visited.push(inspectKey);render();fb(TXT[op][0]);if(S.autoVoice)narrator.say(TXT[op][0],TXT[op][1],n===3?{text:instruction,key:'esq-artic-concluida'}:null);}else{inspect(TXT[op][2]);}return;}
  if(op==='reset'){S.artic={dobradica:false,esferoide:false,pivo:false};inspectKey=null;render();}return;}
 if(kind==='quiz'){const q=quizState(),Q=questoes();if(op==='answer'&&!q.done&&q.answers[q.index]===undefined){const i=Number(a),item=Q[q.index];q.answers[q.index]=i;log('avaliacao',item.skill,{question:item.id,choice:i,correct:i===item.correct});render();fb(item.why,i===item.correct?'ok':'warning');}if(op==='next'&&q.answers[q.index]!==undefined){q.index++;if(q.index>=Q.length){q.done=true;mark(S.modulo==='esq'?'esqDesafio':'desafio');}render();if(S.autoVoice)narrator.say(instruction,instructionKey);}if(op==='reset'){const f={phase:1,index:0,answers:[],done:false};if(S.modulo==='esq')S.esqQuiz=f;else S.quiz=f;render();}return;}
 if(kind==='guide'){if(op==='start'){const esq=S.modulo==='esq';S.gstep=0;if(esq)S.esqContext=0;else S.context=0;switchView(esq?'esqContexto':'contexto');S.guided=true;renderSidebar();return;}if(op==='listen'){const g=guideAtual()[S.gstep];narrator.say(g.goal,g.audio);return;}if(op==='next'&&isGuideDone()){if(S.gstep===guideAtual().length-1){S.guided=false;mark(S.modulo==='esq'?'aulaEsq':'aula');renderSidebar();showSummary();return;}S.gstep++;switchView(guideAtual()[S.gstep].view);return;}if(op==='exit'){S.guided=false;renderSidebar();save();return;}}
 if(kind==='summary'){showSummary();return;}if(kind==='center'){if(view)view.center();return;}if(kind==='rotate'){S.autoRotate=!S.autoRotate;$('rotateBtn').textContent=S.autoRotate?'Ⅱ Pausar':'▷ Girar';$('rotateBtn').setAttribute('aria-pressed',String(S.autoRotate));save();return;}if(kind==='voice'){if(op==='stop')narrator.stop();else narrator.say(instruction,instructionKey);return;}
 if(kind==='vr'){if(view)view.toggleVR();return;}if(kind==='catalog'){narrator.dispose();if(view&&view.xrSession)view.xrSession.end().finally(returnCatalog);else returnCatalog();return;}
}
function returnCatalog(){const url=new URL('../../?catalog=1',location.href).href;try{if(window.top!==window){window.top.location.href=url;return;}}catch(_){}location.href=url;}

class LabView {
 constructor(){this.stage=$('stage');this.canvas=$('scene');this.xr=false;this.xrSession=null;this.drag=null;this.controllers=[];this.held=new Map();this.uiPage=0;this.xrReport=false;this.anchor=null;this.width=0;this.height=0;this.pixel=0;this.az=.25;this.elev=.12;this.dist=12;this.target=new T.Vector3(0,.2,0);this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.last=performance.now();
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(44,1,.025,200);this.scene.add(this.camera);this.root=new T.Group();this.scene.add(this.root);this.ui=new T.Group();this.scene.add(this.ui);this.uiHits=[];
  this.scene.add(new T.HemisphereLight(0xdcefff,0x2a3440,.62));const key=new T.DirectionalLight(0xfff1e0,.95);key.position.set(5,7,8);this.scene.add(key);const fill=new T.DirectionalLight(0x8fd0ec,.6);fill.position.set(-6,2,-4);this.scene.add(fill);
  try{this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true});this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.setClearColor(0x081929,0);this.renderer.xr.enabled=true;this.renderer.setAnimationLoop((time,frame)=>this.frame(time,frame));this.bind();this.ok=true;}catch(e){console.error(e);$('webglError').hidden=false;this.stage.classList.add('error');this.ok=false;}
 }
 clear(){this.hoverMeshes=[];this.hoverKey=null;if(this.model)M.dispose(this.model);this.model=null;this.drag=null;for(const [c,o] of this.held){M.dispose(o);this.held.delete(c);}this.animatedInspect=null;this.copy=null;}
 show(){if(!this.ok)return;this.clear();const g=new T.Group();this.model=g;this.root.add(g);this.root.position.set(0,0,0);this.root.rotation.set(0,0,0);this.root.scale.setScalar(1);let obj;
  if(S.view==='contexto')obj=M.contexto(S.context);
  else if(S.view==='respire')obj=M.respire(S.respire);
  else if(S.view==='caminhoAr')obj=M.sequencia(S.caminhoAr,D.sequencias.caminhoAr);
  else if(S.view==='caminhoSangue')obj=M.sequencia(S.caminhoSangue,D.sequencias.caminhoSangue);
  else if(S.view==='alimento')obj=M.sequencia(S.alimento,D.sequencias.alimento);
  else if(S.view==='troca')obj=M.alveolo(S.troca);
  else if(S.view==='desafio'){obj=M.torax({costelas:false});obj.scale.setScalar(1.0);obj.position.y=-.3;}
  else if(S.view==='esqContexto')obj=ME.contexto(S.esqContext);
  else if(S.view==='ossos')obj=ME.explorar();
  else if(S.view==='movimento')obj=ME.movimento(S.movimento);
  else if(S.view==='coluna')obj=ME.sequencia(S.coluna,D.sequencias.coluna);
  else if(S.view==='braco')obj=ME.sequencia(S.braco,D.sequencias.braco);
  else if(S.view==='articulacoes')obj=ME.articulacoes(S.artic);
  else if(S.view==='musculos')obj=ME.musculosCena();
  else if(S.view==='esqDesafio')obj=ME.desafio();
  else obj=M.explorar();
  g.add(obj);this.obj=obj;
  if(inspectKey&&INSPECT_VIEWS.includes(S.view)){obj.position.set(-2.4,-.1,-2.5);obj.scale.multiplyScalar(.65);const copy=(ehOsso(inspectKey)||ehMusculo(inspectKey)||(ME.ARTIC&&ME.ARTIC[inspectKey]))?ME.inspection(inspectKey):M.inspection(inspectKey);copy.traverse(o=>{if(o.isMesh&&!o.userData.hit)o.userData.hit={type:'inspect',key:inspectKey};});copy.position.set(.95,.05,1.1);copy.userData.rotateCopy=true;g.add(copy);this.copy=copy;this.fitCopy(true);}
  this.modelHitTargets=[];g.traverseVisible(o=>{if(o.isMesh&&o.userData.hit)this.modelHitTargets.push(o);});
  if(this.lastView!==S.view){this.uiPage=0;this.xrReport=false;}this.lastView=S.view;this.az=SEQ_VIEWS.includes(S.view)||S.view==='troca'?0:S.view==='movimento'?-1.25:.25;this.elev=SEQ_VIEWS.includes(S.view)?0:.1;
  $('closeInspect').hidden=!inspectKey;$('stageHint').textContent=inspectKey?'Arraste a peça ampliada para girar · Fechar ficha volta ao modelo':SEQ_VIEWS.includes(S.view)?'Selecione uma peça e clique na posição · Controles equivalentes na lateral':S.view==='respire'?'Clique no diafragma para inspirar e expirar':S.view==='movimento'?'Clique no braço para dobrar e esticar':S.view==='articulacoes'?'Clique nos marcadores amarelos':'Arraste o fundo para girar · use a roda do mouse para aproximar';
  this.legend();this.fit();if(this.xr){this.placeXR();this.buildXRUI();}
 }
 legend(){let pairs=[['#d9434f','Coração'],['#e99a9a','Pulmões'],['#9ed6ef','Vias aéreas'],['#b48ae8','Diafragma']];if(S.view==='alimento')pairs=[['#ffb3a7','Boca'],['#e9a070','Esôfago'],['#e08a50','Estômago'],['#f0c07a','Intestino delgado'],['#c99a6b','Intestino grosso'],['#9e4d40','Fígado']];else if(S.view==='caminhoSangue'||S.view==='troca')pairs=[['#4f7fe0','Sangue pobre em O₂'],['#e8484f','Sangue rico em O₂'],['#9ff3ff','O₂'],['#9a9ab0','CO₂']];else if(S.view==='articulacoes')pairs=[['#ffd166','Marcador a descobrir'],['#3ddc84','Tipo identificado'],['#e9e4d6','Ossos']];else if(S.view==='coluna')pairs=[['#fff0b3','Cervical'],['#ffd166','Torácica'],['#f4a261','Lombar'],['#e76f51','Sacro'],['#c9516b','Cóccix']];else if(ESQ_VIEWS.includes(S.view))pairs=[['#e9e4d6','Ossos'],['#b8343f','Músculos'],['#f1e9c4','Ligamentos'],['#cfe3ee','Cartilagem']];$('sceneLegend').innerHTML=pairs.map(([c,n])=>'<span><i style="background:'+c+'"></i>'+n+'</span>').join('');}
 fit(){if(!this.model)return;const box=this.boxDe(this.model);if(box.isEmpty())return;const size=box.getSize(new T.Vector3()),aspect=this.stage.clientWidth/Math.max(this.stage.clientHeight,1),height=Math.max(size.y,3.5),width=Math.max(size.x,3);const vf=Math.tan(44*Math.PI/360);this.dist=Math.max(6.5,Math.max(height,width/aspect)/(2*vf)*1.25+size.z*.6);const c=box.getCenter(new T.Vector3());this.target.set(0,c.y,0);this.cameraPosition();}
 cameraPosition(){if(this.xr)return;const d=this.dist;this.camera.position.set(this.target.x+d*Math.cos(this.elev)*Math.sin(this.az),this.target.y+d*Math.sin(this.elev),this.target.z+d*Math.cos(this.elev)*Math.cos(this.az));this.camera.lookAt(this.target);this.camera.updateMatrixWorld(true);}
 resize(){if(this.xr)return;const w=Math.max(1,this.stage.clientWidth),h=Math.max(1,this.stage.clientHeight),p=Math.min(devicePixelRatio||1,S.quality==='low'?1:S.quality==='high'?2:1.5);if(w!==this.width||h!==this.height||p!==this.pixel){this.renderer.setPixelRatio(p);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.width=w;this.height=h;this.pixel=p;}}
 center(){if(this.model)this.model.rotation.y=0;if(this.xr){this.anchor=null;this.placeXR();this.buildXRUI();}else{this.az=SEQ_VIEWS.includes(S.view)||S.view==='troca'?0:S.view==='movimento'?-1.25:.25;this.elev=.08;this.fit();}}
 zoom(delta){if(this.xr){this.xrZoom=Math.max(.65,Math.min(1.5,(this.xrZoom||1)+delta*.1));this.placeXR();}else{this.dist=Math.max(3.5,Math.min(40,this.dist*(delta>0?.86:1.16)));this.cameraPosition();}}
 pointerRay(e){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.camera.updateMatrixWorld();this.scene.updateMatrixWorld(true);this.ray.setFromCamera(this.pointer,this.camera);return this.ray;}
 hits(ray=this.ray,exclude=null){return ray.intersectObjects(this.modelHitTargets||[],false).filter(h=>{let o=h.object;while(o){if(o===exclude)return false;o=o.parent;}return true;});}
 hitData(hit){if(!hit)return null;return hit.object.userData.hit;}
 boxDe(obj,tudo){const box=new T.Box3();const v=new T.Vector3();obj.updateMatrixWorld(true);obj.traverse(o=>{if(!tudo){if(o.userData.semEnquadre)return;let p=o.parent,ign=false;while(p&&p!==obj){if(p.userData.semEnquadre){ign=true;break;}p=p.parent;}if(ign)return;}if(o.isMesh&&o.geometry){if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();const bb=o.geometry.boundingBox;for(let i=0;i<8;i++){v.set(i&1?bb.max.x:bb.min.x,i&2?bb.max.y:bb.min.y,i&4?bb.max.z:bb.min.z).applyMatrix4(o.matrixWorld);box.expandByPoint(v);}}});return box;}
 refreshHits(){this.modelHitTargets=[];if(this.model)this.model.traverseVisible(o=>{if(o.isMesh&&o.userData.hit)this.modelHitTargets.push(o);});}
 fitCopy(anim){const copy=this.copy;if(!copy)return;copy.scale.setScalar(1);copy.updateMatrixWorld(true);const box=this.boxDe(copy);if(box.isEmpty())return;const size=box.getSize(new T.Vector3());const maior=Math.max(size.x,size.y,size.z);if(!isFinite(maior)||maior<1e-4)return;const factor=2.6/maior;const local=box.getCenter(new T.Vector3()).sub(copy.position);copy.position.set(.95,.05,1.1).sub(local.multiplyScalar(factor));copy.scale.setScalar(factor);if(anim){this.animatedInspect={object:copy,target:factor,start:performance.now()};if(!S.reducedMotion)copy.scale.setScalar(factor*.82);}}
 modeloChegou(){this.refreshHits();if(this.copy)this.fitCopy(false);if(this.xr){this.placeXR();}else if(!this.drag&&this.model&&!this._fitFeito){this.fit();}}
 setHover(hit){const data=hit?hit.object.userData.hit:null;const chave=data?(data.key||data.type+':'+(data.index??data.gas??data.target??'')):null;if(chave===this.hoverKey)return;
  (this.hoverMeshes||[]).forEach(m=>{if(m.material&&m.material.emissive)m.material.emissive.setHex(m.userData.emissiveBase||0);});this.hoverMeshes=[];this.hoverKey=chave;if(!chave)return;
  (this.modelHitTargets||[]).forEach(m=>{const d=m.userData.hit;if(!d)return;const k=d.key||d.type+':'+(d.index??d.gas??d.target??'');if(k!==chave||!m.material||!m.material.emissive)return;if(m.userData.emissiveBase===undefined)m.userData.emissiveBase=m.material.emissive.getHex();m.material.emissive.setHex(0x3a6d80);this.hoverMeshes.push(m);});
  if(!this.xr)this.canvas.style.cursor='pointer';}
 activate(data){if(!data)return;switch(data.type){
  case'inspect':inspect(data.key);break;
  case'context':handle('context:next');break;
  case'respirar':handle('resp:toggle');break;
  case'mover':handle('mov:toggle');break;
  case'artic':handle('artic:'+data.tipo);break;
  case'seqPiece':handle('seq:pick:'+data.key);break;
  case'seqSlot':{const st=seqState();if(st&&st.selected)seqPlace(data.index);else handle('seq:target:'+data.index);break;}
  case'gas':handle('gas:'+data.gas);break;}}
 closestDrop(world){const st=seqState();if(!st||!this.obj||!this.obj.userData.slots)return null;const {top,dy}=this.obj.userData.slots;let best=null,bd=1e9;st.colocados.forEach((k,i)=>{if(k)return;const p=this.obj.localToWorld(new T.Vector3(.9,top-i*dy,0));const d=world.distanceTo(p);if(d<bd){bd=d;best={type:'seqSlot',index:i};}});const threshold=this.xr?.25:.9;return bd<threshold?best:null;}
 bind(){const canvas=this.canvas;canvas.addEventListener('pointerdown',e=>{if(this.xr)return;this.pointerRay(e);const hit=this.hits()[0];let group=hit?.object;while(group&&group!==this.model&&!group.userData.draggable&&!group.userData.rotateCopy)group=group.parent;const type=group?.userData.draggable?'piece':group?.userData.rotateCopy?'copy':'orbit';let plane=null;if(type==='piece'){const pos=group.getWorldPosition(new T.Vector3()),dir=this.camera.getWorldDirection(new T.Vector3());plane=new T.Plane().setFromNormalAndCoplanarPoint(dir,pos);}
   this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false,hit:this.hitData(hit),group,type,plane};canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(this.xr)return;if(!this.drag){this.pointerRay(e);const h=this.hits()[0];this.setHover(h);canvas.style.cursor=h?'pointer':'grab';return;}const d=this.drag,dx=e.clientX-d.x,dy=e.clientY-d.y;d.x=e.clientX;d.y=e.clientY;if(Math.hypot(e.clientX-d.sx,e.clientY-d.sy)>5)d.moved=true;if(!d.moved)return;S.autoRotate=false;$('rotateBtn').textContent='▷ Girar';if(d.type==='piece'){this.pointerRay(e);const p=this.ray.ray.intersectPlane(d.plane,new T.Vector3());if(p)d.group.position.copy(d.group.parent.worldToLocal(p));}
   else if(d.type==='copy'){d.group.rotation.y+=dx*.008;d.group.rotation.x+=dy*.008;}else{this.az-=dx*.005;this.elev=Math.max(-1.1,Math.min(1.1,this.elev+dy*.005));this.cameraPosition();}});
  canvas.addEventListener('pointerup',e=>{const d=this.drag;this.drag=null;try{canvas.releasePointerCapture(e.pointerId);}catch(_){}if(!d||this.xr)return;if(d.moved&&d.type==='piece'){const world=d.group.getWorldPosition(new T.Vector3()),target=this.closestDrop(world);if(d.hit?.type==='seqPiece'){const st=seqState();if(st)st.selected=d.hit.key;}if(target)this.activate(target);else{render();fb('Aproxime a peça de uma posição. Também é possível selecionar e usar o botão Encaixar.','warning');}}
   else if(!d.moved)this.activate(d.hit);});canvas.addEventListener('pointercancel',()=>{this.drag=null;rebuild();});
  canvas.addEventListener('wheel',e=>{e.preventDefault();this.dist=Math.max(3.5,Math.min(40,this.dist+e.deltaY*.012));this.cameraPosition();},{passive:false});
  canvas.addEventListener('keydown',e=>{if(e.key==='Escape'&&inspectKey){handle('inspect:close');return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home',' '].includes(e.key)){e.preventDefault();if(e.key==='Home')this.center();else if(e.key==='+')this.zoom(1);else if(e.key==='-')this.zoom(-1);else if(e.key===' ')handle('rotate');else{this.az+=(e.key==='ArrowLeft'?.08:e.key==='ArrowRight'?-.08:0);this.elev=Math.max(-1.1,Math.min(1.1,this.elev+(e.key==='ArrowUp'?.08:e.key==='ArrowDown'?-.08:0)));this.cameraPosition();}}});
 }
 frame(time,frame){if(!this.renderer)return;const now=performance.now(),dt=Math.min(.05,Math.max(0,(now-this.last)/1000));this.last=now;this.resize();const t=now/1000;
  if(S.autoRotate&&this.model){if(this.copy)this.copy.rotation.y+=dt*.3;else this.model.rotation.y+=dt*.2;}
  if(this.animatedInspect){const i=this.animatedInspect,tt=Math.min(1,(now-i.start)/300),s=S.reducedMotion?1:.82+.18*(1-(1-tt)**3);i.object.scale.setScalar(i.target*s);if(tt>=1)this.animatedInspect=null;}
  // batimento do coração e respiração suave em qualquer cena que tenha o tórax
  if(this.model){this.model.traverse(o=>{if(o.userData.bate){const b=1+Math.sin(t*5.2)*.035;o.scale.setScalar((o.userData.base||(o.userData.base=o.scale.x))*b);}});
   if(this.obj&&this.obj.userData.tick){if(S.view==='respire'){const r=S.respire,alvo=r.fase==='inspirando'?1:0;r.abertura+=(alvo-r.abertura)*Math.min(1,dt*2.2);this.obj.userData.tick(t,r.abertura);}else if(S.view==='movimento'){const r=S.movimento,alvo=r.fase==='flexionando'?1:0;r.abertura+=(alvo-r.abertura)*Math.min(1,dt*2.2);this.obj.userData.tick(t,r.abertura);}else this.obj.userData.tick(t);}if(this.copy&&this.copy.userData.tick)this.copy.userData.tick(t);}
  if(this.xr){if(this.waitFrames){this.waitFrames--;if(!this.waitFrames){this.anchor=null;this.placeXR();this.buildXRUI();}}this.updateXR(dt);}
  this.renderer.render(this.scene,this.camera);
 }
 head(){const c=this.renderer.xr.getCamera(this.camera),p=c.getWorldPosition(new T.Vector3()),f=c.getWorldDirection(new T.Vector3());f.y=0;if(f.lengthSq()<.001)f.set(0,0,-1);f.normalize();return{p,f,yaw:Math.atan2(-f.x,-f.z)};}
 placeXR(){if(!this.xr||!this.model)return;if(!this.anchor)this.anchor=this.head();const a=this.anchor;this.root.position.set(0,0,0);this.root.scale.setScalar(1);this.root.rotation.set(0,0,0);this.root.updateMatrixWorld(true);const box=this.boxDe(this.model),size=box.isEmpty()?new T.Vector3(5,5,5):box.getSize(new T.Vector3()),tudo=this.boxDe(this.model,true),alt=tudo.isEmpty()?0:tudo.getSize(new T.Vector3()).y;let scale=1.45/Math.max(size.x,size.y,5),dist=1.95;if(alt*scale>1.95){scale=1.95/alt;dist=1.55;}scale*=(this.xrZoom||1);this.root.scale.setScalar(scale);this.root.rotation.y=a.yaw;this.root.position.copy(a.p).addScaledVector(a.f,dist);this.root.position.y-=.2;if(!box.isEmpty()){const c=box.getCenter(new T.Vector3()).multiplyScalar(scale).applyAxisAngle(new T.Vector3(0,1,0),a.yaw);this.root.position.sub(c);const pe=this.root.position.y+tudo.min.y*scale;if(pe<.05)this.root.position.y+=.05-pe;}
  this.ui.position.copy(a.p);this.ui.rotation.set(0,a.yaw,0);this.root.updateMatrixWorld(true);this.ui.updateMatrixWorld(true);}
 clearXRUI(){for(const c of [...this.ui.children])M.dispose(c);this.uiHits=[];}
 textPlane(title,body,w=.82,h=.66){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;const c=canvas.getContext('2d');c.fillStyle='rgba(10,31,46,.97)';c.fillRect(0,0,1024,1024);c.strokeStyle='#4c8294';c.lineWidth=6;c.strokeRect(3,3,1018,1018);let y=90;const write=(text,size,color)=>{c.font=(size>40?'600 ':'400 ')+size+'px Segoe UI,Arial';c.fillStyle=color;let line='';for(const word of String(text).split(/\s+/)){const next=(line?line+' ':'')+word;if(c.measureText(next).width>930&&line){if(y<990)c.fillText(line,52,y);y+=size*1.35;line=word;}else line=next;}if(line&&y<990){c.fillText(line,52,y);y+=size*1.4;}};write(title,64,'#a4e6d1');y+=20;write(body,52,'#d3eaf6');const texture=new T.CanvasTexture(canvas);texture.encoding=T.sRGBEncoding;return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:texture,transparent:true,side:T.DoubleSide,depthWrite:false}));}
 xrButton(label,cmd,x,y,w=.4,disabled=false){const c=document.createElement('canvas');c.width=1024;c.height=256;const g=c.getContext('2d');g.fillStyle=disabled?'#172c3b':'#144957';g.fillRect(0,0,1024,256);g.strokeStyle=disabled?'#314756':'#6098a7';g.lineWidth=10;g.strokeRect(5,5,1014,246);let size=72;g.font='600 '+size+'px Segoe UI,Arial';while(g.measureText(label).width>940&&size>26){size-=3;g.font='600 '+size+'px Segoe UI,Arial';}g.textAlign='center';g.textBaseline='middle';g.fillStyle=disabled?'#6b8190':'#ebfbff';g.fillText(label,512,130);const tex=new T.CanvasTexture(c);tex.encoding=T.sRGBEncoding;const m=new T.Mesh(new T.PlaneGeometry(w,.115),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));m.position.set(x,y,-1.62);m.rotation.y=-Math.atan2(x,1.62);m.userData.command=cmd;this.ui.add(m);if(!disabled)this.uiHits.push(m);return m;}
 buildXRUI(){if(!this.xr)return;this.clearXRUI();if(this.anchor){this.ui.position.copy(this.anchor.p);this.ui.rotation.y=this.anchor.yaw;}let title=$('lessonPanel').querySelector('h2')?.textContent||'Corpo Humano',body=instruction+(feedbackText?' '+feedbackText:'');
  if(this.xrReport){const r=report();title='Resumo da experiência';body=S.completed.length+' atividades concluídas. '+r.errors+' tentativas incorretas. '+r.hints+' pistas consultadas. Exporte os registros no modo 3D.';}
  const panel=this.textPlane(title,body,1.06,.86);panel.position.set(1.16,.3,-1.64);panel.rotation.y=-.6;this.ui.add(panel);
  const list=this.xrReport?[{label:'Voltar à atividade',cmd:'xr:reportclose'}]:this._acoes();const max=8,pages=Math.max(1,Math.ceil(list.length/max));this.uiPage=Math.min(this.uiPage,pages-1);list.slice(this.uiPage*max,(this.uiPage+1)*max).forEach((a,i)=>this.xrButton(a.label,a.cmd,1.16+(i%2?.25:-.25),-.22-Math.floor(i/2)*.15,.46,a.disabled));if(pages>1){this.xrButton('◀ Opções','xr:prev',.91,-.86,.46,this.uiPage===0);this.xrButton('Mais opções ▶','xr:next',1.41,-.86,.46,this.uiPage===pages-1);}
  const atv=D.activities.filter(a=>a.modulo===S.modulo),outro=D.modulos.find(m=>m.id!==S.modulo);atv.forEach((a,i)=>this.xrButton((i+1)+'. '+a.label,'view:'+a.id,-1.18,.52-i*.15,.5));this.xrButton('⇄ '+outro.curto,'modulo:'+outro.id,-1.18,.52-atv.length*.15,.5);this.xrButton('🥽 Sair do VR','vr',-1.18,-.92,.5);this.xrButton('↙ Catálogo','catalog',-1.18,-1.07,.5);this.xrButton('◎ Centralizar','center',-.52,-.86,.46);this.xrButton(S.autoRotate?'Ⅱ Pausar':'▷ Girar','rotate',-.02,-.86,.46);this.xrButton('🔊 Ouvir','voice:repeat',-.52,-1.01,.46);this.xrButton('■ Parar voz','voice:stop',-.02,-1.01,.46);}
 _acoes(){const out=[];document.querySelectorAll('#lessonPanel [data-act]').forEach(b=>{if(/^seq:target:/.test(b.dataset.act))return;if(b.closest('details')&&!b.closest('details').open)return;out.push({label:b.textContent.trim(),cmd:b.dataset.act,disabled:b.disabled});});return out;}
 controllerRay(ctrl){ctrl.updateMatrixWorld(true);const ray=new T.Raycaster();ray.camera=this.renderer.xr.getCamera(this.camera);ray.ray.origin.setFromMatrixPosition(ctrl.matrixWorld);ray.ray.direction.set(0,0,-1).transformDirection(ctrl.matrixWorld);return ray;}
 xrSelect(ctrl){if(this.held.has(ctrl))return;const ray=this.controllerRay(ctrl),ui=ray.intersectObjects(this.uiHits,false)[0];if(ui){const cmd=ui.object.userData.command;if(cmd==='xr:prev'){this.uiPage--;this.buildXRUI();return;}if(cmd==='xr:next'){this.uiPage++;this.buildXRUI();return;}if(cmd==='xr:reportclose'){this.xrReport=false;this.buildXRUI();return;}this.xrReport=false;handle(cmd);return;}this.root.updateMatrixWorld(true);const hit=this.hits(ray)[0];if(hit)this.activate(this.hitData(hit));else narrator.stop();}
 gripStart(ctrl){const ray=this.controllerRay(ctrl),hit=this.hits(ray)[0];if(!hit)return;const data=this.hitData(hit);if(data.type!=='seqPiece'){if(data.type==='inspect')this.activate(data);return;}const cfg=D.sequencias[S.view];const copy=new T.Group();const box=new T.Mesh(new T.BoxGeometry(.92,.44,.2),M.mat(0x2b6f88));copy.add(box);const t=M.label(cfg.rotulos[data.key],'#ffffff',.9,60);t.position.z=.12;copy.add(t);copy.scale.setScalar(.15);copy.position.set(0,-.02,-.32);ctrl.add(copy);copy.userData.heldData=data;this.held.set(ctrl,copy);const st=seqState();if(st)st.selected=data.key;}
 gripEnd(ctrl){const copy=this.held.get(ctrl);if(!copy)return;const pos=copy.getWorldPosition(new T.Vector3()),target=this.closestDrop(pos);M.dispose(copy);this.held.delete(ctrl);if(target)this.activate(target);else{renderSidebar();fb('Peça selecionada. Aponte para a posição e pressione o gatilho.');}}
 controllersInit(){if(this.controllers.length)return;for(let i=0;i<2;i++){const ctrl=this.renderer.xr.getController(i);this.scene.add(ctrl);const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-1)]),line=new T.Line(geo,new T.LineBasicMaterial({color:0x73d8e5}));line.scale.z=3;line.name='ray';ctrl.add(line);ctrl.addEventListener('selectstart',()=>this.xrSelect(ctrl));ctrl.addEventListener('squeezestart',()=>this.gripStart(ctrl));ctrl.addEventListener('squeezeend',()=>this.gripEnd(ctrl));ctrl.addEventListener('disconnected',()=>this.gripEnd(ctrl));this.controllers.push(ctrl);}}
 updateXR(dt){if(!this.anchor)return;this.scene.updateMatrixWorld(true);let alvo=null;for(const ctrl of this.controllers){const ray=this.controllerRay(ctrl),ui=ray.intersectObjects(this.uiHits,false)[0],mh=ui?null:this.hits(ray)[0],hit=ui||mh;if(mh&&!alvo)alvo=mh;const line=ctrl.getObjectByName('ray');line.material.color.setHex(hit?0xb8f6d7:0x66b7cb);line.scale.z=hit?Math.min(4,hit.distance):3;}this.setHover(alvo);
  if(this.xrSession)for(const src of this.xrSession.inputSources){const gp=src.gamepad;if(!gp)continue;const x=gp.axes[2]||0,y=gp.axes[3]||0;if(Math.abs(x)>.23&&this.model){if(this.copy)this.copy.rotation.y-=x*dt;else this.model.rotation.y-=x*dt*.55;}if(Math.abs(y)>.23){this.root.position.y=Math.max(.25,Math.min(2.4,this.root.position.y-y*dt*.25));}}}
 async toggleVR(){if(this.xrSession){await this.xrSession.end();return;}if(!window.isSecureContext||!navigator.xr){fb('O modo VR precisa de HTTPS e de um navegador compatível no óculos. Aqui você pode usar o modo 3D.','warning');return;}
  narrator.stop();try{const supported=await navigator.xr.isSessionSupported('immersive-vr');if(!supported){fb('Este dispositivo não informou suporte a VR imersivo.','warning');return;}const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});let reference='local-floor';try{await session.requestReferenceSpace('local-floor');}catch(_){reference='local';}this.renderer.xr.setReferenceSpaceType(reference);try{await this.renderer.xr.setSession(session);}catch(e){await session.end();throw e;}this.xrSession=session;this.xr=true;this.waitFrames=3;this.anchor=null;this.xrZoom=1;this.camera.position.set(0,0,0);this.camera.rotation.set(0,0,0);this.controllersInit();document.body.classList.add('xr');this.ui.visible=true;session.addEventListener('end',()=>this.exitXR());session.addEventListener('visibilitychange',()=>{if(session.visibilityState!=='visible'){narrator.stop();S.autoRotate=false;}});this.placeXR();this.buildXRUI();}catch(e){fb('Não foi possível iniciar VR: '+e.message,'warning');}}
 exitXR(){for(const [ctrl,copy] of this.held)M.dispose(copy);this.held.clear();this.xr=false;this.xrSession=null;this.anchor=null;this.clearXRUI();document.body.classList.remove('xr');narrator.stop();this.root.position.set(0,0,0);this.root.rotation.set(0,0,0);this.root.scale.setScalar(1);this.width=0;this.cameraPosition();this.show();}
}
function report(){const list=S.events;return{version:D.version,started:new Date(S.started).toISOString(),exported:new Date().toISOString(),completed:[...S.completed],components:[...S.visited],errors:list.filter(e=>e.correct===false).length,hints:list.filter(e=>e.event==='pista').length,respiracao:S.respire.ciclos,caminhoAr:{colocados:S.caminhoAr.colocados,erros:S.caminhoAr.erros,pistas:S.caminhoAr.pistas},caminhoSangue:{colocados:S.caminhoSangue.colocados,erros:S.caminhoSangue.erros,pistas:S.caminhoSangue.pistas},alimento:{colocados:S.alimento.colocados,erros:S.alimento.erros,pistas:S.alimento.pistas},quiz:S.quiz.answers.map((a,i)=>({question:D.questions[i].q,answer:D.questions[i].options[a],correct:a===D.questions[i].correct})),movimento:S.movimento.ciclos,coluna:{colocados:S.coluna.colocados,erros:S.coluna.erros,pistas:S.coluna.pistas},braco:{colocados:S.braco.colocados,erros:S.braco.erros,pistas:S.braco.pistas},articulacoes:{...S.artic},quizEsq:S.esqQuiz.answers.map((a,i)=>({question:D.esqQuestions[i].q,answer:D.esqQuestions[i].options[a],correct:a===D.esqQuestions[i].correct})),events:[...list]};}
function showSummary(){narrator.stop();if(view&&view.xr){view.xrReport=true;view.buildXRUI();return;}const r=report();const rows=[['Contexto',S.completed.includes('contexto')?'Percurso realizado':'Não concluído'],['Exploração',S.visited.length+' órgãos diferentes'],['Respire',S.respire.ciclos+' ciclos'],['Caminho do ar',S.caminhoAr.colocados.filter(Boolean).length+' / 6'],['Caminho do sangue',S.caminhoSangue.colocados.filter(Boolean).length+' / 6'],['Troca gasosa',S.completed.includes('troca')?'Concluída':'Não concluída'],['Caminho do alimento',S.alimento.colocados.filter(Boolean).length+' / 6'],['Desafio (respiração)',S.quiz.done?'Concluído':'Não concluído'],['Ossos',S.visited.filter(ehOsso).length+' estruturas'],['Movimento',S.movimento.ciclos+' ciclos'],['Coluna',S.coluna.colocados.filter(Boolean).length+' / 5'],['Articulações',['dobradica','esferoide','pivo'].filter(k=>S.artic[k]).length+' / 3 tipos'],['Monte o braço',S.braco.colocados.filter(Boolean).length+' / 5'],['Músculos',S.visited.filter(ehMusculo).length+' músculos'],['Desafio (esqueleto)',S.esqQuiz.done?'Concluído':'Não concluído']];$('summaryContent').innerHTML='<p class="fine">Um retrato das ações realizadas nesta sessão.</p><table><thead><tr><th>Atividade</th><th>Registro</th></tr></thead><tbody>'+rows.map(([a,b])=>'<tr><td>'+a+'</td><td>'+b+'</td></tr>').join('')+'</tbody></table><div class="metric-row"><span>Tentativas incorretas</span><b>'+r.errors+'</b></div><div class="metric-row"><span>Pistas consultadas</span><b>'+r.hints+'</b></div><p class="fine">Erros e pistas não diminuem um placar global. Use os registros para conversar com o aluno e escolher uma retomada.</p>';$('summaryDialog').showModal();}
function download(name,text,mime){const blob=new Blob([text],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setup(){
 $('activityNav').innerHTML=D.modulos.map(m=>'<button class="nav-modulo" data-modulo="'+m.id+'" data-view="'+D.activities.find(a=>a.modulo===m.id).id+'" aria-label="'+m.label+'"><span>'+m.curto+'</span></button>'+D.activities.filter(a=>a.modulo===m.id).map((a,i)=>'<button data-view="'+a.id+'" data-mod="'+m.id+'" aria-label="'+a.label+'"><span class="nav-num">'+String(i+1).padStart(2,'0')+'</span><span>'+a.label+'</span></button>').join('')).join('');
 $('activityNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view);});$('sidebar').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b&&!b.disabled)handle(b.dataset.act);});
 document.body.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const ac=b.dataset.action;
  if(ac==='guide')handle('guide:start');else if(ac==='summary')showSummary();else if(ac==='settings'){$('level').value=S.level;$('settingsDialog').showModal();}else if(ac==='closeSummary')$('summaryDialog').close();else if(ac==='sources')$('sourcesDialog').showModal();
  else if(ac==='newStudent'){if(!confirm('Iniciar um novo aluno? Exporte o resumo antes de limpar esta sessão.'))return;narrator.stop();S=initial();inspectKey=null;feedbackText='';$('settingsDialog').close();save();switchView('contexto',false);}
  else if(ac==='repeatVoice')narrator.say(instruction,instructionKey);else if(ac==='stopVoice')narrator.stop();else if(ac==='closeInspect')handle('inspect:close');else if(ac==='center')handle('center');else if(ac==='rotate'){handle('rotate');if(view&&view.xr)view.buildXRUI();}else if(ac==='zoomIn')view&&view.zoom(1);else if(ac==='zoomOut')view&&view.zoom(-1);else if(ac==='vr')handle('vr');
  else if(ac==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen({navigationUI:'hide'}).catch(()=>fb('O navegador não autorizou tela cheia.','warning'));}
  else if(ac==='downloadJSON')download('CorpoHumano-resumo.json',JSON.stringify(report(),null,2),'application/json');
  else if(ac==='downloadCSV'){const r=report(),rows=[['evento','habilidade','correto','posicao','escolha','data'],...r.events.map(e=>[e.event,e.skill,e.correct??'',e.position??'',e.choice??'',e.at])];const csv='﻿'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');download('CorpoHumano-atividades.csv',csv,'text/csv;charset=utf-8');}
  else if(ac==='catalog'){e.preventDefault();handle('catalog');}});
 $('sourcesContent').innerHTML='<p class="fine">Conteúdo elaborado para o Fundamental II e o Ensino Médio, com revisão docente recomendada.</p><p class="fine"><b>Modelos anatômicos 3D:</b> Z-Anatomy, atlas de anatomia de código aberto (<a href="https://github.com/LluisV/Z-Anatomy" target="_blank" rel="noopener noreferrer">github.com/LluisV/Z-Anatomy</a>), licença CC BY-SA 4.0. Órgãos do tórax e do abdome, esqueleto completo (206 ossos em 32 grupos), 14 músculos e ligamentos das articulações, convertidos, agrupados e simplificados pela NEWPC para uso em sala e em óculos; os modelos derivados mantêm a mesma licença. O alvéolo, o capilar e os marcadores didáticos são representações procedurais; a mudança de volume dos músculos no movimento é ilustrativa.</p><ul class="resource-list">'+D.sources.map(([t,u])=>'<li><a href="'+u+'" target="_blank" rel="noopener noreferrer">'+esc(t)+'</a></li>').join('')+'</ul><p class="fine">Limites: as formas e proporções são convencionais; a simulação de respiração e de fluxo sanguíneo é conceitual, sem valores fisiológicos. Não substitui atlas anatômico nem orientação médica.</p>';
 $('level').addEventListener('change',e=>{S.level=e.target.value;renderSidebar();save();});$('voiceVolume').addEventListener('input',e=>{const n=Number(e.target.value);$('voiceValue').textContent=n+'%';narrator.setVoice(n/100);});$('musicVolume').addEventListener('input',e=>{const n=Number(e.target.value);$('musicValue').textContent=n+'%';narrator.setMusic($('musicEnabled').checked,n/100);});$('musicEnabled').addEventListener('change',e=>narrator.setMusic(e.target.checked));$('autoVoice').checked=S.autoVoice;$('autoVoice').addEventListener('change',e=>{S.autoVoice=e.target.checked;if(!S.autoVoice)narrator.stop();save();});$('syntheticVoice').addEventListener('change',e=>{narrator.synthetic=e.target.checked;narrator.stop();});$('captionsEnabled').checked=S.captions;$('captionsEnabled').addEventListener('change',e=>{S.captions=e.target.checked;$('captionText').hidden=!S.captions;save();});$('reducedMotion').checked=S.reducedMotion;$('reducedMotion').addEventListener('change',e=>{S.reducedMotion=e.target.checked;save();});$('quality').value=S.quality;$('quality').addEventListener('change',e=>{S.quality=e.target.value;if(view)view.pixel=0;save();});
 window.addEventListener('pagehide',()=>{save();narrator.dispose();});document.addEventListener('visibilitychange',()=>{if(document.hidden){narrator.stop();narrator.music.pause();}});
 if(T&&M)view=new LabView();else{$('webglError').hidden=false;$('stage').classList.add('error');}
 window.addEventListener('corpo:modelo',()=>{if(view)view.modeloChegou();});if(window.CORPO_GLTF)window.CORPO_GLTF.precarregar(['pulmoes','traqueia','bronquios','coracao','diafragma','costelas','silhueta','aorta','faringe','nariz','laringe','boca']);if(window.ESQ_GLTF)setTimeout(()=>window.ESQ_GLTF.precarregar(['esqueleto','musculos']),4000);
 switchView(S.view,false);$('rotateBtn').textContent=S.autoRotate?'Ⅱ Pausar':'▷ Girar';
 window.CorpoLab={version:D.version,get state(){return S;},command:handle,report,view,narrator};
}
setup();
})();
