/* Corpo Humano Imersivo · Módulo 3: Sistema Nervoso (v4.0)
   Fichas (encéfalo, medula e nervos), missões, aula guiada, arco reflexo e desafio.
   Chaves de áudio: fichas = nome da chave (ex.: cerebelo.mp3); orientações = nerv-*. Modelos: Z-Anatomy (CC BY-SA 4.0). */
(function(D){'use strict';
const I={
 /* encéfalo */
 lobo_frontal:{name:'Lobo frontal',kind:'Encéfalo · cérebro',color:'#f2b8a6',text:'O lobo frontal fica na frente do cérebro, atrás da testa. É onde você planeja, decide, controla os movimentos voluntários e segura os impulsos.',detail:'A parte de trás do lobo frontal, o giro pré-central, é o córtex motor: cada região comanda um pedaço do corpo. Na frente, o córtex pré-frontal cuida de planejar e de tomar decisões, e amadurece até os 25 anos.',medio:'A área de Broca, no lobo frontal esquerdo da maioria das pessoas, coordena a produção da fala.'},
 lobo_parietal:{name:'Lobo parietal',kind:'Encéfalo · cérebro',color:'#f5c98f',text:'O lobo parietal fica no alto do cérebro. Ele recebe o tato, a temperatura, a dor e a posição do corpo, e monta o mapa do espaço ao seu redor.',detail:'Logo atrás do sulco central está o córtex somatossensorial, que recebe as sensações da pele. Lábios e mãos ocupam áreas enormes nesse mapa, porque têm muitos receptores.',medio:'O lobo parietal integra visão e tato para guiar movimentos, como pegar um copo sem olhar para a mão.'},
 lobo_temporal:{name:'Lobo temporal',kind:'Encéfalo · cérebro',color:'#a9d7a4',text:'O lobo temporal fica nas laterais, perto das orelhas. Ele processa os sons, reconhece vozes e rostos e ajuda a guardar memórias.',detail:'O córtex auditivo primário fica aqui. Por dentro do lobo temporal está o hipocampo, essencial para formar memórias novas.',medio:'A área de Wernicke, no lobo temporal esquerdo, participa da compreensão da linguagem.'},
 lobo_occipital:{name:'Lobo occipital',kind:'Encéfalo · cérebro',color:'#9fc5f0',text:'O lobo occipital fica atrás, na nuca. É o centro da visão: tudo o que os olhos captam é interpretado aqui.',detail:'A imagem chega invertida e dividida: o que está à esquerda do campo visual é processado no lado direito, e vice-versa. Uma pancada forte na nuca pode fazer ver "estrelas" por isso.',medio:'O córtex visual primário (área V1) recebe o sinal do nervo óptico via tálamo e o distribui para áreas que reconhecem forma, cor e movimento.'},
 lobo_limbico:{name:'Lobo límbico e ínsula',kind:'Encéfalo · cérebro',color:'#d9a6e0',text:'Escondidos no meio do cérebro, o lobo límbico e a ínsula cuidam das emoções, do medo, do prazer e das sensações do próprio corpo, como fome e nojo.',detail:'O giro do cíngulo faz parte do sistema límbico, ligado à emoção e à motivação. A ínsula registra o estado interno do corpo: batimento, respiração, dor visceral.',medio:'A amígdala, próxima ao hipocampo, dispara respostas de medo antes mesmo de o córtex "entender" o perigo.'},
 cerebelo:{name:'Cerebelo',kind:'Encéfalo',color:'#e8c7a0',text:'O cerebelo fica atrás e embaixo do cérebro. Ele coordena os movimentos, mantém o equilíbrio e deixa os gestos precisos, como escrever ou chutar uma bola.',detail:'Tem só 10% do volume do encéfalo, mas mais da metade dos neurônios. Ele compara o movimento planejado com o movimento feito e corrige na hora.',medio:'Lesões no cerebelo causam ataxia: movimentos desajeitados e tremor ao tentar alcançar um objeto.'},
 tronco:{name:'Tronco encefálico',kind:'Encéfalo',color:'#d8a0a0',text:'O tronco encefálico liga o cérebro à medula. Ele controla o que você nem percebe: respiração, batimento do coração, pressão e sono.',detail:'É formado por mesencéfalo, ponte e bulbo. O bulbo tem os centros da respiração e do ritmo cardíaco; por isso lesões nessa região são tão graves.',medio:'Dez dos doze pares de nervos cranianos saem do tronco encefálico.'},
 talamo:{name:'Tálamo',kind:'Encéfalo · diencéfalo',color:'#c9b0e8',text:'O tálamo é a central de triagem: quase toda informação dos sentidos passa por ele antes de chegar ao córtex.',detail:'Visão, audição, tato e dor fazem escala no tálamo, que decide o que merece atenção. O olfato é a exceção: vai direto ao córtex.',medio:'O tálamo também participa do ciclo de sono e vigília e da consciência.'},
 hipotalamo:{name:'Hipotálamo',kind:'Encéfalo · diencéfalo',color:'#ffd27f',text:'Pequeno como uma amêndoa, o hipotálamo regula a temperatura do corpo, a fome, a sede e o relógio biológico.',detail:'Ele comanda a hipófise, a glândula que controla as outras glândulas. É a ponte entre o sistema nervoso e o sistema endócrino.',medio:'Mantém a homeostase: quando a temperatura sobe, dispara suor e dilatação dos vasos; quando cai, tremor e arrepio.'},
 corpo_caloso:{name:'Corpo caloso',kind:'Encéfalo · cérebro',color:'#f0f0d0',text:'O corpo caloso é uma ponte de fibras que liga os dois hemisférios. Graças a ele, o lado esquerdo e o lado direito do cérebro trabalham juntos.',detail:'São cerca de 200 milhões de axônios. Sem ele, a mão esquerda poderia não "saber" o que a direita está fazendo.',medio:'O hemisfério esquerdo controla o lado direito do corpo e vice-versa; o corpo caloso é o que permite coordenar os dois.'},
 /* medula e nervos */
 medula:{name:'Medula espinhal',kind:'Sistema nervoso central',color:'#f2e6c8',text:'A medula espinhal é um cordão de nervos protegido pela coluna vertebral. Ela leva mensagens do cérebro ao corpo e do corpo ao cérebro, e comanda os reflexos.',detail:'Tem 45 centímetros e a grossura de um dedo. Dela saem 31 pares de nervos espinhais. No reflexo do joelho, a resposta é organizada aqui, sem esperar o cérebro.',medio:'A substância cinzenta fica por dentro (em forma de H) e a branca por fora, ao contrário do cérebro.'},
 cauda_equina:{name:'Cauda equina',kind:'Sistema nervoso central',color:'#f2e6c8',text:'A medula termina na altura da cintura. Abaixo, os nervos descem soltos dentro da coluna, como um rabo de cavalo: a cauda equina.',detail:'É por isso que a punção lombar é feita abaixo da segunda vértebra lombar: ali não há mais medula para ser atingida.',medio:'Da cauda equina saem os nervos lombares e sacrais que formam os plexos para as pernas e a pelve.'},
 plexo_braquial:{name:'Plexo braquial',kind:'Nervo periférico',color:'#f6e3a0',text:'No ombro, os nervos que saem do pescoço se trançam como fios num cabo: é o plexo braquial. Dele nascem todos os nervos do braço.',detail:'Formado pelas raízes de C5 a T1. Uma queda de moto que estira o pescoço pode lesar o plexo e deixar o braço sem força.',medio:'O plexo se organiza em raízes, troncos, divisões, fascículos e ramos terminais, como mediano, ulnar e radial.'},
 mediano:{name:'Nervo mediano',kind:'Nervo periférico',color:'#f6e3a0',text:'O nervo mediano desce pelo meio do braço até a mão. Ele comanda os músculos que dobram os dedos e dá sensibilidade ao polegar, indicador e dedo médio.',detail:'Ele passa por um túnel estreito no punho. Quando esse túnel aperta, surge a síndrome do túnel do carpo: formigamento e dormência nos dedos.',medio:'Lesão do mediano prejudica a pinça entre polegar e indicador, essencial para escrever.'},
 ulnar:{name:'Nervo ulnar',kind:'Nervo periférico',color:'#f6e3a0',text:'O nervo ulnar passa por trás do cotovelo, quase na superfície. Aquele choque quando você bate o cotovelo é ele! Ele cuida do dedinho e do anelar.',detail:'Comanda a maioria dos músculos pequenos da mão, que abrem e fecham os dedos lateralmente.',medio:'Na lesão do ulnar surge a "mão em garra": anelar e mínimo ficam curvados.'},
 radial:{name:'Nervo radial',kind:'Nervo periférico',color:'#f6e3a0',text:'O nervo radial enrola atrás do úmero e segue até o dorso da mão. Ele comanda os músculos que esticam o cotovelo, o punho e os dedos.',detail:'Dormir com o braço pendurado na cadeira pode comprimi-lo: é a "paralisia do sábado à noite", com o punho caído.',medio:'Fraturas da diáfise do úmero podem lesar o radial, porque ele passa colado ao osso.'},
 intercostais:{name:'Nervos intercostais',kind:'Nervo periférico',color:'#f6e3a0',text:'Entre cada par de costelas corre um nervo intercostal. Eles movem os músculos da respiração e dão sensibilidade à pele do tórax e do abdome.',detail:'São 11 pares, um para cada espaço entre as costelas. Quando a pessoa inspira fundo, são eles que comandam os músculos intercostais.',medio:'O herpes-zóster costuma seguir o trajeto de um nervo intercostal, formando uma faixa de dor e bolhas no tórax.'},
 ciatico:{name:'Nervo ciático',kind:'Nervo periférico',color:'#f6e3a0',text:'O nervo ciático é o mais grosso do corpo, da espessura de um dedo. Sai da pelve, desce atrás da coxa e se divide no joelho para chegar ao pé.',detail:'Comanda os músculos de trás da coxa e, pelos seus ramos tibial e fibular, toda a perna e o pé. Uma hérnia de disco pode comprimi-lo: é a dor "ciática".',medio:'Divide-se em nervo tibial e nervo fibular comum logo acima do joelho.'},
 femoral:{name:'Nervo femoral',kind:'Nervo periférico',color:'#f6e3a0',text:'O nervo femoral desce pela frente da coxa. Ele comanda o quadríceps, o músculo que estica o joelho e permite chutar, subir escada e levantar da cadeira.',detail:'Vem do plexo lombar, das raízes L2 a L4. É ele que participa do reflexo do joelho testado pelo médico com o martelinho.',medio:'Também dá sensibilidade à parte da frente da coxa e, pelo nervo safeno, à parte interna da perna.'},
 vago:{name:'Nervo vago',kind:'Nervo craniano',color:'#f6e3a0',text:'O nervo vago sai do tronco encefálico e "vaga" pelo pescoço, tórax e abdome. Ele desacelera o coração, aciona a digestão e controla a voz.',detail:'É o principal nervo do sistema parassimpático, o modo "descansar e digerir". Respirar devagar estimula o vago e acalma o batimento.',medio:'Décimo par craniano (X). Leva informações das vísceras ao cérebro: cerca de 80% das suas fibras são sensitivas.'},
 optico:{name:'Nervo óptico',kind:'Nervo craniano',color:'#f6e3a0',text:'O nervo óptico leva a imagem captada pela retina até o cérebro. Cada um tem cerca de um milhão de fibras.',detail:'Os dois nervos se cruzam parcialmente no quiasma óptico: por isso cada lado do cérebro recebe metade de cada olho.',medio:'Segundo par craniano (II). Na verdade é uma extensão do próprio encéfalo, envolta pelas meninges.'},
 facial:{name:'Nervo facial',kind:'Nervo craniano',color:'#f6e3a0',text:'O nervo facial comanda os músculos da expressão: sorrir, franzir a testa, fechar os olhos. Também leva o gosto dos dois terços da frente da língua.',detail:'Ele atravessa um canal estreito dentro do osso temporal. Quando inflama ali, surge a paralisia facial, com metade do rosto parada.',medio:'Sétimo par craniano (VII). Controla ainda as glândulas lacrimais e salivares.'},
 trigemeo:{name:'Nervo trigêmeo',kind:'Nervo craniano',color:'#f6e3a0',text:'O nervo trigêmeo tem três ramos e cobre a sensibilidade de todo o rosto: testa, bochecha e queixo. Também comanda os músculos da mastigação.',detail:'A dor de dente, a sensibilidade dos olhos e a cosquinha no nariz chegam ao cérebro por ele.',medio:'Quinto par craniano (V): ramos oftálmico, maxilar e mandibular. A neuralgia do trigêmeo é uma das dores mais intensas conhecidas.'}
};
Object.assign(D.info,I);
D.NERV_KEYS=Object.keys(I);
const activities=[
 {id:'nervContexto',label:'Contexto',title:'Quem comanda o corpo?',subtitle:'Do corpo inteiro ao encéfalo, passando pela medula.',kicker:'LOCALIZE',modulo:'nerv'},
 {id:'encefalo',label:'Encéfalo',title:'Um cérebro, muitas regiões.',subtitle:'Aponte em um lobo ou região para ver a ficha e ouvir a explicação.',kicker:'EXPLORE',modulo:'nerv'},
 {id:'nervos',label:'Medula e nervos',title:'Os cabos do corpo.',subtitle:'Siga a medula e os principais nervos até as mãos e os pés.',kicker:'EXPLORE',modulo:'nerv'},
 {id:'reflexo',label:'Arco reflexo',title:'Antes de pensar, o corpo já reagiu.',subtitle:'Organize o caminho do reflexo, da pele ao músculo.',kicker:'ORGANIZE',modulo:'nerv'}
];
D.activities.push(...activities);
D.nervContext=[
 {name:'Sistema nervoso inteiro',text:'Encéfalo, medula e nervos formam uma rede que chega a cada canto do corpo. Toque no corpo para avançar.',audio:'nerv-contexto-0'},
 {name:'Encéfalo e medula',text:'O sistema nervoso central: o encéfalo dentro do crânio e a medula dentro da coluna. Toque de novo para entrar no encéfalo.',audio:'nerv-contexto-1'},
 {name:'Dentro do encéfalo',text:'Cérebro dividido em lobos, cerebelo atrás e tronco encefálico embaixo. Aponte em cada região na missão Encéfalo.',audio:'nerv-contexto-2'}
];
D.sequencias.reflexo={titulo:'ARCO REFLEXO',cor:'#d9a6e0',ordem:['receptor','sensitivo','medula','motor','musculo'],rotulos:{receptor:'Receptor na pele',sensitivo:'Neurônio sensitivo',medula:'Medula espinhal',motor:'Neurônio motor',musculo:'Músculo responde'},pistas:['Tudo começa onde o estímulo é captado: na pele.','Quem leva a mensagem da pele para dentro é o neurônio sensitivo.','No reflexo, o centro de comando é a medula, não o cérebro.','Da medula sai o neurônio motor, levando a ordem.','A resposta termina em quem se contrai: o músculo.']};
D.nervGuide=[
 {view:'nervContexto',title:'Localize o comando',goal:'Avance do corpo inteiro até o encéfalo e identifique cérebro, cerebelo e medula.',check:'nervContexto',audio:'nerv-aula-contexto'},
 {view:'encefalo',title:'Investigue o encéfalo',goal:'Aponte em pelo menos três regiões do encéfalo e ouça o que cada uma faz.',check:'encefalo',audio:'nerv-aula-encefalo'},
 {view:'nervos',title:'Siga os nervos',goal:'Aponte na medula e em pelo menos dois nervos, do pescoço até o pé.',check:'nervos',audio:'nerv-aula-nervos'},
 {view:'reflexo',title:'Monte o arco reflexo',goal:'Coloque as cinco etapas na ordem, da pele até o músculo.',check:'reflexo',audio:'nerv-aula-reflexo'},
 {view:'nervDesafio',title:'Mostre o que entendeu',goal:'Responda às situações finais e consulte o seu resumo.',check:'nervDesafio',audio:'nerv-aula-desafio'}
];
D.nervQuestions=[
 {id:'nervReflexo',skill:'reflexo',q:'Você encosta a mão numa panela quente e a puxa antes de sentir dor. Quem organizou essa resposta?',options:['O lobo frontal, que decidiu puxar a mão','A medula espinhal, por um arco reflexo','O cerebelo, que coordena movimentos','O nervo óptico, que viu a panela'],correct:1,why:'No reflexo, o sinal do receptor entra na medula e volta direto ao músculo. O cérebro só fica sabendo depois, quando a dor é sentida.'},
 {id:'nervCerebelo',skill:'encefalo',q:'Um jogador erra chutes fáceis e cambaleia ao andar depois de um acidente. Qual região provavelmente foi afetada?',options:['Lobo occipital','Cerebelo','Hipotálamo','Nervo facial'],correct:1,why:'O cerebelo coordena os movimentos e o equilíbrio. Sem ele, os gestos ficam desajeitados e o andar, instável.'},
 {id:'nervOccipital',skill:'encefalo',q:'Uma pancada na nuca faz a pessoa "ver estrelas". Por quê?',options:['Porque o nervo óptico fica na nuca','Porque o lobo occipital, atrás, processa a visão','Porque o cerebelo controla os olhos','Porque o tálamo fica na nuca'],correct:1,why:'O lobo occipital fica na parte de trás do cérebro e interpreta as imagens. O impacto estimula essa região e surgem os clarões.'},
 {id:'nervCiatico',skill:'nervos',q:'Uma hérnia de disco na coluna lombar causa dor que desce por trás da coxa até o pé. Qual nervo está comprimido?',options:['Nervo mediano','Nervo facial','Nervo ciático','Nervo vago'],correct:2,why:'O ciático nasce das raízes lombares e sacrais, desce atrás da coxa e chega ao pé. Comprimido na coluna, dói por todo esse trajeto.'},
 {id:'nervTronco',skill:'encefalo',q:'Qual estrutura controla a respiração e o batimento do coração sem você pensar nisso?',options:['Tronco encefálico','Lobo parietal','Corpo caloso','Nervo radial'],correct:0,why:'O tronco encefálico, principalmente o bulbo, mantém a respiração e o ritmo cardíaco automaticamente, até durante o sono.'}
];
D.nervQuestions.forEach(q=>{q.pref='nerv-';});
D.todasQuestoes=D.todasQuestoes.concat(D.nervQuestions);
D.modulos.push({id:'nerv',label:'Sistema nervoso',curto:'Sistema nervoso',pergunta:'Como o corpo sente, decide e reage?'});
const sis=D.sistemas.find(x=>x.id==='nervoso');
if(sis){delete sis.breve;sis.modulo='nerv';sis.atividades=['nervContexto','encefalo','nervos','reflexo'];sis.questoes=D.nervQuestions.map(q=>q.id);}
D.sources.push(['Z-Anatomy · sistema nervoso (encéfalo, medula e nervos), CC BY-SA 4.0, adaptado pela NEWPC','https://github.com/LluisV/Z-Anatomy']);
})(window.CORPO_DATA);
