/* Terra por Dentro · dados (v1.0)
   Conteúdo: tema Camadas da Terra (Contexto, Explorar, Monte as camadas, Viagem ao centro, Desafio).
   Temas: Camadas da Terra, Placas tectônicas, Vulcões e Rochas e minerais. Textos no tom falado das narrações (chaves = nomes dos MP3 em audio/). */
(function(){'use strict';
const D={version:'1.3.1'};
D.temas=[
 {id:'camadas',nome:'Camadas da Terra',estuda:'Do que a Terra é feita por dentro.',exemplos:'Crosta, manto, núcleo externo e núcleo interno',modulo:'cam',atividades:['contexto','explorar','montar','viagem'],questoes:['liquida','kola','manto','magnetico','sismicas','interno','oceanica','temperatura']},
 {id:'placas',nome:'Placas tectônicas',estuda:'Por que a crosta se mexe, treme e se quebra.',exemplos:'Placas, limites, terremotos, vulcões e a deriva dos continentes',modulo:'pla',atividades:['placContexto','placasExp','limites','volta'],questoes:['placasMovem','andes','atlantico','sanandreas','brasil','pangeia']},
 {id:'vulcao',nome:'Vulcões',estuda:'Da câmara de magma à erupção.',exemplos:'Partes do vulcão, lava, cinzas, tipos de erupção e vulcões famosos',modulo:'vul',atividades:['vulContexto','vulcaoExp','erupcao','vulVolta'],questoes:['porqueVulcao','lavaMagma','explosiva','havai','pompeia','brasilVulcao']},
 {id:'rochas',nome:'Rochas e minerais',estuda:'O ciclo das rochas, da lava ao sedimento.',exemplos:'Granito, basalto, arenito, mármore, quartzo e o ciclo das rochas',modulo:'roc',atividades:['rocContexto','rochasExp','ciclo','identificar'],questoes:['granitoBasalto','fossil','marmore','carvao','cicloSed','mineralRocha']}
];
D.modulos=[{id:'cam',label:'Camadas da Terra',curto:'Camadas',pergunta:'O que existe debaixo dos nossos pés?'},{id:'pla',label:'Placas tectônicas',curto:'Placas',pergunta:'Por que a Terra treme e os continentes se movem?'},{id:'vul',label:'Vulcões',curto:'Vulcões',pergunta:'De onde vem o fogo que sai da Terra?'},{id:'roc',label:'Rochas e minerais',curto:'Rochas',pergunta:'De que é feito o chão, e como ele muda?'}];
D.PREF={cam:'',pla:'plac-',vul:'vul-',roc:'roc-'};
D.activities=[
 {id:'contexto',label:'Contexto',title:'O que existe debaixo dos seus pés?',subtitle:'Do planeta visto do espaço até a casca fina em que vivemos.',kicker:'LOCALIZE',modulo:'cam'},
 {id:'explorar',label:'Explorar',title:'A Terra aberta ao meio.',subtitle:'Aponte em uma camada para ver a ficha e ouvir a explicação.',kicker:'EXPLORE',modulo:'cam'},
 {id:'montar',label:'Monte as camadas',title:'Da superfície ao centro.',subtitle:'Coloque as camadas na ordem, de fora para dentro.',kicker:'ORGANIZE',modulo:'cam'},
 {id:'viagem',label:'Viagem ao centro',title:'Desça até o centro da Terra.',subtitle:'Uma viagem em primeira pessoa: 6.371 km em sete trechos.',kicker:'VIAJE',modulo:'cam'},
 {id:'desafio',label:'Desafio',title:'Agora, explique o que descobriu.',subtitle:'Situações para aplicar o que você viu.',kicker:'APLIQUE',modulo:'cam'},
 {id:'placContexto',label:'Contexto',title:'A casca está quebrada.',subtitle:'A litosfera é um quebra-cabeça de placas que se movem.',kicker:'LOCALIZE',modulo:'pla'},
 {id:'placasExp',label:'Explorar',title:'As placas e seus limites.',subtitle:'Aponte em uma placa do globo ou escolha na lista.',kicker:'EXPLORE',modulo:'pla'},
 {id:'limites',label:'Que limite é esse?',title:'Três jeitos de as placas se encontrarem.',subtitle:'Toque em cada maquete e descubra o tipo de limite.',kicker:'INVESTIGUE',modulo:'pla'},
 {id:'volta',label:'Volta ao mundo',title:'Uma volta ao mundo tectônica.',subtitle:'Seis lugares onde a Terra mostra as placas em ação.',kicker:'ACOMPANHE',modulo:'pla'},
 {id:'vulContexto',label:'Contexto',title:'Onde a Terra respira fogo.',subtitle:'Dos vulcões no mapa à câmara de magma lá embaixo.',kicker:'LOCALIZE',modulo:'vul'},
 {id:'vulcaoExp',label:'Explorar',title:'O vulcão aberto ao meio.',subtitle:'Aponte em uma parte do vulcão para ver a ficha e ouvir a explicação.',kicker:'EXPLORE',modulo:'vul'},
 {id:'erupcao',label:'Laboratório de erupção',title:'Que erupção vai ser?',subtitle:'Escolha o magma e o gás, suba a pressão e veja o resultado.',kicker:'EXPERIMENTE',modulo:'vul'},
 {id:'vulVolta',label:'Volta ao mundo',title:'Uma volta ao mundo dos vulcões.',subtitle:'Sete vulcões que marcaram a história.',kicker:'ACOMPANHE',modulo:'vul'},
 {id:'rocContexto',label:'Contexto',title:'Tudo o que você pisa é rocha.',subtitle:'Três famílias, feitas de minerais, que viram umas as outras.',kicker:'LOCALIZE',modulo:'roc'},
 {id:'rochasExp',label:'Explorar',title:'A bancada de rochas e minerais.',subtitle:'Toque em uma amostra para ver a ficha e ouvir a explicação.',kicker:'EXPLORE',modulo:'roc'},
 {id:'ciclo',label:'Ciclo das rochas',title:'Nenhuma rocha é para sempre.',subtitle:'Leve uma rocha pelas transformações e passe pelos cinco estados.',kicker:'TRANSFORME',modulo:'roc'},
 {id:'identificar',label:'Que rocha é essa?',title:'Olhe, compare e descubra.',subtitle:'Cinco amostras misteriosas: use as pistas para identificar.',kicker:'INVESTIGUE',modulo:'roc'}
];
/* placas: contexto em três etapas */
D.placContext=[
 {name:'A litosfera quebrada',target:'movem',text:'Olhe a casca da Terra de perto: ela não é inteira. A litosfera está quebrada em grandes pedaços, as placas tectônicas, como a casca de um ovo rachado. As linhas amarelas são as fronteiras entre elas.'},
 {name:'As placas se movem',target:'tremem',text:'E esses pedaços se mexem, muito devagar: uns centímetros por ano, a velocidade em que a sua unha cresce. Quem empurra é o manto quente, que se move por baixo. Em milhões de anos, isso leva continentes inteiros de um lado para o outro.'},
 {name:'Onde a Terra treme',text:'Agora repare nos pontos vermelhos: são terremotos. Quase todos acontecem nas fronteiras das placas, onde elas se chocam, se afastam ou se esfregam. O mesmo vale para os vulcões. O anel em volta do Pacífico é o lugar mais agitado do planeta.'}
];
/* placas (polígonos simplificados, lon/lat; a Pacífica usa lon > 180 para não cruzar a linha de data) */
D.placas=[
 {key:'antartica',cor:'#d8ecff',pts:[[-180,-55],[180,-55],[180,-90],[-180,-90]]},
 {key:'pacifica',cor:'#7fc8ff',pts:[[135,50],[150,45],[145,35],[140,25],[125,10],[135,-5],[150,-12],[165,-25],[175,-45],[190,-55],[220,-55],[250,-40],[265,-20],[255,0],[250,20],[240,35],[235,48],[210,58],[180,55],[160,52]]},
 {key:'norteamericana',cor:'#ffb27a',pts:[[-170,65],[-140,60],[-125,48],[-120,35],[-110,20],[-95,15],[-85,10],[-75,15],[-55,15],[-45,20],[-40,30],[-30,60],[-10,75],[-20,85],[-90,85],[-150,80],[-170,70]]},
 {key:'sulamericana',cor:'#9ee09e',pts:[[-75,15],[-85,10],[-80,0],[-75,-15],[-72,-30],[-75,-45],[-70,-55],[-60,-58],[-20,-58],[-15,-40],[-25,-20],[-30,0],[-40,10],[-55,15]]},
 {key:'africana',cor:'#ffd27f',pts:[[-15,40],[-25,20],[-30,0],[-25,-20],[-15,-40],[-10,-55],[25,-55],[45,-45],[50,-30],[45,-10],[40,5],[40,15],[35,25],[35,35],[20,38],[0,38]]},
 {key:'euroasiatica',cor:'#d0a6ff',pts:[[-10,75],[-30,60],[-15,40],[0,38],[20,38],[35,35],[40,30],[60,25],[70,30],[90,30],[100,20],[110,15],[125,10],[140,25],[145,35],[150,45],[135,50],[140,60],[160,65],[180,70],[180,85],[-10,85]]},
 {key:'indoaustraliana',cor:'#ff9aa8',pts:[[40,15],[60,25],[70,30],[90,30],[100,20],[110,15],[125,10],[135,-5],[150,-12],[165,-25],[175,-45],[150,-55],[100,-55],[60,-50],[45,-45],[50,-30],[45,-10]]},
 {key:'nazca',cor:'#9ff3ff',pts:[[-105,0],[-95,-20],[-110,-40],[-80,-45],[-75,-45],[-72,-30],[-75,-15],[-80,0]]}
];
/* volta ao mundo: seis paradas (lat, lon) */
D.volta=[
 {titulo:'Cordilheira dos Andes',lat:-20,lon:-68,chips:['Convergente','Nazca × Sul-Americana','Subducção'],text:'Primeira parada: os Andes. Aqui a placa de Nazca, do fundo do Pacífico, mergulha debaixo da placa Sul-Americana. O choque amassa a borda do continente e levanta a cordilheira, com vulcões e terremotos fortes, como o do Chile.',audio:'volta-0'},
 {titulo:'Falha de San Andreas',lat:36,lon:-120,chips:['Transformante','Pacífica × Norte-Americana','Terremotos'],text:'Califórnia, Estados Unidos. A placa do Pacífico e a Norte-Americana não se chocam: elas deslizam uma ao lado da outra. Onde a rocha trava e depois solta de repente, a terra treme. É a falha de San Andreas.',audio:'volta-1'},
 {titulo:'Islândia',lat:64,lon:-18,chips:['Divergente','Dorsal Meso-Atlântica','Nova crosta'],text:'Islândia, no meio do Atlântico. A ilha fica em cima da dorsal, onde a placa Norte-Americana e a Euroasiática se afastam. O magma sobe pela fenda, vira rocha nova e o oceano cresce uns 2 centímetros por ano.',audio:'volta-2'},
 {titulo:'Himalaia',lat:28,lon:87,chips:['Convergente','Indo-Australiana × Euroasiática','Montanhas'],text:'O Himalaia. A Índia era uma ilha e viajou para o norte até bater na Ásia. Como as duas são continentais e nenhuma afunda, a crosta se dobra e sobe: o Everest ainda cresce uns milímetros por ano.',audio:'volta-3'},
 {titulo:'Japão',lat:36,lon:138,chips:['Convergente','Anel de Fogo','Tsunamis'],text:'Japão, no Anel de Fogo do Pacífico. Aqui a placa do Pacífico mergulha sob o Japão. É por isso que o país tem tantos vulcões, terremotos e tsunamis, como o de 2011. Os prédios lá são construídos para balançar sem cair.',audio:'volta-4'},
 {titulo:'Brasil',lat:-15,lon:-50,chips:['Meio da placa','Estável','Crosta antiga'],text:'Última parada: o Brasil. Estamos bem no meio da placa Sul-Americana, longe das fronteiras. Por isso quase não temos terremotos fortes nem vulcões ativos. Já tivemos, há milhões de anos: as rochas antigas do planalto central contam essa história.',audio:'volta-5'}
];
D.VOLTA_FIM={text:'Volta completa. Andes, San Andreas, Islândia, Himalaia, Japão e Brasil: cada lugar mostra um jeito de as placas se encontrarem, ou de ficarem em paz.',audio:'volta-fim'};
/* ===== Vulcões ===== */
D.vulContext=[
 {name:'Onde ficam os vulcões',target:'origem',text:'Cada ponto laranja é um vulcão ativo. Repare: quase todos ficam em fila, nas fronteiras das placas. O Anel de Fogo, em volta do Pacífico, concentra três de cada quatro vulcões do mundo. Mas tem vulcão no meio de placa também, como no Havaí.'},
 {name:'De onde vem o magma',target:'corte',text:'O magma nasce de três jeitos. Onde uma placa mergulha embaixo da outra, a água que ela carrega faz o manto derreter: é o vulcão de subducção, como nos Andes. Onde as placas se afastam, o manto sobe e derrete porque a pressão cai: é a dorsal. E no ponto quente, uma pluma de manto fura a placa por baixo, como no Havaí.'},
 {name:'O vulcão por dentro',text:'Este é um vulcão aberto ao meio. Embaixo, a câmara de magma: uma bolsa de rocha derretida a mais de mil graus. Dela sobe o conduto, até a cratera no topo. Quando a pressão vence, o magma sobe e vira lava, cinzas e gases. As camadas do cone são erupções antigas, uma em cima da outra.'}
];
/* vulcões ativos (lon, lat) para o globo: Anel de Fogo, Mediterrâneo, Atlântico, África, pontos quentes */
D.vulcoes=[[-70,-40],[-71,-36],[-70,-33],[-68,-23],[-68,-16],[-78,-1],[-78,1],[-90,14],[-92,15],[-98,19],[-104,19],[-122,46],[-121,44],[-122,41],[-152,60],[-158,56],[-170,53],[-178,52],[178,51],[160,55],[158,53],[155,50],[145,44],[141,40],[138,35],[131,32],[124,13],[121,14],[124,8],[110,-7],[113,-8],[106,-6],[101,-2],[95,5],[125,2],[150,-5],[176,-38],[177,-39],[-18,65],[-22,64],[-28,38],[-16,28],[-25,37],[14,41],[15,38],[12,38],[25,37],[36,8],[38,1],[36,-3],[29,-1],[41,13],[-155,19],[-156,21],[55,-21],[-91,0],[-90,-1],[43,-12],[-176,-17],[-25,15]];
D.vulVolta=[
 {titulo:'Kilauea, Havaí',lat:19.4,lon:-155.3,terreno:'kilauea',chips:['Vulcão em escudo','Ponto quente','Lava fluida'],text:'Primeira parada: o Kilauea, no Havaí. Ele fica no meio da placa do Pacífico, longe de qualquer fronteira: é um ponto quente, uma pluma de manto que fura a placa por baixo. A lava é fluida e escorre em rios, por isso o vulcão é baixo e largo, em forma de escudo. No relevo real, veja a caldeira no alto e, à esquerda, a encosta do vizinho gigante, o Mauna Loa.',audio:'vul-volta-0'},
 {titulo:'Vesúvio, Itália',lat:40.8,lon:14.4,terreno:'vesuvio',chips:['Estratovulcão','Explosivo','Pompeia, ano 79'],text:'O Vesúvio, perto de Nápoles. No ano 79, uma erupção explosiva cobriu a cidade de Pompeia com metros de cinzas e piroclastos em poucas horas. Hoje três milhões de pessoas moram em volta dele, e ele continua ativo: é um dos vulcões mais vigiados do mundo. No relevo real, o cone fica a poucos quilômetros da baía de Nápoles.',audio:'vul-volta-1'},
 {titulo:'Etna, Sicília',lat:37.75,lon:15.0,terreno:'etna',chips:['Estratovulcão','Placa Africana × Euroasiática','O mais ativo da Europa'],text:'O Etna, na Sicília, é o vulcão mais ativo da Europa: entra em erupção quase todo ano. Ele nasce do encontro da placa Africana com a Euroasiática. As erupções costumam ser de lava e fontes de fogo, e os agricultores plantam nas encostas porque o solo vulcânico é muito fértil. No relevo real, repare na cicatriz escura do lado leste do cume: é o Vale do Bove, onde um pedaço da montanha desabou.',audio:'vul-volta-2'},
 {titulo:'Monte Fuji, Japão',lat:35.36,lon:138.73,terreno:'fuji',chips:['Estratovulcão','Anel de Fogo','Dormente desde 1707'],text:'O Fuji, o cartão-postal do Japão, é um estratovulcão quase perfeito, com 3.776 metros. Fica no Anel de Fogo, onde a placa do Pacífico mergulha sob o Japão. A última erupção foi em 1707; ele está dormente, não extinto, e por isso é monitorado o tempo todo. No relevo real, repare no cone simétrico e nos lagos ao norte.',audio:'vul-volta-3'},
 {titulo:'Monte St. Helens, EUA',lat:46.19,lon:-122.19,terreno:'sthelens',chips:['Estratovulcão','Erupção lateral de 1980','Cascatas'],text:'O Monte St. Helens, no noroeste dos Estados Unidos. Em 18 de maio de 1980 o lado norte da montanha desabou e a erupção saiu de lado, numa explosão que derrubou florestas a 30 quilômetros de distância e tirou 400 metros do topo. A cratera em forma de ferradura, aberta para o norte, ficou como cicatriz. Olhe o relevo real: dá para ver a cratera e o leque cinza por onde passou a explosão.',audio:'vul-volta-sthelens'},
 {titulo:'Krakatoa, Indonésia',lat:-6.1,lon:105.4,terreno:'krakatoa',chips:['Estratovulcão','Explosão de 1883','Tsunami'],text:'O Krakatoa, entre Java e Sumatra. Em 1883 ele explodiu com tanta força que o barulho foi ouvido a quase 5 mil quilômetros. A ilha desapareceu, o tsunami matou mais de 36 mil pessoas e as cinzas esfriaram o planeta por anos. Hoje um vulcão novo, o Anak Krakatoa, cresce no mesmo lugar. No relevo real, as ilhas em volta são os pedaços da borda do vulcão antigo; a ilhota do meio é o Anak Krakatoa.',audio:'vul-volta-4'},
 {titulo:'Poços de Caldas, Brasil',lat:-21.8,lon:-46.6,terreno:'pocos',chips:['Vulcão extinto','Caldeira','80 milhões de anos'],text:'Última parada: Poços de Caldas, em Minas Gerais. O Brasil não tem vulcões ativos, mas já teve. Aqui ficava um vulcão gigante que desabou e virou uma caldeira de 30 quilômetros de largura, há uns 80 milhões de anos. A cidade fica dentro dela, e as águas quentes da região são a lembrança desse passado de fogo. No relevo real, dá para ver o anel de serras que é a borda da caldeira.',audio:'vul-volta-5'}
];
/* terrenos reais (Copernicus DEM 30 m): alturas em metros e lado da janela em km */
D.TERRENOS={fuji:{min:57,max:3728,km:34,exag:1.35,nome:'Monte Fuji',alt:'3.776 m',giro:0},sthelens:{min:389,max:2514,km:22,exag:1.35,nome:'Monte St. Helens',alt:'2.549 m (era 2.950 m antes de 1980)',giro:Math.PI},vesuvio:{min:-1,max:1273,km:22,exag:1.6,nome:'Vesúvio e a baía de Nápoles',alt:'1.281 m',giro:0},kilauea:{min:89,max:2132,km:24,exag:1.6,nome:'Kilauea e a encosta do Mauna Loa',alt:'1.247 m',giro:0},krakatoa:{min:-1,max:751,km:20,exag:1.8,nome:'Krakatoa e o Anak Krakatoa',alt:'Rakata 813 m',giro:0},etna:{min:0,max:3300,km:34,exag:1.35,nome:'Etna e o Vale do Bove',alt:'3.357 m',giro:0},pocos:{min:754,max:1630,km:40,exag:3.0,nome:'Caldeira de Poços de Caldas',alt:'borda a 1.600 m · 30 km de largura',giro:0}};
D.VUL_VOLTA_FIM={text:'Volta completa. Kilauea, Vesúvio, Etna, Fuji, St. Helens, Krakatoa e Poços de Caldas: cada vulcão conta de onde vem o seu magma e por que ele é manso ou explosivo.',audio:'vul-volta-fim'};
/* laboratório de erupção */
D.ERUPCAO={
 magmas:{fluido:{nome:'Fluido',longo:'Magma fluido (basáltico)',desc:'Pouca sílica: escorre fácil e deixa o gás escapar. É o magma do Havaí e da Islândia.'},viscoso:{nome:'Viscoso',longo:'Magma viscoso (andesítico)',desc:'Muita sílica: grosso como mel gelado, segura o gás até a pressão explodir. É o magma dos Andes, do Vesúvio e do Fuji.'}},
 gases:['Pouco','Médio','Muito'],
 resultados:{
  efusiva:{nome:'Erupção efusiva',chips:['Rios de lava','Pouco perigo imediato','Havaí, Islândia'],text:'Magma fluido com pouco gás: a lava sobe sem pressa, transborda pela cratera e escorre em rios pelas encostas. Não explode, mas a lava pode andar quilômetros e engolir estradas e casas. É a erupção do Kilauea.',audio:'vul-erupcao-efusiva'},
  fonte:{nome:'Fonte de lava',chips:['Jatos de lava','Estromboliana','Etna, Stromboli'],text:'Magma fluido com muito gás: as bolhas sobem rápido e estouram na cratera, jogando lava para o alto em fontes de fogo de centenas de metros. Bonito de longe e perigoso de perto. É o jeito do Etna e do Stromboli.',audio:'vul-erupcao-fonte'},
  domo:{nome:'Domo de lava',chips:['Lava que não escorre','Cresce devagar','Pode desabar'],text:'Magma viscoso com pouco gás: a lava é tão grossa que não escorre. Ela se empilha na cratera e forma um domo, uma cúpula de rocha quente que cresce por meses. O perigo é quando o domo desaba e solta uma avalanche de rocha e gás quente.',audio:'vul-erupcao-domo'},
  explosiva:{nome:'Erupção explosiva',chips:['Coluna de cinzas','Piroclastos','Vesúvio, Krakatoa'],text:'Magma viscoso cheio de gás: o gás fica preso até a pressão vencer, e aí o vulcão explode. Uma coluna de cinzas sobe dezenas de quilômetros, bombas de rocha voam e avalanches de gás e cinza descem as encostas a centenas de quilômetros por hora. Foi assim em Pompeia.',audio:'vul-erupcao-explosiva'}
 }
};
D.ERUPCAO_FIM={text:'Você já viu uma erupção mansa e uma explosiva. A diferença está no magma: fluido e com pouco gás escorre; viscoso e cheio de gás explode.',audio:'vul-erupcao-concluido'};
/* ===== Rochas e minerais ===== */
D.rocContext=[
 {name:'Três famílias',target:'minerais',text:'Toda rocha nasce de um de três jeitos. As ígneas vêm de magma que esfriou, como o granito e o basalto. As sedimentares nascem de pedaços de outras rochas, areia e lama, que se juntaram no fundo de rios e mares, como o arenito. E as metamórficas são rochas que foram cozidas e apertadas dentro da Terra até mudar, como o mármore.'},
 {name:'Rocha é feita de minerais',target:'ciclo',text:'Olhe o granito de perto: ele não é uma coisa só. Tem grãos brancos ou cinza de quartzo, grãos rosados de feldspato e lâminas brilhantes de mica. Mineral é o tijolo; rocha é a parede feita de vários tijolos. Cada mineral tem a sua cor, o seu brilho e a sua dureza.'},
 {name:'O ciclo das rochas',text:'E nenhuma rocha fica igual para sempre. O magma esfria e vira rocha ígnea; a chuva e o vento quebram a rocha em grãos, que se juntam e viram rocha sedimentar; o calor e a pressão transformam qualquer rocha em metamórfica; e, lá no fundo, tudo pode derreter e virar magma de novo. É o ciclo das rochas, que leva milhões de anos para dar uma volta.'}
];
D.CICLO={
 estados:{
  magma:{nome:'Magma',cor:'#ff7a20',text:'Rocha derretida, a mais de 700 graus, dentro da Terra. Daqui tudo começa.',audio:'roc-ciclo-magma'},
  ignea:{nome:'Rocha ígnea',cor:'#9a8c80',text:'O magma esfriou e endureceu. Devagar, lá embaixo, dá granito, de grãos grandes; rápido, na superfície, dá basalto, de grãos miúdos.',audio:'roc-ciclo-ignea'},
  sedimento:{nome:'Sedimento',cor:'#d8b878',text:'Chuva, vento, gelo e rios quebraram a rocha em pedaços: cascalho, areia, lama. A água carrega tudo para baixo, até o fundo de um lago ou do mar.',audio:'roc-ciclo-sedimento'},
  sedimentar:{nome:'Rocha sedimentar',cor:'#e0c08a',text:'Camada sobre camada, o peso apertou os grãos e a água cimentou: o sedimento virou rocha, como o arenito e o calcário. É aqui que os fósseis ficam guardados.',audio:'roc-ciclo-sedimentar'},
  metamorfica:{nome:'Rocha metamórfica',cor:'#c8c0d8',text:'Enterrada fundo, cozida e apertada, a rocha mudou sem derreter: os minerais se reorganizaram. O calcário virou mármore; a argila virou ardósia.',audio:'roc-ciclo-metamorfica'}
 },
 ordem:['magma','ignea','sedimento','sedimentar','metamorfica'],
 processos:[
  {id:'esfriar',nome:'Esfriar e endurecer',de:['magma'],para:'ignea',text:'O magma esfriou e cristalizou: nasceu uma rocha ígnea.'},
  {id:'erodir',nome:'Intemperismo e erosão',de:['ignea','sedimentar','metamorfica'],para:'sedimento',text:'Chuva, vento e gelo quebraram a rocha; os rios levaram os grãos embora.'},
  {id:'compactar',nome:'Compactar e cimentar',de:['sedimento'],para:'sedimentar',text:'Camadas de sedimento, apertadas e coladas: virou rocha sedimentar.'},
  {id:'metamorfizar',nome:'Calor e pressão',de:['ignea','sedimentar'],para:'metamorfica',text:'Enterrada fundo, cozida e espremida: a rocha mudou sem derreter.'},
  {id:'derreter',nome:'Derreter',de:['ignea','sedimentar','metamorfica'],para:'magma',text:'Fundo demais, quente demais: a rocha virou magma de novo. O ciclo recomeça.'}
 ]
};
D.CICLO_FIM={text:'Você passou pelos cinco estados: magma, ígnea, sedimento, sedimentar e metamórfica. Qualquer rocha pode virar qualquer outra; só depende do caminho e de muito tempo.',audio:'roc-ciclo-concluido'};
/* que rocha é essa? cinco rodadas com pistas */
D.IDENTIFICAR=[
 {amostra:'basalto',pistas:['Escura, quase preta','Grãos tão finos que não dá para ver','Algumas bolhinhas de gás'],opcoes:['basalto','granito','ardosia'],why:'Escura e de grãos finos: é o basalto, lava que esfriou rápido na superfície. O granito teria grãos grandes e claros; a ardósia se partiria em placas.'},
 {amostra:'arenito',pistas:['Cor de areia','Dá para ver os grãos, parecem colados','Tem camadas horizontais'],opcoes:['marmore','arenito','obsidiana'],why:'Grãos de areia colados em camadas: é o arenito, rocha sedimentar. O mármore é liso e com veios; a obsidiana é um vidro preto.'},
 {amostra:'marmore',pistas:['Clara, branca ou creme','Lisa, com veios cinza','Brilha quando polida'],opcoes:['calcario','arenito','marmore'],why:'Branco com veios e brilho: é o mármore, calcário que foi cozido e apertado. O calcário é mais fosco e pode ter fósseis.'},
 {amostra:'obsidiana',pistas:['Preta e brilhante como vidro','Sem grãos nenhum','Quebra em lascas afiadas'],opcoes:['carvao','obsidiana','basalto'],why:'Vidro vulcânico: a lava esfriou tão rápido que nem formou cristais. O carvão é preto, mas fosco e leve; o basalto tem grãos.'},
 {amostra:'granito',pistas:['Clara, com pintas rosa, branco e preto','Grãos grandes, dá para ver cada um','Dura e pesada'],opcoes:['granito','pomes','arenito'],why:'Pintas de quartzo, feldspato e mica, grãos grandes: granito, magma que esfriou devagar no fundo. A pedra-pomes é leve e cheia de furos.'}
];
D.IDENTIFICAR_FIM={text:'Cinco amostras identificadas. Cor, tamanho dos grãos, camadas, brilho e bolhas: com essas pistas dá para ler a história de quase qualquer pedra.',audio:'roc-identificar-concluido'};
/* contexto em três etapas (cena muda a cada etapa) */
D.context=[
 {name:'Planeta Terra',target:'aberta',text:'Esta é a Terra vista do espaço: uma bola de rocha e metal com 12.742 quilômetros de diâmetro. A gente vive na superfície e quase nunca pensa no que tem lá embaixo. Vamos abrir o planeta ao meio.'},
 {name:'A Terra por dentro',target:'crosta',text:'Aberta ao meio, a Terra mostra as suas camadas: a crosta fininha por fora, o manto enorme no meio, e no centro o núcleo, de ferro e níquel, com a parte de fora líquida e a de dentro sólida. Olhe agora bem de perto a camada onde a gente vive.'},
 {name:'A casca fina',text:'A crosta é a casca da Terra. Comparando com uma maçã, ela é mais fina que a casca da fruta: no oceano tem uns 7 quilômetros, nos continentes de 30 a 70. Tudo o que o ser humano já perfurou, cerca de 12 quilômetros, não chegou nem a atravessá-la.'}
];
/* fichas (chaves = nomes dos áudios) */
D.info={
 terra:{name:'Terra',kind:'Planeta',color:'#6fb7e0',text:'A Terra tem 6.371 quilômetros de raio e é feita de camadas, como uma cebola: crosta, manto e núcleo. Quanto mais fundo, mais quente e mais apertado.',detail:'Diâmetro: 12.742 km. Idade: cerca de 4,5 bilhões de anos. É o planeta rochoso mais denso do Sistema Solar, por causa do núcleo metálico.',medio:'A diferenciação em camadas aconteceu no início da formação do planeta: os materiais mais densos (ferro e níquel) afundaram para o centro, e os silicatos, mais leves, ficaram por fora.'},
 crosta:{name:'Crosta',kind:'Camada externa · sólida',color:'#8fd0a0',text:'A crosta é a camada de fora, onde a gente vive. É de rocha sólida e fininha: de 5 a 70 quilômetros. Debaixo dos oceanos é mais fina e mais pesada; nos continentes é mais grossa e mais leve.',detail:'Duas crostas diferentes: a continental (granito, 30 a 70 km, mais antiga) e a oceânica (basalto, 5 a 10 km, mais densa). A fronteira com o manto chama-se descontinuidade de Mohorovičić, a "Moho".',medio:'A crosta corresponde a menos de 1% da massa da Terra. A oceânica é renovada nas dorsais e destruída nas zonas de subducção; por isso nenhuma rocha do fundo do mar tem mais de 200 milhões de anos.'},
 crosta_continental:{name:'Crosta continental',kind:'Crosta · 30 a 70 km',color:'#a8d8a0',text:'Esta é a crosta continental: a parte grossa, de granito, que forma os continentes. Chega a 70 quilômetros debaixo das grandes montanhas. É a rocha mais antiga do planeta: algumas têm 4 bilhões de anos.',detail:'Menos densa que a oceânica, ela "boia" sobre o manto. Por isso os continentes ficam acima do nível do mar.',medio:'Densidade média de 2,7 g/cm³, rica em sílica e alumínio. Em colisões de placas ela dobra e se espessa, formando cadeias como os Andes e o Himalaia.'},
 crosta_oceanica:{name:'Crosta oceânica',kind:'Crosta · 5 a 10 km',color:'#5fa8c8',text:'Esta é a crosta oceânica: fina, escura, de basalto. Fica no fundo dos mares. Ela nasce nas dorsais, onde a lava sobe, e é jovem: nenhuma parte tem mais de 200 milhões de anos.',detail:'Mais densa que a continental (3,0 g/cm³). Quando encontra um continente, mergulha por baixo dele: é a subducção.',medio:'Formada pelo resfriamento do basalto nas dorsais meso-oceânicas, registra as inversões do campo magnético em faixas simétricas, uma das provas da tectônica de placas.'},
 litosfera:{name:'Litosfera',kind:'Crosta + topo do manto · rígida',color:'#c9c2a0',text:'A litosfera é a crosta mais o pedacinho de cima do manto, tudo rígido, com uns 100 quilômetros. É ela que está quebrada em placas, as placas tectônicas, que se movem devagar sobre a camada mole de baixo.',detail:'As placas se movem de 2 a 10 cm por ano, mais ou menos a velocidade com que a sua unha cresce.',medio:'O limite inferior da litosfera é térmico (isoterma de cerca de 1.300 °C), não de composição: abaixo dela a mesma rocha passa a se comportar de modo dúctil.'},
 astenosfera:{name:'Astenosfera',kind:'Manto superior · plástica',color:'#e0a060',text:'Logo abaixo da litosfera vem a astenosfera. A rocha aqui é tão quente que fica mole, como uma massa de modelar. É sobre ela que as placas deslizam.',detail:'Vai de cerca de 100 a 350 km de profundidade. Não é líquida: é sólida, mas se deforma devagar.',medio:'Uma pequena fração de rocha parcialmente fundida reduz a rigidez e a velocidade das ondas sísmicas (zona de baixa velocidade), o que permitiu identificá-la.'},
 manto_superior:{name:'Manto superior',kind:'Manto · até 660 km',color:'#e07a3c',text:'O manto superior vai até 660 quilômetros de profundidade. É rocha quente, de 1.000 a 1.600 graus, que se mexe muito devagar, como caramelo. Esse movimento empurra as placas lá em cima.',detail:'Feito principalmente de peridotito, uma rocha rica em olivina, um mineral verde. Inclui a astenosfera.',medio:'A 410 km e a 660 km a olivina muda de estrutura cristalina com a pressão (transições de fase), o que separa o manto superior do inferior e aparece nas ondas sísmicas.'},
 manto_inferior:{name:'Manto inferior',kind:'Manto · 660 a 2.900 km',color:'#c84a28',text:'O manto inferior é a maior camada da Terra: vai de 660 até 2.900 quilômetros. Sozinho, o manto todo tem 84 por cento do volume do planeta. Aqui a temperatura chega a 3.700 graus, mas a pressão é tão grande que a rocha continua sólida.',detail:'A rocha se move por convecção: a quente sobe, a fria desce, em correntes que levam milhões de anos para dar uma volta.',medio:'Composto por bridgmanita e ferropericlase, estáveis sob alta pressão. Na base, a camada D″ interage com o núcleo e pode originar as plumas mantélicas (como a do Havaí).'},
 nucleo_externo:{name:'Núcleo externo',kind:'Núcleo · líquido · 2.900 a 5.150 km',color:'#f0a030',text:'O núcleo externo é um oceano de metal derretido: ferro e níquel líquidos a mais de 4.000 graus. Ele gira e se mexe, e é esse movimento que cria o campo magnético da Terra, o escudo que protege a gente do vento solar.',detail:'Sabemos que é líquido porque as ondas sísmicas do tipo S, que não atravessam líquidos, somem quando chegam nele.',medio:'O geodínamo: a convecção de metal condutor, combinada com a rotação da Terra, gera correntes elétricas que sustentam o campo magnético. O campo inverte de polaridade em intervalos irregulares.'},
 nucleo_interno:{name:'Núcleo interno',kind:'Núcleo · sólido · 5.150 a 6.371 km',color:'#fff0a0',text:'No centro de tudo, o núcleo interno: uma bola de ferro sólido com 1.220 quilômetros de raio, quase do tamanho da Lua. É o lugar mais quente da Terra, uns 5.400 graus, tão quente quanto a superfície do Sol. Mas é sólido, porque a pressão é gigantesca.',detail:'A pressão no centro é de cerca de 3,6 milhões de vezes a pressão do ar na superfície.',medio:'Descoberto em 1936 pela sismóloga Inge Lehmann. Cresce lentamente conforme o núcleo externo se solidifica, liberando calor que ajuda a mover o geodínamo.'},
 moho:{name:'Descontinuidade de Moho',kind:'Fronteira crosta · manto',color:'#d8e8c0',text:'A Moho é a linha que separa a crosta do manto. Ela foi descoberta em 1909 por Andrija Mohorovičić, que percebeu que as ondas dos terremotos aceleravam de repente ao cruzar essa profundidade.',detail:'Fica a 5 a 10 km sob os oceanos e a 30 a 70 km sob os continentes.',medio:'Marca a mudança de rochas da crosta (granito, basalto) para o peridotito do manto, mais denso, o que aumenta a velocidade das ondas P de ~7 para ~8 km/s.'},
 ondas_sismicas:{name:'Ondas sísmicas',kind:'Como conhecemos o interior',color:'#9fd0ff',text:'Ninguém nunca viu o interior da Terra. Tudo o que sabemos veio dos terremotos: as ondas que eles produzem atravessam o planeta e mudam de velocidade e de direção em cada camada. Os sismógrafos do mundo inteiro registram isso, e os cientistas montam a imagem de dentro.',detail:'Ondas P atravessam sólidos e líquidos; ondas S só atravessam sólidos. Como as S desaparecem no núcleo externo, descobrimos que ele é líquido.',medio:'A "zona de sombra" das ondas S (entre 104° e 180° do epicentro) e a refração das ondas P no núcleo permitiram a Gutenberg (1914) medir o raio do núcleo.'},
 campo_magnetico:{name:'Campo magnético',kind:'Escudo da Terra',color:'#b0a0ff',text:'A Terra é um ímã gigante por causa do núcleo externo: o ferro líquido em movimento gera o campo magnético. É ele que faz a bússola apontar para o norte e que desvia as partículas do Sol, formando as auroras nos polos.',detail:'Sem o campo magnético, o vento solar arrancaria a atmosfera aos poucos, como aconteceu em Marte.',medio:'O campo é aproximadamente dipolar, com intensidade de 25 a 65 microteslas na superfície. Os polos magnéticos migram e o campo já inverteu centenas de vezes.'},
 pacifica:{name:'Placa do Pacífico',kind:'Placa oceânica · a maior',color:'#7fc8ff',text:'A placa do Pacífico é a maior de todas, e é quase toda oceânica: debaixo dela só tem fundo de mar. Ela está rodeada pelo Anel de Fogo, a faixa de vulcões e terremotos que vai do Chile ao Japão.',detail:'Move-se para noroeste cerca de 7 a 10 cm por ano. O Havaí nasceu de um ponto quente no meio dela.',medio:'Como é oceânica e densa, mergulha sob as placas vizinhas em quase toda a sua borda: por isso o Anel de Fogo concentra 75% dos vulcões ativos do mundo.'},
 norteamericana:{name:'Placa Norte-Americana',kind:'Placa continental',color:'#ffb27a',text:'A placa Norte-Americana carrega os Estados Unidos, o Canadá, a Groenlândia e metade do oceano Atlântico. Ela se afasta da Europa pela dorsal e esfrega na placa do Pacífico na falha de San Andreas.',detail:'Afasta-se da placa Euroasiática a cerca de 2,5 cm por ano.',medio:'Inclui também o nordeste da Sibéria e o Japão setentrional: o limite com a Euroasiática não coincide com a divisão dos continentes.'},
 sulamericana:{name:'Placa Sul-Americana',kind:'Placa continental',color:'#9ee09e',text:'A nossa placa. Ela carrega a América do Sul inteira e metade do Atlântico Sul. Do lado do Pacífico, a placa de Nazca mergulha debaixo dela e levanta os Andes. O Brasil fica bem no meio, longe de tudo isso.',detail:'Move-se para oeste, cerca de 2 a 3 cm por ano, afastando-se da África.',medio:'A borda oeste é um limite convergente (subducção de Nazca); a leste, a dorsal Meso-Atlântica é divergente. No interior estável, o cráton brasileiro tem rochas de mais de 2 bilhões de anos.'},
 africana:{name:'Placa Africana',kind:'Placa continental',color:'#ffd27f',text:'A placa Africana carrega o continente africano e está se rasgando ao meio: o Vale do Rift, no leste da África, é uma fenda que um dia vai virar um oceano. Os grandes lagos africanos ficam dentro dela.',detail:'Afasta-se da América do Sul pela dorsal Meso-Atlântica.',medio:'O rifte leste-africano separa a subplaca Somali da Núbia; é um exemplo atual de limite divergente em continente, estágio inicial da abertura de um oceano.'},
 euroasiatica:{name:'Placa Euroasiática',kind:'Placa continental',color:'#d0a6ff',text:'A placa Euroasiática vai de Portugal até o Japão: Europa e a maior parte da Ásia. No sul, ela recebe o empurrão da Índia, que levantou o Himalaia, e da África, que levanta os Alpes.',detail:'É das placas mais lentas: 1 a 2 cm por ano.',medio:'Colisões continentais no seu limite sul (Alpes, Cáucaso, Himalaia) produzem as maiores montanhas do planeta, sem subducção de crosta oceânica.'},
 indoaustraliana:{name:'Placa Indo-Australiana',kind:'Placa mista',color:'#ff9aa8',text:'A placa Indo-Australiana carrega a Índia e a Austrália. Ela é a viajante: a Índia saiu de perto da Antártida, cruzou o oceano a 15 centímetros por ano e bateu na Ásia. Esse choque fez o Himalaia.',detail:'Hoje avança para o norte a cerca de 6 cm por ano.',medio:'Alguns modelos a dividem em placa Indiana e placa Australiana, separadas por uma zona difusa de deformação no oceano Índico.'},
 antartica:{name:'Placa Antártica',kind:'Placa continental e oceânica',color:'#d8ecff',text:'A placa Antártica fica no fundo do mundo: o continente gelado e o oceano em volta. Quase toda a sua borda é divergente, então ela é cercada de dorsais e tem poucos terremotos.',detail:'É quase estacionária: as outras placas se afastam dela.',medio:'Como as bordas são quase todas divergentes, a placa cresce de todos os lados; isso a torna uma referência útil para medir o movimento das demais.'},
 nazca:{name:'Placa de Nazca',kind:'Placa oceânica',color:'#9ff3ff',text:'A placa de Nazca é um pedaço de fundo de mar na frente do Chile e do Peru. Ela mergulha debaixo da América do Sul, e é esse mergulho que faz os vulcões dos Andes e os maiores terremotos já medidos, como o do Chile em 1960.',detail:'Nasce na dorsal do Pacífico Leste e some na fossa Peru-Chile.',medio:'O terremoto de Valdívia (1960, magnitude 9,5) ocorreu nessa zona de subducção; a fossa Peru-Chile chega a 8 km de profundidade.'},
 divergente:{name:'Limite divergente',kind:'As placas se afastam',color:'#ffb27a',text:'No limite divergente, duas placas se afastam. O magma sobe pela fenda, esfria e vira rocha nova: é assim que nasce fundo de oceano. As dorsais no meio dos oceanos são isso: cordilheiras submarinas de lava.',detail:'Exemplo: a dorsal Meso-Atlântica, que passa pela Islândia.',medio:'A crosta oceânica nova registra o campo magnético da época em faixas simétricas, evidência decisiva da expansão do assoalho oceânico.'},
 convergente:{name:'Limite convergente',kind:'As placas se chocam',color:'#ff7a5a',text:'No limite convergente, duas placas se chocam. Se uma é oceânica, ela mergulha por baixo da outra, derrete e vira vulcão: a subducção. Se as duas são continentais, nenhuma afunda e a crosta dobra para cima: nascem montanhas.',detail:'Exemplos: os Andes (subducção) e o Himalaia (colisão continental).',medio:'A placa que mergulha arrasta água para o manto, baixando o ponto de fusão da rocha: por isso os vulcões ficam em arco, a cerca de 100 km da fossa.'},
 transformante:{name:'Limite transformante',kind:'As placas deslizam',color:'#ffe08a',text:'No limite transformante, as placas não se chocam nem se afastam: deslizam uma ao lado da outra. A rocha trava, acumula força por décadas e solta de uma vez. Esse estalo é o terremoto.',detail:'Exemplo: a falha de San Andreas, na Califórnia.',medio:'Não cria nem destrói crosta. Os sismos são rasos (até 20 km), o que os torna muito destrutivos nas cidades próximas.'},
 terremoto:{name:'Terremoto',kind:'Fenômeno',color:'#ff6b6b',text:'Terremoto é a rocha estalando. Quando duas placas travam e a força acumulada vence, a rocha se parte e libera energia em ondas que sacodem o chão. A escala de magnitude mede essa energia: cada ponto a mais é 32 vezes mais energia.',detail:'O ponto de origem, em profundidade, é o hipocentro; na superfície, acima dele, o epicentro.',medio:'As ondas P chegam primeiro e as S depois; a diferença de tempo entre elas permite calcular a distância do epicentro em cada sismógrafo.'},
 tsunami:{name:'Tsunami',kind:'Fenômeno',color:'#5fa8c8',text:'Tsunami é a onda gigante que nasce quando um terremoto levanta o fundo do mar de repente. No oceano aberto ela passa quase sem ser notada, mas perto da costa cresce e invade a terra. Foi o que aconteceu no Japão em 2011.',detail:'Viaja a até 800 km por hora, a velocidade de um avião.',medio:'A altura cresce ao se aproximar da costa porque a velocidade cai com a profundidade e a energia se concentra: a onda "freia" e empilha.'},
 pangeia:{name:'Pangeia e a deriva',kind:'História da Terra',color:'#c9a070',text:'Há 250 milhões de anos todos os continentes estavam juntos num só, a Pangeia. Alfred Wegener percebeu isso em 1912 olhando o encaixe da costa do Brasil com a da África, e fósseis iguais nos dois lados. Os continentes se separaram devagar, carregados pelas placas.',detail:'Wegener não sabia o que movia os continentes; a resposta, o manto em convecção, só veio nos anos 1960.',medio:'Evidências: encaixe das costas, continuidade de cadeias de montanhas e rochas, fósseis de Mesosaurus na América do Sul e na África, e marcas glaciais em continentes hoje tropicais.'},
 anel_fogo:{name:'Anel de Fogo',kind:'Região',color:'#ffa040',text:'O Anel de Fogo é a faixa em volta do oceano Pacífico onde ficam três de cada quatro vulcões ativos do mundo e a maior parte dos terremotos fortes. Vai do Chile até o Alasca, desce pelo Japão e chega à Nova Zelândia.',detail:'Cerca de 40 mil km de comprimento e 450 vulcões.',medio:'É o conjunto das zonas de subducção que cercam a placa do Pacífico e as placas oceânicas menores (Nazca, Cocos, Filipina).'},
 camara_magmatica:{name:'Câmara de magma',kind:'Parte do vulcão · 2 a 10 km de profundidade',color:'#ff7a20',text:'A câmara de magma é a bolsa de rocha derretida embaixo do vulcão, a uns poucos quilômetros de profundidade. Ali o magma fica guardado, quente e cheio de gás, até a pressão ser grande demais. Quando a câmara se esvazia depois de uma erupção enorme, o teto pode desabar e virar uma caldeira.',detail:'Temperatura do magma: 700 a 1.300 °C. As câmaras não são cavernas cheias de líquido: são regiões de rocha parcialmente derretida, como uma esponja encharcada.',medio:'A câmara é alimentada por magma que sobe do manto por diferença de densidade. A cristalização dentro dela muda a composição do magma restante (diferenciação magmática), tornando-o mais rico em sílica e mais viscoso.'},
 conduto:{name:'Conduto',kind:'Parte do vulcão · o caminho do magma',color:'#ff5a10',text:'O conduto é o tubo que liga a câmara de magma à cratera. Por ele o magma sobe quando a pressão aperta. Em vulcões antigos, o magma que endureceu dentro do conduto forma uma coluna de rocha dura, o neck, que aparece quando o resto do cone é levado pela erosão.',detail:'Pode ter alguns metros ou dezenas de metros de largura. Vulcões grandes têm vários condutos e fissuras laterais.',medio:'Conforme o magma sobe pelo conduto, a pressão diminui e os gases dissolvidos formam bolhas (vesiculação), o que acelera a subida e pode fragmentar o magma em piroclastos.'},
 cratera:{name:'Cratera',kind:'Parte do vulcão · a boca',color:'#ffb27a',text:'A cratera é a boca do vulcão, a depressão em forma de funil no topo do cone por onde a erupção sai. Em alguns vulcões ela guarda um lago de lava; em outros, depois de muito tempo parado, enche de água da chuva e vira um lago comum.',detail:'Costuma ter de dezenas de metros a 1 km de largura. Não confundir com caldeira, que é muito maior e nasce de um desabamento.',medio:'Crateras são construídas pela acumulação de material ao redor do conduto e podem ser alargadas por explosões que arrancam parte do topo do edifício vulcânico.'},
 cone:{name:'Cone vulcânico',kind:'Parte do vulcão · o edifício',color:'#8a7a6a',text:'O cone é a montanha do vulcão, e ele é feito das próprias erupções: cada camada é uma erupção antiga, lava endurecida ou cinzas, uma em cima da outra. Por isso os vulcões crescem ao longo de milhares de anos. Olhando o corte, dá para contar as erupções como anéis de uma árvore.',detail:'O Fuji tem 3.776 m; o Mauna Kea, no Havaí, medido desde o fundo do mar, passa de 10 km: é a maior montanha da Terra.',medio:'Estratovulcões alternam camadas de lava e de piroclastos (estratos), daí o nome. Vulcões em escudo são feitos quase só de lavas fluidas sobrepostas.'},
 magma:{name:'Magma',kind:'Material · rocha derretida dentro da Terra',color:'#ff6a30',text:'Magma é rocha derretida enquanto ainda está dentro da Terra, misturada com gases e cristais. Ele nasce no manto ou na base da crosta e sobe porque é mais leve que a rocha em volta. O magma tem nome e comportamento diferentes conforme a quantidade de sílica: pouca sílica, fluido; muita sílica, viscoso.',detail:'Temperatura: 700 a 1.300 °C. O magma basáltico (pouca sílica) é o mais fluido; o riolítico (muita sílica) é o mais viscoso.',medio:'A viscosidade cresce com o teor de SiO₂ porque os tetraedros de sílica se ligam em cadeias. Magmas basálticos têm ~50% de SiO₂; riolíticos, ~70%.'},
 lava:{name:'Lava',kind:'Material · o magma do lado de fora',color:'#ff8a3c',text:'Lava é o mesmo magma, só que já fora da Terra. Quando sai pela cratera ou por uma fissura, perde os gases e começa a esfriar. A lava fluida corre como um rio e forma mantos lisos; a viscosa anda devagar e se empilha. Ao endurecer, vira rocha vulcânica, como o basalto.',detail:'A lava fluida pode correr a 30 km/h em encostas íngremes. No Havaí, os rios de lava chegam ao mar e criam terra nova.',medio:'Tipos de superfície da lava basáltica: pahoehoe (lisa, em cordas) e aa (áspera, em blocos). A lava almofadada (pillow) forma-se debaixo d’água, nas dorsais.'},
 nuvem_cinzas:{name:'Nuvem de cinzas',kind:'Material · rocha pulverizada',color:'#b9b2a8',text:'A nuvem cinza que sobe do vulcão não é fumaça: são cinzas, pedacinhos de rocha e vidro vulcânico menores que um grão de areia, lançados pela explosão. A coluna pode subir dezenas de quilômetros e o vento espalha as cinzas por países inteiros, fechando aeroportos e cobrindo cidades.',detail:'Em 2010, as cinzas do Eyjafjallajökull, na Islândia, pararam os aviões da Europa por uma semana.',medio:'Cinzas finas na estratosfera refletem luz solar e podem resfriar o clima global por um ou dois anos, como após o Pinatubo (1991) e o Tambora (1815, o “ano sem verão”).'},
 piroclastos:{name:'Piroclastos',kind:'Material · fragmentos lançados',color:'#5a4a40',text:'Piroclasto quer dizer “pedaço de fogo”: é tudo o que o vulcão lança quebrado. Vai das cinzas finas até as bombas vulcânicas, blocos de lava do tamanho de um carro que voam pelo ar. O mais perigoso é o fluxo piroclástico: uma avalanche de gás e cinza a 600 graus, que desce o vulcão a mais de 100 km/h.',detail:'Pompeia foi soterrada por cinzas e fluxos piroclásticos, não por lava.',medio:'Classificação por tamanho: cinza (< 2 mm), lapíli (2 a 64 mm) e blocos ou bombas (> 64 mm). As bombas saem ainda moles e ganham forma aerodinâmica no ar.'},
 gases_vulcanicos:{name:'Gases vulcânicos',kind:'Material · o motor da erupção',color:'#cfe0f0',text:'O magma é cheio de gás dissolvido, principalmente vapor de água e gás carbônico, como um refrigerante fechado. Quando o magma sobe e a pressão cai, o gás vira bolhas e empurra tudo para fora: é o gás que faz a erupção. As fumarolas, buracos que soltam vapor e enxofre, mostram que o vulcão está vivo lá embaixo.',detail:'Medir os gases é um dos jeitos de prever erupções: quando o dióxido de enxofre aumenta, o magma está subindo.',medio:'Composição típica: H₂O (60 a 90%), CO₂, SO₂, H₂S, HCl. O CO₂ pode se acumular em lagos vulcânicos e escapar de repente, como em Nyos (1986).'},
 estratovulcao:{name:'Estratovulcão',kind:'Tipo de vulcão · cone alto e explosivo',color:'#8a6a5a',text:'O estratovulcão é o vulcão de desenho: cone alto, pontudo, com encostas íngremes. É feito de camadas alternadas de lava e cinzas. O magma viscoso e cheio de gás faz dele o tipo mais explosivo. Fuji, Vesúvio, Etna e os vulcões dos Andes são estratovulcões.',detail:'A maioria fica nas zonas de subducção, no Anel de Fogo.',medio:'Também chamado de vulcão composto. A alternância de estratos de lava (que dão resistência) e de piroclastos (que dão volume) permite que cresçam até vários quilômetros.'},
 escudo:{name:'Vulcão em escudo',kind:'Tipo de vulcão · baixo, largo e manso',color:'#9a8a6a',text:'O vulcão em escudo é baixo e muito largo, como um escudo deitado no chão. Ele é feito de lava fluida que escorre para longe antes de endurecer, camada sobre camada. As erupções são mansas, de rios de lava. Os vulcões do Havaí são os maiores exemplos: o Mauna Loa tem 120 km de largura.',detail:'O maior vulcão do Sistema Solar, o Monte Olimpo, em Marte, é um vulcão em escudo com 600 km de largura.',medio:'Formados por lavas basálticas de baixa viscosidade, em geral sobre pontos quentes ou em zonas de rifte. Encostas de apenas 5 a 10 graus.'},
 caldeira:{name:'Caldeira',kind:'Tipo de vulcão · o teto que desabou',color:'#c9a070',text:'Caldeira é o que sobra quando uma erupção gigante esvazia a câmara de magma e o vulcão inteiro desaba para dentro do buraco. Fica uma panela enorme, de quilômetros de largura, que às vezes vira um lago. Yellowstone, nos Estados Unidos, é uma caldeira de 70 km; Poços de Caldas, no Brasil, tem 30.',detail:'As maiores erupções da história da Terra formaram caldeiras: Toba (74 mil anos atrás) lançou 2.800 km³ de material.',medio:'Supervulcões são sistemas de caldeira capazes de erupções de índice VEI 8. O ressurgimento (soerguimento do piso da caldeira) indica recarga da câmara.'},
 ponto_quente:{name:'Ponto quente',kind:'Origem do magma · vulcão no meio da placa',color:'#ffa040',text:'A maioria dos vulcões fica nas fronteiras das placas, mas o Havaí está bem no meio da placa do Pacífico. É um ponto quente: uma pluma de manto quente sobe de muito fundo e fura a placa. Como a placa se move e a pluma fica parada, nasce uma fila de ilhas: as mais velhas vão se afastando e apagando.',detail:'A cadeia havaiana tem mais de 80 vulcões ao longo de 6 mil km; só os da ponta, como o Kilauea, estão ativos.',medio:'Plumas mantélicas podem ter origem no limite manto-núcleo. Outros exemplos: Islândia (ponto quente sobre uma dorsal), Galápagos, Reunião, Yellowstone.'},
 vulcao_ativo:{name:'Ativo, dormente ou extinto',kind:'Estado do vulcão',color:'#ffe08a',text:'Um vulcão ativo entrou em erupção nos últimos 10 mil anos e pode voltar a qualquer momento, como o Etna. Dormente é o que está quieto há séculos, mas ainda tem magma embaixo, como o Fuji. Extinto é o que não tem mais como entrar em erupção, porque a fonte de magma acabou, como os antigos vulcões do Brasil.',detail:'Existem cerca de 1.500 vulcões ativos no mundo, e uns 50 entram em erupção por ano.',medio:'A classificação é imprecisa: o Vesúvio e o Pinatubo eram considerados dormentes antes de erupções grandes. O monitoramento usa sismos, deformação do solo e gases.'},
 granito:{name:'Granito',kind:'Rocha ígnea · esfriou devagar',color:'#d8b8a8',text:'O granito é a rocha das montanhas e das pedras de pia. Nasceu de magma que esfriou bem devagar, lá no fundo, e por isso os grãos cresceram grandes: dá para ver o quartzo branco, o feldspato rosado e a mica brilhante a olho nu. É duro e resiste por milhões de anos.',detail:'Pão de Açúcar e Corcovado, no Rio, são granito e gnaisse. O granito é a rocha mais comum da crosta continental.',medio:'Rocha plutônica (intrusiva), felsica: quartzo, feldspatos (ortoclásio e plagioclásio) e micas. Textura fanerítica indica resfriamento lento.'},
 basalto:{name:'Basalto',kind:'Rocha ígnea · esfriou rápido',color:'#4a4440',text:'O basalto é lava que esfriou rápido na superfície. Por isso é escuro e de grãos miúdos, que não dá para ver. Às vezes tem bolhinhas, que eram gás preso na lava. O fundo de todos os oceanos é feito de basalto, e no Brasil ele cobre o sul inteiro, formando a terra roxa.',detail:'Os paredões do Parque de Vila Velha e os derrames da bacia do Paraná (um dos maiores do mundo) são basalto.',medio:'Rocha vulcânica (extrusiva), máfica: plagioclásio e piroxênio, pobre em sílica. Textura afanítica; vesículas quando o gás escapa.'},
 obsidiana:{name:'Obsidiana',kind:'Rocha ígnea · vidro vulcânico',color:'#1a1a22',text:'A obsidiana é um vidro de verdade, feito pela natureza: lava que esfriou tão depressa que não deu tempo de formar cristais. É preta, brilhante e quebra em lascas afiadas como navalha. Povos antigos faziam facas e pontas de flecha com ela.',detail:'Lâminas de obsidiana ainda são usadas em bisturis experimentais, por serem mais finas que o aço.',medio:'Vidro vulcânico riolítico, rico em sílica, com fratura conchoidal. A ausência de estrutura cristalina a classifica como mineraloide.'},
 pomes:{name:'Pedra-pomes',kind:'Rocha ígnea · cheia de furos',color:'#d8d4cc',text:'A pedra-pomes é a espuma da lava: sai do vulcão cheia de gás, esfria rápido e fica crivada de furinhos. É tão leve que boia na água. Depois de erupções grandes, jangadas de pomes atravessam o oceano.',detail:'Usada para lixar pés e para fazer concreto leve.',medio:'Piroclasto vesicular de composição félsica, formado em erupções explosivas; densidade inferior a 1 g/cm³ por causa das vesículas.'},
 arenito:{name:'Arenito',kind:'Rocha sedimentar · areia colada',color:'#e0c08a',text:'O arenito é areia que virou pedra: grãos de uma praia ou de um deserto antigo, apertados por camadas e camadas por cima, e colados por minerais que a água trouxe. Dá para ver as camadas, e às vezes as marcas das ondas de milhões de anos atrás.',detail:'As chapadas e as cidades de pedra do Brasil (Vila Velha, Sete Cidades, Chapada dos Guimarães) são arenito.',medio:'Rocha sedimentar clástica: grãos de 0,06 a 2 mm, em geral quartzo, com cimento de sílica, carbonato ou óxido de ferro. Estratificação cruzada indica dunas ou correntes.'},
 calcario:{name:'Calcário',kind:'Rocha sedimentar · conchas e corais',color:'#e8e0c8',text:'O calcário é feito de conchas, corais e esqueletos minúsculos que se acumularam no fundo de mares antigos. É claro, fosco e meio mole: a água da chuva dissolve e forma cavernas. É daqui que vem o cimento e a cal.',detail:'As grutas de Bonito e de Minas Gerais são calcário dissolvido pela água.',medio:'Composição: carbonato de cálcio (calcita). Reage com ácido clorídrico diluído (efervescência). Pode ser bioquímico (recifal) ou químico (precipitação).'},
 carvao:{name:'Carvão mineral',kind:'Rocha sedimentar · floresta soterrada',color:'#22201e',text:'O carvão é uma floresta antiga que virou pedra. Plantas de pântanos morreram, afundaram na lama sem apodrecer e ficaram enterradas por milhões de anos, cada vez mais apertadas, até virar essa rocha preta que pega fogo. Por isso ele é um combustível fóssil.',detail:'As jazidas brasileiras ficam no sul (Santa Catarina e Rio Grande do Sul), de florestas de 280 milhões de anos.',medio:'Rocha sedimentar orgânica: turfa → linhito → hulha → antracito, com teor de carbono crescente. Queimá-lo devolve à atmosfera CO₂ guardado há milhões de anos.'},
 marmore:{name:'Mármore',kind:'Rocha metamórfica · calcário cozido',color:'#f0ecea',text:'O mármore é calcário que foi enterrado, cozido e apertado até os grãos se reorganizarem. Fica liso, branco ou colorido, com veios, e brilha quando polido. É a rocha das estátuas e dos pisos.',detail:'O Davi de Michelangelo foi esculpido num bloco de mármore de Carrara, na Itália.',medio:'Metamorfismo da calcita recristaliza os grãos (textura granoblástica) e apaga fósseis e estratificação. Veios vêm de impurezas (argila, óxidos).'},
 ardosia:{name:'Ardósia',kind:'Rocha metamórfica · lama apertada',color:'#4a4e58',text:'A ardósia é lama que virou rocha e depois foi apertada de lado, dentro da Terra. Por isso ela se parte em placas finas e retas: era usada nas lousas das escolas antigas e ainda cobre telhados e pisos.',detail:'O Brasil é um dos maiores produtores do mundo, em Minas Gerais.',medio:'Metamorfismo de baixo grau de folhelhos: a foliação (clivagem ardosiana) é perpendicular à pressão, independente das camadas originais.'},
 quartzo:{name:'Quartzo',kind:'Mineral · o mais comum',color:'#e8f0f8',text:'O quartzo é o mineral mais comum da crosta. É duro, transparente ou branco, e forma cristais em ponta de seis lados. Está no granito, na areia da praia, no vidro e no relógio de pulso, onde ele vibra e marca o tempo.',detail:'Dureza 7 na escala de Mohs: risca o vidro. A ametista e o citrino são quartzo colorido.',medio:'SiO₂, sistema trigonal. Piezoelétrico: gera tensão elétrica sob pressão, por isso é usado em osciladores.'},
 feldspato:{name:'Feldspato',kind:'Mineral · o mais abundante',color:'#f0c0b0',text:'O feldspato é o mineral mais abundante da Terra: é mais da metade da crosta. São os grãos rosados ou brancos, de faces retas, do granito. Quando o feldspato apodrece com a chuva, vira argila, a matéria-prima do tijolo e da cerâmica.',detail:'Dureza 6. A porcelana leva feldspato na receita.',medio:'Grupo de silicatos de alumínio com K, Na ou Ca (ortoclásio, plagioclásio). Duas direções de clivagem em ângulo quase reto.'},
 mica:{name:'Mica',kind:'Mineral · lâminas brilhantes',color:'#c8a060',text:'A mica são aquelas lâminas brilhantes, prateadas ou pretas, que se soltam em folhas finas como papel. Está no granito e brilha na areia de alguns rios, o que já enganou muito garimpeiro. Aguenta calor e não conduz eletricidade.',detail:'Usada em janelas de fornos antigos e em cosméticos com brilho.',medio:'Filossilicatos (muscovita clara, biotita escura) com clivagem basal perfeita. Isolante térmico e elétrico.'},
 kola:{name:'Poço de Kola',kind:'Até onde chegamos',color:'#e8d8b0',text:'O buraco mais fundo que o ser humano já cavou fica na Rússia: o poço de Kola, com 12 quilômetros. Parece muito, mas é só 0,2 por cento do caminho até o centro. Lá no fundo a rocha estava a 180 graus, e as brocas não aguentaram mais.',detail:'Foram 20 anos de perfuração, de 1970 a 1992. O buraco tem 23 cm de largura.',medio:'A temperatura subiu mais rápido do que o previsto (gradiente de ~15 °C/km nas camadas profundas) e a rocha tornou-se plástica, fechando o poço.'}
};
D.CATALOGO={rochasExp:[['Ígneas: nasceram do magma',['granito','basalto','obsidiana','pomes']],['Sedimentares: pedaços que se juntaram',['arenito','calcario','carvao']],['Metamórficas: mudaram com calor e pressão',['marmore','ardosia']],['Minerais: os tijolos das rochas',['quartzo','feldspato','mica']]],vulcaoExp:[['Partes do vulcão',['camara_magmatica','conduto','cratera','cone']],['O que sai na erupção',['magma','lava','nuvem_cinzas','piroclastos','gases_vulcanicos']],['Tipos e estados',['estratovulcao','escudo','caldeira','ponto_quente','vulcao_ativo']]],placasExp:[['As grandes placas',['pacifica','norteamericana','sulamericana','africana','euroasiatica','indoaustraliana','antartica','nazca']],['Os três limites',['divergente','convergente','transformante']],['O que acontece nas fronteiras',['terremoto','tsunami','anel_fogo','pangeia']]],explorar:[['Camadas, de fora para dentro',['crosta','manto_superior','manto_inferior','nucleo_externo','nucleo_interno']],['Dentro da crosta e do manto',['crosta_continental','crosta_oceanica','litosfera','astenosfera','moho']],['Como sabemos disso',['ondas_sismicas','campo_magnetico','kola']]]};
D.LEGENDA_ROCHAS=[['#b09080','Ígneas'],['#e0c08a','Sedimentares'],['#c8c0d8','Metamórficas'],['#e8f0f8','Minerais']];
D.LEGENDA_VULCAO=[['#ff7a20','Magma e lava'],['#8a7a6a','Rocha do cone'],['#b9b2a8','Cinzas'],['#ff8a40','Vulcões ativos']];
D.LEGENDA_PLACAS=[['#ffe08a','Fronteira de placas'],['#ff6b6b','Terremotos'],['#ffb27a','Divergente'],['#ff7a5a','Convergente'],['#ffe08a','Transformante']];
D.LEGENDA=[['#8fd0a0','Crosta'],['#e07a3c','Manto superior'],['#c84a28','Manto inferior'],['#f0a030','Núcleo externo'],['#fff0a0','Núcleo interno']];
/* sequência: camadas da superfície ao centro */
D.sequencias={montar:{titulo:'DA SUPERFÍCIE AO CENTRO',cor:'#f6c37a',ordem:['crosta','manto_superior','manto_inferior','nucleo_externo','nucleo_interno'],rotulos:{crosta:'Crosta',manto_superior:'Manto superior',manto_inferior:'Manto inferior',nucleo_externo:'Núcleo externo',nucleo_interno:'Núcleo interno'},
 pistas:['Comece pela camada onde a gente pisa.','O manto é a camada do meio, e tem duas partes: a de cima vem antes.','O núcleo tem uma parte líquida por fora e uma sólida por dentro.']}};
/* viagem ao centro: sete trechos (profundidade em km, temperatura e pressão didáticas) */
D.viagem=[
 {titulo:'Crosta: até o fundo do poço',de:0,ate:12,temp:'20 → 180 °C',pressao:'1 → 3.000 atm',cor:0x8fd0a0,dur:13,text:'Estamos descendo pela crosta. Rocha sólida, fria, cheia de rachaduras com água. Aos 12 quilômetros passamos pelo ponto mais fundo que o ser humano já perfurou: o poço de Kola. Daqui para baixo, ninguém nunca esteve.',audio:'viagem-0'},
 {titulo:'Crosta: até a Moho',de:12,ate:35,temp:'180 → 500 °C',pressao:'3 mil → 10 mil atm',cor:0x7cc090,dur:12,text:'Continuamos na crosta continental. A rocha fica cada vez mais quente, e a pressão já apertaria qualquer coisa que a gente conhece. Aos 35 quilômetros, cruzamos a Moho: acabou a crosta, começa o manto.',audio:'viagem-1'},
 {titulo:'Litosfera e astenosfera',de:35,ate:100,temp:'500 → 1.300 °C',pressao:'até 30 mil atm',cor:0xd09060,dur:12,text:'Entramos no manto. Nos primeiros quilômetros ele ainda é rígido: é a base da litosfera, da placa que carrega os continentes. Perto dos 100 quilômetros a rocha passa de 1.300 graus e começa a ficar mole: é a astenosfera.',audio:'viagem-2'},
 {titulo:'Manto superior',de:100,ate:660,temp:'1.300 → 1.600 °C',pressao:'até 240 mil atm',cor:0xe07a3c,dur:14,text:'Manto superior: rocha vermelha, quente, que se mexe devagar como caramelo. É esse movimento que, lá em cima, arrasta as placas e levanta montanhas. Aos 660 quilômetros os minerais mudam de forma por causa da pressão.',audio:'viagem-3'},
 {titulo:'Manto inferior',de:660,ate:2900,temp:'1.600 → 3.700 °C',pressao:'até 1,4 milhão atm',cor:0xc84a28,dur:16,text:'Este é o trecho mais longo da viagem: o manto inferior, mais de 2.000 quilômetros de rocha. Está a milhares de graus, mas a pressão é tão grande que ela continua sólida. Lá embaixo, uma luz alaranjada: estamos chegando ao núcleo.',audio:'viagem-4'},
 {titulo:'Núcleo externo',de:2900,ate:5150,temp:'3.700 → 5.000 °C',pressao:'até 3,3 milhões atm',cor:0xf0a030,dur:16,text:'Mergulhamos no núcleo externo: um mar de ferro e níquel derretidos. Correntes de metal líquido giram em volta de nós. É daqui que vem o campo magnético, o escudo invisível que protege a vida na superfície.',audio:'viagem-5'},
 {titulo:'Núcleo interno',de:5150,ate:6371,temp:'5.400 °C',pressao:'3,6 milhões atm',cor:0xfff0a0,dur:14,text:'Chegamos ao núcleo interno: ferro sólido, mais quente que a superfície do Sol, e sólido só porque toda a Terra está em cima dele. Mais alguns quilômetros e estamos no centro exato do planeta. Daqui, qualquer direção é para cima.',audio:'viagem-6'}
];
D.VIAGEM_FIM={text:'Viagem completa: 6.371 quilômetros, da crosta ao centro. Crosta, manto superior, manto inferior, núcleo externo e núcleo interno. Agora você sabe o que existe debaixo dos seus pés.',audio:'viagem-fim'};
/* desafio */
D.questions=[
 {id:'liquida',skill:'camadas',q:'Qual camada da Terra está no estado líquido?',options:['A crosta oceânica','O manto inferior','O núcleo externo','O núcleo interno'],correct:2,why:'O núcleo externo é ferro e níquel derretidos. As ondas sísmicas S não o atravessam, e foi assim que descobrimos que ele é líquido.'},
 {id:'kola',skill:'escala',q:'O buraco mais fundo já feito pelo ser humano tem 12 km. Até onde ele chegou?',options:['Até o manto superior','Nem atravessou a crosta','Até a astenosfera','Até o núcleo externo'],correct:1,why:'O poço de Kola parou dentro da crosta continental, que ali tem uns 35 km. São 0,2% do caminho até o centro.'},
 {id:'manto',skill:'camadas',q:'Qual camada ocupa a maior parte do volume da Terra?',options:['A crosta','O manto','O núcleo externo','O núcleo interno'],correct:1,why:'O manto tem 84% do volume do planeta. Vai de 35 km até 2.900 km de profundidade.'},
 {id:'magnetico',skill:'fenomenos',q:'O que produz o campo magnético da Terra?',options:['O ferro sólido do núcleo interno','As rochas magnéticas da crosta','O movimento do metal líquido no núcleo externo','O calor do manto'],correct:2,why:'O ferro líquido do núcleo externo se move e conduz eletricidade: isso gera o campo magnético, o geodínamo.'},
 {id:'sismicas',skill:'evidencias',q:'Como os cientistas conhecem o interior da Terra, se ninguém nunca esteve lá?',options:['Por fotos de satélite','Pelas ondas dos terremotos, que mudam em cada camada','Por perfurações até o núcleo','Pela cor da lava dos vulcões'],correct:1,why:'As ondas sísmicas mudam de velocidade e de direção ao cruzar cada camada. Registradas no mundo inteiro, elas revelam o que há dentro.'},
 {id:'interno',skill:'fenomenos',q:'O núcleo interno é a parte mais quente da Terra. Por que ele é sólido?',options:['Porque é feito de rocha','Porque a pressão enorme impede o ferro de derreter','Porque está esfriando há bilhões de anos','Porque não tem oxigênio'],correct:1,why:'A 3,6 milhões de atmosferas, o ferro se mantém sólido mesmo a 5.400 graus. É a pressão que decide, não só a temperatura.'},
 {id:'oceanica',skill:'camadas',q:'Comparando a crosta oceânica com a continental, a oceânica é…',options:['Mais grossa e mais leve','Mais fina e mais densa','Mais antiga','Feita de granito'],correct:1,why:'A crosta oceânica tem 5 a 10 km, é de basalto e mais densa. Por isso ela mergulha sob os continentes nas zonas de subducção.'},
 {id:'placasMovem',skill:'placas',pref:'plac-',q:'O que faz as placas tectônicas se moverem?',options:['O vento e as marés','O manto quente, que se move por baixo delas','A rotação da Terra','Os terremotos'],correct:1,why:'As correntes do manto, que sobe quente e desce frio, arrastam as placas da litosfera uns centímetros por ano.'},
 {id:'andes',skill:'limites',pref:'plac-',q:'Como se formou a cordilheira dos Andes?',options:['Duas placas se afastando','Uma placa oceânica mergulhando sob a América do Sul','Duas placas deslizando lado a lado','Um vulcão gigante'],correct:1,why:'A placa de Nazca mergulha sob a Sul-Americana (limite convergente). O choque dobra a borda do continente e alimenta os vulcões andinos.'},
 {id:'atlantico',skill:'limites',pref:'plac-',q:'O oceano Atlântico está ficando maior a cada ano. Por quê?',options:['Porque as geleiras derretem','Porque a dorsal no meio dele cria fundo de mar novo','Porque a África afunda','Porque os rios trazem água'],correct:1,why:'Na dorsal Meso-Atlântica, limite divergente, o magma sobe e vira crosta nova. As placas se afastam uns 2 cm por ano.'},
 {id:'sanandreas',skill:'limites',pref:'plac-',q:'Na falha de San Andreas, as placas…',options:['se chocam de frente','se afastam','deslizam uma ao lado da outra','não se movem'],correct:2,why:'É um limite transformante: a placa do Pacífico e a Norte-Americana deslizam lado a lado, travam e soltam, gerando terremotos.'},
 {id:'brasil',skill:'placas',pref:'plac-',q:'Por que o Brasil quase não tem terremotos fortes nem vulcões ativos?',options:['Porque o clima é quente','Porque fica no meio da placa Sul-Americana, longe das fronteiras','Porque a crosta aqui é mais fina','Porque não há montanhas'],correct:1,why:'Terremotos e vulcões se concentram nas bordas das placas. O Brasil está no interior estável da placa Sul-Americana.'},
 {id:'pangeia',skill:'historia',pref:'plac-',q:'Qual destas é uma evidência de que os continentes já estiveram juntos?',options:['O Brasil e a África têm o mesmo clima','Fósseis iguais nos dois lados do Atlântico e o encaixe das costas','Os oceanos têm a mesma profundidade','A Lua gira em volta da Terra'],correct:1,why:'Wegener usou o encaixe das costas, fósseis iguais (como o Mesosaurus) e rochas contínuas para propor a Pangeia e a deriva dos continentes.'},
 {id:'porqueVulcao',skill:'origem',pref:'vul-',q:'Por que os Andes e o Japão têm tantos vulcões?',options:['Porque ficam perto do mar','Porque uma placa mergulha sob a outra e a água dela faz o manto derreter','Porque a crosta ali é mais fina','Porque ficam perto do Equador'],correct:1,why:'Nas zonas de subducção, a placa que afunda leva água para o manto, baixa o ponto de fusão da rocha e gera magma. É a origem do Anel de Fogo.'},
 {id:'lavaMagma',skill:'materiais',pref:'vul-',q:'Qual é a diferença entre magma e lava?',options:['Magma é frio, lava é quente','Magma é a rocha derretida dentro da Terra; lava é quando ela sai para fora','Lava é mais líquida que magma','Não há diferença, são sinônimos'],correct:1,why:'É o mesmo material: chama-se magma enquanto está dentro da Terra e lava quando chega à superfície e perde os gases.'},
 {id:'explosiva',skill:'erupcoes',pref:'vul-',q:'O que torna uma erupção explosiva, como a do Vesúvio?',options:['Lava muito quente','Magma viscoso e cheio de gás, que prende o gás até a pressão vencer','Muita chuva na cratera','Um vulcão muito alto'],correct:1,why:'O magma viscoso não deixa o gás escapar aos poucos. A pressão sobe até estourar, lançando cinzas e piroclastos. Magma fluido escorre e não explode.'},
 {id:'havai',skill:'origem',pref:'vul-',q:'O Havaí fica no meio da placa do Pacífico, longe das fronteiras. Como existem vulcões lá?',options:['A placa é muito fina ali','Um ponto quente: uma pluma de manto fura a placa por baixo','O oceano esquenta a crosta','São restos de um meteoro'],correct:1,why:'O Havaí está sobre um ponto quente. A pluma fica parada e a placa se move por cima, por isso as ilhas formam uma fila, das mais velhas às mais novas.'},
 {id:'pompeia',skill:'materiais',pref:'vul-',q:'O que soterrou Pompeia na erupção do Vesúvio, no ano 79?',options:['Rios de lava','Cinzas e fluxos piroclásticos','Um tsunami','Um terremoto'],correct:1,why:'Pompeia foi coberta por metros de cinzas e atingida por fluxos piroclásticos, avalanches de gás e cinza quente. A lava não chegou à cidade.'},
 {id:'brasilVulcao',skill:'origem',pref:'vul-',q:'Por que o Brasil não tem vulcões ativos?',options:['Porque o clima é tropical','Porque fica no meio da placa Sul-Americana, longe das fronteiras, e sem ponto quente ativo','Porque a Amazônia resfria o solo','Porque os vulcões brasileiros foram apagados pela chuva'],correct:1,why:'Vulcões aparecem nas bordas das placas ou sobre pontos quentes. O Brasil está no interior estável da placa; os vulcões que teve, como Poços de Caldas, se extinguiram há milhões de anos.'},
 {id:'granitoBasalto',skill:'igneas',pref:'roc-',q:'Granito e basalto nascem do mesmo magma. Por que o granito tem grãos grandes e o basalto, miúdos?',options:['O granito é mais velho','O granito esfriou devagar no fundo; o basalto esfriou rápido na superfície','O basalto é mais duro','O granito tem mais água'],correct:1,why:'Resfriamento lento dá tempo para os cristais crescerem (granito, plutônico). Lava que esfria em horas forma grãos minúsculos (basalto, vulcânico).'},
 {id:'fossil',skill:'sedimentares',pref:'roc-',q:'Em que tipo de rocha é possível encontrar fósseis?',options:['No granito','No basalto','Nas rochas sedimentares, como o calcário e o arenito','No mármore'],correct:2,why:'Fósseis ficam guardados nas camadas de sedimento que viram rocha. Magma derrete qualquer resto, e o metamorfismo apaga as marcas.'},
 {id:'marmore',skill:'metamorficas',pref:'roc-',q:'O mármore é uma rocha metamórfica. De qual rocha ele se formou?',options:['Do granito','Do basalto','Do calcário','Da areia'],correct:2,why:'Calcário enterrado, cozido e apertado recristaliza e vira mármore. Argila vira ardósia; arenito vira quartzito.'},
 {id:'carvao',skill:'sedimentares',pref:'roc-',q:'De onde vem o carvão mineral?',options:['De lava que esfriou','De florestas de pântano soterradas por milhões de anos','De conchas do fundo do mar','Do fundo dos vulcões'],correct:1,why:'Plantas de pântanos antigos, enterradas sem apodrecer, foram apertadas por milhões de anos até virar carvão: por isso é um combustível fóssil.'},
 {id:'cicloSed',skill:'ciclo',pref:'roc-',q:'A areia de uma praia pode virar rocha? Como?',options:['Não, areia nunca vira rocha','Sim, se for aquecida até derreter','Sim, enterrada em camadas, apertada e cimentada pela água, vira arenito','Sim, se chover muito'],correct:2,why:'Compactação e cimentação: camadas por cima apertam os grãos e minerais dissolvidos na água os colam. É assim que nascem as rochas sedimentares.'},
 {id:'mineralRocha',skill:'minerais',pref:'roc-',q:'Qual é a diferença entre mineral e rocha?',options:['Mineral é mais duro que rocha','Mineral é um só material, com fórmula própria; rocha é uma mistura de minerais','Rocha é mais valiosa','Não há diferença'],correct:1,why:'Quartzo, feldspato e mica são minerais, cada um com composição definida. O granito é uma rocha: a mistura dos três.'},
 {id:'temperatura',skill:'escala',q:'O que acontece com a temperatura conforme descemos para o centro da Terra?',options:['Diminui, porque fica longe do Sol','Fica igual','Aumenta, até cerca de 5.400 °C no centro','Aumenta só até o manto e depois cai'],correct:2,why:'A temperatura sobe o tempo todo: uns 25 graus por quilômetro na crosta, chegando a cerca de 5.400 °C no núcleo interno.'}
];
D.todasQuestoes=D.questions;
/* aula guiada */
D.guide=[
 {view:'contexto',title:'Localize-se',goal:'Veja a Terra do espaço, abra o planeta ao meio e olhe de perto a crosta onde a gente vive.',check:'contexto',audio:'aula-contexto'},
 {view:'explorar',title:'Investigue as camadas',goal:'Aponte em pelo menos três camadas da Terra aberta e ouça o que cada uma é.',check:'explorar',audio:'aula-explorar'},
 {view:'montar',title:'Monte as camadas',goal:'Coloque as cinco camadas na ordem, da superfície ao centro.',check:'montar',audio:'aula-montar'},
 {view:'viagem',title:'Desça ao centro',goal:'Faça a viagem completa, trecho a trecho, até o centro da Terra. Repare na temperatura e na pressão subindo.',check:'viagem',audio:'aula-viagem'},
 {view:'desafio',title:'Mostre o que entendeu',goal:'Responda às situações finais e consulte o seu resumo.',check:'desafio',audio:'aula-desafio'},
 {view:'placContexto',title:'Veja a casca quebrada',goal:'Olhe as fronteiras das placas no globo, veja para onde elas se movem e onde a Terra treme.',check:'placContexto',audio:'plac-aula-contexto'},
 {view:'placasExp',title:'Investigue as placas',goal:'Aponte em pelo menos três placas ou limites e ouça o que cada um é.',check:'placasExp',audio:'plac-aula-explorar'},
 {view:'limites',title:'Descubra os limites',goal:'Toque nas três maquetes e descubra qual é divergente, convergente e transformante.',check:'limites',audio:'plac-aula-limites'},
 {view:'volta',title:'Dê a volta ao mundo',goal:'Visite os seis lugares e repare no tipo de limite de cada um.',check:'volta',audio:'plac-aula-volta'},
 {view:'placDesafio',title:'Mostre o que entendeu',goal:'Hora de mostrar o que você entendeu. Responda às situações e, no final, confira o seu resumo.',check:'placDesafio',audio:'plac-aula-desafio'},
 {view:'vulContexto',title:'Localize o fogo',goal:'Veja onde ficam os vulcões no globo, de onde vem o magma e como é um vulcão por dentro.',check:'vulContexto',audio:'vul-aula-contexto'},
 {view:'vulcaoExp',title:'Investigue o vulcão',goal:'Aponte em pelo menos três partes do vulcão aberto e ouça o que cada uma é.',check:'vulcaoExp',audio:'vul-aula-explorar'},
 {view:'erupcao',title:'Provoque erupções',goal:'Monte uma erupção mansa e uma explosiva: troque o tipo de magma e a quantidade de gás e compare.',check:'erupcao',audio:'vul-aula-erupcao'},
 {view:'vulVolta',title:'Dê a volta ao mundo',goal:'Visite os sete vulcões e repare no tipo de cada um e de onde vem o seu magma. No Fuji e no St. Helens, abra o relevo real.',check:'vulVolta',audio:'vul-aula-volta'},
 {view:'vulDesafio',title:'Mostre o que entendeu',goal:'Hora de mostrar o que você entendeu. Responda às situações e, no final, confira o seu resumo.',check:'vulDesafio',audio:'vul-aula-desafio'},
 {view:'rocContexto',title:'Conheça as três famílias',goal:'Veja as três famílias de rochas, descubra que rocha é feita de minerais e dê uma volta pelo ciclo.',check:'rocContexto',audio:'roc-aula-contexto'},
 {view:'rochasExp',title:'Investigue a bancada',goal:'Toque em pelo menos três amostras da bancada e ouça o que cada uma é.',check:'rochasExp',audio:'roc-aula-explorar'},
 {view:'ciclo',title:'Transforme a rocha',goal:'Leve a rocha pelos cinco estados do ciclo: magma, ígnea, sedimento, sedimentar e metamórfica.',check:'ciclo',audio:'roc-aula-ciclo'},
 {view:'identificar',title:'Identifique as amostras',goal:'Use as pistas para descobrir as cinco rochas misteriosas.',check:'identificar',audio:'roc-aula-identificar'},
 {view:'rocDesafio',title:'Mostre o que entendeu',goal:'Hora de mostrar o que você entendeu. Responda às situações e, no final, confira o seu resumo.',check:'rocDesafio',audio:'roc-aula-desafio'}
];
D.WELCOME='Bem-vindo ao Terra por Dentro! Aqui você vai abrir o planeta ao meio, conhecer cada camada, montar a Terra de fora para dentro e fazer uma viagem até o centro, onde ninguém nunca chegou. Vamos começar?';
D.sources=[['Copernicus DEM GLO-30 (relevo real do Fuji e do St. Helens) · © DLR e.V. 2010-2014 e © Airbus Defence and Space GmbH 2014-2018, fornecido sob COPERNICUS pela União Europeia e ESA','https://registry.opendata.aws/copernicus-dem/'],['three.js · textura de lava dos exemplos (licença MIT)','https://github.com/mrdoob/three.js/tree/r128/examples/textures/lava'],['Babylon.js Assets · texturas de rocha e normal map (CC BY 4.0)','https://github.com/BabylonJS/Assets'],['NASA Visible Earth · Blue Marble (texturas da superfície, domínio público; cópias distribuídas com o three.js)','https://visibleearth.nasa.gov/collection/1484/blue-marble'],['Smithsonian Global Volcanism Program (vulcões ativos do Holoceno; pontos do globo simplificados)','https://volcano.si.edu/'],['USGS · Volcano Hazards Program','https://www.usgs.gov/programs/VHP'],['USGS · Earth\'s interior','https://www.usgs.gov/faqs/what-are-earths-layers'],['IRIS · Exploring the Earth using seismology','https://www.iris.edu/hq/inclass/animation/exploring_the_earth_using_seismology'],['Kola Superdeep Borehole · dados históricos','https://en.wikipedia.org/wiki/Kola_Superdeep_Borehole'],['BNCC · EF06CI11 (camadas da Terra); EF06CI12, EF07CI15 e EF07CI16 nos temas seguintes','http://basenacionalcomum.mec.gov.br/']];
window.TERRA_DATA=D;
})();
