/* Terra por Dentro · dados (v1.0)
   Conteúdo: tema Camadas da Terra (Contexto, Explorar, Monte as camadas, Viagem ao centro, Desafio).
   Placas, Vulcão e Rochas entram como temas "em breve". Textos no tom falado das narrações (chaves = nomes dos MP3 em audio/). */
(function(){'use strict';
const D={version:'1.1.0'};
D.temas=[
 {id:'camadas',nome:'Camadas da Terra',estuda:'Do que a Terra é feita por dentro.',exemplos:'Crosta, manto, núcleo externo e núcleo interno',modulo:'cam',atividades:['contexto','explorar','montar','viagem'],questoes:['liquida','kola','manto','magnetico','sismicas','interno','oceanica','temperatura']},
 {id:'placas',nome:'Placas tectônicas',estuda:'Por que a crosta se mexe, treme e se quebra.',exemplos:'Placas, limites, terremotos, vulcões e a deriva dos continentes',modulo:'pla',atividades:['placContexto','placasExp','limites','volta'],questoes:['placasMovem','andes','atlantico','sanandreas','brasil','pangeia']},
 {id:'vulcao',nome:'Vulcões',estuda:'Da câmara de magma à erupção.',breve:true},
 {id:'rochas',nome:'Rochas e minerais',estuda:'O ciclo das rochas, da lava ao sedimento.',breve:true}
];
D.modulos=[{id:'cam',label:'Camadas da Terra',curto:'Camadas',pergunta:'O que existe debaixo dos nossos pés?'},{id:'pla',label:'Placas tectônicas',curto:'Placas',pergunta:'Por que a Terra treme e os continentes se movem?'}];
D.PREF={cam:'',pla:'plac-'};
D.activities=[
 {id:'contexto',label:'Contexto',title:'O que existe debaixo dos seus pés?',subtitle:'Do planeta visto do espaço até a casca fina em que vivemos.',kicker:'LOCALIZE',modulo:'cam'},
 {id:'explorar',label:'Explorar',title:'A Terra aberta ao meio.',subtitle:'Aponte em uma camada para ver a ficha e ouvir a explicação.',kicker:'EXPLORE',modulo:'cam'},
 {id:'montar',label:'Monte as camadas',title:'Da superfície ao centro.',subtitle:'Coloque as camadas na ordem, de fora para dentro.',kicker:'ORGANIZE',modulo:'cam'},
 {id:'viagem',label:'Viagem ao centro',title:'Desça até o centro da Terra.',subtitle:'Uma viagem em primeira pessoa: 6.371 km em sete trechos.',kicker:'VIAJE',modulo:'cam'},
 {id:'desafio',label:'Desafio',title:'Agora, explique o que descobriu.',subtitle:'Situações para aplicar o que você viu.',kicker:'APLIQUE',modulo:'cam'},
 {id:'placContexto',label:'Contexto',title:'A casca está quebrada.',subtitle:'A litosfera é um quebra-cabeça de placas que se movem.',kicker:'LOCALIZE',modulo:'pla'},
 {id:'placasExp',label:'Explorar',title:'As placas e seus limites.',subtitle:'Aponte em uma placa do globo ou escolha na lista.',kicker:'EXPLORE',modulo:'pla'},
 {id:'limites',label:'Que limite é esse?',title:'Três jeitos de as placas se encontrarem.',subtitle:'Toque em cada maquete e descubra o tipo de limite.',kicker:'INVESTIGUE',modulo:'pla'},
 {id:'volta',label:'Volta ao mundo',title:'Uma volta ao mundo tectônica.',subtitle:'Seis lugares onde a Terra mostra as placas em ação.',kicker:'ACOMPANHE',modulo:'pla'}
];
/* placas: contexto em três etapas */
D.placContext=[
 {name:'A litosfera quebrada',target:'movem',text:'Olhe a casca da Terra de perto: ela não é inteira. A litosfera está quebrada em grandes pedaços, as placas tectônicas, como a casca de um ovo rachado. As linhas amarelas são as fronteiras entre elas.'},
 {name:'As placas se movem',target:'tremem',text:'E esses pedaços se mexem, muito devagar: uns centímetros por ano, a velocidade em que a sua unha cresce. Quem empurra é o manto quente, que se move por baixo. Em milhões de anos, isso leva continentes inteiros de um lado para o outro.'},
 {name:'Onde a Terra treme',text:'Agora repare nos pontos vermelhos: são terremotos. Quase todos acontecem nas fronteiras das placas, onde elas se chocam, se afastam ou se esfregam. O mesmo vale para os vulcões. O anel em volta do Pacífico é o lugar mais agitado do planeta.'}
];
/* placas (polígonos simplificados, lon/lat; a Pacífica usa lon > 180 para não cruzar a linha de data) */
D.placas=[
 {key:'antartica',cor:'#d8ecff',pts:[[-180,-55],[180,-55],[180,-90],[-180,-90]]},
 {key:'pacifica',cor:'#7fc8ff',pts:[[135,50],[150,45],[145,35],[140,25],[125,10],[135,-5],[150,-12],[165,-25],[175,-45],[190,-55],[220,-55],[250,-40],[265,-20],[255,0],[250,20],[240,35],[235,48],[210,58],[180,55],[160,52]]},
 {key:'norteamericana',cor:'#ffb27a',pts:[[-170,65],[-140,60],[-125,48],[-120,35],[-110,20],[-95,15],[-85,10],[-75,15],[-55,15],[-45,20],[-40,30],[-30,60],[-10,75],[-20,85],[-90,85],[-150,80],[-170,70]]},
 {key:'sulamericana',cor:'#9ee09e',pts:[[-75,15],[-85,10],[-80,0],[-75,-15],[-72,-30],[-75,-45],[-70,-55],[-60,-58],[-20,-58],[-15,-40],[-25,-20],[-30,0],[-40,10],[-55,15]]},
 {key:'africana',cor:'#ffd27f',pts:[[-15,40],[-25,20],[-30,0],[-25,-20],[-15,-40],[-10,-55],[25,-55],[45,-45],[50,-30],[45,-10],[40,5],[40,15],[35,25],[35,35],[20,38],[0,38]]},
 {key:'euroasiatica',cor:'#d0a6ff',pts:[[-10,75],[-30,60],[-15,40],[0,38],[20,38],[35,35],[40,30],[60,25],[70,30],[90,30],[100,20],[110,15],[125,10],[140,25],[145,35],[150,45],[135,50],[140,60],[160,65],[180,70],[180,85],[-10,85]]},
 {key:'indoaustraliana',cor:'#ff9aa8',pts:[[40,15],[60,25],[70,30],[90,30],[100,20],[110,15],[125,10],[135,-5],[150,-12],[165,-25],[175,-45],[150,-55],[100,-55],[60,-50],[45,-45],[50,-30],[45,-10]]},
 {key:'nazca',cor:'#9ff3ff',pts:[[-105,0],[-95,-20],[-110,-40],[-80,-45],[-75,-45],[-72,-30],[-75,-15],[-80,0]]}
];
/* volta ao mundo: seis paradas (lat, lon) */
D.volta=[
 {titulo:'Cordilheira dos Andes',lat:-20,lon:-68,chips:['Convergente','Nazca × Sul-Americana','Subducção'],text:'Primeira parada: os Andes. Aqui a placa de Nazca, do fundo do Pacífico, mergulha debaixo da placa Sul-Americana. O choque amassa a borda do continente e levanta a cordilheira, com vulcões e terremotos fortes, como o do Chile.',audio:'volta-0'},
 {titulo:'Falha de San Andreas',lat:36,lon:-120,chips:['Transformante','Pacífica × Norte-Americana','Terremotos'],text:'Califórnia, Estados Unidos. A placa do Pacífico e a Norte-Americana não se chocam: elas deslizam uma ao lado da outra. Onde a rocha trava e depois solta de repente, a terra treme. É a falha de San Andreas.',audio:'volta-1'},
 {titulo:'Islândia',lat:64,lon:-18,chips:['Divergente','Dorsal Meso-Atlântica','Nova crosta'],text:'Islândia, no meio do Atlântico. A ilha fica em cima da dorsal, onde a placa Norte-Americana e a Euroasiática se afastam. O magma sobe pela fenda, vira rocha nova e o oceano cresce uns 2 centímetros por ano.',audio:'volta-2'},
 {titulo:'Himalaia',lat:28,lon:87,chips:['Convergente','Indo-Australiana × Euroasiática','Montanhas'],text:'O Himalaia. A Índia era uma ilha e viajou para o norte até bater na Ásia. Como as duas são continentais e nenhuma afunda, a crosta se dobra e sobe: o Everest ainda cresce uns milímetros por ano.',audio:'volta-3'},
 {titulo:'Japão',lat:36,lon:138,chips:['Convergente','Anel de Fogo','Tsunamis'],text:'Japão, no Anel de Fogo do Pacífico. Aqui a placa do Pacífico mergulha sob o Japão. É por isso que o país tem tantos vulcões, terremotos e tsunamis, como o de 2011. Os prédios lá são construídos para balançar sem cair.',audio:'volta-4'},
 {titulo:'Brasil',lat:-15,lon:-50,chips:['Meio da placa','Estável','Crosta antiga'],text:'Última parada: o Brasil. Estamos bem no meio da placa Sul-Americana, longe das fronteiras. Por isso quase não temos terremotos fortes nem vulcões ativos. Já tivemos, há milhões de anos: as rochas antigas do planalto central contam essa história.',audio:'volta-5'}
];
D.VOLTA_FIM={text:'Volta completa. Andes, San Andreas, Islândia, Himalaia, Japão e Brasil: cada lugar mostra um jeito de as placas se encontrarem, ou de ficarem em paz.',audio:'volta-fim'};
/* contexto em três etapas (cena muda a cada etapa) */
D.context=[
 {name:'Planeta Terra',target:'aberta',text:'Esta é a Terra vista do espaço: uma bola de rocha e metal com 12.742 quilômetros de diâmetro. A gente vive na superfície e quase nunca pensa no que tem lá embaixo. Vamos abrir o planeta ao meio.'},
 {name:'A Terra por dentro',target:'crosta',text:'Aberta ao meio, a Terra mostra as suas camadas: a crosta fininha por fora, o manto enorme no meio, e no centro o núcleo, de ferro e níquel, com a parte de fora líquida e a de dentro sólida. Olhe agora bem de perto a camada onde a gente vive.'},
 {name:'A casca fina',text:'A crosta é a casca da Terra. Comparando com uma maçã, ela é mais fina que a casca da fruta: no oceano tem uns 7 quilômetros, nos continentes de 30 a 70. Tudo o que o ser humano já perfurou, cerca de 12 quilômetros, não chegou nem a atravessá-la.'}
];
/* fichas (chaves = nomes dos áudios) */
D.info={
 terra:{name:'Terra',kind:'Planeta',color:'#6fb7e0',text:'A Terra tem 6.371 quilômetros de raio e é feita de camadas, como uma cebola: crosta, manto e núcleo. Quanto mais fundo, mais quente e mais apertado.',detail:'Diâmetro: 12.742 km. Idade: cerca de 4,5 bilhões de anos. É o planeta rochoso mais denso do Sistema Solar, por causa do núcleo metálico.',medio:'A diferenciação em camadas aconteceu no início da formação do planeta: os materiais mais densos (ferro e níquel) afundaram para o centro, e os silicatos, mais leves, ficaram por fora.'},
 crosta:{name:'Crosta',kind:'Camada externa · sólida',color:'#8fd0a0',text:'A crosta é a camada de fora, onde a gente vive. É de rocha sólida e fininha: de 5 a 70 quilômetros. Debaixo dos oceanos é mais fina e mais pesada; nos continentes é mais grossa e mais leve.',detail:'Duas crostas diferentes: a continental (granito, 30 a 70 km, mais antiga) e a oceânica (basalto, 5 a 10 km, mais densa). A fronteira com o manto chama-se descontinuidade de Mohorovičić, a "Moho".',medio:'A crosta corresponde a menos de 1% da massa da Terra. A oceânica é renovada nas dorsais e destruída nas zonas de subducção; por isso nenhuma rocha do fundo do mar tem mais de 200 milhões de anos.'},
 crosta_continental:{name:'Crosta continental',kind:'Crosta · 30 a 70 km',color:'#a8d8a0',text:'Esta é a crosta continental: a parte grossa, de granito, que forma os continentes. Chega a 70 quilômetros debaixo das grandes montanhas. É a rocha mais antiga do planeta: algumas têm 4 bilhões de anos.',detail:'Menos densa que a oceânica, ela "boia" sobre o manto. Por isso os continentes ficam acima do nível do mar.',medio:'Densidade média de 2,7 g/cm³, rica em sílica e alumínio. Em colisões de placas ela dobra e se espessa, formando cadeias como os Andes e o Himalaia.'},
 crosta_oceanica:{name:'Crosta oceânica',kind:'Crosta · 5 a 10 km',color:'#5fa8c8',text:'Esta é a crosta oceânica: fina, escura, de basalto. Fica no fundo dos mares. Ela nasce nas dorsais, onde a lava sobe, e é jovem: nenhuma parte tem mais de 200 milhões de anos.',detail:'Mais densa que a continental (3,0 g/cm³). Quando encontra um continente, mergulha por baixo dele: é a subducção.',medio:'Formada pelo resfriamento do basalto nas dorsais meso-oceânicas, registra as inversões do campo magnético em faixas simétricas, uma das provas da tectônica de placas.'},
 litosfera:{name:'Litosfera',kind:'Crosta + topo do manto · rígida',color:'#c9c2a0',text:'A litosfera é a crosta mais o pedacinho de cima do manto, tudo rígido, com uns 100 quilômetros. É ela que está quebrada em placas, as placas tectônicas, que se movem devagar sobre a camada mole de baixo.',detail:'As placas se movem de 2 a 10 cm por ano, mais ou menos a velocidade com que a sua unha cresce.',medio:'O limite inferior da litosfera é térmico (isoterma de cerca de 1.300 °C), não de composição: abaixo dela a mesma rocha passa a se comportar de modo dúctil.'},
 astenosfera:{name:'Astenosfera',kind:'Manto superior · plástica',color:'#e0a060',text:'Logo abaixo da litosfera vem a astenosfera. A rocha aqui é tão quente que fica mole, como uma massa de modelar. É sobre ela que as placas deslizam.',detail:'Vai de cerca de 100 a 350 km de profundidade. Não é líquida: é sólida, mas se deforma devagar.',medio:'Uma pequena fração de rocha parcialmente fundida reduz a rigidez e a velocidade das ondas sísmicas (zona de baixa velocidade), o que permitiu identificá-la.'},
 manto_superior:{name:'Manto superior',kind:'Manto · até 660 km',color:'#e07a3c',text:'O manto superior vai até 660 quilômetros de profundidade. É rocha quente, de 1.000 a 1.600 graus, que se mexe muito devagar, como caramelo. Esse movimento empurra as placas lá em cima.',detail:'Feito principalmente de peridotito, uma rocha rica em olivina, um mineral verde. Inclui a astenosfera.',medio:'A 410 km e a 660 km a olivina muda de estrutura cristalina com a pressão (transições de fase), o que separa o manto superior do inferior e aparece nas ondas sísmicas.'},
 manto_inferior:{name:'Manto inferior',kind:'Manto · 660 a 2.900 km',color:'#c84a28',text:'O manto inferior é a maior camada da Terra: vai de 660 até 2.900 quilômetros. Sozinho, o manto todo tem 84 por cento do volume do planeta. Aqui a temperatura chega a 3.700 graus, mas a pressão é tão grande que a rocha continua sólida.',detail:'A rocha se move por convecção: a quente sobe, a fria desce, em correntes que levam milhões de anos para dar uma volta.',medio:'Composto por bridgmanita e ferropericlase, estáveis sob alta pressão. Na base, a camada D″ interage com o núcleo e pode originar as plumas mantélicas (como a do Havaí).'},
 nucleo_externo:{name:'Núcleo externo',kind:'Núcleo · líquido · 2.900 a 5.150 km',color:'#f0a030',text:'O núcleo externo é um oceano de metal derretido: ferro e níquel líquidos a mais de 4.000 graus. Ele gira e se mexe, e é esse movimento que cria o campo magnético da Terra, o escudo que protege a gente do vento solar.',detail:'Sabemos que é líquido porque as ondas sísmicas do tipo S, que não atravessam líquidos, somem quando chegam nele.',medio:'O geodínamo: a convecção de metal condutor, combinada com a rotação da Terra, gera correntes elétricas que sustentam o campo magnético. O campo inverte de polaridade em intervalos irregulares.'},
 nucleo_interno:{name:'Núcleo interno',kind:'Núcleo · sólido · 5.150 a 6.371 km',color:'#fff0a0',text:'No centro de tudo, o núcleo interno: uma bola de ferro sólido com 1.220 quilômetros de raio, quase do tamanho da Lua. É o lugar mais quente da Terra, uns 5.400 graus, tão quente quanto a superfície do Sol. Mas é sólido, porque a pressão é gigantesca.',detail:'A pressão no centro é de cerca de 3,6 milhões de vezes a pressão do ar na superfície.',medio:'Descoberto em 1936 pela sismóloga Inge Lehmann. Cresce lentamente conforme o núcleo externo se solidifica, liberando calor que ajuda a mover o geodínamo.'},
 moho:{name:'Descontinuidade de Moho',kind:'Fronteira crosta · manto',color:'#d8e8c0',text:'A Moho é a linha que separa a crosta do manto. Ela foi descoberta em 1909 por Andrija Mohorovičić, que percebeu que as ondas dos terremotos aceleravam de repente ao cruzar essa profundidade.',detail:'Fica a 5 a 10 km sob os oceanos e a 30 a 70 km sob os continentes.',medio:'Marca a mudança de rochas da crosta (granito, basalto) para o peridotito do manto, mais denso, o que aumenta a velocidade das ondas P de ~7 para ~8 km/s.'},
 ondas_sismicas:{name:'Ondas sísmicas',kind:'Como conhecemos o interior',color:'#9fd0ff',text:'Ninguém nunca viu o interior da Terra. Tudo o que sabemos veio dos terremotos: as ondas que eles produzem atravessam o planeta e mudam de velocidade e de direção em cada camada. Os sismógrafos do mundo inteiro registram isso, e os cientistas montam a imagem de dentro.',detail:'Ondas P atravessam sólidos e líquidos; ondas S só atravessam sólidos. Como as S desaparecem no núcleo externo, descobrimos que ele é líquido.',medio:'A "zona de sombra" das ondas S (entre 104° e 180° do epicentro) e a refração das ondas P no núcleo permitiram a Gutenberg (1914) medir o raio do núcleo.'},
 campo_magnetico:{name:'Campo magnético',kind:'Escudo da Terra',color:'#b0a0ff',text:'A Terra é um ímã gigante por causa do núcleo externo: o ferro líquido em movimento gera o campo magnético. É ele que faz a bússola apontar para o norte e que desvia as partículas do Sol, formando as auroras nos polos.',detail:'Sem o campo magnético, o vento solar arrancaria a atmosfera aos poucos, como aconteceu em Marte.',medio:'O campo é aproximadamente dipolar, com intensidade de 25 a 65 microteslas na superfície. Os polos magnéticos migram e o campo já inverteu centenas de vezes.'},
 pacifica:{name:'Placa do Pacífico',kind:'Placa oceânica · a maior',color:'#7fc8ff',text:'A placa do Pacífico é a maior de todas, e é quase toda oceânica: debaixo dela só tem fundo de mar. Ela está rodeada pelo Anel de Fogo, a faixa de vulcões e terremotos que vai do Chile ao Japão.',detail:'Move-se para noroeste cerca de 7 a 10 cm por ano. O Havaí nasceu de um ponto quente no meio dela.',medio:'Como é oceânica e densa, mergulha sob as placas vizinhas em quase toda a sua borda: por isso o Anel de Fogo concentra 75% dos vulcões ativos do mundo.'},
 norteamericana:{name:'Placa Norte-Americana',kind:'Placa continental',color:'#ffb27a',text:'A placa Norte-Americana carrega os Estados Unidos, o Canadá, a Groenlândia e metade do oceano Atlântico. Ela se afasta da Europa pela dorsal e esfrega na placa do Pacífico na falha de San Andreas.',detail:'Afasta-se da placa Euroasiática a cerca de 2,5 cm por ano.',medio:'Inclui também o nordeste da Sibéria e o Japão setentrional: o limite com a Euroasiática não coincide com a divisão dos continentes.'},
 sulamericana:{name:'Placa Sul-Americana',kind:'Placa continental',color:'#9ee09e',text:'A nossa placa. Ela carrega a América do Sul inteira e metade do Atlântico Sul. Do lado do Pacífico, a placa de Nazca mergulha debaixo dela e levanta os Andes. O Brasil fica bem no meio, longe de tudo isso.',detail:'Move-se para oeste, cerca de 2 a 3 cm por ano, afastando-se da África.',medio:'A borda oeste é um limite convergente (subducção de Nazca); a leste, a dorsal Meso-Atlântica é divergente. No interior estável, o cráton brasileiro tem rochas de mais de 2 bilhões de anos.'},
 africana:{name:'Placa Africana',kind:'Placa continental',color:'#ffd27f',text:'A placa Africana carrega o continente africano e está se rasgando ao meio: o Vale do Rift, no leste da África, é uma fenda que um dia vai virar um oceano. Os grandes lagos africanos ficam dentro dela.',detail:'Afasta-se da América do Sul pela dorsal Meso-Atlântica.',medio:'O rifte leste-africano separa a subplaca Somali da Núbia; é um exemplo atual de limite divergente em continente, estágio inicial da abertura de um oceano.'},
 euroasiatica:{name:'Placa Euroasiática',kind:'Placa continental',color:'#d0a6ff',text:'A placa Euroasiática vai de Portugal até o Japão: Europa e a maior parte da Ásia. No sul, ela recebe o empurrão da Índia, que levantou o Himalaia, e da África, que levanta os Alpes.',detail:'É das placas mais lentas: 1 a 2 cm por ano.',medio:'Colisões continentais no seu limite sul (Alpes, Cáucaso, Himalaia) produzem as maiores montanhas do planeta, sem subducção de crosta oceânica.'},
 indoaustraliana:{name:'Placa Indo-Australiana',kind:'Placa mista',color:'#ff9aa8',text:'A placa Indo-Australiana carrega a Índia e a Austrália. Ela é a viajante: a Índia saiu de perto da Antártida, cruzou o oceano a 15 centímetros por ano e bateu na Ásia. Esse choque fez o Himalaia.',detail:'Hoje avança para o norte a cerca de 6 cm por ano.',medio:'Alguns modelos a dividem em placa Indiana e placa Australiana, separadas por uma zona difusa de deformação no oceano Índico.'},
 antartica:{name:'Placa Antártica',kind:'Placa continental e oceânica',color:'#d8ecff',text:'A placa Antártica fica no fundo do mundo: o continente gelado e o oceano em volta. Quase toda a sua borda é divergente, então ela é cercada de dorsais e tem poucos terremotos.',detail:'É quase estacionária: as outras placas se afastam dela.',medio:'Como as bordas são quase todas divergentes, a placa cresce de todos os lados; isso a torna uma referência útil para medir o movimento das demais.'},
 nazca:{name:'Placa de Nazca',kind:'Placa oceânica',color:'#9ff3ff',text:'A placa de Nazca é um pedaço de fundo de mar na frente do Chile e do Peru. Ela mergulha debaixo da América do Sul, e é esse mergulho que faz os vulcões dos Andes e os maiores terremotos já medidos, como o do Chile em 1960.',detail:'Nasce na dorsal do Pacífico Leste e some na fossa Peru-Chile.',medio:'O terremoto de Valdívia (1960, magnitude 9,5) ocorreu nessa zona de subducção; a fossa Peru-Chile chega a 8 km de profundidade.'},
 divergente:{name:'Limite divergente',kind:'As placas se afastam',color:'#ffb27a',text:'No limite divergente, duas placas se afastam. O magma sobe pela fenda, esfria e vira rocha nova: é assim que nasce fundo de oceano. As dorsais no meio dos oceanos são isso: cordilheiras submarinas de lava.',detail:'Exemplo: a dorsal Meso-Atlântica, que passa pela Islândia.',medio:'A crosta oceânica nova registra o campo magnético da época em faixas simétricas, evidência decisiva da expansão do assoalho oceânico.'},
 convergente:{name:'Limite convergente',kind:'As placas se chocam',color:'#ff7a5a',text:'No limite convergente, duas placas se chocam. Se uma é oceânica, ela mergulha por baixo da outra, derrete e vira vulcão: a subducção. Se as duas são continentais, nenhuma afunda e a crosta dobra para cima: nascem montanhas.',detail:'Exemplos: os Andes (subducção) e o Himalaia (colisão continental).',medio:'A placa que mergulha arrasta água para o manto, baixando o ponto de fusão da rocha: por isso os vulcões ficam em arco, a cerca de 100 km da fossa.'},
 transformante:{name:'Limite transformante',kind:'As placas deslizam',color:'#ffe08a',text:'No limite transformante, as placas não se chocam nem se afastam: deslizam uma ao lado da outra. A rocha trava, acumula força por décadas e solta de uma vez. Esse estalo é o terremoto.',detail:'Exemplo: a falha de San Andreas, na Califórnia.',medio:'Não cria nem destrói crosta. Os sismos são rasos (até 20 km), o que os torna muito destrutivos nas cidades próximas.'},
 terremoto:{name:'Terremoto',kind:'Fenômeno',color:'#ff6b6b',text:'Terremoto é a rocha estalando. Quando duas placas travam e a força acumulada vence, a rocha se parte e libera energia em ondas que sacodem o chão. A escala de magnitude mede essa energia: cada ponto a mais é 32 vezes mais energia.',detail:'O ponto de origem, em profundidade, é o hipocentro; na superfície, acima dele, o epicentro.',medio:'As ondas P chegam primeiro e as S depois; a diferença de tempo entre elas permite calcular a distância do epicentro em cada sismógrafo.'},
 tsunami:{name:'Tsunami',kind:'Fenômeno',color:'#5fa8c8',text:'Tsunami é a onda gigante que nasce quando um terremoto levanta o fundo do mar de repente. No oceano aberto ela passa quase sem ser notada, mas perto da costa cresce e invade a terra. Foi o que aconteceu no Japão em 2011.',detail:'Viaja a até 800 km por hora, a velocidade de um avião.',medio:'A altura cresce ao se aproximar da costa porque a velocidade cai com a profundidade e a energia se concentra: a onda "freia" e empilha.'},
 pangeia:{name:'Pangeia e a deriva',kind:'História da Terra',color:'#c9a070',text:'Há 250 milhões de anos todos os continentes estavam juntos num só, a Pangeia. Alfred Wegener percebeu isso em 1912 olhando o encaixe da costa do Brasil com a da África, e fósseis iguais nos dois lados. Os continentes se separaram devagar, carregados pelas placas.',detail:'Wegener não sabia o que movia os continentes; a resposta, o manto em convecção, só veio nos anos 1960.',medio:'Evidências: encaixe das costas, continuidade de cadeias de montanhas e rochas, fósseis de Mesosaurus na América do Sul e na África, e marcas glaciais em continentes hoje tropicais.'},
 anel_fogo:{name:'Anel de Fogo',kind:'Região',color:'#ffa040',text:'O Anel de Fogo é a faixa em volta do oceano Pacífico onde ficam três de cada quatro vulcões ativos do mundo e a maior parte dos terremotos fortes. Vai do Chile até o Alasca, desce pelo Japão e chega à Nova Zelândia.',detail:'Cerca de 40 mil km de comprimento e 450 vulcões.',medio:'É o conjunto das zonas de subducção que cercam a placa do Pacífico e as placas oceânicas menores (Nazca, Cocos, Filipina).'},
 kola:{name:'Poço de Kola',kind:'Até onde chegamos',color:'#e8d8b0',text:'O buraco mais fundo que o ser humano já cavou fica na Rússia: o poço de Kola, com 12 quilômetros. Parece muito, mas é só 0,2 por cento do caminho até o centro. Lá no fundo a rocha estava a 180 graus, e as brocas não aguentaram mais.',detail:'Foram 20 anos de perfuração, de 1970 a 1992. O buraco tem 23 cm de largura.',medio:'A temperatura subiu mais rápido do que o previsto (gradiente de ~15 °C/km nas camadas profundas) e a rocha tornou-se plástica, fechando o poço.'}
};
D.CATALOGO={placasExp:[['As grandes placas',['pacifica','norteamericana','sulamericana','africana','euroasiatica','indoaustraliana','antartica','nazca']],['Os três limites',['divergente','convergente','transformante']],['O que acontece nas fronteiras',['terremoto','tsunami','anel_fogo','pangeia']]],explorar:[['Camadas, de fora para dentro',['crosta','manto_superior','manto_inferior','nucleo_externo','nucleo_interno']],['Dentro da crosta e do manto',['crosta_continental','crosta_oceanica','litosfera','astenosfera','moho']],['Como sabemos disso',['ondas_sismicas','campo_magnetico','kola']]]};
D.LEGENDA_PLACAS=[['#ffe08a','Fronteira de placas'],['#ff6b6b','Terremotos'],['#ffb27a','Divergente'],['#ff7a5a','Convergente'],['#ffe08a','Transformante']];
D.LEGENDA=[['#8fd0a0','Crosta'],['#e07a3c','Manto superior'],['#c84a28','Manto inferior'],['#f0a030','Núcleo externo'],['#fff0a0','Núcleo interno']];
/* sequência: camadas da superfície ao centro */
D.sequencias={montar:{titulo:'DA SUPERFÍCIE AO CENTRO',cor:'#f6c37a',ordem:['crosta','manto_superior','manto_inferior','nucleo_externo','nucleo_interno'],rotulos:{crosta:'Crosta',manto_superior:'Manto superior',manto_inferior:'Manto inferior',nucleo_externo:'Núcleo externo',nucleo_interno:'Núcleo interno'},
 pistas:['Comece pela camada onde a gente pisa.','O manto é a camada do meio, e tem duas partes: a de cima vem antes.','O núcleo tem uma parte líquida por fora e uma sólida por dentro.']}};
/* viagem ao centro: sete trechos (profundidade em km, temperatura e pressão didáticas) */
D.viagem=[
 {titulo:'Crosta: até o fundo do poço',de:0,ate:12,temp:'20 → 180 °C',pressao:'1 → 3.000 atm',cor:0x8fd0a0,dur:13,text:'Estamos descendo pela crosta. Rocha sólida, fria, cheia de rachaduras com água. Aos 12 quilômetros passamos pelo ponto mais fundo que o ser humano já perfurou: o poço de Kola. Daqui para baixo, ninguém nunca esteve.',audio:'viagem-0'},
 {titulo:'Crosta: até a Moho',de:12,ate:35,temp:'180 → 500 °C',pressao:'3 mil → 10 mil atm',cor:0x7cc090,dur:12,text:'Continuamos na crosta continental. A rocha fica cada vez mais quente, e a pressão já apertaria qualquer coisa que a gente conhece. Aos 35 quilômetros, cruzamos a Moho: acabou a crosta, começa o manto.',audio:'viagem-1'},
 {titulo:'Litosfera e astenosfera',de:35,ate:100,temp:'500 → 1.300 °C',pressao:'até 30 mil atm',cor:0xd09060,dur:12,text:'Entramos no manto. Nos primeiros quilômetros ele ainda é rígido: é a base da litosfera, da placa que carrega os continentes. Perto dos 100 quilômetros a rocha passa de 1.300 graus e começa a ficar mole: é a astenosfera.',audio:'viagem-2'},
 {titulo:'Manto superior',de:100,ate:660,temp:'1.300 → 1.600 °C',pressao:'até 240 mil atm',cor:0xe07a3c,dur:14,text:'Manto superior: rocha vermelha, quente, que se mexe devagar como caramelo. É esse movimento que, lá em cima, arrasta as placas e levanta montanhas. Aos 660 quilômetros os minerais mudam de forma por causa da pressão.',audio:'viagem-3'},
 {titulo:'Manto inferior',de:660,ate:2900,temp:'1.600 → 3.700 °C',pressao:'até 1,4 milhão atm',cor:0xc84a28,dur:16,text:'Este é o trecho mais longo da viagem: o manto inferior, mais de 2.000 quilômetros de rocha. Está a milhares de graus, mas a pressão é tão grande que ela continua sólida. Lá embaixo, uma luz alaranjada: estamos chegando ao núcleo.',audio:'viagem-4'},
 {titulo:'Núcleo externo',de:2900,ate:5150,temp:'3.700 → 5.000 °C',pressao:'até 3,3 milhões atm',cor:0xf0a030,dur:16,text:'Mergulhamos no núcleo externo: um mar de ferro e níquel derretidos. Correntes de metal líquido giram em volta de nós. É daqui que vem o campo magnético, o escudo invisível que protege a vida na superfície.',audio:'viagem-5'},
 {titulo:'Núcleo interno',de:5150,ate:6371,temp:'5.400 °C',pressao:'3,6 milhões atm',cor:0xfff0a0,dur:14,text:'Chegamos ao núcleo interno: ferro sólido, mais quente que a superfície do Sol, e sólido só porque toda a Terra está em cima dele. Mais alguns quilômetros e estamos no centro exato do planeta. Daqui, qualquer direção é para cima.',audio:'viagem-6'}
];
D.VIAGEM_FIM={text:'Viagem completa: 6.371 quilômetros, da crosta ao centro. Crosta, manto superior, manto inferior, núcleo externo e núcleo interno. Agora você sabe o que existe debaixo dos seus pés.',audio:'viagem-fim'};
/* desafio */
D.questions=[
 {id:'liquida',skill:'camadas',q:'Qual camada da Terra está no estado líquido?',options:['A crosta oceânica','O manto inferior','O núcleo externo','O núcleo interno'],correct:2,why:'O núcleo externo é ferro e níquel derretidos. As ondas sísmicas S não o atravessam, e foi assim que descobrimos que ele é líquido.'},
 {id:'kola',skill:'escala',q:'O buraco mais fundo já feito pelo ser humano tem 12 km. Até onde ele chegou?',options:['Até o manto superior','Nem atravessou a crosta','Até a astenosfera','Até o núcleo externo'],correct:1,why:'O poço de Kola parou dentro da crosta continental, que ali tem uns 35 km. São 0,2% do caminho até o centro.'},
 {id:'manto',skill:'camadas',q:'Qual camada ocupa a maior parte do volume da Terra?',options:['A crosta','O manto','O núcleo externo','O núcleo interno'],correct:1,why:'O manto tem 84% do volume do planeta. Vai de 35 km até 2.900 km de profundidade.'},
 {id:'magnetico',skill:'fenomenos',q:'O que produz o campo magnético da Terra?',options:['O ferro sólido do núcleo interno','As rochas magnéticas da crosta','O movimento do metal líquido no núcleo externo','O calor do manto'],correct:2,why:'O ferro líquido do núcleo externo se move e conduz eletricidade: isso gera o campo magnético, o geodínamo.'},
 {id:'sismicas',skill:'evidencias',q:'Como os cientistas conhecem o interior da Terra, se ninguém nunca esteve lá?',options:['Por fotos de satélite','Pelas ondas dos terremotos, que mudam em cada camada','Por perfurações até o núcleo','Pela cor da lava dos vulcões'],correct:1,why:'As ondas sísmicas mudam de velocidade e de direção ao cruzar cada camada. Registradas no mundo inteiro, elas revelam o que há dentro.'},
 {id:'interno',skill:'fenomenos',q:'O núcleo interno é a parte mais quente da Terra. Por que ele é sólido?',options:['Porque é feito de rocha','Porque a pressão enorme impede o ferro de derreter','Porque está esfriando há bilhões de anos','Porque não tem oxigênio'],correct:1,why:'A 3,6 milhões de atmosferas, o ferro se mantém sólido mesmo a 5.400 graus. É a pressão que decide, não só a temperatura.'},
 {id:'oceanica',skill:'camadas',q:'Comparando a crosta oceânica com a continental, a oceânica é…',options:['Mais grossa e mais leve','Mais fina e mais densa','Mais antiga','Feita de granito'],correct:1,why:'A crosta oceânica tem 5 a 10 km, é de basalto e mais densa. Por isso ela mergulha sob os continentes nas zonas de subducção.'},
 {id:'placasMovem',skill:'placas',pref:'plac-',q:'O que faz as placas tectônicas se moverem?',options:['O vento e as marés','O manto quente, que se move por baixo delas','A rotação da Terra','Os terremotos'],correct:1,why:'As correntes do manto, que sobe quente e desce frio, arrastam as placas da litosfera uns centímetros por ano.'},
 {id:'andes',skill:'limites',pref:'plac-',q:'Como se formou a cordilheira dos Andes?',options:['Duas placas se afastando','Uma placa oceânica mergulhando sob a América do Sul','Duas placas deslizando lado a lado','Um vulcão gigante'],correct:1,why:'A placa de Nazca mergulha sob a Sul-Americana (limite convergente). O choque dobra a borda do continente e alimenta os vulcões andinos.'},
 {id:'atlantico',skill:'limites',pref:'plac-',q:'O oceano Atlântico está ficando maior a cada ano. Por quê?',options:['Porque as geleiras derretem','Porque a dorsal no meio dele cria fundo de mar novo','Porque a África afunda','Porque os rios trazem água'],correct:1,why:'Na dorsal Meso-Atlântica, limite divergente, o magma sobe e vira crosta nova. As placas se afastam uns 2 cm por ano.'},
 {id:'sanandreas',skill:'limites',pref:'plac-',q:'Na falha de San Andreas, as placas…',options:['se chocam de frente','se afastam','deslizam uma ao lado da outra','não se movem'],correct:2,why:'É um limite transformante: a placa do Pacífico e a Norte-Americana deslizam lado a lado, travam e soltam, gerando terremotos.'},
 {id:'brasil',skill:'placas',pref:'plac-',q:'Por que o Brasil quase não tem terremotos fortes nem vulcões ativos?',options:['Porque o clima é quente','Porque fica no meio da placa Sul-Americana, longe das fronteiras','Porque a crosta aqui é mais fina','Porque não há montanhas'],correct:1,why:'Terremotos e vulcões se concentram nas bordas das placas. O Brasil está no interior estável da placa Sul-Americana.'},
 {id:'pangeia',skill:'historia',pref:'plac-',q:'Qual destas é uma evidência de que os continentes já estiveram juntos?',options:['O Brasil e a África têm o mesmo clima','Fósseis iguais nos dois lados do Atlântico e o encaixe das costas','Os oceanos têm a mesma profundidade','A Lua gira em volta da Terra'],correct:1,why:'Wegener usou o encaixe das costas, fósseis iguais (como o Mesosaurus) e rochas contínuas para propor a Pangeia e a deriva dos continentes.'},
 {id:'temperatura',skill:'escala',q:'O que acontece com a temperatura conforme descemos para o centro da Terra?',options:['Diminui, porque fica longe do Sol','Fica igual','Aumenta, até cerca de 5.400 °C no centro','Aumenta só até o manto e depois cai'],correct:2,why:'A temperatura sobe o tempo todo: uns 25 graus por quilômetro na crosta, chegando a cerca de 5.400 °C no núcleo interno.'}
];
D.todasQuestoes=D.questions;
/* aula guiada */
D.guide=[
 {view:'contexto',title:'Localize-se',goal:'Veja a Terra do espaço, abra o planeta ao meio e olhe de perto a crosta onde a gente vive.',check:'contexto',audio:'aula-contexto'},
 {view:'explorar',title:'Investigue as camadas',goal:'Aponte em pelo menos três camadas da Terra aberta e ouça o que cada uma é.',check:'explorar',audio:'aula-explorar'},
 {view:'montar',title:'Monte as camadas',goal:'Coloque as cinco camadas na ordem, da superfície ao centro.',check:'montar',audio:'aula-montar'},
 {view:'viagem',title:'Desça ao centro',goal:'Faça a viagem completa, trecho a trecho, até o centro da Terra. Repare na temperatura e na pressão subindo.',check:'viagem',audio:'aula-viagem'},
 {view:'desafio',title:'Mostre o que entendeu',goal:'Responda às situações finais e consulte o seu resumo.',check:'desafio',audio:'aula-desafio'},
 {view:'placContexto',title:'Veja a casca quebrada',goal:'Olhe as fronteiras das placas no globo, veja para onde elas se movem e onde a Terra treme.',check:'placContexto',audio:'plac-aula-contexto'},
 {view:'placasExp',title:'Investigue as placas',goal:'Aponte em pelo menos três placas ou limites e ouça o que cada um é.',check:'placasExp',audio:'plac-aula-explorar'},
 {view:'limites',title:'Descubra os limites',goal:'Toque nas três maquetes e descubra qual é divergente, convergente e transformante.',check:'limites',audio:'plac-aula-limites'},
 {view:'volta',title:'Dê a volta ao mundo',goal:'Visite os seis lugares e repare no tipo de limite de cada um.',check:'volta',audio:'plac-aula-volta'},
 {view:'placDesafio',title:'Mostre o que entendeu',goal:'Hora de mostrar o que você entendeu. Responda às situações e, no final, confira o seu resumo.',check:'placDesafio',audio:'plac-aula-desafio'}
];
D.WELCOME='Bem-vindo ao Terra por Dentro! Aqui você vai abrir o planeta ao meio, conhecer cada camada, montar a Terra de fora para dentro e fazer uma viagem até o centro, onde ninguém nunca chegou. Vamos começar?';
D.sources=[['NASA Visible Earth · Blue Marble (texturas da superfície, domínio público; cópias distribuídas com o three.js)','https://visibleearth.nasa.gov/collection/1484/blue-marble'],['USGS · Earth\'s interior','https://www.usgs.gov/faqs/what-are-earths-layers'],['IRIS · Exploring the Earth using seismology','https://www.iris.edu/hq/inclass/animation/exploring_the_earth_using_seismology'],['Kola Superdeep Borehole · dados históricos','https://en.wikipedia.org/wiki/Kola_Superdeep_Borehole'],['BNCC · EF06CI11 (camadas da Terra); EF06CI12, EF07CI15 e EF07CI16 nos temas seguintes','http://basenacionalcomum.mec.gov.br/']];
window.TERRA_DATA=D;
})();
