/* Terra por Dentro v1.1 · controlador das missões, interface e WebXR
   Base: arquitetura do Corpo Humano Imersivo v4.7 (Portal 360º VR). Regra 9: data-act + delegação. */
(function(){'use strict';
const D=TERRA_DATA,M=window.TERRA_MODELS,T=window.THREE,$=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const embaralhar=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const freshSeq=(id)=>{const ordem=D.sequencias[id].ordem;return {colocados:Array(ordem.length).fill(null),target:0,selected:null,erros:0,pistas:0,done:false,bandeja:embaralhar(ordem)};};
const initial=()=>({version:D.version,welcomed:false,tour:null,view:'contexto',tema:'camadas',modulo:'cam',quizzes:{},level:'intro',guided:false,gstep:0,context:0,montar:freshSeq('montar'),viagem:{trecho:0,u:0,andando:true},placContext:0,limites:{divergente:false,convergente:false,transformante:false},volta:{etapa:0},visited:[],completed:[],events:[],started:Date.now(),autoRotate:false,reducedMotion:window.matchMedia('(prefers-reduced-motion: reduce)').matches,quality:'balanced',captions:true,autoVoice:true,chaoVR:'discreto'});
const INSPECT_VIEWS=['explorar','montar','desafio','contexto','placContexto','placasExp','limites','volta'],SEQ_VIEWS=['montar'];const prefMod=()=>(D.PREF||{})[S.modulo]||'';const desafioDe=m=>m==='pla'?'placDesafio':'desafio';
const temaAtual=()=>D.temas.find(x=>x.id===S.tema)||D.temas[0];
const atividadesDe=tid=>{const t=D.temas.find(x=>x.id===tid);if(!t||t.breve)return[];const list=t.atividades.map(id=>D.activities.find(a=>a.id===id)).filter(Boolean);list.push(D.activities.find(a=>a.id==='desafio'));return list;};
const quizState=()=>{if(!S.quizzes)S.quizzes={};if(!S.quizzes[S.tema])S.quizzes[S.tema]={phase:1,index:0,answers:[],done:false};return S.quizzes[S.tema];};
const questoes=()=>{const ids=temaAtual().questoes||[];return ids.map(id=>D.todasQuestoes.find(q=>q.id===id)).filter(Boolean);};
const guideAtual=()=>{const t=temaAtual();const steps=t.atividades.map(v=>D.guide.find(g=>g.view===v)).filter(Boolean);const des=D.guide.find(g=>g.view===desafioDe(t.modulo));if(des)steps.push(Object.assign({},des,{view:'desafio'}));return steps;};
let S=initial(),view=null,feedbackText='',instruction='',instructionKey=null,inspectKey=null;
try{const saved=JSON.parse(sessionStorage.getItem('pde_terra_v1')||'null');if(saved&&saved.version===D.version&&D.activities.some(a=>a.id===saved.view)){S=Object.assign(initial(),saved);}}catch(_){}
function save(){try{sessionStorage.setItem('pde_terra_v1',JSON.stringify(S));}catch(_){}}
function log(event,skill,value={}){S.events.push({event,skill,...value,at:new Date().toISOString()});if(S.events.length>600)S.events.shift();save();updateStatus();}
function mark(key){if(!S.completed.includes(key))S.completed.push(key);save();}
function fb(text,type='ok'){feedbackText=text;const e=$('feedback');e.hidden=!text;e.className='feedback'+(type==='ok'?'':' '+type);e.textContent=text;if(view&&view.xr)view.buildXRUI();}
function setInstruction(text,key){instruction=text;instructionKey=key;const c=$('captionText');c.textContent=text;c.hidden=true;}
const listaDe=v=>(D.CATALOGO[v]||[]).flatMap(g=>g[1]);const vistosDe=v=>listaDe(v).filter(k=>S.visited.includes(k)).length;
const narrator=new CorpoNarrator(({state,text,key})=>{const labels={loading:'CARREGANDO NARRAÇÃO',playing:'ÁUDIO GRAVADO',speech:'VOZ DO NAVEGADOR',text:'ORIENTAÇÃO EM TEXTO',ended:'NARRAÇÃO CONCLUÍDA',stopped:'ORIENTAÇÃO DA ATIVIDADE'};$('voiceStatus').textContent=labels[state]||'ORIENTAÇÃO';$('stopVoice').hidden=!['loading','playing','speech'].includes(state);if(text){$('captionText').textContent=text;}$('captionText').hidden=!S.captions||!['loading','playing','speech'].includes(state);if(state==='ended'&&S.tour&&S.tour.ativo&&key===listaDe(S.tour.view)[S.tour.i]){clearTimeout(S._tourT);S._tourT=setTimeout(()=>{if(S.tour&&S.tour.ativo)tourNext();},900);}});
function btn(label,cmd,style='',disabled=false){return '<button data-act="'+esc(cmd)+'" class="'+esc(style)+'" '+(disabled?'disabled':'')+'>'+esc(label)+'</button>';}
function pill(s){return '<span class="status-pill">'+esc(s)+'</span>';}
function isGuideDone(){const g=guideAtual()[S.gstep];if(!g)return false;const key=g.check;if(key==='explorar'||key==='placasExp')return vistosDe(key)>=3;if(key==='placDesafio')return S.completed.includes('desafio:'+S.tema);return S.completed.includes(key);}
function updateStatus(){$('sessionStatus').textContent=S.visited.length+' estruturas investigadas · '+S.completed.length+' atividades concluídas';}
function renderGuide(){const p=$('guidePanel');if(S.guided&&!guideAtual()[S.gstep]){S.guided=false;S.gstep=0;}p.hidden=!S.guided;if(!S.guided)return;const G=guideAtual(),g=G[S.gstep],done=isGuideDone();p.innerHTML='<span class="eyebrow">AULA GUIADA · '+(S.gstep+1)+' / '+G.length+'</span><h3>'+esc(g.title)+'</h3><p>'+esc(g.goal)+'</p><progress value="'+(S.gstep+(done?1:0))+'" max="'+G.length+'"></progress><div class="button-row">'+btn('Ouvir','guide:listen')+btn(S.gstep===G.length-1?'Concluir aula':'Continuar','guide:next','primary',!done)+'</div>'+btn('Sair da aula guiada','guide:exit','wide')+(done?'<p>✓ Objetivo desta etapa realizado.</p>':'<p>Complete a ação indicada para liberar a próxima etapa.</p>');}
function seqUI(id){const st=S[id],cfg=D.sequencias[id];let h='<p>Escolha uma peça e clique na posição de destino, ou arraste a peça até ela. A ordem vai de fora para dentro.</p><div class="pair-choices seq">';
 cfg.ordem.forEach(k=>{const usado=st.colocados.includes(k);h+='<button data-act="seq:pick:'+k+'" class="'+(st.selected===k?'selected':'')+'" '+(usado?'disabled':'')+' style="--base:'+cfg.cor+'">'+esc(cfg.rotulos[k])+'</button>';});h+='</div>';
 h+='<p class="fine">'+(st.done?'Camadas completas.':'Destino atual: posição '+(st.target+1)+' de '+cfg.ordem.length+'.')+'</p><div class="slot-choices">';st.colocados.forEach((k,i)=>{h+='<button class="'+(k?'filled':'')+(st.target===i?' current':'')+'" data-act="seq:target:'+i+'">'+(k?esc(cfg.rotulos[k]):String(i+1).padStart(2,'0'))+'</button>';});h+='</div>';
 h+='<div class="metric-row"><span>Posições completadas</span><b>'+st.colocados.filter(Boolean).length+' / '+cfg.ordem.length+'</b></div><div class="metric-row"><span>Tentativas incorretas</span><b>'+st.erros+'</b></div>';
 h+='<div class="button-row">'+btn('Encaixar','seq:place','primary',!st.selected||st.done)+btn('Pista','seq:hint','',st.done)+'</div>'+btn('Recomeçar','seq:reset','wide');return h;}
function listaHTML(v){return '<details class="lista"><summary>Escolher na lista ('+listaDe(v).length+')</summary>'+(D.CATALOGO[v]||[]).map(([titulo,keys])=>'<div class="lista-grupo">'+esc(titulo)+'</div><div class="pair-choices seq">'+keys.map(k=>'<button data-act="inspect:'+k+'" class="'+(S.visited.includes(k)?'visto':'')+'" style="--base:'+(D.info[k]&&D.info[k].color||'#c9a070')+'">'+esc(D.info[k]?D.info[k].name:k)+'</button>').join('')+'</div>').join('')+'</details>';}
function tourHTML(v){const lista=listaDe(v),vistos=lista.filter(k=>S.visited.includes(k)).length,t=S.tour;const ativo=t&&t.view===v&&t.ativo;
 return '<div class="tour"><div class="metric-row"><span>Investigados</span><b>'+vistos+' / '+lista.length+'</b></div><div class="button-row">'+(ativo?btn('■ Parar tour','tour:stop','primary')+btn('▶ Próximo','tour:next'):btn('▶ Tour: ouvir um por um','tour:start','primary'))+'</div>'+(ativo?'<p class="fine">Tour '+(t.i+1)+' de '+lista.length+': '+esc(D.info[lista[t.i]].name)+'. Cada ficha toca e a próxima entra sozinha.</p>':'<p class="fine">O tour projeta cada '+(S.modulo==='pla'?'placa ou limite':'camada')+', toca a ficha e passa para a próxima.</p>')+'</div>';}
function tourStart(v){const lista=listaDe(v);if(!lista.length)return;S.tour={view:v,i:0,ativo:true};tourPlay();}
function tourPlay(){const t=S.tour;if(!t||!t.ativo)return;const lista=listaDe(t.view);if(t.i>=lista.length){tourStop();fb('Tour concluído: você ouviu todas as '+lista.length+' fichas.');narrator.say('Tour concluído. Você conheceu todas as camadas e fenômenos desta missão.',null);return;}if(S.view!==t.view)switchView(t.view,false);inspect(lista[t.i],true);}
function tourNext(){const t=S.tour;if(!t||!t.ativo)return;t.i++;tourPlay();}
function tourStop(){if(S.tour)S.tour.ativo=false;renderSidebar();save();}
function renderSidebar(){renderGuide();let h='',a=D.activities.find(x=>x.id===S.view);h+='<span class="eyebrow">'+esc(a.kicker)+' · '+(S.level==='medio'?'APROFUNDAMENTO':'INTRODUÇÃO')+'</span>';
 if(inspectKey&&INSPECT_VIEWS.includes(S.view)){const i=D.info[inspectKey]||D.info.terra;h+='<h2>'+esc(i.name)+'</h2>'+pill(i.kind)+'<p>'+esc(i.text)+'</p><details'+(S.level==='medio'?' open':'')+'><summary>Mais detalhes</summary><p>'+esc(i.detail)+'</p>'+(S.level==='medio'&&i.medio?'<p class="medio">'+esc(i.medio)+'</p>':'')+'</details>'+(S.level!=='medio'&&i.medio?'<p class="fine">Ajustes → Ensino Médio libera o aprofundamento desta ficha.</p>':'')+'<div class="button-row">'+btn('Ouvir novamente','inspect:listen','primary')+btn('Fechar ficha','inspect:close')+'</div>'+((S.tour&&S.tour.ativo&&S.tour.view===S.view)?tourHTML(S.view):'');setInstruction(i.text,inspectKey);}
 else if(S.view==='contexto'){const c=D.context[S.context];h+='<h2>'+esc(c.name)+'</h2><div class="step-list">'+D.context.map((x,i)=>'<span class="'+(i<=S.context?'done':'')+'"></span>').join('')+'</div><p>'+esc(c.text)+'</p><div class="button-row">'+btn('Etapa anterior','context:back','',S.context===0)+btn(c.target?(c.target==='aberta'?'Abrir a Terra':'Olhar a crosta'):'Explorar as camadas',c.target?'context:next':'view:explorar','primary')+'</div><div class="info-card"><p>'+(S.context===2?'A fatia da direita está em escala: 100 km de profundidade. A crosta real é tão fina que, na Terra ao lado, ela aparece engrossada para dar para ver.':'Proporções didáticas: a crosta aparece mais grossa do que é (na escala real teria 0,5% do raio e ficaria invisível).')+'</p></div>';setInstruction(c.text,'contexto-'+S.context);}
 else if(S.view==='explorar'){h+='<h2>Explore as camadas</h2><p>Aponte em uma camada da Terra aberta ou escolha abaixo. A ficha aparece aqui, com explicação em áudio.</p>'+listaHTML('explorar')+tourHTML('explorar')+'<p class="fine">Pergunta central: <b>o que existe debaixo dos nossos pés?</b></p>';setInstruction('Aponte em uma camada para ver a ficha e ouvir a explicação. Investigue pelo menos três.','aula-explorar');}
 else if(S.view==='montar'){h+='<h2>Monte as camadas</h2>'+pill('DE FORA PARA DENTRO')+seqUI('montar');setInstruction(S.montar.done?'Camadas completas: crosta, manto superior, manto inferior, núcleo externo e núcleo interno. Quanto mais fundo, mais quente e mais apertado.':'Coloque as cinco camadas na ordem, da superfície até o centro da Terra.',S.montar.done?'montar-concluido':'aula-montar');}
 else if(S.view==='viagem'){const v=S.viagem,tr=D.viagem[v.trecho],n=D.viagem.length,fim=v.trecho===n-1&&v.u>=1;const prof=Math.round(tr.de+(tr.ate-tr.de)*v.u);h+='<h2>'+esc((v.trecho+1)+'. '+tr.titulo)+'</h2><div class="step-list">'+D.viagem.map((x,i)=>'<span class="'+(i<v.trecho||(i===v.trecho&&v.u>=1)?'done':'')+'"></span>').join('')+'</div><div class="gauge"><div><small>PROFUNDIDADE</small><b>'+prof.toLocaleString('pt-BR')+' km</b></div><div><small>TEMPERATURA</small><b>'+esc(tr.temp)+'</b></div><div><small>PRESSÃO</small><b>'+esc(tr.pressao)+'</b></div></div><p>'+esc(tr.text)+'</p><div class="metric-row"><span>Percurso do trecho</span><b>'+Math.round(v.u*100)+'%</b></div><div class="button-row">'+btn(v.andando?'⏸ Parar':'▶ Seguir','viag:toggle','',v.u>=1)+btn(v.trecho===n-1?'Fim da viagem':'Trecho seguinte ▶','viag:next','primary',v.trecho===n-1)+'</div><div class="button-row">'+btn('◀ Trecho anterior','viag:back','',v.trecho===0)+btn('Recomeçar','viag:reset')+'</div>'+(view&&view.xr?'<div class="button-row">'+btn('Túnel menor','viag:menor')+btn('Túnel maior','viag:maior')+'</div>':'')+btn('✕ Sair da viagem','view:explorar','wide')+(fim?'<p>✓ Viagem completa: da crosta ao centro.</p>':'')+'<p class="fine">Arraste a cena para olhar em volta. No óculos, o analógico direito avança e recua; vire a cabeça para ver as paredes.</p>';setInstruction(fim?D.VIAGEM_FIM.text:tr.text,fim?'viagem-fim':tr.audio);}
 else if(S.view==='placContexto'){const c=D.placContext[S.placContext];h+='<h2>'+esc(c.name)+'</h2><div class="step-list">'+D.placContext.map((x,i)=>'<span class="'+(i<=S.placContext?'done':'')+'"></span>').join('')+'</div><p>'+esc(c.text)+'</p><div class="button-row">'+btn('Etapa anterior','pctx:back','',S.placContext===0)+btn(c.target?(c.target==='movem'?'Ver o movimento':'Ver onde treme'):'Explorar as placas',c.target?'pctx:next':'view:placasExp','primary')+'</div><div class="info-card"><p>Fronteiras simplificadas das oito maiores placas. Arraste o globo para dar a volta.</p></div>';setInstruction(c.text,'plac-contexto-'+S.placContext);}
 else if(S.view==='placasExp'){h+='<h2>Explore as placas</h2><p>Aponte em uma placa do globo ou escolha abaixo. A ficha aparece aqui, com explicação em áudio.</p>'+listaHTML('placasExp')+tourHTML('placasExp')+'<p class="fine">Pergunta central: <b>por que a Terra treme e os continentes se movem?</b></p>';setInstruction('Aponte em uma placa ou escolha um limite na lista. Investigue pelo menos três.','plac-aula-explorar');}
 else if(S.view==='limites'){const t=S.limites;const n=['divergente','convergente','transformante'].filter(k=>t[k]).length;h+='<h2>Que limite é esse?</h2><p>Toque em cada maquete para descobrir se as placas se afastam, se chocam ou deslizam. Encontre os três.</p><div class="button-row">'+btn((t.divergente?'✓ ':'')+'Divergente','lim:divergente','',t.divergente)+btn((t.convergente?'✓ ':'')+'Convergente','lim:convergente','',t.convergente)+btn((t.transformante?'✓ ':'')+'Transformante','lim:transformante','',t.transformante)+'</div><div class="info-card"><p>'+(n===3?'✓ Três limites encontrados. Divergente: afastam e nasce crosta. Convergente: chocam, subducção ou montanhas. Transformante: deslizam e a terra treme.':'Afastar, chocar ou deslizar: cada maquete mostra um jeito. Observe o movimento.')+'</p></div>'+btn('Recomeçar','lim:reset','wide');setInstruction(n===3?'Três limites encontrados. É o tipo de encontro entre as placas que decide se nasce oceano, montanha ou terremoto.':'Toque nas três maquetes e descubra qual é divergente, convergente e transformante.',n===3?'plac-limites-concluido':'plac-aula-limites');}
 else if(S.view==='volta'){const v=S.volta,par=D.volta[v.etapa],fim=v.etapa===D.volta.length-1;h+='<h2>'+esc((v.etapa+1)+'. '+par.titulo)+'</h2><div class="step-list">'+D.volta.map((x,i)=>'<span class="'+(i<=v.etapa?'done':'')+'"></span>').join('')+'</div><p>'+esc(par.text)+'</p><div class="chips">'+par.chips.map(c=>pill(c)).join('')+'</div><div class="button-row">'+btn('Parada anterior','volta:back','',v.etapa===0)+btn(fim?'Recomeçar a volta':'Próxima parada',fim?'volta:reset':'volta:next','primary')+'</div>'+(fim&&S.completed.includes('volta')?'<p>✓ Volta completa.</p>':'<p class="fine">O globo gira até a parada. Aponte numa placa para abrir a ficha.</p>');setInstruction(fim&&S.completed.includes('volta')?D.VOLTA_FIM.text:par.text,fim&&S.completed.includes('volta')?'volta-fim':par.audio);}
 else if(S.view==='desafio'){const q=quizState(),Q=questoes();h+='<h2>'+(q.done?'Desafio concluído':'Explique o que descobriu')+'</h2>';if(!q.done){const item=Q[q.index],answer=q.answers[q.index];h+=pill('Situação '+(q.index+1)+' / '+Q.length)+'<p>'+esc(item.q)+'</p><div class="answer-list">';item.options.forEach((o,i)=>{h+=btn(o,'quiz:answer:'+i,answer!==undefined?(i===item.correct?'correct':i===answer?'incorrect':''):'',answer!==undefined);});h+='</div>';if(answer!==undefined)h+='<div class="info-card"><p>'+esc(item.why)+'</p></div>'+btn(q.index===Q.length-1?'Concluir desafio':'Próxima situação','quiz:next','wide primary');setInstruction(item.q,(item.pref||'')+'desafio-'+item.id);}else{const correct=q.answers.filter((a,i)=>a===Q[i].correct).length;h+='<div class="big-stat">'+correct+' / '+Q.length+'</div><p>Situações respondidas corretamente na primeira tentativa.</p><div class="button-row">'+btn('Ver resumo','summary','primary')+btn('Novo desafio','quiz:reset')+'</div>';setInstruction('Desafio concluído. Compare suas respostas com as explicações e retome as missões que geraram dúvidas.',prefMod()+'desafio-fim');}}
 $('lessonPanel').innerHTML=h;$('modelNote').textContent='Modelos procedurais, gerados no navegador. As espessuras das camadas são didáticas (a crosta aparece engrossada); temperaturas e pressões são valores médios de referência.';
 if(view&&view.xr)view.buildXRUI();updateStatus();}
function renderNav(){const atv=atividadesDe(S.tema);
 const missoes=atv.map((a,i)=>'<button data-view="'+a.id+'" class="nav-missao '+(a.id===S.view?'active':'')+'" aria-current="'+(a.id===S.view?'page':'false')+'" aria-label="'+esc(a.label)+'"><span class="nav-num">'+String(i+1).padStart(2,'0')+'</span><span>'+esc(a.label)+'</span></button>').join('');
 let h='<div class="nav-grupo">TEMAS</div>';
 D.temas.filter(x=>!x.breve).forEach(x=>{const on=x.id===S.tema;h+='<button class="nav-sistema'+(on?' active':'')+'" data-tema="'+x.id+'" aria-expanded="'+on+'" aria-label="Tema '+esc(x.nome)+'"><span>'+(on?'▾ ':'▸ ')+esc(x.nome)+'</span></button>'+(on?'<div class="nav-missoes">'+missoes+'</div>':'');});
 h+='<details class="nav-breve"><summary>+ '+D.temas.filter(x=>x.breve).length+' temas em breve</summary>'+D.temas.filter(x=>x.breve).map(x=>'<button class="nav-sistema breve" disabled title="Em breve"><span>'+esc(x.nome)+'</span></button>').join('')+'</details>';
 $('activityNav').innerHTML=h;}
const MENU_ICONE={camadas:'🌍',placas:'🧩',vulcao:'🌋',rochas:'🪨'};const MENU_COR={camadas:'#f6c37a',placas:'#9ff3ff',vulcao:'#ff9c6a',rochas:'#cfd8e6'};
function progressoDe(t){if(t.breve)return{feitas:0,total:0};const total=t.atividades.length+1;const feitas=t.atividades.filter(id=>S.completed.includes(id)).length+(((S.quizzes||{})[t.id]||{}).done?1:0);return{feitas,total};}
function renderMenu(){const el=$('menuSistemas');if(!el)return;const disp=D.temas.filter(x=>!x.breve),breve=D.temas.filter(x=>x.breve);
 const card=(x,i)=>{const p=progressoDe(x);return '<button class="menu-card'+(x.breve?' breve':'')+(x.id===S.tema?' atual':'')+'" data-tema="'+x.id+'" style="--cor:'+(MENU_COR[x.id]||'#f6c37a')+'" '+(x.breve?'disabled':'')+' aria-label="Tema '+esc(x.nome)+(x.breve?' (em breve)':'')+'"><span class="n">'+(x.breve?'EM BREVE':String(i+1).padStart(2,'0'))+'</span><span class="ic">'+(MENU_ICONE[x.id]||'●')+'</span><b>'+esc(x.nome)+'</b><small>'+esc(x.estuda)+(x.breve?'':'<br>'+esc(x.exemplos))+'</small>'+(x.breve?'':'<small>'+p.total+' missões · '+p.feitas+' concluída'+(p.feitas===1?'':'s')+'</small><span class="prog"><i style="width:'+Math.round(100*p.feitas/p.total)+'%"></i></span>')+'</button>';};
 el.innerHTML='<div class="cab"><div><span class="eyebrow">TERRA POR DENTRO · MENU PRINCIPAL</span><h2>Escolha um tema</h2><p>Toque em um tema para começar. Cada um tem o Explorar com fichas narradas, missões práticas e o Desafio final; a Aula guiada percorre tudo na ordem.</p></div><div class="acoes">'+btn('▷ Aula guiada do tema atual','menu:guia','primary')+btn('Continuar onde parei','menu:fechar')+'</div></div><div class="menu-grid">'+disp.map(card).join('')+breve.map(x=>card(x,0)).join('')+'</div><div class="rodape"><span>'+disp.length+(disp.length===1?' tema disponível · ':' temas disponíveis · ')+disp.reduce((a,x)=>a+x.atividades.length+1,0)+' missões · '+Object.keys(D.info).length+' fichas narradas</span><span>Modelos procedurais · Portal do Educador · NEWPC</span></div>';}
function abrirMenu(){renderMenu();const el=$('menuSistemas');if(el)el.hidden=false;narrator.stop();}
function fecharMenu(){const el=$('menuSistemas');if(el)el.hidden=true;}
function rebuild(){if(view)view.show();}
function render(){renderSidebar();rebuild();save();}
function switchView(id,announce=true){fecharMenu();if(!D.activities.some(a=>a.id===id))return;if(S.tour&&S.tour.ativo&&S.tour.view!==id)S.tour.ativo=false;narrator.stop(false);inspectKey=null;const tv=D.temas.find(x=>!x.breve&&(x.atividades||[]).includes(id));if(tv&&tv.id!==S.tema){if(S.guided){S.guided=false;S.gstep=0;}S.tema=tv.id;S.modulo=tv.modulo;}S.view=id;renderNav();fb('');log('atividade','navegacao',{value:id});const a=D.activities.find(x=>x.id===id);$('sceneTitle').textContent=a.title;$('sceneSub').textContent=a.subtitle;$('sceneKicker').textContent=a.kicker;render();
 if(announce&&S.autoVoice){const intro=!S.guided&&((id==='desafio'&&quizState().index===0&&!quizState().done&&quizState().answers[0]===undefined)?prefMod()+'aula-desafio':(id==='contexto'&&S.context===0)?'aula-contexto':(id==='viagem'&&S.viagem.trecho===0&&S.viagem.u===0)?'aula-viagem':(id==='montar'&&!S.montar.done&&S.montar.colocados.every(x=>!x))?'aula-montar':(id==='placContexto'&&S.placContext===0)?'plac-aula-contexto':(id==='volta'&&S.volta.etapa===0)?'plac-aula-volta':null);const g=intro&&D.guide.find(x=>x.audio===intro);if(g)narrator.say(g.goal,g.audio,{text:instruction,key:instructionKey});else narrator.say(instruction,instructionKey);}}
function inspect(key,announce=true){if(!D.info[key])return;inspectKey=key;if(!S.visited.includes(key))S.visited.push(key);if(vistosDe('explorar')>=3)mark('explorar');if(vistosDe('placasExp')>=3)mark('placasExp');log('inspecao','explorar',{component:key});render();if(announce&&S.autoVoice)narrator.say(D.info[key].text,key);}
function seqState(){return SEQ_VIEWS.includes(S.view)?S[S.view]:null;}
function seqPlace(index){const st=seqState();if(!st||st.done)return;const cfg=D.sequencias[S.view];if(index===undefined)index=st.target;if(st.colocados[index])return;if(!st.selected){st.target=index;render();fb('Escolha primeiro uma peça.','warning');return;}
 const ok=cfg.ordem[index]===st.selected;log('tentativa',S.view,{position:index,choice:st.selected,correct:ok});if(!ok){st.erros++;render();fb('Ainda não. Pense se essa camada fica mais perto da superfície ou do centro.','warning');return;}
 st.colocados[index]=st.selected;st.selected=null;st.target=st.colocados.findIndex(x=>!x);st.done=st.target<0;if(st.done)mark(S.view);render();fb(st.done?'Camadas completas!':'Encaixe correto. Próxima posição.');if(st.done&&S.autoVoice)narrator.say(instruction,instructionKey);}
function handle(cmd){const [kind,op,a]=cmd.split(':');
 if(kind==='view'){switchView(op);return;}
 if(kind==='context'){if(op==='next'&&S.context<2){S.context++;log('contexto','camadas',{level:S.context});if(S.context===2)mark('contexto');}if(op==='back')S.context=Math.max(0,S.context-1);render();if(S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='viag'){const v=S.viagem,n=D.viagem.length;if(op==='maior'||op==='menor'){if(view){view.xrZoom=Math.max(.4,Math.min(3,(view.xrZoom||1)*(op==='maior'?1.3:1/1.3)));renderSidebar();}return;}if(op==='toggle'){v.andando=!v.andando;renderSidebar();save();return;}if(op==='next'&&v.trecho<n-1){v.trecho++;v.u=0;v.andando=true;log('viagem','camadas',{trecho:v.trecho});}if(op==='back'&&v.trecho>0){v.trecho--;v.u=0;v.andando=true;}if(op==='reset'){S.viagem={trecho:0,u:0,andando:true};}if(view&&view.xr)view.anchor=null;render();if(S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='pctx'){if(op==='next'&&S.placContext<2){S.placContext++;log('contexto','placas',{level:S.placContext});if(S.placContext===2)mark('placContexto');}if(op==='back')S.placContext=Math.max(0,S.placContext-1);render();if(S.autoVoice)narrator.say(instruction,instructionKey);return;}
 if(kind==='lim'){const t=S.limites;if(op==='reset'){S.limites={divergente:false,convergente:false,transformante:false};inspectKey=null;render();return;}if(!(op in t))return;const novo=!t[op];t[op]=true;log('limite','limites',{tipo:op});if(novo){const n=['divergente','convergente','transformante'].filter(k=>t[k]).length;if(n===3)mark('limites');inspectKey=op;if(!S.visited.includes(op))S.visited.push(op);render();fb(D.info[op].name+': '+D.info[op].kind.toLowerCase()+'.');if(S.autoVoice)narrator.say(D.info[op].text,op,n===3?{text:instruction,key:'plac-limites-concluido'}:null);}else inspect(op);return;}
 if(kind==='volta'){const v=S.volta,n=D.volta.length;if(op==='next'&&v.etapa<n-1){v.etapa++;log('volta','placas',{etapa:v.etapa});if(v.etapa===n-1)mark('volta');}if(op==='back')v.etapa=Math.max(0,v.etapa-1);if(op==='reset')v.etapa=0;if(view&&!view.xr)view.elev=Math.max(-.9,Math.min(.9,D.volta[v.etapa].lat*Math.PI/180*.9));render();if(S.autoVoice){const fim=v.etapa===n-1&&S.completed.includes('volta');narrator.say(D.volta[v.etapa].text,D.volta[v.etapa].audio,fim?{text:D.VOLTA_FIM.text,key:'volta-fim'}:null);}return;}
 if(kind==='tema'){const t=D.temas.find(x=>x.id===op);if(!t||t.breve)return;if(op!==S.tema&&S.guided){S.guided=false;S.gstep=0;}S.tema=op;S.modulo=t.modulo;const first=atividadesDe(op)[0];if(first)switchView(first.id);return;}
 if(kind==='inspect'){if(op==='close'){inspectKey=null;if(S.tour&&S.tour.ativo)S.tour.ativo=false;render();narrator.stop();}else if(op==='listen'){const i=D.info[inspectKey]||D.info.terra;narrator.say(i.text,inspectKey||'terra');}else inspect(op);return;}
 if(kind==='seq'){const st=seqState();if(!st)return;if(op==='pick'){if(!st.colocados.includes(a)){st.selected=a;render();fb('Selecionado: '+D.sequencias[S.view].rotulos[a]+'. Clique na posição de destino.');}return;}if(op==='target'){if(!st.colocados[Number(a)]){st.target=Number(a);render();}return;}if(op==='place'){seqPlace();return;}if(op==='at'){seqPlace(Number(a));return;}
  if(op==='hint'&&!st.done){st.pistas++;log('pista',S.view,{position:st.target});const cfg=D.sequencias[S.view];fb(st.pistas>cfg.pistas.length?'Posição '+(st.target+1)+': '+cfg.rotulos[cfg.ordem[st.target]]+'.':cfg.pistas[(st.pistas-1)%cfg.pistas.length],'warning');return;}
  if(op==='reset'){S[S.view]=freshSeq(S.view);render();fb('Peças embaralhadas de novo.');return;}}
 if(kind==='quiz'){const q=quizState(),Q=questoes();if(op==='answer'&&!q.done&&q.answers[q.index]===undefined){const i=Number(a),item=Q[q.index];q.answers[q.index]=i;log('avaliacao',item.skill,{question:item.id,choice:i,correct:i===item.correct});render();fb(item.why,i===item.correct?'ok':'warning');}if(op==='next'&&q.answers[q.index]!==undefined){q.index++;if(q.index>=Q.length){q.done=true;mark('desafio:'+S.tema);mark(desafioDe(S.modulo));}render();if(S.autoVoice)narrator.say(instruction,instructionKey);}if(op==='reset'){S.quizzes[S.tema]={phase:1,index:0,answers:[],done:false};render();}return;}
 if(kind==='guide'){if(op==='start'){S.gstep=0;S.context=0;S.placContext=0;const first=guideAtual()[0];switchView(first?first.view:'contexto');S.guided=true;renderSidebar();return;}if(op==='listen'){const g=guideAtual()[S.gstep];narrator.say(g.goal,g.audio);return;}if(op==='next'&&isGuideDone()){if(S.gstep===guideAtual().length-1){S.guided=false;mark('aula:'+S.tema);renderSidebar();showSummary();return;}S.gstep++;switchView(guideAtual()[S.gstep].view);return;}if(op==='exit'){S.guided=false;renderSidebar();save();return;}}
 if(kind==='tour'){if(op==='start')tourStart(S.view);else if(op==='next')tourNext();else if(op==='stop'){tourStop();narrator.stop();}return;}
 if(kind==='menu'){if(op==='guia'){fecharMenu();handle('guide:start');}else if(op==='abrir')abrirMenu();else fecharMenu();return;}
 if(kind==='summary'){showSummary();return;}if(kind==='center'){if(view)view.center();return;}if(kind==='rotate'){S.autoRotate=!S.autoRotate;$('rotateBtn').textContent=S.autoRotate?'Ⅱ Pausar':'▷ Girar';$('rotateBtn').setAttribute('aria-pressed',String(S.autoRotate));save();return;}if(kind==='voice'){if(op==='stop')narrator.stop();else narrator.say(instruction,instructionKey);return;}
 if(kind==='vr'){if(view)view.toggleVR('vr');return;}if(kind==='ar'){if(view)view.toggleVR('ar');return;}if(kind==='catalog'){narrator.dispose();if(view&&view.xrSession)view.xrSession.end().finally(returnCatalog);else returnCatalog();return;}
}
function boasVindas(){S.welcomed=true;save();if(!S.autoVoice)return;const g=D.guide.find(x=>x.view==='contexto');const intro=(S.view==='contexto'&&S.context===0&&g)?{text:g.goal,key:'aula-contexto',next:{text:instruction,key:instructionKey}}:{text:instruction,key:instructionKey};narrator.say(D.WELCOME,'boas-vindas',intro);}
function returnCatalog(){const url=new URL('../../?catalog=1',location.href).href;try{if(window.top!==window){window.top.location.href=url;return;}}catch(_){}location.href=url;}

class LabView {
 constructor(){this.stage=$('stage');this.canvas=$('scene');this.xr=false;this.xrSession=null;this.drag=null;this.controllers=[];this.held=new Map();this.uiPage=0;this.xrReport=false;this.anchor=null;this.width=0;this.height=0;this.pixel=0;this.az=.25;this.elev=.12;this.dist=12;this.target=new T.Vector3(0,.2,0);this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.last=performance.now();
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(44,1,.025,200);this.scene.add(this.camera);this.root=new T.Group();this.scene.add(this.root);this.ui=new T.Group();this.scene.add(this.ui);this.uiHits=[];
  this.scene.add(new T.HemisphereLight(0xdcefff,0x2a3440,.62));const key=new T.DirectionalLight(0xfff1e0,.95);key.position.set(5,7,8);this.scene.add(key);const fill=new T.DirectionalLight(0x8fd0ec,.6);fill.position.set(-6,2,-4);this.scene.add(fill);
  try{this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true});this.renderer.outputEncoding=T.sRGBEncoding;this.renderer.localClippingEnabled=true;this.renderer.toneMapping=T.NoToneMapping;this.renderer.setClearColor(0x081929,0);this.renderer.xr.enabled=true;this.renderer.setAnimationLoop((time,frame)=>this.frame(time,frame));this.bind();this.ok=true;}catch(e){console.error(e);$('webglError').hidden=false;this.stage.classList.add('error');this.ok=false;}
 }
 clear(){this.hoverMeshes=[];this.hoverKey=null;this.duasMaos=null;for(const [c,o] of [...this.held]){if(o.userData&&o.userData.pegaReal)this.soltar(c);}this.retornos=[];for(const ctrl of this.controllers||[]){const grip=ctrl.userData.grip||ctrl;for(const ch of [...grip.children]){if(ch.userData&&(ch.userData.pegaReal||ch.userData.pegavel)){grip.remove(ch);M.dispose(ch);}}}if(this.model){this.model.userData.disposed=true;M.dispose(this.model);}this.model=null;this.drag=null;for(const [c,o] of this.held){M.dispose(o);this.held.delete(c);}this.animatedInspect=null;this.copy=null;}
 show(){if(!this.ok)return;this.clear();const g=new T.Group();this.model=g;this.root.add(g);this.root.position.set(0,0,0);this.root.rotation.set(0,0,0);this.root.scale.setScalar(1);let obj;
  if(S.view==='contexto')obj=M.contexto(S.context);
  else if(S.view==='montar')obj=M.sequencia(S.montar,D.sequencias.montar);
  else if(S.view==='viagem'){obj=M.viagemCena(S.viagem);S.autoRotate=false;}
  else if(S.view==='desafio')obj=M.desafio(S.modulo);
  else if(S.view==='placContexto')obj=M.placContexto(S.placContext);
  else if(S.view==='placasExp')obj=M.placasExp();
  else if(S.view==='limites')obj=M.limitesCena(S.limites);
  else if(S.view==='volta'){obj=M.voltaCena(S.volta);S.autoRotate=false;}
  else obj=M.explorar();
  g.add(obj);this.obj=obj;
  if(inspectKey&&INSPECT_VIEWS.includes(S.view)){const seqAberta=SEQ_VIEWS.includes(S.view);const largo=!seqAberta&&this.boxDe(obj,true).getSize(new T.Vector3()).x>4.5;obj.position.set(seqAberta?-4.2:largo?-3.2:-2.4,seqAberta?-.4:largo?-.4:-.1,seqAberta?-3.5:largo?-3.2:-2.5);obj.scale.multiplyScalar(seqAberta?.5:largo?.5:.65);this.copyAnchor=largo?[1.5,.1,1.0]:[.9,.05,1.6];const copy=M.inspection(inspectKey);copy.traverse(o=>{if(o.isMesh&&!o.userData.hit)o.userData.hit={type:'inspect',key:inspectKey};});copy.position.set(.95,.05,1.1);copy.userData.rotateCopy=true;g.add(copy);this.copy=copy;this.fitCopy(true);}
  this.modelHitTargets=[];g.traverseVisible(o=>{if(o.isMesh&&o.userData.hit)this.modelHitTargets.push(o);});
  if(this.lastView!==S.view){this.uiPage=0;this.xrReport=false;this.xrMenu='raiz';if(this.xr&&(S.view==='desafio'||this.lastView==='desafio'))this.anchor=null;}this.lastView=S.view;this.az=SEQ_VIEWS.includes(S.view)||S.view==='limites'?0:.25;this.elev=SEQ_VIEWS.includes(S.view)?0:S.view==='limites'?.28:S.view==='volta'?Math.max(-.9,Math.min(.9,D.volta[S.volta.etapa].lat*Math.PI/180*.9)):.1;
  $('closeInspect').hidden=!inspectKey;$('stageHint').textContent=S.view==='limites'&&!inspectKey?'Toque numa maquete para descobrir o tipo de limite':inspectKey?'Arraste a peça ampliada para girar · Toque na Terra ao fundo para trazê-la de volta':SEQ_VIEWS.includes(S.view)?'Selecione uma peça e clique na posição · Controles equivalentes na lateral':S.view==='viagem'?'Arraste para olhar em volta · Seguir, Parar e trechos na lateral':'Arraste o fundo para girar · toque numa camada · use a roda do mouse para aproximar';
  this.legend();this.fit();if(this.xr){this.placeXR();this.buildXRUI();}
 }
 legend(){let pairs=D.LEGENDA;if(S.modulo==='pla')pairs=D.LEGENDA_PLACAS;if(S.view==='viagem')pairs=[['#8fd0a0','Crosta'],['#e07a3c','Manto'],['#f0a030','Núcleo externo'],['#fff0a0','Núcleo interno'],['#fff2c0','Trilha do trecho']];$('sceneLegend').innerHTML=pairs.map(([c,n])=>'<span><i style="background:'+c+'"></i>'+n+'</span>').join('');}
 fit(){if(!this.model)return;/* com ficha aberta, enquadra a cópia ampliada (o modelo de fundo fica como contexto) */const naCopia=!!this.copy&&!SEQ_VIEWS.includes(S.view);const box=naCopia?this.boxDe(this.copy):this.boxDe(this.model);if(box.isEmpty())return;const size=box.getSize(new T.Vector3()),aspect=this.stage.clientWidth/Math.max(this.stage.clientHeight,1),height=Math.max(size.y,2.4),width=Math.max(naCopia?2*Math.max(Math.abs(box.min.x),Math.abs(box.max.x)):size.x,2.2);const vf=Math.tan(44*Math.PI/360);this.dist=Math.max(4.8,Math.max(height,width/aspect)/(2*vf)*(naCopia?1.45:1.25)+size.z*.6);const c=box.getCenter(new T.Vector3());this.target.set(0,c.y,0);this.cameraPosition();}
 cameraPosition(){if(this.xr)return;const d=this.dist;this.camera.position.set(this.target.x+d*Math.cos(this.elev)*Math.sin(this.az),this.target.y+d*Math.sin(this.elev),this.target.z+d*Math.cos(this.elev)*Math.cos(this.az));this.camera.lookAt(this.target);this.camera.updateMatrixWorld(true);}
 resize(){if(this.xr)return;const w=Math.max(1,this.stage.clientWidth),h=Math.max(1,this.stage.clientHeight),p=Math.min(devicePixelRatio||1,S.quality==='low'?1:S.quality==='high'?2:1.5);if(w!==this.width||h!==this.height||p!==this.pixel){this.renderer.setPixelRatio(p);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.width=w;this.height=h;this.pixel=p;}}
 center(){if(this.model)this.model.rotation.y=0;if(this.xr){this.anchor=null;this.placeXR();this.buildXRUI();}else{this.az=SEQ_VIEWS.includes(S.view)?0:.25;this.elev=.08;this.fit();}}
 zoom(delta){if(this.xr){this.xrZoom=Math.max(.65,Math.min(1.5,(this.xrZoom||1)+delta*.1));this.placeXR();}else{this.dist=Math.max(3.5,Math.min(40,this.dist*(delta>0?.86:1.16)));this.cameraPosition();}}
 pointerRay(e){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.camera.updateMatrixWorld();this.scene.updateMatrixWorld(true);this.ray.setFromCamera(this.pointer,this.camera);return this.ray;}
 hits(ray=this.ray,exclude=null){return ray.intersectObjects(this.modelHitTargets||[],false).filter(h=>{let o=h.object;while(o){if(!o.visible||o===exclude)return false;o=o.parent;}/* com corte, ignora a metade recortada da esfera */const pl=this.planoDe(h.object);if(pl&&pl.distanceToPoint(h.point)<0)return false;return true;});}
 planoDe(o){let p=o;while(p){if(p.userData.plano)return p.userData.plano;p=p.parent;}return null;}
 hitData(hit){if(!hit)return null;const d=hit.object.userData.hit;if(d&&d.type==='inspect'&&hit.object.userData.dinamico==='crosta')return Object.assign({},d,{key:M.tipoCrosta(hit.uv)});if(d&&d.type==='inspect'&&hit.object.userData.dinamico==='placa'){const k=M.placaEm(hit.uv);return k?Object.assign({},d,{key:k}):null;}return d;}
 naCopia(obj){let o=obj;while(o){if(o===this.copy)return true;o=o.parent;}return false;}
 boxDe(obj,tudo){const box=new T.Box3();const v=new T.Vector3();obj.updateMatrixWorld(true);obj.traverse(o=>{if(!o.visible)return;if(!tudo){if(o.userData.semEnquadre)return;let p=o.parent,ign=false;while(p&&p!==obj){if(p.userData.semEnquadre||!p.visible){ign=true;break;}p=p.parent;}if(ign)return;}if(o.isMesh&&o.geometry){if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();const bb=o.geometry.boundingBox;for(let i=0;i<8;i++){v.set(i&1?bb.max.x:bb.min.x,i&2?bb.max.y:bb.min.y,i&4?bb.max.z:bb.min.z).applyMatrix4(o.matrixWorld);box.expandByPoint(v);}}});return box;}
 refreshHits(){this.modelHitTargets=[];if(this.model)this.model.traverseVisible(o=>{if(o.isMesh&&o.userData.hit)this.modelHitTargets.push(o);});}
 fitCopy(anim){const copy=this.copy;if(!copy||copy.userData.held)return;copy.scale.setScalar(1);copy.updateMatrixWorld(true);const box=this.boxDe(copy);if(box.isEmpty())return;const size=box.getSize(new T.Vector3());const maior=Math.max(size.x,size.y,size.z);if(!isFinite(maior)||maior<1e-4)return;const factor=2.5/maior;const local=box.getCenter(new T.Vector3()).sub(copy.position);copy.position.fromArray(this.copyAnchor||[.9,.05,1.6]).sub(local.multiplyScalar(factor));copy.scale.setScalar(factor);if(anim){this.animatedInspect={object:copy,target:factor,start:performance.now()};if(!S.reducedMotion)copy.scale.setScalar(factor*.82);}}
 setHover(hit){const data=hit?hit.object.userData.hit:null;const chave=data?(data.key||data.type+':'+(data.index??data.target??data.tipo??'')):null;if(chave===this.hoverKey)return;
  (this.hoverMeshes||[]).forEach(m=>{if(m.material&&m.material.emissive)m.material.emissive.setHex(m.userData.emissiveBase||0);});this.hoverMeshes=[];this.hoverKey=chave;if(!chave)return;
  (this.modelHitTargets||[]).forEach(m=>{const d=m.userData.hit;if(!d)return;const k=d.key||d.type+':'+(d.index??d.target??d.tipo??'');if(k!==chave||!m.material||!m.material.emissive)return;if(m.userData.emissiveBase===undefined)m.userData.emissiveBase=m.material.emissive.getHex();m.material.emissive.setHex(0x3a6d80);this.hoverMeshes.push(m);});
  if(!this.xr)this.canvas.style.cursor='pointer';}
 activate(data){if(!data)return;switch(data.type){
  case'inspect':inspect(data.key);break;
  case'context':handle(S.view==='placContexto'?'pctx:next':'context:next');break;
  case'lim':handle('lim:'+data.tipo);break;
  case'seqPiece':handle('seq:pick:'+data.key);break;
  case'seqSlot':{const st=seqState();if(st&&st.selected)seqPlace(data.index);else handle('seq:target:'+data.index);break;}}}
 closestDrop(world){const st=seqState();if(!st||!this.obj||!this.obj.userData.slots)return null;const {top,dy}=this.obj.userData.slots;let best=null,bd=1e9;st.colocados.forEach((k,i)=>{if(k)return;const p=this.obj.localToWorld(new T.Vector3(.9,top-i*dy,0));const d=world.distanceTo(p);if(d<bd){bd=d;best={type:'seqSlot',index:i};}});const threshold=this.xr?.25:.9;return bd<threshold?best:null;}
 bind(){const canvas=this.canvas;canvas.addEventListener('pointerdown',e=>{if(this.xr)return;this.pointerRay(e);const hit=this.hits()[0];let group=hit?.object;while(group&&group!==this.model&&!group.userData.draggable&&!group.userData.rotateCopy)group=group.parent;const type=group?.userData.draggable?'piece':group?.userData.rotateCopy?'copy':'orbit';let plane=null;if(type==='piece'){const pos=group.getWorldPosition(new T.Vector3()),dir=this.camera.getWorldDirection(new T.Vector3());plane=new T.Plane().setFromNormalAndCoplanarPoint(dir,pos);}
   this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false,hit:this.hitData(hit),group,type,plane,fundo:!!(hit&&inspectKey&&this.copy&&!this.naCopia(hit.object))};canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(this.xr)return;if(!this.drag){this.pointerRay(e);const h=this.hits()[0];this.setHover(h);canvas.style.cursor=h?'pointer':'grab';return;}const d=this.drag,dx=e.clientX-d.x,dy=e.clientY-d.y;d.x=e.clientX;d.y=e.clientY;if(Math.hypot(e.clientX-d.sx,e.clientY-d.sy)>5)d.moved=true;if(!d.moved)return;S.autoRotate=false;$('rotateBtn').textContent='▷ Girar';if(d.type==='piece'){this.pointerRay(e);const p=this.ray.ray.intersectPlane(d.plane,new T.Vector3());if(p){d.group.position.copy(d.group.parent.worldToLocal(p));}}
   else if(d.type==='copy'){d.group.rotation.y+=dx*.008;d.group.rotation.x+=dy*.008;}else{this.az-=dx*.005;this.elev=Math.max(-1.1,Math.min(1.1,this.elev+dy*.005));this.cameraPosition();}});
  canvas.addEventListener('pointerup',e=>{const d=this.drag;this.drag=null;try{canvas.releasePointerCapture(e.pointerId);}catch(_){}if(!d||this.xr)return;if(d.moved&&d.type==='piece'){const world=d.group.getWorldPosition(new T.Vector3()),target=this.closestDrop(world);if(d.hit?.type==='seqPiece'){const st=seqState();if(st)st.selected=d.hit.key;}if(target)this.activate(target);else{render();fb('Aproxime a peça de uma posição. Também é possível selecionar e usar o botão Encaixar.','warning');}}
   else if(!d.moved){if(d.fundo&&d.hit&&d.hit.type==='inspect'){handle('inspect:close');}else this.activate(d.hit);}});canvas.addEventListener('pointercancel',()=>{this.drag=null;rebuild();});
  canvas.addEventListener('wheel',e=>{e.preventDefault();if(this.xr)return;this.dist=Math.max(3.5,Math.min(40,this.dist+e.deltaY*.012));this.cameraPosition();},{passive:false});
  canvas.addEventListener('keydown',e=>{if(e.key==='Escape'&&inspectKey){handle('inspect:close');return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home',' '].includes(e.key)){e.preventDefault();if(e.key==='Home')this.center();else if(e.key==='+')this.zoom(1);else if(e.key==='-')this.zoom(-1);else if(e.key===' ')handle('rotate');else{this.az+=(e.key==='ArrowLeft'?.08:e.key==='ArrowRight'?-.08:0);this.elev=Math.max(-1.1,Math.min(1.1,this.elev+(e.key==='ArrowUp'?.08:e.key==='ArrowDown'?-.08:0)));this.cameraPosition();}}});
 }
 frame(time,frame){if(!this.renderer)return;const now=performance.now(),dt=Math.min(.05,Math.max(0,(now-this.last)/1000));this.last=now;this.resize();const t=now/1000;
  if(S.autoRotate&&this.model){if(this.copy)this.copy.rotation.y+=dt*.3;else if(!(this.obj&&this.obj.userData.semGiro))this.model.rotation.y+=dt*.2;}
  if(this.animatedInspect&&this.animatedInspect.object.userData.held)this.animatedInspect=null;
  if(this.animatedInspect){const i=this.animatedInspect,tt=Math.min(1,(now-i.start)/300),s=S.reducedMotion?1:.82+.18*(1-(1-tt)**3);i.object.scale.setScalar(i.target*s);if(tt>=1)this.animatedInspect=null;}
  if(this.model){if(this.obj&&this.obj.userData.tick)this.obj.userData.tick(t);if(this.copy&&this.copy.userData.tick)this.copy.userData.tick(t);}
  if(this.xr){if(this.waitFrames){this.waitFrames--;if(!this.waitFrames){this.anchor=null;this.placeXR();this.buildXRUI();}}this.updateXR(dt);}
  if(S.view==='viagem'&&this.obj&&this.obj.userData.viagem){this.viagemTick(dt);this.luzes(.22);}else{if(this.farol)this.farol.visible=false;this.luzes(1);}
  this.renderer.render(this.scene,this.camera);
 }
 viagemTick(dt){const v=S.viagem,tr=D.viagem[v.trecho],info=this.obj.userData.viagem;if(!tr||!info)return;const agora=performance.now();dt=Math.min(.25,(agora-(this._vt||agora))/1000);this._vt=agora;
  if(v.andando&&info.curva&&v.u<1){v.u=Math.min(1,v.u+dt/tr.dur);if(v.u>=1){v.andando=false;const fim=v.trecho===D.viagem.length-1&&!S.completed.includes('viagem');if(fim)mark('viagem');renderSidebar();save();if(fim&&S.autoVoice)narrator.say(D.VIAGEM_FIM.text,'viagem-fim');}else if(((agora/250)|0)!==this._vUI){this._vUI=(agora/250)|0;const g=$('lessonPanel').querySelector('.gauge b');if(g)g.textContent=Math.round(tr.de+(tr.ate-tr.de)*v.u).toLocaleString('pt-BR')+' km';}}
  if(!this.farol){this.farol=new T.PointLight(0xfff1e0,.6,60,1.3);this.camera.add(this.farol);}this.farol.visible=true;/* cor do farol acompanha a camada */this.farol.color.setHex(v.trecho>=5?0xffd090:v.trecho>=2?0xffc8a0:0xfff1e0);
  const up=new T.Vector3(0,1,0);const p=info.curva.getPointAt(v.u),tg=info.curva.getTangentAt(v.u).normalize();
  const yawDe=d=>Math.atan2(-d.x,-d.z);
  if(this.xr){if(!this.anchor)this.anchor=this.head();const a=this.anchor,K=info.escalaVR*(this.xrZoom||1);const alvo=a.yaw-yawDe(tg);let y=this.root.rotation.y;let d=alvo-y;while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;y+=d*Math.min(1,dt*2.5);this.root.scale.setScalar(K);this.root.rotation.set(0,y,0);const pw=p.clone().multiplyScalar(K).applyAxisAngle(up,y);this.root.position.copy(a.p).sub(pw);this.root.updateMatrixWorld(true);}
  else{this.camera.position.copy(p);const dir=tg.clone().applyAxisAngle(up,this.az);dir.y+=Math.max(-.9,Math.min(.9,this.elev));dir.normalize();this.camera.lookAt(p.clone().add(dir));this.camera.updateMatrixWorld(true);}
 }
 luzes(k){if(this._luzK===k)return;this._luzK=k;this.scene.children.forEach(o=>{if(o.isLight&&o!==this.farol){if(o.userData.base===undefined)o.userData.base=o.intensity;o.intensity=o.userData.base*k;}});}
 head(){const c=this.renderer.xr.getCamera(this.camera),p=c.getWorldPosition(new T.Vector3()),f=c.getWorldDirection(new T.Vector3());f.y=0;if(f.lengthSq()<.001)f.set(0,0,-1);f.normalize();return{p,f,yaw:Math.atan2(-f.x,-f.z)};}
 placeXR(){if(!this.xr||!this.model)return;if(!this.anchor)this.anchor=this.head();const a=this.anchor;this.root.position.set(0,0,0);this.root.scale.setScalar(1);this.root.rotation.set(0,0,0);this.root.updateMatrixWorld(true);const box=this.boxDe(this.model),size=box.isEmpty()?new T.Vector3(5,5,5):box.getSize(new T.Vector3()),tudo=this.boxDe(this.model,true),alt=tudo.isEmpty()?0:tudo.getSize(new T.Vector3()).y;let scale=1.45/Math.max(size.x,size.y,5),dist=1.95;if(alt*scale>1.95){scale=1.95/alt;dist=1.55;}scale*=(this.xrZoom||1);this.root.scale.setScalar(scale);this.root.rotation.y=a.yaw;this.root.position.copy(a.p).addScaledVector(a.f,dist);this.root.position.y-=.2;if(!box.isEmpty()){const c=box.getCenter(new T.Vector3()).multiplyScalar(scale).applyAxisAngle(new T.Vector3(0,1,0),a.yaw);this.root.position.sub(c);const pe=this.root.position.y+tudo.min.y*scale;if(pe<.05)this.root.position.y+=.05-pe;}
  this.ui.position.copy(a.p);this.ui.rotation.set(0,a.yaw,0);this.root.updateMatrixWorld(true);this.ui.updateMatrixWorld(true);}
 clearXRUI(){for(const c of [...this.ui.children])M.dispose(c);this.uiHits=[];}
 textPlane(title,body,w=.82,h=.66){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;const c=canvas.getContext('2d');c.fillStyle='rgba(10,31,46,.97)';c.fillRect(0,0,1024,1024);let y=90;const write=(text,size,color)=>{c.font=(size>40?'600 ':'400 ')+size+'px Segoe UI,Arial';c.fillStyle=color;let line='';for(const word of String(text).split(/\s+/)){const next=(line?line+' ':'')+word;if(c.measureText(next).width>930&&line){if(y<990)c.fillText(line,52,y);y+=size*1.35;line=word;}else line=next;}if(line&&y<990){c.fillText(line,52,y);y+=size*1.4;}};write(title,64,'#a4e6d1');y+=20;write(body,52,'#d3eaf6');const texture=new T.CanvasTexture(canvas);texture.encoding=T.sRGBEncoding;return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:texture,transparent:true,side:T.DoubleSide,depthWrite:false}));}
 xrButton(label,cmd,x,y,w=.4,disabled=false){const c=document.createElement('canvas');c.width=1024;c.height=256;const g=c.getContext('2d');g.fillStyle=disabled?'#172c3b':'#144957';g.fillRect(0,0,1024,256);g.font='600 72px Segoe UI,Arial';g.textAlign='center';g.textBaseline='middle';g.fillStyle=disabled?'#6b8190':'#ebfbff';g.fillText(label,512,130);const tex=new T.CanvasTexture(c);tex.encoding=T.sRGBEncoding;const m=new T.Mesh(new T.PlaneGeometry(w,.115),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));m.position.set(x,y,-1.62);m.userData.command=cmd;this.ui.add(m);if(!disabled)this.uiHits.push(m);return m;}
 buildXRUI(){if(!this.xr)return;this.clearXRUI();const panel=this.textPlane($('lessonPanel').querySelector('h2')?.textContent||'Terra por Dentro',instruction,1.06,.86);panel.position.set(1.16,.3,-1.64);panel.rotation.y=-.6;this.ui.add(panel);this._acoes().slice(0,8).forEach((a,i)=>this.xrButton(a.label,a.cmd,1.16+(i%2?.25:-.25),-.22-Math.floor(i/2)*.15,.46,a.disabled));}
 _acoes(){const out=[];document.querySelectorAll('#lessonPanel [data-act]').forEach(b=>{if(/^seq:target:/.test(b.dataset.act))return;if(b.closest('details')&&!b.closest('details').open)return;out.push({label:b.dataset.xr||b.textContent.trim(),cmd:b.dataset.act,disabled:b.disabled});});return out;}
 controllerRay(ctrl){ctrl.updateMatrixWorld(true);const ray=new T.Raycaster();ray.camera=this.renderer.xr.getCamera(this.camera);ray.ray.origin.setFromMatrixPosition(ctrl.matrixWorld);ray.ray.direction.set(0,0,-1).transformDirection(ctrl.matrixWorld);return ray;}
 xrSelect(ctrl){if(this.held.has(ctrl))return;const ray=this.controllerRay(ctrl),ui=ray.intersectObjects(this.uiHits,false)[0];if(ui){const cmd=ui.object.userData.command;if(/^xr:menu:/.test(cmd)){this.xrMenu=cmd.split(':')[2];this.buildXRUI();return;}if(cmd==='xr:prev'){this.uiPage--;this.buildXRUI();return;}if(cmd==='xr:next'){this.uiPage++;this.buildXRUI();return;}if(cmd==='xr:reportclose'){this.xrReport=false;this.buildXRUI();return;}this.xrReport=false;handle(cmd);return;}this.root.updateMatrixWorld(true);const hit=this.hits(ray)[0];if(hit){const data=this.hitData(hit);if(inspectKey&&this.copy&&!this.naCopia(hit.object)&&data&&data.type==='inspect')handle('inspect:close');else this.activate(data);}else narrator.stop();}
 gripStart(ctrl){const ray=this.controllerRay(ctrl),hit=this.hits(ray)[0];if(!hit)return;const data=this.hitData(hit);if(data.type!=='seqPiece'){this.pegar(ctrl,hit,data);return;}const cfg=D.sequencias[S.view];const copy=new T.Group();const box=new T.Mesh(new T.BoxGeometry(.92,.44,.2),M.mat(0x5a3a1e));copy.add(box);const t=M.label(cfg.rotulos[data.key],'#ffffff',.9,60);t.position.z=.12;copy.add(t);copy.scale.setScalar(.15);copy.position.set(0,-.02,-.32);ctrl.add(copy);copy.userData.heldData=data;this.held.set(ctrl,copy);const st=seqState();if(st)st.selected=data.key;}
 gripEnd(ctrl){const copy=this.held.get(ctrl);if(copy&&copy.userData&&copy.userData.pegaReal){this.soltar(ctrl);return;}if(!copy)return;const pos=copy.getWorldPosition(new T.Vector3()),target=this.closestDrop(pos);M.dispose(copy);this.held.delete(ctrl);if(target)this.activate(target);else{renderSidebar();fb('Peça selecionada. Aponte para a posição e pressione o gatilho.');}}
 alvoPegavel(obj){let o=obj;while(o&&o!==this.model){if(o.userData.rotateCopy||o.userData.pegavel)return o;o=o.parent;}return null;}
 pegar(ctrl,hit,data){const g=this.alvoPegavel(hit.object);if(!g){if(data&&data.type==='inspect')this.activate(data);return;}
  const outro=[...this.held.entries()].find(([c,o])=>o===g&&c!==ctrl);
  if(outro){const a=(outro[0].userData.grip||outro[0]).getWorldPosition(new T.Vector3()),b=(ctrl.userData.grip||ctrl).getWorldPosition(new T.Vector3());this.duasMaos={obj:g,d0:Math.max(.05,a.distanceTo(b)),s0:g.scale.x,c1:outro[0],c2:ctrl};this.held.set(ctrl,g);return;}
  if(g.userData.pegaReal)return;
  g.userData.pegaReal={parent:g.parent,position:g.position.clone(),quaternion:g.quaternion.clone(),scale:g.scale.clone()};
  const grip=ctrl.userData.grip||ctrl;grip.attach(g);g.userData.held=true;this.held.set(ctrl,g);
  const key=data&&data.key;if(key&&D.info[key]){if(!S.visited.includes(key))S.visited.push(key);log('inspecao','explorar',{component:key,modo:'mao'});setInstruction(D.info[key].text,key);if(S.autoVoice)narrator.say(D.info[key].text,key);this.buildXRUI();}
 }
 soltar(ctrl){const g=this.held.get(ctrl);if(!g)return;this.held.delete(ctrl);
  if(this.duasMaos&&this.duasMaos.obj===g){const dm=this.duasMaos;this.duasMaos=null;if(ctrl===dm.c2)return;const grip=dm.c2.userData.grip||dm.c2;grip.attach(g);this.held.set(dm.c2,g);return;}
  const r=g.userData.pegaReal;if(!r)return;delete g.userData.pegaReal;g.userData.held=false;
  if(r.parent)r.parent.attach(g);this.retornos=this.retornos||[];this.retornos.push({obj:g,p0:g.position.clone(),q0:g.quaternion.clone(),s0:g.scale.clone(),p1:r.position,q1:r.quaternion,s1:r.scale,t0:performance.now()});
 }
 animarRetornos(){if(!this.retornos||!this.retornos.length)return;const agora=performance.now();this.retornos=this.retornos.filter(r=>{const t=Math.min(1,(agora-r.t0)/380),k=S.reducedMotion?1:1-Math.pow(1-t,3);r.obj.position.lerpVectors(r.p0,r.p1,k);r.obj.quaternion.slerpQuaternions(r.q0,r.q1,k);r.obj.scale.lerpVectors(r.s0,r.s1,k);return t<1;});}
 controllersInit(){if(this.controllers.length)return;for(let i=0;i<2;i++){const ctrl=this.renderer.xr.getController(i);this.scene.add(ctrl);const grip=this.renderer.xr.getControllerGrip(i);this.scene.add(grip);ctrl.userData.grip=grip;const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-1)]),line=new T.Line(geo,new T.LineBasicMaterial({color:0x73d8e5}));line.scale.z=3;line.name='ray';ctrl.add(line);ctrl.addEventListener('selectstart',()=>this.xrSelect(ctrl));ctrl.addEventListener('squeezestart',()=>this.gripStart(ctrl));ctrl.addEventListener('squeezeend',()=>this.gripEnd(ctrl));ctrl.addEventListener('disconnected',()=>this.gripEnd(ctrl));this.controllers.push(ctrl);}}
 updateXR(dt){if(!this.anchor)return;this.scene.updateMatrixWorld(true);let alvo=null;for(const ctrl of this.controllers){const ray=this.controllerRay(ctrl),ui=ray.intersectObjects(this.uiHits,false)[0],mh=ui?null:this.hits(ray)[0],hit=ui||mh;if(mh&&!alvo)alvo=mh;const line=ctrl.getObjectByName('ray');line.material.color.setHex(hit?0xb8f6d7:0x66b7cb);line.scale.z=hit?Math.min(4,hit.distance):3;}this.setHover(alvo);
  this.animarRetornos();
  if(this.duasMaos){const dm=this.duasMaos,a=(dm.c1.userData.grip||dm.c1).getWorldPosition(new T.Vector3()),b=(dm.c2.userData.grip||dm.c2).getWorldPosition(new T.Vector3());const k=Math.max(.3,Math.min(8,a.distanceTo(b)/dm.d0));dm.obj.scale.setScalar(dm.s0*k);}
  if(this.xrSession)for(const src of this.xrSession.inputSources){const gp=src.gamepad;if(!gp)continue;const x=gp.axes[2]||0,y=gp.axes[3]||0;const st=src.userData||(src.userData={});
   if(src.handedness==='left'){if(Math.abs(y)>.3)this.root.position.y=Math.max(.2,Math.min(2.6,this.root.position.y-y*dt*.3));}
   else{if(Math.abs(x)>.6&&!st.snapX){st.snapX=true;const alvo=this.copy||this.model;if(alvo)alvo.rotation.y-=Math.sign(x)*Math.PI/6;}else if(Math.abs(x)<.3)st.snapX=false;
    if(Math.abs(y)>.6&&!st.snapY){st.snapY=true;if(S.view==='viagem'){const v=S.viagem;v.u=Math.max(0,Math.min(1,v.u-Math.sign(y)*.08));v.andando=false;renderSidebar();}else if(this.anchor){this.root.position.addScaledVector(this.anchor.f,-Math.sign(y)*.25);}}else if(Math.abs(y)<.3)st.snapY=false;}
   const bA=gp.buttons[4]&&gp.buttons[4].pressed;if(bA&&!st.bA){st.bA=true;this.center();}else if(!bA)st.bA=false;
   const bB=gp.buttons[5]&&gp.buttons[5].pressed;if(bB&&!st.bB){st.bB=true;this.xrMenu=this.xrMenu==='raiz'?'missoes':'raiz';this.buildXRUI();}else if(!bB)st.bB=false;}}
 async toggleVR(modo,silencioso){modo=modo||'vr';if(this.xrSession){if(modo!==this.xrModo){this.xrPendente=modo;}await this.xrSession.end();return;}if(!window.isSecureContext||!navigator.xr){fb('O modo VR precisa de HTTPS e de um navegador compatível no óculos. Aqui você pode usar o modo 3D.','warning');return;}
  narrator.stop();try{const tipo=modo==='ar'?'immersive-ar':'immersive-vr';const supported=await navigator.xr.isSessionSupported(tipo);if(!supported){fb(modo==='ar'?'Este óculos não informou suporte a realidade mista (passthrough).':'Este dispositivo não informou suporte a VR imersivo.','warning');return;}const session=await navigator.xr.requestSession(tipo,{optionalFeatures:['local-floor','hand-tracking']});this.xrModo=modo;let reference='local-floor';try{await session.requestReferenceSpace('local-floor');}catch(_){reference='local';}this.renderer.xr.setReferenceSpaceType(reference);try{await this.renderer.xr.setSession(session);}catch(e){await session.end();throw e;}this.xrSession=session;this.xr=true;this.waitFrames=3;this.anchor=null;this.xrZoom=1;this.camera.position.set(0,0,0);this.camera.rotation.set(0,0,0);this.controllersInit();document.body.classList.add('xr');this.ui.visible=true;session.addEventListener('end',()=>this.exitXR());if(modo==='ar'){this.renderer.setClearColor(0x000000,0);}session.addEventListener('visibilitychange',()=>{if(session.visibilityState!=='visible'){narrator.stop();S.autoRotate=false;}});this.placeXR();this.buildXRUI();return true;}catch(e){this.xrModo=null;if(silencioso)return false;fb('Não foi possível iniciar VR: '+e.message,'warning');try{const d=document.createElement('div');d.className='stage-error';d.style.zIndex='2147483400';d.innerHTML='<p><b>O óculos não abriu a sessão de VR.</b></p><p>'+esc(e.name+': '+e.message)+'</p><p class="fine">Verifique se o navegador do óculos está atualizado e se a página foi aberta em HTTPS. Toque fora para fechar.</p>';d.addEventListener('click',()=>d.remove());$('stage').appendChild(d);}catch(_){}return false;}}
 retomarXR(modo){const ov=document.createElement('div');ov.id='vrGate';ov.innerHTML='<div class="vrgate-box"><img src="assets/logo.png" alt=""><div class="vrgate-t">'+(modo==='ar'?'Realidade mista':'Modo VR')+'</div><div class="vrgate-s">O navegador pede um toque para abrir a nova sessão</div><button type="button" data-action="retomar">'+(modo==='ar'?'⬚ Entrar na minha sala':'🥽 Entrar em VR')+'</button><button type="button" class="sec" data-action="ficar">Ficar no 3D</button></div>';document.body.appendChild(ov);ov.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='retomar'){this.toggleVR(modo).finally(()=>ov.remove());}else ov.remove();});}
 exitXR(){const pendente=this.xrPendente;this.xrPendente=null;this.xrModo=null;for(const [ctrl,copy] of this.held){if(copy.userData&&copy.userData.pegaReal)this.soltar(ctrl);else M.dispose(copy);}this.held.clear();this.duasMaos=null;this.retornos=[];this.xr=false;this.xrSession=null;this.anchor=null;this.clearXRUI();document.body.classList.remove('xr');narrator.stop();this.root.position.set(0,0,0);this.root.rotation.set(0,0,0);this.root.scale.setScalar(1);this.width=0;this.cameraPosition();this.show();if(pendente)setTimeout(()=>{this.toggleVR(pendente,true).then(ok=>{if(!ok)this.retomarXR(pendente);});},150);}
}
function report(){const list=S.events;return{version:D.version,started:new Date(S.started).toISOString(),exported:new Date().toISOString(),completed:[...S.completed],components:[...S.visited],errors:list.filter(e=>e.correct===false).length,hints:list.filter(e=>e.event==='pista').length,montar:{colocados:S.montar.colocados,erros:S.montar.erros,pistas:S.montar.pistas},viagem:{trecho:S.viagem.trecho,concluida:S.completed.includes('viagem')},explorar:S.visited.filter(k=>listaDe('explorar').includes(k)),quizzes:S.quizzes,events:[...list]};}
function showSummary(){narrator.stop();if(view&&view.xr){view.xrReport=true;view.buildXRUI();return;}const r=report();const rows=[['Contexto',S.completed.includes('contexto')?'Percurso realizado':'Não concluído'],['Camadas investigadas',vistosDe('explorar')+' / '+listaDe('explorar').length],['Monte as camadas',S.montar.colocados.filter(Boolean).length+' / 5'],['Viagem ao centro',S.completed.includes('viagem')?'Concluída':'Trecho '+(S.viagem.trecho+1)+' de '+D.viagem.length],['Placas investigadas',vistosDe('placasExp')+' / '+listaDe('placasExp').length],['Que limite é esse?',['divergente','convergente','transformante'].filter(k=>S.limites[k]).length+' / 3'],['Volta ao mundo',S.completed.includes('volta')?'Completa':'Parada '+(S.volta.etapa+1)+' de '+D.volta.length],['Desafios',D.temas.filter(x=>!x.breve).map(x=>x.nome+': '+((S.quizzes||{})[x.id]&&S.quizzes[x.id].done?'✓':'–')).join(' · ')]];$('summaryContent').innerHTML='<p class="fine">Um retrato das ações realizadas nesta sessão.</p><table><thead><tr><th>Atividade</th><th>Registro</th></tr></thead><tbody>'+rows.map(([a,b])=>'<tr><td>'+a+'</td><td>'+b+'</td></tr>').join('')+'</tbody></table><div class="metric-row"><span>Tentativas incorretas</span><b>'+r.errors+'</b></div><div class="metric-row"><span>Pistas consultadas</span><b>'+r.hints+'</b></div><p class="fine">Erros e pistas não diminuem um placar global. Use os registros para conversar com o aluno e escolher uma retomada.</p>';$('summaryDialog').showModal();}
function download(name,text,mime){const blob=new Blob([text],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setup(){
 renderNav();
 const menuEl=$('menuSistemas');if(menuEl)menuEl.addEventListener('click',e=>{const c=e.target.closest('[data-tema]');if(c&&!c.disabled){handle('tema:'+c.dataset.tema);return;}const b=e.target.closest('[data-act]');if(b&&!b.disabled)handle(b.dataset.act);});
 $('activityNav').addEventListener('click',e=>{const sb=e.target.closest('[data-tema]');if(sb&&!sb.disabled){handle('tema:'+sb.dataset.tema);return;}const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view);});$('sidebar').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b&&!b.disabled)handle(b.dataset.act);});
 document.body.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const ac=b.dataset.action;
  if(ac==='guide'){fecharMenu();handle('guide:start');}else if(ac==='sistemas')abrirMenu();else if(ac==='summary')showSummary();else if(ac==='settings'){$('level').value=S.level;$('settingsDialog').showModal();}else if(ac==='closeSummary')$('summaryDialog').close();else if(ac==='sources')$('sourcesDialog').showModal();
  else if(ac==='newStudent'){if(!confirm('Iniciar um novo aluno? Exporte o resumo antes de limpar esta sessão.'))return;narrator.stop();S=initial();inspectKey=null;feedbackText='';$('settingsDialog').close();save();switchView('contexto',false);abrirMenu();try{$('welcomeDialog').showModal();}catch(_){}}
  else if(ac==='repeatVoice')narrator.say(instruction,instructionKey);else if(ac==='stopVoice')narrator.stop();else if(ac==='closeInspect')handle('inspect:close');else if(ac==='center')handle('center');else if(ac==='rotate'){handle('rotate');if(view&&view.xr)view.buildXRUI();}else if(ac==='zoomIn')view&&view.zoom(1);else if(ac==='zoomOut')view&&view.zoom(-1);else if(ac==='vr')handle('vr');else if(ac==='ar')handle('ar');
  else if(ac==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen({navigationUI:'hide'}).catch(()=>fb('O navegador não autorizou tela cheia.','warning'));}
  else if(ac==='welcomeStart'){$('welcomeDialog').close();abrirMenu();boasVindas();}else if(ac==='welcomeSkip'){S.welcomed=true;save();$('welcomeDialog').close();abrirMenu();}
  else if(ac==='offlineBaixar')offlineBaixar();else if(ac==='downloadJSON')download('TerraPorDentro-resumo.json',JSON.stringify(report(),null,2),'application/json');
  else if(ac==='downloadCSV'){const r=report(),rows=[['evento','habilidade','correto','posicao','escolha','data'],...r.events.map(e=>[e.event,e.skill,e.correct??'',e.position??'',e.choice??'',e.at])];const csv='﻿'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');download('TerraPorDentro-atividades.csv',csv,'text/csv;charset=utf-8');}
  else if(ac==='catalog'){e.preventDefault();handle('catalog');}});
 $('sourcesContent').innerHTML='<p class="fine">Conteúdo elaborado para o Fundamental II (6º e 7º anos) e o Ensino Médio, com revisão docente recomendada.</p><p class="fine"><b>Modelos 3D:</b> procedurais, gerados no navegador pela NEWPC (camadas em esferas, secção com textura de rocha e magma, túnel da viagem). A superfície usa as imagens Blue Marble da NASA (domínio público). As espessuras das camadas são didáticas: a crosta real tem cerca de 0,5% do raio.</p><ul class="resource-list">'+D.sources.map(([t,u])=>'<li><a href="'+u+'" target="_blank" rel="noopener noreferrer">'+esc(t)+'</a></li>').join('')+'</ul><p class="fine">Limites: temperaturas e pressões são valores médios de referência; a viagem é uma representação (ninguém jamais desceu além de 12 km). Não substitui atlas geológico.</p>';
 $('level').addEventListener('change',e=>{S.level=e.target.value;renderSidebar();save();});$('voiceVolume').addEventListener('input',e=>{const n=Number(e.target.value);$('voiceValue').textContent=n+'%';narrator.setVoice(n/100);});$('musicVolume').addEventListener('input',e=>{const n=Number(e.target.value);$('musicValue').textContent=n+'%';narrator.setMusic($('musicEnabled').checked,n/100);});$('musicEnabled').addEventListener('change',e=>narrator.setMusic(e.target.checked));$('autoVoice').checked=S.autoVoice;$('autoVoice').addEventListener('change',e=>{S.autoVoice=e.target.checked;if(!S.autoVoice)narrator.stop();save();});$('syntheticVoice').addEventListener('change',e=>{narrator.synthetic=e.target.checked;narrator.stop();});$('captionsEnabled').checked=S.captions;$('captionsEnabled').addEventListener('change',e=>{S.captions=e.target.checked;$('captionText').hidden=!S.captions;save();});$('reducedMotion').checked=S.reducedMotion;$('reducedMotion').addEventListener('change',e=>{S.reducedMotion=e.target.checked;save();});$('quality').value=S.quality;$('quality').addEventListener('change',e=>{S.quality=e.target.value;if(view)view.pixel=0;save();});if($('chaoVR')){$('chaoVR').value=S.chaoVR||'discreto';$('chaoVR').addEventListener('change',e=>{S.chaoVR=e.target.value;save();});}
 window.addEventListener('pagehide',()=>{save();narrator.dispose();});document.addEventListener('visibilitychange',()=>{if(document.hidden){narrator.stop();narrator.music.pause();}});
 if(T&&M)view=new LabView();else{$('webglError').hidden=false;$('stage').classList.add('error');}
 switchView(S.view,false);{const q=new URLSearchParams(location.search),normal=q.get('vr')!=='1'&&q.get('embed')!=='1';if(normal){abrirMenu();if(!S.welcomed&&$('welcomeDialog')&&$('welcomeDialog').showModal){try{$('welcomeDialog').showModal();}catch(_){}}}}$('rotateBtn').textContent=S.autoRotate?'Ⅱ Pausar':'▷ Girar';
function offlineUI(d){const st=$('offlineStatus'),det=$('offlineDetalhe');if(!st)return;const mb=d.bytes?(d.bytes/1e6).toFixed(0)+' MB':'';
 if(d.erro){st.textContent='Offline: indisponível';st.className='offline erro';if(det)det.textContent='Não foi possível preparar o uso sem internet ('+d.erro+'). A aplicação continua funcionando online.';return;}
 if(d.pronto||(d.total&&d.feitos>=d.total)){st.textContent='✓ Pronto para uso sem internet';st.className='offline pronto';if(det)det.textContent='Narrações ('+mb+') guardadas neste dispositivo. A aplicação abre e narra mesmo sem internet.';return;}
 const pct=d.total?Math.round(100*d.feitos/d.total):0;st.textContent='Preparando uso sem internet… '+pct+'%';st.className='offline';if(det)det.textContent='Baixando as narrações para este dispositivo: '+d.feitos+' de '+d.total+' arquivos ('+mb+'). Pode continuar usando normalmente.';}
function registrarSW(){if(!('serviceWorker' in navigator))return offlineUI({erro:'navegador sem suporte'});if(!(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))return offlineUI({erro:'precisa de HTTPS'});
 navigator.serviceWorker.addEventListener('message',e=>{if(e.data&&e.data.tipo==='offline')offlineUI(e.data);});
 navigator.serviceWorker.register('sw.js').then(reg=>{const pedir=()=>{if(navigator.serviceWorker.controller)navigator.serviceWorker.controller.postMessage({tipo:'status'});};if(navigator.serviceWorker.controller)pedir();else navigator.serviceWorker.addEventListener('controllerchange',pedir);offlineUI({feitos:0,total:0});}).catch(e=>offlineUI({erro:e.message}));}
function offlineBaixar(){if(navigator.serviceWorker&&navigator.serviceWorker.controller)navigator.serviceWorker.controller.postMessage({tipo:'precache'});else registrarSW();}
 registrarSW();
 if(window.isSecureContext&&navigator.xr&&navigator.xr.isSessionSupported){navigator.xr.isSessionSupported('immersive-ar').then(ok=>{window.__arOK=!!ok;const b=$('arBtn');if(b&&ok)b.hidden=false;}).catch(()=>{});}
 window.TerraLab={version:D.version,get state(){return S;},command:handle,report,view,narrator,quizAtual:quizState,questoesAtuais:questoes,atividadesDe,temaAtual,refresh:render,boasVindas,abrirMenu,fecharMenu,WELCOME:D.WELCOME,inspect,get inspectKey(){return inspectKey;}};
}
setup();
})();
