/* Terra por Dentro · dados (v1.0)
   Conteúdo: tema Camadas da Terra (Contexto, Explorar, Monte as camadas, Viagem ao centro, Desafio).
   Placas, Vulcão e Rochas entram como temas "em breve". Textos no tom falado das narrações (chaves = nomes dos MP3 em audio/). */
(function(){'use strict';
const D={version:'1.0.1'};
D.temas=[
 {id:'camadas',nome:'Camadas da Terra',estuda:'Do que a Terra é feita por dentro.',exemplos:'Crosta, manto, núcleo externo e núcleo interno',modulo:'cam',atividades:['contexto','explorar','montar','viagem'],questoes:['liquida','kola','manto','magnetico','sismicas','interno','oceanica','temperatura']},
 {id:'placas',nome:'Placas tectônicas',estuda:'Por que a crosta se mexe, treme e se quebra.',breve:true},
 {id:'vulcao',nome:'Vulcões',estuda:'Da câmara de magma à erupção.',breve:true},
 {id:'rochas',nome:'Rochas e minerais',estuda:'O ciclo das rochas, da lava ao sedimento.',breve:true}
];
D.modulos=[{id:'cam',label:'Camadas da Terra',curto:'Camadas',pergunta:'O que existe debaixo dos nossos pés?'}];
D.activities=[
 {id:'contexto',label:'Contexto',title:'O que existe debaixo dos seus pés?',subtitle:'Do planeta visto do espaço até a casca fina em que vivemos.',kicker:'LOCALIZE',modulo:'cam'},
 {id:'explorar',label:'Explorar',title:'A Terra aberta ao meio.',subtitle:'Aponte em uma camada para ver a ficha e ouvir a explicação.',kicker:'EXPLORE',modulo:'cam'},
 {id:'montar',label:'Monte as camadas',title:'Da superfície ao centro.',subtitle:'Coloque as camadas na ordem, de fora para dentro.',kicker:'ORGANIZE',modulo:'cam'},
 {id:'viagem',label:'Viagem ao centro',title:'Desça até o centro da Terra.',subtitle:'Uma viagem em primeira pessoa: 6.371 km em sete trechos.',kicker:'VIAJE',modulo:'cam'},
 {id:'desafio',label:'Desafio',title:'Agora, explique o que descobriu.',subtitle:'Situações para aplicar o que você viu.',kicker:'APLIQUE',modulo:'cam'}
];
/* contexto em três etapas (cena muda a cada etapa) */
D.context=[
 {name:'Planeta Terra',target:'aberta',text:'Esta é a Terra vista do espaço: uma bola de rocha e metal com 12.742 quilômetros de diâmetro. A gente vive na superfície e quase nunca pensa no que tem lá embaixo. Vamos abrir o planeta ao meio.'},
 {name:'A Terra por dentro',target:'crosta',text:'Aberta ao meio, a Terra mostra as suas camadas: a crosta fininha por fora, o manto enorme no meio, e no centro o núcleo, de ferro e níquel, com a parte de fora líquida e a de dentro sólida. Olhe agora bem de perto a camada onde a gente vive.'},
 {name:'A casca fina',text:'A crosta é a casca da Terra. Comparando com uma maçã, ela é mais fina que a casca da fruta: no oceano tem uns 7 quilômetros, nos continentes de 30 a 70. Tudo o que o ser humano já perfurou, cerca de 12 quilômetros, não chegou nem a atravessá-la.'}
];
/* fichas (chaves = nomes dos áudios) */
D.info={
 terra:{name:'Terra',kind:'Planeta',color:'#6fb7e0',text:'A Terra tem 6.371 quilômetros de raio e é feita de camadas, como uma cebola: crosta, manto e núcleo. Quanto mais fundo, mais quente e mais apertado.',detail:'Diâmetro: 12.742 km. Idade: cerca de 4,5 bilhões de anos. É o planeta rochoso mais denso do Sistema Solar, por causa do núcleo metálico.',medio:'A diferenciação em camadas aconteceu no início da formação do planeta: os materiais mais densos (ferro e níquel) afundaram para o centro, e os silicatos, mais leves, ficaram por fora.'},
 crosta:{name:'Crosta',kind:'Camada externa · sólida',color:'#8fd0a0',text:'A crosta é a camada de fora, onde a gente vive. É de rocha sólida e fininha: de 5 a 70 quilômetros. Debaixo dos oceanos é mais fina e mais pesada; nos continentes é mais grossa e mais leve.',detail:'Duas crostas diferentes: a continental (granito, 30 a 70 km, mais antiga) e a oceânica (basalto, 5 a 10 km, mais densa). A fronteira com o manto chama-se descontinuidade de Mohorovičić, a "Moho".',medio:'A crosta corresponde a menos de 1% da massa da Terra. A oceânica é renovada nas dorsais e destruída nas zonas de subducção; por isso nenhuma rocha do fundo do mar tem mais de 200 milhões de anos.'},
 crosta_continental:{name:'Crosta continental',kind:'Crosta · 30 a 70 km',color:'#a8d8a0',text:'Esta é a crosta continental: a parte grossa, de granito, que forma os continentes. Chega a 70 quilômetros debaixo das grandes montanhas. É a rocha mais antiga do planeta: algumas têm 4 bilhões de anos.',detail:'Menos densa que a oceânica, ela "boia" sobre o manto. Por isso os continentes ficam acima do nível do mar.',medio:'Densidade média de 2,7 g/cm³, rica em sílica e alumínio. Em colisões de placas ela dobra e se espessa, formando cadeias como os Andes e o Himalaia.'},
 crosta_oceanica:{name:'Crosta oceânica',kind:'Crosta · 5 a 10 km',color:'#5fa8c8',text:'Esta é a crosta oceânica: fina, escura, de basalto. Fica no fundo dos mares. Ela nasce nas dorsais, onde a lava sobe, e é jovem: nenhuma parte tem mais de 200 milhões de anos.',detail:'Mais densa que a continental (3,0 g/cm³). Quando encontra um continente, mergulha por baixo dele: é a subducção.',medio:'Formada pelo resfriamento do basalto nas dorsais meso-oceânicas, registra as inversões do campo magnético em faixas simétricas, uma das provas da tectônica de placas.'},
 litosfera:{name:'Litosfera',kind:'Crosta + topo do manto · rígida',color:'#c9c2a0',text:'A litosfera é a crosta mais o pedacinho de cima do manto, tudo rígido, com uns 100 quilômetros. É ela que está quebrada em placas, as placas tectônicas, que se movem devagar sobre a camada mole de baixo.',detail:'As placas se movem de 2 a 10 cm por ano, mais ou menos a velocidade com que a sua unha cresce.',medio:'O limite inferior da litosfera é térmico (isoterma de cerca de 1.300 °C), não de composição: abaixo dela a mesma rocha passa a se comportar de modo dúctil.'},
 astenosfera:{name:'Astenosfera',kind:'Manto superior · plástica',color:'#e0a060',text:'Logo abaixo da litosfera vem a astenosfera. A rocha aqui é tão quente que fica mole, como uma massa de modelar. É sobre ela que as placas deslizam.',detail:'Vai de cerca de 100 a 350 km de profundidade. Não é líquida: é sólida, mas se deforma devagar.',medio:'Uma pequena fração de rocha parcialmente fundida reduz a rigidez e a velocidade das ondas sísmicas (zona de baixa velocidade), o que permitiu identificá-la.'},
 manto_superior:{name:'Manto superior',kind:'Manto · até 660 km',color:'#e07a3c',text:'O manto superior vai até 660 quilômetros de profundidade. É rocha quente, de 1.000 a 1.600 graus, que se mexe muito devagar, como caramelo. Esse movimento empurra as placas lá em cima.',detail:'Feito principalmente de peridotito, uma rocha rica em olivina, um mineral verde. Inclui a astenosfera.',medio:'A 410 km e a 660 km a olivina muda de estrutura cristalina com a pressão (transições de fase), o que separa o manto superior do inferior e aparece nas ondas sísmicas.'},
 manto_inferior:{name:'Manto inferior',kind:'Manto · 660 a 2.900 km',color:'#c84a28',text:'O manto inferior é a maior camada da Terra: vai de 660 até 2.900 quilômetros. Sozinho, o manto todo tem 84 por cento do volume do planeta. Aqui a temperatura chega a 3.700 graus, mas a pressão é tão grande que a rocha continua sólida.',detail:'A rocha se move por convecção: a quente sobe, a fria desce, em correntes que levam milhões de anos para dar uma volta.',medio:'Composto por bridgmanita e ferropericlase, estáveis sob alta pressão. Na base, a camada D″ interage com o núcleo e pode originar as plumas mantélicas (como a do Havaí).'},
 nucleo_externo:{name:'Núcleo externo',kind:'Núcleo · líquido · 2.900 a 5.150 km',color:'#f0a030',text:'O núcleo externo é um oceano de metal derretido: ferro e níquel líquidos a mais de 4.000 graus. Ele gira e se mexe, e é esse movimento que cria o campo magnético da Terra, o escudo que protege a gente do vento solar.',detail:'Sabemos que é líquido porque as ondas sísmicas do tipo S, que não atravessam líquidos, somem quando chegam nele.',medio:'O geodínamo: a convecção de metal condutor, combinada com a rotação da Terra, gera correntes elétricas que sustentam o campo magnético. O campo inverte de polaridade em intervalos irregulares.'},
 nucleo_interno:{name:'Núcleo interno',kind:'Núcleo · sólido · 5.150 a 6.371 km',color:'#fff0a0',text:'No centro de tudo, o núcleo interno: uma bola de ferro sólido com 1.220 quilômetros de raio, quase do tamanho da Lua. É o lugar mais quente da Terra, uns 5.400 graus, tão quente quanto a superfície do Sol. Mas é sólido, porque a pressão é gigantesca.',detail:'A pressão no centro é de cerca de 3,6 milhões de vezes a pressão do ar na superfície.',medio:'Descoberto em 1936 pela sismóloga Inge Lehmann. Cresce lentamente conforme o núcleo externo se solidifica, liberando calor que ajuda a mover o geodínamo.'},
 moho:{name:'Descontinuidade de Moho',kind:'Fronteira crosta · manto',color:'#d8e8c0',text:'A Moho é a linha que separa a crosta do manto. Ela foi descoberta em 1909 por Andrija Mohorovičić, que percebeu que as ondas dos terremotos aceleravam de repente ao cruzar essa profundidade.',detail:'Fica a 5 a 10 km sob os oceanos e a 30 a 70 km sob os continentes.',medio:'Marca a mudança de rochas da crosta (granito, basalto) para o peridotito do manto, mais denso, o que aumenta a velocidade das ondas P de ~7 para ~8 km/s.'},
 ondas_sismicas:{name:'Ondas sísmicas',kind:'Como conhecemos o interior',color:'#9fd0ff',text:'Ninguém nunca viu o interior da Terra. Tudo o que sabemos veio dos terremotos: as ondas que eles produzem atravessam o planeta e mudam de velocidade e de direção em cada camada. Os sismógrafos do mundo inteiro registram isso, e os cientistas montam a imagem de dentro.',detail:'Ondas P atravessam sólidos e líquidos; ondas S só atravessam sólidos. Como as S desaparecem no núcleo externo, descobrimos que ele é líquido.',medio:'A "zona de sombra" das ondas S (entre 104° e 180° do epicentro) e a refração das ondas P no núcleo permitiram a Gutenberg (1914) medir o raio do núcleo.'},
 campo_magnetico:{name:'Campo magnético',kind:'Escudo da Terra',color:'#b0a0ff',text:'A Terra é um ímã gigante por causa do núcleo externo: o ferro líquido em movimento gera o campo magnético. É ele que faz a bússola apontar para o norte e que desvia as partículas do Sol, formando as auroras nos polos.',detail:'Sem o campo magnético, o vento solar arrancaria a atmosfera aos poucos, como aconteceu em Marte.',medio:'O campo é aproximadamente dipolar, com intensidade de 25 a 65 microteslas na superfície. Os polos magnéticos migram e o campo já inverteu centenas de vezes.'},
 kola:{name:'Poço de Kola',kind:'Até onde chegamos',color:'#e8d8b0',text:'O buraco mais fundo que o ser humano já cavou fica na Rússia: o poço de Kola, com 12 quilômetros. Parece muito, mas é só 0,2 por cento do caminho até o centro. Lá no fundo a rocha estava a 180 graus, e as brocas não aguentaram mais.',detail:'Foram 20 anos de perfuração, de 1970 a 1992. O buraco tem 23 cm de largura.',medio:'A temperatura subiu mais rápido do que o previsto (gradiente de ~15 °C/km nas camadas profundas) e a rocha tornou-se plástica, fechando o poço.'}
};
D.CATALOGO={explorar:[['Camadas, de fora para dentro',['crosta','manto_superior','manto_inferior','nucleo_externo','nucleo_interno']],['Dentro da crosta e do manto',['crosta_continental','crosta_oceanica','litosfera','astenosfera','moho']],['Como sabemos disso',['ondas_sismicas','campo_magnetico','kola']]]};
D.LEGENDA=[['#8fd0a0','Crosta'],['#e07a3c','Manto superior'],['#c84a28','Manto inferior'],['#f0a030','Núcleo externo'],['#fff0a0','Núcleo interno']];
/* sequência: camadas da superfície ao centro */
D.sequencias={montar:{titulo:'DA SUPERFÍCIE AO CENTRO',cor:'#f6c37a',ordem:['crosta','manto_superior','manto_inferior','nucleo_externo','nucleo_interno'],rotulos:{crosta:'Crosta',manto_superior:'Manto superior',manto_inferior:'Manto inferior',nucleo_externo:'Núcleo externo',nucleo_interno:'Núcleo interno'},
 pistas:['Comece pela camada onde a gente pisa.','O manto é a camada do meio, e tem duas partes: a de cima vem antes.','O núcleo tem uma parte líquida por fora e uma sólida por dentro.']}};
/* viagem ao centro: sete trechos (profundidade em km, temperatura e pressão didáticas) */
D.viagem=[
 {titulo:'Crosta: até o fundo do poço',de:0,ate:12,temp:'20 → 180 °C',pressao:'1 → 3.000 atm',cor:0x8fd0a0,dur:13,text:'Estamos descendo pela crosta. Rocha sólida, fria, cheia de rachaduras com água. Aos 12 quilômetros passamos pelo ponto mais fundo que o ser humano já perfurou: o poço de Kola. Daqui para baixo, ninguém nunca esteve.',audio:'viagem-0'},
 {titulo:'Crosta: até a Moho',de:12,ate:35,temp:'180 → 500 °C',pressao:'3 mil → 10 mil atm',cor:0x7cc090,dur:12,text:'Continuamos na crosta continental. A rocha fica cada vez mais quente, e a pressão já apertaria qualquer coisa que a gente conhece. Aos 35 quilômetros, cruzamos a Moho: acabou a crosta, começa o manto.',audio:'viagem-1'},
 {titulo:'Litosfera e astenosfera',de:35,ate:100,temp:'500 → 1.300 °C',pressao:'até 30 mil atm',cor:0xd09060,dur:12,text:'Entramos no manto. Nos primeiros quilômetros ele ainda é rígido: é a base da litosfera, da placa que carrega os continentes. Perto dos 100 quilômetros a rocha passa de 1.300 graus e começa a ficar mole: é a astenosfera.',audio:'viagem-2'},
 {titulo:'Manto superior',de:100,ate:660,temp:'1.300 → 1.600 °C',pressao:'até 240 mil atm',cor:0xe07a3c,dur:14,text:'Manto superior: rocha vermelha, quente, que se mexe devagar como caramelo. É esse movimento que, lá em cima, arrasta as placas e levanta montanhas. Aos 660 quilômetros os minerais mudam de forma por causa da pressão.',audio:'viagem-3'},
 {titulo:'Manto inferior',de:660,ate:2900,temp:'1.600 → 3.700 °C',pressao:'até 1,4 milhão atm',cor:0xc84a28,dur:16,text:'Este é o trecho mais longo da viagem: o manto inferior, mais de 2.000 quilômetros de rocha. Está a milhares de graus, mas a pressão é tão grande que ela continua sólida. Lá embaixo, uma luz alaranjada: estamos chegando ao núcleo.',audio:'viagem-4'},
 {titulo:'Núcleo externo',de:2900,ate:5150,temp:'3.700 → 5.000 °C',pressao:'até 3,3 milhões atm',cor:0xf0a030,dur:16,text:'Mergulhamos no núcleo externo: um mar de ferro e níquel derretidos. Correntes de metal líquido giram em volta de nós. É daqui que vem o campo magnético, o escudo invisível que protege a vida na superfície.',audio:'viagem-5'},
 {titulo:'Núcleo interno',de:5150,ate:6371,temp:'5.400 °C',pressao:'3,6 milhões atm',cor:0xfff0a0,dur:14,text:'Chegamos ao núcleo interno: ferro sólido, mais quente que a superfície do Sol, e sólido só porque toda a Terra está em cima dele. Mais alguns quilômetros e estamos no centro exato do planeta. Daqui, qualquer direção é para cima.',audio:'viagem-6'}
];
D.VIAGEM_FIM={text:'Viagem completa: 6.371 quilômetros, da crosta ao centro. Crosta, manto superior, manto inferior, núcleo externo e núcleo interno. Agora você sabe o que existe debaixo dos seus pés.',audio:'viagem-fim'};
/* desafio */
D.questions=[
 {id:'liquida',skill:'camadas',q:'Qual camada da Terra está no estado líquido?',options:['A crosta oceânica','O manto inferior','O núcleo externo','O núcleo interno'],correct:2,why:'O núcleo externo é ferro e níquel derretidos. As ondas sísmicas S não o atravessam, e foi assim que descobrimos que ele é líquido.'},
 {id:'kola',skill:'escala',q:'O buraco mais fundo já feito pelo ser humano tem 12 km. Até onde ele chegou?',options:['Até o manto superior','Nem atravessou a crosta','Até a astenosfera','Até o núcleo externo'],correct:1,why:'O poço de Kola parou dentro da crosta continental, que ali tem uns 35 km. São 0,2% do caminho até o centro.'},
 {id:'manto',skill:'camadas',q:'Qual camada ocupa a maior parte do volume da Terra?',options:['A crosta','O manto','O núcleo externo','O núcleo interno'],correct:1,why:'O manto tem 84% do volume do planeta. Vai de 35 km até 2.900 km de profundidade.'},
 {id:'magnetico',skill:'fenomenos',q:'O que produz o campo magnético da Terra?',options:['O ferro sólido do núcleo interno','As rochas magnéticas da crosta','O movimento do metal líquido no núcleo externo','O calor do manto'],correct:2,why:'O ferro líquido do núcleo externo se move e conduz eletricidade: isso gera o campo magnético, o geodínamo.'},
 {id:'sismicas',skill:'evidencias',q:'Como os cientistas conhecem o interior da Terra, se ninguém nunca esteve lá?',options:['Por fotos de satélite','Pelas ondas dos terremotos, que mudam em cada camada','Por perfurações até o núcleo','Pela cor da lava dos vulcões'],correct:1,why:'As ondas sísmicas mudam de velocidade e de direção ao cruzar cada camada. Registradas no mundo inteiro, elas revelam o que há dentro.'},
 {id:'interno',skill:'fenomenos',q:'O núcleo interno é a parte mais quente da Terra. Por que ele é sólido?',options:['Porque é feito de rocha','Porque a pressão enorme impede o ferro de derreter','Porque está esfriando há bilhões de anos','Porque não tem oxigênio'],correct:1,why:'A 3,6 milhões de atmosferas, o ferro se mantém sólido mesmo a 5.400 graus. É a pressão que decide, não só a temperatura.'},
 {id:'oceanica',skill:'camadas',q:'Comparando a crosta oceânica com a continental, a oceânica é…',options:['Mais grossa e mais leve','Mais fina e mais densa','Mais antiga','Feita de granito'],correct:1,why:'A crosta oceânica tem 5 a 10 km, é de basalto e mais densa. Por isso ela mergulha sob os continentes nas zonas de subducção.'},
 {id:'temperatura',skill:'escala',q:'O que acontece com a temperatura conforme descemos para o centro da Terra?',options:['Diminui, porque fica longe do Sol','Fica igual','Aumenta, até cerca de 5.400 °C no centro','Aumenta só até o manto e depois cai'],correct:2,why:'A temperatura sobe o tempo todo: uns 25 graus por quilômetro na crosta, chegando a cerca de 5.400 °C no núcleo interno.'}
];
D.todasQuestoes=D.questions;
/* aula guiada */
D.guide=[
 {view:'contexto',title:'Localize-se',goal:'Veja a Terra do espaço, abra o planeta ao meio e olhe de perto a crosta onde a gente vive.',check:'contexto',audio:'aula-contexto'},
 {view:'explorar',title:'Investigue as camadas',goal:'Aponte em pelo menos três camadas da Terra aberta e ouça o que cada uma é.',check:'explorar',audio:'aula-explorar'},
 {view:'montar',title:'Monte as camadas',goal:'Coloque as cinco camadas na ordem, da superfície ao centro.',check:'montar',audio:'aula-montar'},
 {view:'viagem',title:'Desça ao centro',goal:'Faça a viagem completa, trecho a trecho, até o centro da Terra. Repare na temperatura e na pressão subindo.',check:'viagem',audio:'aula-viagem'},
 {view:'desafio',title:'Mostre o que entendeu',goal:'Responda às situações finais e consulte o seu resumo.',check:'desafio',audio:'aula-desafio'}
];
D.WELCOME='Bem-vindo ao Terra por Dentro! Aqui você vai abrir o planeta ao meio, conhecer cada camada, montar a Terra de fora para dentro e fazer uma viagem até o centro, onde ninguém nunca chegou. Vamos começar?';
D.sources=[['NASA Visible Earth · Blue Marble (texturas da superfície, domínio público; cópias distribuídas com o three.js)','https://visibleearth.nasa.gov/collection/1484/blue-marble'],['USGS · Earth\'s interior','https://www.usgs.gov/faqs/what-are-earths-layers'],['IRIS · Exploring the Earth using seismology','https://www.iris.edu/hq/inclass/animation/exploring_the_earth_using_seismology'],['Kola Superdeep Borehole · dados históricos','https://en.wikipedia.org/wiki/Kola_Superdeep_Borehole'],['BNCC · EF06CI11 (camadas da Terra); EF06CI12, EF07CI15 e EF07CI16 nos temas seguintes','http://basenacionalcomum.mec.gov.br/']];
window.TERRA_DATA=D;
})();
